### ISSUE TITLE
How to add attributes to input element ?

### ISSUE THREAD

**Issue by pascalheraud** [Vuepic/vue-datepicker#100]
How do you add extra attributes to the input element ? I see no prop to achieve that.

About the "dp-input" slot, we may use it to override the <input> tag but in this case, how do we access to inputClass, uid, ... props that are used on <input> ?

**Comment by Jasenkoo** [comment]
You replace the input with that slot, so you add attributes directly that you need. Also, you have some exposed functions to call also.
