### ISSUE TITLE
Language EU not working on chrome or safari

### ISSUE THREAD

**Issue by oottoo** [Vuepic/vue-datepicker#1004]
Basque language not working in CHROME or SAFARI but works on firefox!! (EU)

You can test it on the playground adding locale="eu" and you will see it works on Firefox but not on Chrome

1.     Go to playground ( https://stackblitz.com/edit/vuepic-vue-datepicker?file=src%2Fcomponents%2FPlayground.vue )
2.     Add locale="eu"  `<Datepicker v-model="date" locale="eu" />`
3.     On Chrome shows SPANISH language but on Firefox will translate to Basque

Expected behavior
Should work on any browser

Desktop & mobile (please complete the following information):

    Browser [chrome, safari]
    Library version [9.0.3]

**Comment by Jasenkoo** [comment]
This is a standard javascript browser locale implementation. The best approach would be to use the full locale code.
