### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by letoast** [Vuepic/vue-datepicker#1007]
**Describe the bug**
Even after setting the autocomplete attribute, I can't get it to work

**To Reproduce**
https://stackblitz.com/edit/vuepic-vue-datepicker-qgwj4f?file=src%2Fcomponents%2FPlayground.vue

**Expected behavior**
I would expect the date field to be filled with values. Native inputs are (see screenshot)

**Screenshots**
<img width="254" alt="image" src="https://github.com/user-attachments/assets/79e8d798-5901-48c2-a8f1-18be9ed541f5">

**Desktop & mobile (please complete the following information):**
 - Browser: Brave, desktop
 - Library version "^9.0.3"

**Comment by Jasenkoo** [comment]
Not sure what you mean by not working, you have to enable `text-input` in order to have a valid input field.
