### ISSUE TITLE
In period picker

### ISSUE THREAD

**Issue by nick-shaydayuk** [Vuepic/vue-datepicker#1009]
**Is your feature request related to a problem? Please describe.**
I need to disable dates, that are out of given period, for example i picked june 2024, so i cant pick any month that is out of 2024

**Describe the solution you'd like**
Disable any pickable dates that are out of given period (year/month) on range start

**Describe alternatives you've considered**
Disabling button on range start and enabling on range end

**Comment by Jasenkoo** [comment]
@nick-shaydayuk You can use `min-date` and `max-date` props to handle this behavior. You can listen on selected date from `internal-model-change` event
