### ISSUE TITLE
Preset range dates styling

### ISSUE THREAD

**Issue by onurusluca** [Vuepic/vue-datepicker#101]
I don't know if this is possible with the current settings but I couldn't find any settings related to this so I am writing here.

It would be great if we have a way to style preset ranges. I added them but they are very close to each other and doesn't look like buttons. 

With the language English it looks fine
![image](https://user-images.githubusercontent.com/51825926/182276669-47eba476-9b57-437e-96c2-daa7ea14d043.png)

But with other languages with shorter text, it looks cramped.
![image](https://user-images.githubusercontent.com/51825926/182276780-556fbaab-d5fc-4fe6-abb4-98baca386948.png)

Thanks a lot!

Is there a way to do this?

@Jasenkoo Also great job with the library. I love it!

**Comment by Jasenkoo** [comment]
You can set the style for a range, for example:
 `{ range: [new Date(), new Date()], label: 'Today', style: { minWidth: '300px', padding: '10px' } }` and so on.
