### ISSUE TITLE
Question. Is there a way to only change the year?

### ISSUE THREAD

**Issue by dbateson** [Vuepic/vue-datepicker#1010]
I have a time date picker but our users want to change only the year and keep the time, month and day selected as they were before they changed the year. So they don't need to re-select the day of the month before they confirm the date. Is this possible?

**Comment by Jasenkoo** [comment]
I tried tweaking a bit to see if  I can add this, but as it was not intended by design, it would require changing a whole approach. This will not be worked on for now, maybe in the future.
