### ISSUE TITLE
Question. Using floating-vue for positioning calendar menu.

### ISSUE THREAD

**Issue by cotowamasha** [Vuepic/vue-datepicker#1011]
Hello!
Sometimes calendar has problems with positioning near input/trigger while scrolling and opening. Problems: menu does not follow input while scrolling; part of menu is cut by window edge after opening; if menu was opened under input and user scroll and there is not free place in the bottom user expects menu placing over input but it is not happen.

My suggestion is using [floating-vue](https://floating-vue.starpad.dev/guide/) for better calculating placement.

**Comment by Jasenkoo** [comment]
Mostly edge cases, no need for external dependency. There is an option to use `alt-position` too.
