### ISSUE TITLE
Date picker with multi-calendars allowing scroll to previous disabled months on second calendar

### ISSUE THREAD

**Issue by filipemamorim** [Vuepic/vue-datepicker#1013]
**Describe the bug**
When we create a date picker with the options "multi-calendars" and a min-date, it shouldn't be possible to scroll to the months before the selectable dates and actually it works fine in case that you go to the previous month on the first calendar, but when doing the same on the second month shown, it will go back to the disabled one.
It have the same behaviour if we use it with the option "month-change-on-scroll"

**To Reproduce**

1. Create a multi-calendar instance
2. Click on the left arrow of the second calendar in order to go to the previous month
3. Use scroll on the second calendar if the "month-change-on-scroll" is active

**Expected behavior**
It should not go back to any month before the one where the dates are possible to select

**Screenshots**
![image](https://github.com/user-attachments/assets/ec278e97-af5d-42c0-b979-e0a4b575c8cb)
![image](https://github.com/user-attachments/assets/0aa53e33-f3ca-4f52-a12b-d3588cc39d3f)

**Desktop & mobile (please complete the following information):**
 - Browser [all]
 - Library version [9.0.3]

**Comment by Jasenkoo** [comment]
Not sure what you mean, but I think you need to use `prevent-min-max-navigation` prop
