### ISSUE TITLE
Date picker (without time picker)  to work without a timezone

### ISSUE THREAD

**Issue by srabi** [Vuepic/vue-datepicker#1014]
**Describe the bug**
Not sure it's a bug. Maybe I'm missing something in how to use the component.
I'm mostly using the component as a date picker without the user having to specify the time.
I wish to set the date picker in such a way that no matter what - the date returned is the date the user picked in the picker.
This means that the result date can be without a timezone - however it should always return the selected date, regardless of the local timezone of the browser, etc.

How do I achieve this? I fumbled with the timezone settings for too long without success.
Using version 9.0.3

**Comment by Jasenkoo** [comment]
Perhaps, take a look at the `utc` prop, but I believe this is just a matter of keeping the date in the UTC string.
