### ISSUE TITLE
[Bug] Changing calendar (multi) view while change text-input date

### ISSUE THREAD

**Issue by cotowamasha** [Vuepic/vue-datepicker#1016]
**Describe the bug**
When user changes text value in input he expects changing calendars view around start-date, but sometimes it isn't happen.

**To Reproduce**
1. Datepicker has default range - **10**/17/2024, 16:41 - **10**/24/2024, 16:41 (dates have same month)
2. Click on text-input, we see Oct-2024 instance.
3. Input - 10/17/**2004**, 16:41 - 10/24/2024, 16:41, we see Oct-2004 instance ✅
4. Input - 10/17/**2024**, 16:41 - 10/24/2024, 16:41, we see Oct-2024 instance ✅
5. Input - **05**/17/2024, 16:41 - 10/24/2024, 16:41, we see Oct-2024 instance ❌ (expects May-2024)
6. Input - 10/17/**2004**, 16:41 - 10/24/2024, 16:41, we see Oct-2004 instance ✅
7. Input - **05**/17/2004, 16:41 - 10/24/2024, 16:41, we see Oct-2024 instance ❌ (expects May-2004)

**Expected behavior**
User should see start-date instance all time or see instance for date was last modified.

**Screencasts**

https://github.com/user-attachments/assets/72c70529-8c27-45e9-80f7-db2765260266

https://github.com/user-attachments/assets/25098eae-456f-45b9-accc-56ed904ccec2

**Desktop & mobile (please complete the following information):**
 - Browser all
 - Library version 9.0.3

**Comment by Jasenkoo** [comment]
Edge cases that require too much boilerplate code to handle possible scenarios. You can take a look at `focus-start-date`
