### ISSUE TITLE
preset-date-range-button template does not work

### ISSUE THREAD

**Issue by tkamstra** [Vuepic/vue-datepicker#1017]
**Describe the bug**
Any customizations within the preset-date-range-button template is ignored

**To Reproduce**
Pass in preset-dates into VueDatePicker, add preset-date-range-button template and change it from the default (in this case add ...) While the left side bar rendered, and the presetDate method works, it does NOT use your customized template

**Expected behavior**
It would use your customized template for the range button

**Screenshots**
![image](https://github.com/user-attachments/assets/40416f3f-6ff4-48d3-8086-5bb3b114af24)
![image](https://github.com/user-attachments/assets/540d5a2d-ed69-46a6-abc5-dea940912d8d)

**Desktop & mobile (please complete the following information):**
 - All Browser 
 - Library version 9.0.3

**Comment by Jasenkoo** [comment]
If you copied from the documentation, you need to set `preset-date-range-button` per date in the provided config.
