### ISSUE TITLE
Multi-calendar view to show current and previous month

### ISSUE THREAD

**Issue by emilyDZC** [Vuepic/vue-datepicker#1019]
Firstly thank you for creating this great datepicker!

**Is your feature request related to a problem? Please describe.**
My use case requires people to select a date range in the past. All future dates are disabled. So when opening the calendar I want to show two months with the current month on the right, and the _previous_ month on the left. But I cannot find a way to do this: the current month always shows on the left with the _next_ month on the right. Even when using a `max-date` of today and `prevent-min-max-navigation`, the disabled month will still show.

**Describe the solution you'd like**
A new prop to allow the calendar to open with two months side-by-side, like multi-calendars, but with the current month on the right.

**Describe alternatives you've considered**
 - Using single calendar (only viable option)
 - Setting `max-date` with `prevent-min-max-navigation` (disabled month still shows on initial opening)
 - Trying to manually click back button on opening (element not loaded in time)

**Additional context**
How it currently opens:
<img width="634" alt="Screenshot 2024-10-21 at 14 27 51" src="https://github.com/user-attachments/assets/0735db87-038d-4987-8043-6b1acad8dbef">

How I'd like it to open:
<img width="624" alt="Screenshot 2024-10-21 at 14 29 45" src="https://github.com/user-attachments/assets/7a1ad441-bf1e-48d4-aa87-1cd8da6953ff">

**Comment by emilyDZC** [comment]
UPDATE - I found a way to solve this by using `start-date` and `focus-start-date` - so no urgency for this feature!

**Comment by vukadinFE** [comment]
@emilyDZC How have you solved it?

**Comment by DeanYa2112** [comment]
I came across this ticket while trying to address a similar problem I was facing. Specifically, I managed to resolve the issue of the initial opening of the date picker using the start-date and focus-start-date properties.

However, I've encountered a challenge when updating the selected dates using the presets I added on the left side. When the dates are updated, the view also changes, causing the current month to appear on the left and the next month on the right.

I've attempted to use the setMonthYear method to fix this behavior, but it hasn't resolved the issue. Could you provide guidance on how to address this using the available properties and methods?
