### ISSUE TITLE
select hours static

### ISSUE THREAD

**Issue by hossein439** [Vuepic/vue-datepicker#102]
Hi guys
and thanks for made vue-datepicker

![Screenshot from 2022-08-06 17-31-22](https://user-images.githubusercontent.com/69785388/183250138-fc617197-2060-4a53-80da-d5d7eac44310.png)

I want it to be selected when the user clicks on any of the times I defined below, and in other words, I want to have only specific hours to choose from.
Also, I save my information in the database and I am going to disable the hours selected by the user so that no other user can choose them, and when all the hours are selected, the day itself will be disabled.
Thank you very much for your help

**Comment by Jasenkoo** [comment]
You have 2 options, as it is right now, you can handle it manually, add the `@click` event on each defined time, and map to `v-model`. Or implemented a custom time picker, as described [here](https://vue3datepicker.com/api/components/#timepickercomponent), end `emit` selected time.
