### ISSUE TITLE
var --dp-primary-color dont work

### ISSUE THREAD

**Issue by gizmo174** [Vuepic/vue-datepicker#1020]
**Describe the bug**
var --dp-primary-color dont work
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by gizmo174** [comment]
<style scoped>
.dp__theme_light {
  --dp-background-color: #fff;
  --dp-text-color: #212121;
  --dp-hover-color: red;
  --dp-hover-text-color: red;
  --dp-hover-icon-color: #959595;
  --dp-primary-color: red;
  --dp-primary-disabled-color: red;
  --dp-primary-text-color: #f8f5f5;
  --dp-secondary-color: #c0c4cc;
  --dp-border-color: #ddd;
  --dp-menu-border-color: #ddd;
  --dp-border-color-hover: #aaaeb7;
  --dp-border-color-focus: #aaaeb7;
  --dp-disabled-color: #f6f6f6;
  --dp-scroll-bar-background: #f3f3f3;
  --dp-scroll-bar-color: #959595;
  --dp-success-color: #76d275;
  --dp-success-color-disabled: #a3d9b1;
  --dp-icon-color: #959595;
  --dp-danger-color: #ff6f60;
  --dp-marker-color: #ff6f60;
  --dp-tooltip-color: #fafafa;
  --dp-disabled-color-text: #8e8e8e;
  --dp-highlight-color: rgb(25 118 210 / 10%);
  --dp-range-between-dates-background-color: var(--dp-hover-color, red);
  --dp-range-between-dates-text-color: var(--dp-hover-text-color, red);
  --dp-range-between-border-color: var(--dp-hover-color, red);
}
</style>

меняю цвет на RED и в меню ничего не работает. в input - все ok

**Comment by Jasenkoo** [comment]
Please use English. The variable works, but you can't use scoped style when overriding the variable
