### ISSUE TITLE
Required doesn't work in combination with inline

### ISSUE THREAD

**Issue by solidevolution** [Vuepic/vue-datepicker#1021]
**Describe the bug**
If the datepicker is set to inline, there is no input element for required form validation

**To Reproduce**
1. Set date picker to inline and required
2. Create a form with submit
3. Submit form with empty date

**Expected behavior**
HTML Form validation jumps in

**Comment by Jasenkoo** [comment]
I think you already know the reason as mentioned in the issue. There is no form element for this. You can use inline with input in that case.
