### ISSUE TITLE
Allow text input when setting the time through the time picker

### ISSUE THREAD

**Issue by cojohnson1999** [Vuepic/vue-datepicker#1024]
**Is your feature request related to a problem? Please describe.**
Hi there!  I've been working with this date picker component for a bit now and love it.  However, it feels a bit clunky the only way to enter a time into the time picker is by using the increment arrows or the grid selection overlay.  I think it'd be a better user experience to allow text input when entering a time in the time picker, instead of having to click a bunch or find the time they want in the grid overlay.

(I realize that the input field can be used to do this, but it also requires setting the date.  It'd be preferable if you could use text input to enter a time without also having to do so for the date.)

**Describe the solution you'd like**
Add a configurable prop that allows the time to be selected through the time picker with text input.  I imagine this would be rendered as an alternative to the grid overlay.  So, if the prop was enabled, clicking on the hours, minutes, or seconds would allow you to enter them through text input _instead_ of opening the grid overlay.  I imagine typing in the hours would also focus the cursor on the minutes field, then the seconds field if enabled.

**Describe alternatives you've considered**
Using the existing grid overlay, incrementing time picker arrows, and the text input field are all alternatives here, albeit they're slightly less convenient than directly allowing for text input in the time picker.

Any help or guidance to an adequate, existing alternative would be much appreciated!  Thanks for all the good work you guys have done on this component already! :)

**Comment by Jasenkoo** [comment]
It is a bit tricky to add this and can result in a lot of boilerplate code. The best way would be to use overlays or `time-picker-inline`. You can also make a slot and handle input there in a desired way.
