### ISSUE TITLE
[nuxt] [request error] Cannot read properties of null (reading 'setupContext')

### ISSUE THREAD

**Issue by mohArifJauhari** [Vuepic/vue-datepicker#103]
**Description the bug**
an error occurred : [nuxt] [request error] Cannot read properties of null (reading 'setupContext'), when running the command npm run preview on nuxt 3

with detail : 

PS C:\Users\arifj\Documents\work\ASDP\TIKET-ONLINE\nuxt3ws\asdp.toba.ferizy> npm run preview
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> preview
> nuxt preview

Nuxt CLI v3.0.0-rc.6                                                                                          13:31:39
i Node.js version: 16.16.0                                                                                    13:31:39
i Preset: node-server                                                                                         13:31:39
i Working dir: .output                                                                                        13:31:39
i Starting preview command: node ./server/index.mjs                                                           13:31:39
                                                                                                              13:31:39
Listening on http://0.0.0.0:3000/
TypeError: Cannot read properties of null (reading 'setupContext')
    at getContext (C:\Users\arifj\Documents\work\ASDP\TIKET-ONLINE\nuxt3ws\asdp.toba.ferizy\.output\server\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6018:14)
    at Object.useSlots (C:\Users\arifj\Documents\work\ASDP\TIKET-ONLINE\nuxt3ws\asdp.toba.ferizy\.output\server\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6011:12)
    at setup (C:\Users\arifj\Documents\work\ASDP\TIKET-ONLINE\nuxt3ws\asdp.toba.ferizy\.output\server\node_modules\@vuepic\vue-datepicker\dist\vue-datepicker.umd.js:1:86198)
    at callWithErrorHandling (file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/chunks/renderer.mjs:2536:23)
    at setupStatefulComponent (file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/chunks/renderer.mjs:8182:30)
    at setupComponent (file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/chunks/renderer.mjs:8163:12)
    at renderComponentVNode (file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/chunks/renderer.mjs:10508:17)
    at Object.ssrRenderComponent (file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/chunks/renderer.mjs:10944:12)
    at file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/chunks/server.mjs:23778:36
    at renderComponentSubTree (file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/chunks/renderer.mjs:10589:13)
[Vue warn]: Component <Anonymous> is missing template or render function.
[h3] [unhandled] H3Error: Cannot read properties of null (reading 'setupContext')
    at createError (file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/node_modules/h3/dist/index.mjs:196:15)
    at Server.nodeHandler (file:///C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/node_modules/h3/dist/index.mjs:386:21) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] Cannot read properties of null (reading 'setupContext')
  at createError (/C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/node_modules/h3/dist/index.mjs:196:15)
  at Server.nodeHandler (/C:/Users/arifj/Documents/work/ASDP/TIKET-ONLINE/nuxt3ws/asdp.toba.ferizy/.output/server/node_modules/h3/dist/index.mjs:386:21)

**To Reproduce**
1. create a project using
`npx nuxi init nuxt-app
`
2. add library @vuepic/vue-datepicker according to the guide in https://www.npmjs.com/package/@vuepic/vue-datepicker
3. in app.vue section add simple invocation <Datepicker v-model="date"></Datepicker>
`<script setup lang="ts">
import Datepicker from "@vuepic/vue-datepicker";
import "@vuepic/vue-datepicker/dist/main.css";

const date = ref();
</script>

<template>
  <div>
    <Datepicker v-model="date"></Datepicker>
  </div>
</template>
`
4. Run `npm run build`
5. Run `npm run preview`

6. Open browser http://localhost:3000/

![Screenshot_102](https://user-images.githubusercontent.com/8744750/183356388-72b61d7c-0102-4a8c-bee1-1f6ee4c0e791.png)

**Details : **
 - NuxtJS 3 ["nuxt": "3.0.0-rc.6"]

**Comment by Jasenkoo** [comment]
This looks a like nuxt error. Try removing `.nuxt` folder then start the app again. If the problem persists, remove `node_modules` also and install it again.

**Comment by mohArifJauhari** [comment]
Hi @Jasenkoo 
I have done what you suggested but the result is still the same ☹️
![Screenshot_103](https://user-images.githubusercontent.com/8744750/183385187-d417080e-f3e0-4039-9c6b-26b308b9b48d.png)
![Screenshot_104](https://user-images.githubusercontent.com/8744750/183385214-479df165-4433-4d6b-8493-16135c2118fd.png)

**Comment by Jasenkoo** [comment]
@mohArifJauhari If you remove picker imports is it starting the server properly? I have a project right now, with nuxt 3.rc-6 and the picker is working correctly.

**Comment by mohArifJauhari** [comment]
@Jasenkoo it runs fine when i run `npm run dev` , however the problem appears when `npm run preview`

@mohArifJauhari If you remove picker imports is it starting the server properly? I have a project right now, with nuxt 3.rc-6 and the picker is working correctly.
> Yes, right

**Comment by Jasenkoo** [comment]
@mohArifJauhari So, when the picker is removed, the preview starts fine?

**Comment by mohArifJauhari** [comment]
> @mohArifJauhari So, when the picker is removed, the preview starts fine?
Yes the preview starts fine

**Comment by Jasenkoo** [comment]
WIll take a look what is happening

**Comment by mohArifJauhari** [comment]
> WIll take a look what is happening

here's the project I made
[n3-vuepicdatepick.zip](https://github.com/Vuepic/vue-datepicker/files/9281072/n3-vuepicdatepick.zip)

**Comment by mohArifJauhari** [comment]
Hi @Jasenkoo 
Is this information helpful, I'm using node js version v16.16.0 and when installing the @vuepic/vue-datepicker package I get an error message

`npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.2.37
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 3.0.0 < 4" from @fortawesome/vue-fontawesome@3.0.1
npm ERR!   node_modules/@fortawesome/vue-fontawesome
npm ERR!     @fortawesome/vue-fontawesome@"^3.0.1" from the root project
npm ERR!   peer vue@">=3.2.0" from @vuepic/vue-datepicker@3.4.1
npm ERR!   node_modules/@vuepic/vue-datepicker
npm ERR!     @vuepic/vue-datepicker@"^3.4.1" from the root project
npm ERR!   1 more (nuxt)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! pinia@"^2.0.17" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.17
npm ERR!     node_modules/pinia
npm ERR!       pinia@"^2.0.17" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\arifj\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arifj\AppData\Local\npm-cache\_logs\2022-08-08T14_10_34_478Z-debug-0.log`

i ignored it by running the command `npm i --legacy-peer-deps`

**Comment by Jasenkoo** [comment]
You can't mix vue 2 and 3, it looks like you have some package that installs vue 2 and overrides vue 3 dependencies. Datepicker is only compatible with Vue 3.

**Comment by mohArifJauhari** [comment]
> > WIll take a look what is happening
> 
> here's the project I made [n3-vuepicdatepick.zip](https://github.com/Vuepic/vue-datepicker/files/9281072/n3-vuepicdatepick.zip)

it's not mixed, I attached my pure project using only nuxt 3 👆🏻

**Comment by mohArifJauhari** [comment]
> Hi @Jasenkoo Is this information helpful, I'm using node js version v16.16.0 and when installing the @vuepic/vue-datepicker package I get an error message
> 
> `npm WARN config global `--global`, `--local`are deprecated. Use`--location=global` instead. npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: undefined@undefined npm ERR! Found: vue@3.2.37 npm ERR! node_modules/vue npm ERR! peer vue@">= 3.0.0 < 4" from @fortawesome/vue-fontawesome@3.0.1 npm ERR! node_modules/@fortawesome/vue-fontawesome npm ERR! @fortawesome/vue-fontawesome@"^3.0.1" from the root project npm ERR! peer vue@">=3.2.0" from @vuepic/vue-datepicker@3.4.1 npm ERR! node_modules/@vuepic/vue-datepicker npm ERR! @vuepic/vue-datepicker@"^3.4.1" from the root project npm ERR! 1 more (nuxt) npm ERR! npm ERR! Could not resolve dependency: npm ERR! pinia@"^2.0.17" from the root project npm ERR! npm ERR! Conflicting peer dependency: vue@2.6.14 npm ERR! node_modules/vue npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0 npm ERR! node_modules/@vue/composition-api npm ERR! peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.17 npm ERR! node_modules/pinia npm ERR! pinia@"^2.0.17" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See C:\Users\arifj\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\arifj\AppData\Local\npm-cache_logs\2022-08-08T14_10_34_478Z-debug-0.log`
> 
> i ignored it by running the command `npm i --legacy-peer-deps`

this is just another project i will deploy on Openshift

**Comment by Jasenkoo** [comment]
@mohArifJauhari Figured it out, I've set it up to use .umd build with nuxt, like for nuxt 2, but turns out for vite, you don't need to.

You can replace the import with the following for now, until the patch is released.

`import VueDatePicker from "@vuepic/vue-datepicker/dist/vue-datepicker.es"`

I will publish a patch to update the import to use the correct build.

**Comment by mohArifJauhari** [comment]
Awesome, 😆

![image](https://user-images.githubusercontent.com/8744750/183457417-7f5c73f1-8680-490c-a7eb-54d752f3cd6d.png)

**Comment by Jasenkoo** [comment]
@mohArifJauhari Can you try updating nuxt to `rc.8` and import it regularly to check if it works? It was using correct build, however, there might be changes between vite 2 and 3
