### ISSUE TITLE
Transition does not happen when using Headless UI Modal

### ISSUE THREAD

**Issue by drehimself** [Vuepic/vue-datepicker#1045]
**Describe the bug**
I'm using a Headless UI Modal/Dialog and have a `VueDatePicker` component within the modal. The transition for opening the modal does not happen. It looks like the `VueDatePicker` has its own transition that is taking priority.

Only happens in v10 of library, works fine in v9 and below.

CodeSandbox here: https://codesandbox.io/p/devbox/vue-datepicker-headless-ui-modal-bug-4s43g4

**To Reproduce**
See CodeSandbox.

**Expected behavior**
The specified open transition on the modal should work.

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome, Firefox
 - Library version: Happens in vue-datepicker v10. Works fine in v9 and below.

**Comment by Jasenkoo** [comment]
Works ok on my end, both open and close

**Comment by admin847** [comment]
This works in Firefox but doesn't work in Chrome.
