### ISSUE TITLE
Provide custom labels for MONTH NAMES in the calendar

### ISSUE THREAD

**Issue by Judyll** [Vuepic/vue-datepicker#1046]
REQUESTED FEATURE:
We currently have a way to change the day names using the `day-names` props which we will supply an array of 7 strings. But, I don't see a way we can set the month names.

SOLUTION:
There should be a `month-names` props where we can set an array of 12 strings. These array of strings should then replace the month names shown in the calendar.

**Comment by Jasenkoo** [comment]
You can use a slot for this, and also build in `long/short` format
