### ISSUE TITLE
Deprecation warnings and import path issue in @vuepic/vue-datepicker SCSS files

### ISSUE THREAD

**Issue by akbarism** [Vuepic/vue-datepicker#1049]
**Describe the bug**
I encountered an issue when using the @vuepic/vue-datepicker library. Specifically, there are deprecation warnings and an error related to SCSS imports. Here are the details:
```
╷
4 │ @import "components/Calendar";
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
    node_modules\@vuepic\vue-datepicker\src\VueDatePicker\style\main.scss 4:9  @import
    src\components\base\BaseDatePicker.vue 2:9                                 root stylesheet

Warning: 4 repetitive deprecation warnings omitted.

```
**To Reproduce**
1. Install @vuepic/vue-datepicker in a Vue project.
2. Import and use the VueDatePicker component in a Vue file.
3. Run the project and check the console for warnings/errors.
 

**Expected behavior**
The component should work without any warnings or errors during SCSS compilation.
Actual Behavior:
- SCSS import fails to resolve components/Calendar.
- Deprecation warnings appear (details unclear due to repetition).

**Screenshots**
 -

**Desktop & mobile (please complete the following information):**
- Node.js version:v18.18.2
- Vue version: 3.3.4
- vite: 4.4.5
- @vuepic/vue-datepicker version: ^3.6.3

**Comment by Jasenkoo** [comment]
This is fixed in latest version, you are using quite an outdated one.
