### ISSUE TITLE
node_modules/date-fns/esm/getWeek/index.js

### ISSUE THREAD

**Issue by EdrickNubla** [Vuepic/vue-datepicker#105]
ERROR in ./node_modules/date-fns/esm/getWeek/index.js 2:0-58
Module not found: Error: Can't resolve '../startOfWeekYear/index.js' in '---\node_modules\date-fns\esm\getWeek'

ERROR in ./node_modules/date-fns/esm/index.js 222:0-72
Module not found: Error: Can't resolve './startOfWeekYear/index.js' in ---\node_modules\date-fns\esm'     

ERROR in ./node_modules/date-fns/esm/setWeekYear/index.js 2:0-58
Module not found: Error: Can't resolve '../startOfWeekYear/index.js' in ---\RSBCI_HRIS_WS_2.0\node_modules\date-fns\esm\setWeekYear'

**Comment by Jasenkoo** [comment]
Can you provide more info?
