### ISSUE TITLE
Using "inline" property hides the "Cancel" button.

### ISSUE THREAD

**Issue by darderemedy** [Vuepic/vue-datepicker#1052]
**Describe the bug**
I'm currently working with the Date picker, and I'm applying some custom configurations, as you can see below:

```javascript
<VueDatePicker
  range
  :multi-calendars="!isMobile"
  inline
  :enable-time-picker="false"
  select-text="Apply"
  :ui="customStyles"
  @update:model-value="handleDate"
  @range-start="onRangeStart"
  v-model="date"
  ref="datepicker"
  :action-row="{ showSelect: true, showCancel: true }"
/>
```

However, if I add the `inline` property, because I don't want to see the input field, I loose the `Cancel` button. Is there a reason for that? I searched in the docs but didn't find any mention.

**To Reproduce**

1. Create a Datepicker instance
2. Add add the "inline" property
3. As you can see the "Cancel" button hides.

**Expected behavior**
I expect the "Cancel" button remain in the widget even with the "inline" property present.

**Screenshots**

<img width="575" alt="Screenshot 2024-11-27 at 15 39 27" src="https://github.com/user-attachments/assets/4630ff5b-b206-4bc3-9f78-08be8208c633">

**Desktop & mobile (please complete the following information):**
 - Google Chrome
 - @vuepic/vue-datepicker": "^10.0.0"

**Comment by Jasenkoo** [comment]
There is nothing to cancel in inline mode, on default one, it just closes the picker
