### ISSUE TITLE
Customer text input parser

### ISSUE THREAD

**Issue by NikolajDL** [Vuepic/vue-datepicker#106]
Hi,

I'm using the timepicker and have text input enabled. I want to allow multiple ways to enter the time, i.e. using both the `HHmm` format and the `HH:mm` format. Is there a way to configure multiple patterns for parsing the text input - or alternatively, replace the default text parser with my own?

Here is how my timepicker is configured:

```js
<VDatepicker
  time-picker
  v-model="myTime"
  :text-input="true"
  :text-input-options="timeTextInputOptions"
/>
 
...

const timeTextInputOptions = ref({
  format: 'HHmm',
});
  ```

With this configuration, I can enter `1230` and it'll turn into `12:30`. 
I cannot enter `12:30` though - or even just change the minute part. It'll just ignore the input altogether and eventually reset to the previously valid time. 

I want to be able to parse by both patterns. How can I do that?

**Comment by Jasenkoo** [comment]
Not right now, will see to add it.

**Comment by NikolajDL** [comment]
Sounds good. I'd be willing to put in a PR for it, if that'll help speed up the process? :-) 
I have a customer breathing down my neck for this particular feature.

**Comment by Jasenkoo** [comment]
Should be published today or tomorrow.

**Comment by NikolajDL** [comment]
Excellent! Thank you for the fast response.
