### ISSUE TITLE
handleInvalidSelect method parameter is null

### ISSUE THREAD

**Issue by Viking-x** [Vuepic/vue-datepicker#107]
@invalidSelect="handleInvalidSelect"
handleInvalidSelect method parameter is null
handleInvalidSelect(val){
      console.log(val)
}
this val is null

**Comment by Jasenkoo** [comment]
Are you pressing the select button without the selected date?

**Comment by Viking-x** [comment]
> 
mode textInput
enter an incorrect value

**Comment by Viking-x** [comment]
![image](https://user-images.githubusercontent.com/31274660/184327870-7448f774-11da-4b5a-81f4-21a72a4abfad.png)

**Comment by Viking-x** [comment]
![image](https://user-images.githubusercontent.com/31274660/184328141-a4ef22a2-f928-41c9-b617-3f75a8a221ec.png)

**Comment by Viking-x** [comment]
I want to listen to the value of this error for processing

**Comment by Jasenkoo** [comment]
Will be added, this is not implemented on text input.
