### ISSUE TITLE
Could you share an example(timepickercomponent)

### ISSUE THREAD

**Issue by Viking-x** [Vuepic/vue-datepicker#109]
Could you share an example
Components:  timepickercomponent
Modes:  range="true" multi-calendars="true"
I can only generate one
![image](https://user-images.githubusercontent.com/31274660/184473103-84240eb4-d67e-40a8-a132-4ae179948f8e.png)

**Comment by Jasenkoo** [comment]
@Viking-x Here is the [demo](https://stackblitz.com/edit/vuepic-vue-datepicker-etaxyy?file=src%2Fcomponents%2FPlayground.vue). You might organize the code a bit depending on the needs, this is just a raw example.
