### ISSUE TITLE
Body dimensions awareness issue

### ISSUE THREAD

**Issue by devhus** [Vuepic/vue-datepicker#110]
**Describe the bug**
The datepicker element does not have a good logic for window/body dimensions awareness.
When your screen size is small or using a mobile view the datepicker will not show up correctly nor will position itself correctly

**To Reproduce**
1. use a small screen
2- open the datepicker

**Expected behavior**
The datepicker should be opened at a top position 

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/58523735/184495157-5dfafc2e-e21b-4de8-9963-b29b02e173b8.png)

**Desktop & mobile (please complete the following information):**
 - chrome,firefox, ms edge
 - Library version: 3.4.2

**Comment by Jasenkoo** [comment]
I don't know how the whole page looks, but it will position based on the available space below and above the input. If there is not enough space for either top or bottom, it will default to bottom. What would be the desired effect here? What issue do you encounter?

**Comment by devhus** [comment]
> I don't know how the whole page looks, but it will position based on the available space below and above the input. If there is not enough space for either top or bottom, it will default to bottom. What would be the desired effect here? What issue do you encounter?

That's the whole page in height. However, It will not position if there is enough space as you can see in this image 
![Screenshot_6](https://user-images.githubusercontent.com/58523735/184506266-68d024d4-c983-46f5-82a8-36c200f57af8.png)
There is enough or bigger space above but it's positioned on the bottom.

The issue is that the package does not render its element in a correct position on some screens, Nor can be opened as a modal or dialog in the center of the screen.

**Comment by Jasenkoo** [comment]
Do you have page overscroll in this case?

**Comment by devhus** [comment]
> Do you have page overscroll in this case?

Nope.
