### ISSUE TITLE
No CSS class for highlighted days if this day is active.

### ISSUE THREAD

**Issue by proandreyyy** [Vuepic/vue-datepicker#112]
Hi, @Jasenkoo. I use the class **.dp__cell_highlight** for add css **::after** to highlight highlighted days with custom new css layer. 

But if selected day is active, there is no class **.dp__cell_highlight** on div, only **.dp__active_date**

vue-datepicker.es.js, line:3595, 
`dp__cell_highlight: props.highlight ? matchDate(calendarDay.value, props.highlight) && !isActive : false`

I think it's enough to remove **&& !isActive**, or to add new class for this case, like **.dp__cell_hightlight_active**.

**Comment by proandreyyy** [comment]
@Jasenkoo, sorry, but it doesn't work..
Only classes I have on selected and highlighted day: `dp__cell_inner dp__pointer dp__active_date calendar-cell`
And I'm pretty sure that day is in the array of highlighted dates.

**Comment by Jasenkoo** [comment]
Agh, I see, will be corrected
