### ISSUE TITLE
SCSS malformation

### ISSUE THREAD

**Issue by yuukinya** [Vuepic/vue-datepicker#113]
**Describe the bug**
There is an issue while using the scss of the library (as of the release v3.4.4), an extra comma generates build error while trying to extend the scss.

![image](https://user-images.githubusercontent.com/5659997/184871173-cfd0bb9c-9716-4844-b5e5-148addbc525a.png)

![image](https://user-images.githubusercontent.com/5659997/184871509-57ebdff2-b773-4fb4-b419-faa44aab72c9.png)

Fixing the extra comma, solves the issue.

**Comment by jackkitley** [comment]
Yes, same here.
![Screenshot 2022-08-16 at 14 02 38](https://user-images.githubusercontent.com/3243014/184874873-967621f3-6ae8-45bc-8618-e4143e36e26a.png)

**Comment by jackkitley** [comment]
@Jasenkoo  mix. need to switch to vite now

**Comment by Jasenkoo** [comment]
Ok, I'll patch it today
