### ISSUE TITLE
Additional aria states and props

### ISSUE THREAD

**Issue by dirkweber** [Vuepic/vue-datepicker#115]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to have additional aria states and properties on a datepicker. "aria-describedby", "aria-description", "aria-invalid", etc.... Currently adding new properties will apply them to the wrapper, not the input element.

**Describe the solution you'd like**
Passing a ref with a configuration similiar to the way aria-labels are configured.

**Describe alternatives you've considered**
Adding props to the component itself: `:ariaDescribedBy = ".."`

**Comment by Jasenkoo** [comment]
You can just use [`dp-input` slot](https://vue3datepicker.com/api/slots/#dp-input) and set needed attributes.
