### ISSUE TITLE
fails in Vite dev, after 3.4.1

### ISSUE THREAD

**Issue by narration-sd** [Vuepic/vue-datepicker#116]
Below is the stack trace, where you can notice that  UMD files are being somehow used under esbuild, which may account for the error.

All had been working in 3.4.0. I've easter-egged back, and 3.4.1 still works. As of 3.4.2, the fault appears that you upgraded in 3.4.3 by adding the "type": "module".

But somehow this isn't working correctly either,  from 3.4.3 on, per this trace. I've had to pin to 3.4.1 until cleared, thanks.

error   Cannot read properties of undefined (reading 'createElementVNode')
at file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.umd.js:1:496
at file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.umd.js:1:240
at file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.umd.js:1:261
at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
at async Promise.all (index 0)
at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
at async nodeImport (file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/our-app/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:50528:21)
at async eval (/src/components/MdThree.vue:43:31)
at async instantiateModule (file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/our-app/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:50457:9)

**Comment by Jasenkoo** [comment]
What Vite version are you using?

**Comment by narration-sd** [comment]
@jasenkoo `npm ls` says it's `vite@3.0.8`, thanks

**Comment by Jasenkoo** [comment]
@narration-sd Can you give me more info about it, `vite.config`, global or local import, vue version?

**Comment by narration-sd** [comment]
yes, I can. This is inside a fairly complex system, so the best is to print out the actual Vite config, not just what I may add to the situation.

It's very latest Vue, all things, but I'll get you the version also.

It's pre-dawn here...will collect these a little later in the day, but wanted to keep up the conversation across apparent timezones with you -- lived in Europe a long time

**Comment by narration-sd** [comment]
...it's a local, Vue 3 install.

```
<script setup>
import Datepicker from '@vuepic/vue-datepicker'
import '@vuepic/vue-datepicker/dist/main.css'
...
</script>
```

**Comment by Jasenkoo** [comment]
> It's pre-dawn here...will collect these a little later in the day, but wanted to keep up the conversation across apparent timezones with you -- lived in Europe a long time

No problem

**Comment by narration-sd** [comment]
Ok, here is information you asked for, I hope complete:

from npm ls
+-- vite@3.0.8
+-- vue@3.2.37

local install, ordinary as above.

Vite config on dev, which is the case that fails (build runs without failure), I believe complete,,,
(this dev server is producing both SSG and hydration, thus running ssr side I think for that)

```
{
    "optimizeDeps": {
        "include": [
            "@our-appjs/vue/client.js",
            "vue"
        ],
        "exclude": [
            "@our-appjs/vue/server.js"
        ]
    },
    "plugins": [
        {
            "name": "vite:vue"
        },
        {
            "name": "fix-pinia-persist",
            "enforce": "pre"
        }
    ],
    "ssr": {
        "external": [
            "@vue/server-renderer"
        ],
        "noExternal": [
            "vuetify"
        ]
    }
}
```

The Vite plugin is one I put in-line as the configuration is built. It's interesting perhaps in that it corrects for another kind of ESM failure, this time in the pinia-plugin-persist module, which lacks the proper "type": "module" configuration in its package.json (or any alternative move). I first made it work by patching the package.json, but this plugin manages to fool Vite into believing it's a module wihtout that, by falsifying its name and going straight to the es.js code later. I'm using it because the issue and simple pull request over there isn't responded to, at least yet - published there on matching issue.

Here is that plugin in full, which is pushed to the vite.plugins array as you can se bones in the config:

```
{
    name: 'fix-pinia-persist',
    enforce: 'pre',
    resolveId(id) {
      if (id.includes('pinia-plugin-persist')) {
        return 'pinia-plugin-persist.mjs'
      }
    },
    async load(id) {
      if (id === 'pinia-plugin-persist.mjs') {
        return await readFile(
            './node_modules/pinia-plugin-persist//dist/pinia-persist.es.js',
            'utf-8',
        )
      }
    }
  }
```

Ok -- I will try a thing or two today, perhaps, given there is time, but I think the fail is solid, and I don't know just what might be going wrong that your own ` "type": "module"` isn't working just as well as it did when I similarly patched that way on the pinia plugin.

Oh yes, here is the error on dev once more. I note that it doesn't appear on first construction of the server, but only as a page containing a Vue component with your module is dynamically served.

Once again, that Vite is going for the umd.js version seems the root of the issue:

```
error   Cannot read properties of undefined (reading 'createElementVNode')
at file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.umd.js:1:496
at file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.umd.js:1:240
at file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.umd.js:1:261
at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
at async Promise.all (index 0)
at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
at async nodeImport (file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/our-app/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:50528:21)
at async eval (/src/components/MdThree.vue:43:31)
at async instantiateModule (file:///C:/vagrant/release/our-app/our-appblog-beta/node_modules/our-app/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:50457:9) 
```

**Comment by Jasenkoo** [comment]
@narration-sd Thank you for the details. Can you try the following and tell me if it works? 

1. Navigate to the package in the `node_modules` and in the `dist` folder rename `vue-datepicker.umd.js` to `vue-datepicker.umd.cjs`
2. In `package.json` replace the `exports.require` to `cjs` extension
3. Same thing for `"main"`, just replace the `js` to `cjs`

Now try to run the app. Side note, do **not** run `npm install` in the meantime since it will override and revert it to default.

**Comment by narration-sd** [comment]
yes, fully understand -- I will try this now...

**Comment by narration-sd** [comment]
Ok!  Yes, this brought the correct ES module file to be used, and dev gave no errors, while build continued to operate well.

You can imagine, that I checked very carefully that your calendar  fully functioned...and it did, in both build and dev.

I wonder if you have any idea why this works. There are a number of platform plugins applied in my build case with _build_ Vite config, and I was about to dissect them one by one to see if I could recognize a Vite config or trick like mine that made build work.

Before this, I'd taken apart your project..json, in comparison to that of the pinia-plugin-persist where adding the "type": "module" made it work.  I found:
- actually, your configs there were quite similar - you just have more detail
- I kept adjusting to make them more exactly the same...and nothing changed the situation
- I was trying some things with the "type": "module" line, finally...and discovered that *leaving it out* would cause dev to work, with the es.js properly imported. Against this nonsequitor, of course build them failed.
- your note caught me in the middle of trying to find a reference to such behavior, or a better project.json config model -- so far, it looks like you'd done everything perfectly.  And so far, no mention of needing to use umd.cjs -- umd.js is all, though with that noted, I can look further...

Conclusion:
- ES modules are great, but the handling by platforms...not so great. In fact I found Vite problems at the first of the year where they were not handing correctly vs. "type": "module". With the guru himself stepping in, Evan You, if he was not already at the center of the room.
- I think you've found a fix. I'm not convinced its over something that would be necessary, if it were possible to understand Vite/Vue configuration for this accurately. I don't give that a high score for chances at least just now :)
- what you've changed follows the rules that are visible, and I can't see where the naming might hurt...given the layers follow those rules...

Thus, I suspect it's just right to make this change and publish it. I would then cross fingers it really doesn't upset any other situation, and guess monitoring issues would be the way to get broad enough testing and find out.

My thoughts of the moment, if useful. And my thanks to you, wondering if you found a reference to why this was necessary??

Best,
Clive
'good work' :)




I've in fact been

**Comment by Jasenkoo** [comment]
Woah, first of all, thank you. I did not expect that you go into this much detail.

So, while checking the Vite docs, when building a library there is a recommended `package.json` example. You can check it [here](https://vitejs.dev/guide/build.html#library-mode). By default, it will output `.mjs` and `.js` for es and umd builds. When you set `"type": "module"` it will output `.js` for es build and `.cjs` for umd build.

I was considering leaving it as it is. However, there were reported issues in nuxt (#103) which for some unknown reason, worked fine in dev mode, but when the app is built, it wouldn't start and the issue with classic SSR build with Vite (#111)

The only reason I left it as it is, is because of `nuxt`. 

**In conclusion, using `"type": "module"` with `.js` and `cjs` extensions is a correct way to go.**

 Reading your update, and the other reports, made me think that the error in `nuxt` was from `nuxt` side and not the library itself. On the other side, it could be a Vite bug, since `nuxt` is using Vite in the background.

Something I noticed while debugging the issue in `nuxt`, that could translate to the issue You reported

- In the dev mode it was loading the correct build
- When building, it switched to the `umd`  build
- Specifying directly the build  resolved the issue, like `import Datepicker from '@vuepic/vue-datepicer/dist/vue-datepicker.es.js'`

However, the question stays, why it is using the wrong build when everything is specified correctly. 

The fix should be published any day now.

**Comment by narration-sd** [comment]
great ;) -- and your last fix is what that little plugin automates happening. Something to keep in back pocket, maybe :)

**Comment by narration-sd** [comment]
...and glad to see that line in the Vite doc, about using cjs.  Many, many people have shown differently...which may be because of the checkered path of getting this all to work, over time.

More confidence then  that you'll be doing the right thing, and then if Nuxt issues remain, they will know where to begin on sorting their end out...

**Comment by narration-sd** [comment]
(last)...and yea, the question does remain, of why this all doesn't follow the straightforward package.json config when done  by the rules. However, I've turned up some rather loose conversations about repairing such errors, and don't need to read more :)

**Comment by narration-sd** [comment]
3.4.6 is in and working fine -- apropos thank you, @Jasenkoo 🌿

**Comment by Jasenkoo** [comment]
Great
