### ISSUE TITLE
Display location

### ISSUE THREAD

**Issue by Viking-x** [Vuepic/vue-datepicker#118]
If the browser pixel is low, can you determine the display position according to input, such as on the right
![1660812021070](https://user-images.githubusercontent.com/31274660/185351164-fddd1676-ccea-453c-805d-859dd7a1b4ce.jpg)

**Comment by Jasenkoo** [comment]
You can use [`altPosition prop`](https://vue3datepicker.com/api/props/#altposition) for custom positioning if needed. As you described can't be implemented, since not everyone would like to position it this way.
