### ISSUE TITLE
closeOnAutoApply not working

### ISSUE THREAD

**Issue by stephanieraymos** [Vuepic/vue-datepicker#120]
**Describe the bug**
I am using the datepicker inside my app, but some of the props don't work. 
This is one instance of the datepicker:
```
    <Datepicker
      ref="datepicker"
      v-model="date"
      inline
      auto-apply
      close-on-auto-apply
      text-input
      inline-with-input
      :enable-time-picker="false"
      required
      :dark="true"
    ></Datepicker>
```
ref is there because I attempted to use the closeMenu method when auto close wasn't working:
```
  if (datepicker.value) {
    // Close the menu programmatically
    datepicker.value.closeMenu();
  }
```

**Expected behavior**
I would expect that when I select a date, the menu closes. 
I also noticed that enter on submit works without enterSubmit. Not sure why, but I like it lol.

**Desktop & mobile (please complete the following information):**
 - Browser [chrome]
 - Library version [latest]

**Comment by Jasenkoo** [comment]
You are using `inline` mode, which will always show the menu. If you don't want to show it, remove the prop.

**Comment by stephanieraymos** [comment]
Thanks. The issue there is I want the datepicker to pop up when a user clicks the field. If I remove inline the user then has to click the text input after already having clicked the field in my table. And this also closes the picker, but not the text input.

What would be the best way to show everything I have with inline, without having inline?? 

I really want the datepicker to be shown automagically. And for auto-apply to close not only the datepicker, but the text/paste input your component offers as well.

**Comment by Jasenkoo** [comment]
You can always listen to a click in the table, then programmatically open the picker via ref.

**Comment by stephanieraymos** [comment]
Is there no way to do that natively with this app? I want everything to be the same as it is with inline, but I just want it to close when a user selects a date. I feel like that's a pretty common/expected workflow so I'm hoping there's a way. 

When a user clicks the field in my table, I want the picker _and_ the text / paste field to open, just like it does with "inline". But when they select a date, I want it to close.
