### ISSUE TITLE
Arabic days names

### ISSUE THREAD

**Issue by mazin01** [Vuepic/vue-datepicker#121]
When using the attribute `locale="ar"` it looks like the text of the days names is the first 2 characters, whish doesn't make sense in this case, because the first 2 characters in every word is 'ال' whish means 'the' in English, and the real meaning of the text  starts after it 

to fix it you can make it slice the text starting from the third character and write 3 characters

ex: instead of 'ال' for Monday it should be 'إثن'

 - Library version [3.4.0]

**Comment by Jasenkoo** [comment]
You can use [`dayNames`](https://vue3datepicker.com/api/props/#daynames) prop
