### ISSUE TITLE
SassError: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by fech-dev** [Vuepic/vue-datepicker#122]
**Describe the bug**
In a vue-CLI project,  I've installed dependencies with yarn 
and when I run `yarn serve` and I got this error. 

```bash
SassError: Can't find stylesheet to import.
  ╷
4 │ @import "@vuepic/vue-datepicker/src/VueDatePicker/style/main.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```
The file is imported in the style section of an SFC file with lang set to "scss"

**To Reproduce**
1. create a vue-cli project with vue 3 and install the vuepic library
2. import the scss file in a scss file or in the style section of SFC
3. run yarn serve

**Expected behavior**
Import correctly and find the file.

**Desktop & mobile (please complete the following information):**
 - Browser: Firefox, Chrome (Desktop)
 - Library version: 3.4.6

**Comment by Jasenkoo** [comment]
It looks like it is something with wabpack, due to the `@` prefix, if you don't want to configure it manually just add `node_modules` like this:

`@import "node_modules/@vuepic/vue-datepicker/src/VueDatePicker/style/main.scss";`
