### ISSUE TITLE
Disable next/prev-Buttons when min/max-range is reached

### ISSUE THREAD

**Issue by FynnZW** [Vuepic/vue-datepicker#126]
When a min and/or max date is set, the user can't change months any further.
But right now, the arrow buttons are still enabled, which may be confusing.
Disabling those buttons, when no previous or next month can be selected, would be nice.

<img width="268" alt="Bildschirmfoto 2022-09-01 um 17 47 33" src="https://user-images.githubusercontent.com/14918334/187957261-391de27a-7908-4158-a726-97e983cb164a.png">

**Comment by qxygene** [comment]
this feature is not working.

**Comment by haritha2112** [comment]
Are there updates on this? It's definitely a nice UX to have!
