### ISSUE TITLE
It opens the keyboard after selecting a date on iOS 15.6.1 (started with 3.4.0)

### ISSUE THREAD

**Issue by Eicher-MA** [Vuepic/vue-datepicker#128]
**Describe the bug**
It opens the keyboard after selecting a date on version 3.4.0 or later

**Screenshots**
I can upload a video if you want.

**Desktop & mobile (please complete the following information):**
on iOS 15.6.1

**Comment by Jasenkoo** [comment]
This is probably due to the focus on the input again, will check.

**Comment by jackysupit** [comment]
it also opens the keyboard on Android chrome. It would be awesome if it could read the attribute of inputmode="none" [https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode)
