### ISSUE TITLE
Warning msgs after installing on Vue3 with @vue-cli

### ISSUE THREAD

**Issue by llvllohd** [Vuepic/vue-datepicker#129]
**Describe the bug**
Getting error msgs after installing on Vue3 with @vue-cli
such as
"export 'onScopeDispose' (imported as 'Aa') was not found in 'vue'
"export 'normalizeStyle' (imported as 'ft') was not found in 'vue'

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45881527/188266436-35d63225-81cb-4165-b12f-6abe5cbc4129.png)

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by Jasenkoo** [comment]
What version of `vue` do you have installed? Also, this will not be worked on, since @vue/cli is now recommending vite for Vue 3 projects.
