### ISSUE TITLE
[Accessibility] Keyboard navigation on date view - To implement roving tabindex pattern

### ISSUE THREAD

**Issue by jennylgh** [Vuepic/vue-datepicker#134]
**Is your feature request related to a problem? Please describe.**
[Roving tabindex](https://ebay.gitbook.io/mindpatterns/techniques/roving-tabindex) is a common pattern for complex components/widgets like DatePicker.
It'll be great if this DatePicker can implement the pattern for easier keyboard navigation.

**Describe the solution you'd like**
Assuming following steps:
1. DatePicker dropdown is showing. User start tabbing.
2. Focus will move over focusable elements: Prev month icon => Month overlay button => Year overlay button => Next month => all date cells => Cancel and Select buttons.

Notice all date cells will receive focus. When is it an issue? Keyboard user has to tab over all date cells before focus finally comes to Select button or focusable elements outside DatePicker but on same page. Of course we can argue that we enable arrowNavigation, autoApply, or other props to help selecting new date, but it still requires extra keyboard pressing. Or won't work in all scenario like inline mode.

**Describe alternatives you've considered**
An alternative tabbing behavior (aka "roving tabindex") is make active date tabindex="0", all other date cells tabindex="-1" (so such cell no longer receives focus on keyboard Tab, but code focus() still works, then keyboard navigation with arrow up/down/left/right inside calendar continues to work)

**Additional context**
Please let me know if I have described this issue properly, or if more info is needed.

**Comment by Jasenkoo** [comment]
@jennylgh I don't see a point of this, since it will disable tabbing over calendar days.

**Comment by FynnZW** [comment]
> @jennylgh I don't see a point of this, since it will disable tabbing over calendar days.

The idea is to replace tab with arrow key navigation (left, right, up, down). I believe it's a good idea since it's greatly shortens the necessary key presses. It's implemented in other datepickers, for example these:
- [flatpickr](https://flatpickr.js.org/examples/)
- [v-calendar](https://vcalendar.io/examples/datepickers.html#button-dropdown)

**Comment by Jasenkoo** [comment]
You can enable [`arrowNavigation`](https://vue3datepicker.com/api/props/#arrownavigation) to use arrows instead of tabs.
