### ISSUE TITLE
[Accessibility] Keyboard Escape to close Month/Year overlay depending on prop escClose

### ISSUE THREAD

**Issue by jennylgh** [Vuepic/vue-datepicker#139]
**Is your feature request related to a problem? Please describe.**
DatePicker has a header component to change month or year. When Month/Year overlay is showing, the container has role="dialog" (we have nested dialogs, ie month/year dialog inside date picker menu dialog). For most users that relies on assistive technology, they know keyboard Esc can close a dialog to return to previous view. 
Using Esc to close dialog is also recommended by [a11y best practice](https://w3c.github.io/aria-practices/#dialog_modal).

**Describe the solution you'd like**
Allow keypress Esc to close month or year overlay. But we may need to distinguish a few scenario, depending on value of prop escClose. Some thoughts:
1. With dropdown mode, date picker will close when Esc is pressed if the prop is true. If user presses Esc when month/year overlay is showing, what's user intension here? do they want to return to date view or close entire date picker? Keeping old behaviour - closing entire date picker - seems to make sense. But returning to date view is also Ok, if we think of the flow, use opens a second dialog inside the first one. Pressing Esc two times will close the two dialog sequentially. 
2. With inline mode, currently escClose does not do much. Can we repurpose the prop to allow Esc to close month/year overlay?
3. A few other scenario, like monthPicker or yearPicker is enabled to select month-year or year only.
4. When escClose = false, this is the easiest scenario, no change is needed.

**Describe alternatives you've considered**
As above

**Additional context**
A screenshot from W3C aria authoring practice.
<img width="841" alt="image" src="https://user-images.githubusercontent.com/5761640/189508478-019ea1a9-d9bb-41a8-894a-ad48083eec98.png">

**Comment by jennylgh** [comment]
Supporting Esc to close overlay based on escClose is [implemented by this PR](https://github.com/Vuepic/vue-datepicker/pull/141). Closing issue

**Comment by Jasenkoo** [comment]
@jennylgh Tnx for pull, will be released at the start of October, need to handle other features.
