### ISSUE TITLE
access all selected dates in multiDates

### ISSUE THREAD

**Issue by DejiAwoniyi** [Vuepic/vue-datepicker#14]
Is there a way to access all the selected dates in the multiDates prop? I want to be able to console.log all the selecteddates after clicking "select" in the compnent.

**Comment by Jasenkoo** [comment]
You can use [this event](https://vue3datepicker.com/api/events/#internalmodelchange). The function receives the current state of the internal `v-model`. WIll update the docs.

**Comment by DejiAwoniyi** [comment]
Thank you. Can the documentation show an example of how to use the events similar to how the props show a code example. Thank you because those were very helpful

**Comment by Jasenkoo** [comment]
Sure

**Comment by DejiAwoniyi** [comment]
Thank you so much. I will wait for the updated documentation

**Comment by Jasenkoo** [comment]
Updated

**Comment by DejiAwoniyi** [comment]
thank you so much. Excellent component

**Comment by Jasenkoo** [comment]
Thank you 😄

**Comment by DejiAwoniyi** [comment]
Honestly, a life saver. Keep going!
