### ISSUE TITLE
Problem to find location with path "/main.css.map"

### ISSUE THREAD

**Issue by AncaEmilia** [Vuepic/vue-datepicker#145]
After installation, I got the following error " No match found for location with path "/client/main.css.map ".
The error appears just when devTools is open.
I used vue 3 and nuxt 3.

**Describe the bug**
The app works, but I have the above error displayed in the terminal. I think it happens because the package is searching for the main.css.map file in the wrong directory.

**To Reproduce**
1. Reload the page where the component is used

**Expected behavior**
The error described above should not be in the terminal, and the .css.map file should be loaded without the error

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Browser : Chrome
 - Library version : 3.4.8

**Comment by Jasenkoo** [comment]
Feel free to ignore it, this is added by chrome and will not be shown in production, if you want to hide it, uncheck *"Enable CSS source maps"* in chrome dev tools
