### ISSUE TITLE
Failed to resolve entry for package "vue3-date-time-picker"

### ISSUE THREAD

**Issue by andreas83** [Vuepic/vue-datepicker#146]
**Describe the bug**
While upgrading from 2.8.2 to 2.8.3 i encounter following error :

Failed to resolve entry for package "vue3-date-time-picker". 
The package may have incorrect main/module/exports specified in its package.json:

**Environment**
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.3-27536227.36512d0`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `buildModules`, `build`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.2.8`
------------------------------

**Comment by Jasenkoo** [comment]
Please don't use that package, it is no longer maintained, also, I think that v2.8.3 is just depreciation, and doesn't have a built package.
