### ISSUE TITLE
When using month range, cannot pick a range that goes from the current year to a future year

### ISSUE THREAD

**Issue by NTass02** [Vuepic/vue-datepicker#152]
**Describe the bug**
The month range date picker does not allow a month range that crosses over to future years.

**To Reproduce**
1. Open a month range date picker.
2. Click on September (or the current month).
3. Click the arrow next to the year to change the year.
4. Notice how it auto selects the same month but in the next year.
5. Try selecting January (so the range is September 2022-January 2023).
6. Notice that this is not allowed (it resets the range to a start date of January 2023).

**Expected behavior**
It is expected that the month range date picker behaves like the regular range date picker. When you select on a start month, if you switch years, you can then click on an end month, and the range will be correct.

**Desktop & mobile (please complete the following information):**
 - All browsers I've tried (Chrome, Safari, and FireFox)
 - Library version 3.4.8

**Comment by Jasenkoo** [comment]
Already included (#147)
