### ISSUE TITLE
Trouble with calendar modal position when in fixed container

### ISSUE THREAD

**Issue by firescott** [Vuepic/vue-datepicker#153]
Having a little trouble with the position of the calendar modal after the user selects the input. Initially, the calendar loads in the correct position below the input field, but when you scroll, the modal is fixed in the position relative to the top of the screen, instead of maintaining its position under the field (see screenshots).

Before scroll:
![before-scroll](https://user-images.githubusercontent.com/114405994/192271028-e22cb3c8-fafb-4cdb-94bf-b48f39a75b59.png)

After scroll:
![after-scroll](https://user-images.githubusercontent.com/114405994/192271022-6dd76b59-3e0c-48a1-822e-d2822b97259f.png)

The input/calendar is within a fixed position div. After some testing, this is the issue as if i remove `position: fixed` from the overlay, the modal stays in the correct place.

I've tried adding `altPosition` but no luck. `closeOnScroll` also has no effect when in a fixed position container. Looks like the modal is relative to the fixed container instead of relative to the input?

Is there anything I can do to resolve?

**Comment by Jasenkoo** [comment]
Try setting the `id` on the modal and then add that `id` as a  [`teleport`](https://vue3datepicker.com/api/props/#teleport) and let me know if it works.

**Comment by firescott** [comment]
That did it! Thanks!
