### ISSUE TITLE
Datepicker not working

### ISSUE THREAD

**Issue by FenderStrat85** [Vuepic/vue-datepicker#154]
**Describe the bug**
Datepicker does not load when added at root or component level

**To Reproduce**
1. Go to https://github.com/FenderStrat85/Bucketlist-client-vue
2. Run project
3. Add user
4. Click on personal goal form

**Expected behavior**
Form loads and datepicker works

**Screenshots**
<img width="1421" alt="Screenshot 2022-09-26 at 20 17 31" src="https://user-images.githubusercontent.com/77243567/192361427-c464e5d5-3573-4d89-85dc-890e3c90a099.png">

chrome

**Comment by Jasenkoo** [comment]
It works, I don't have the database to check the page, but when added on the Sign Up page, it works. However, the package was not in the `package.json`. Make sure that you have installed it.

![test](https://user-images.githubusercontent.com/23171105/192366355-a5be44cd-145c-4147-b9ab-647e3a175104.png)

**Comment by FenderStrat85** [comment]
I have added  it to the package.json and I am still getting the same error inside of the component, so I don't think that has solved it.

**Comment by FenderStrat85** [comment]
Thanks for the quick reply though

**Comment by FenderStrat85** [comment]
Any chance you could shoot me over a screenshot of what you did? Maybe I'm missing something inside the component?

**Comment by Jasenkoo** [comment]
Literally nothing, I just copied your definition and added it on the signup page. Try to remove `package-lock.json` and `node_modules` and install everything again.

**Comment by FenderStrat85** [comment]
That’s exactly what I did, and I was still get the same error messages. I’ll delete the package-lock and node modules, but if you could ping me over a screenshot that’d be great ☺️

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FenderStrat85** [comment]
Got it working, by declaring the datepicker component inside of the component that is rendering it using the component option in the script. However, it's not in any of the docs. It says that when declared in the root it is available in all components, but no examples show the component being declared inside of the component that is rendering the datepicker. Could be worth updating?

**Comment by Jasenkoo** [comment]
There is part of registering either per component or globally

https://vue3datepicker.com/installation/#local

I am not sure why it is not working on that specific page when imported globally. Like I said previously, I just copied the definition and pasted in on the signup page. Nothing else is added/removed.
