### ISSUE TITLE
Calendar shows wrong month when minDate and preventMinMaxNavigation are set

### ISSUE THREAD

**Issue by simonda86** [Vuepic/vue-datepicker#155]
**Describe the bug**
When minDate is a date next month and preventMinMaxNavigation is set to true, the calendar shows the current month with all the days disabled.

**To Reproduce**
1. Create Datepicker with `:minDate` a date next month and `preventMinMaxNavigation`
2. Notice that the calendar shows the current month
3. When clicking next month, notice you can't navigate back to the current month any more,

https://stackblitz.com/edit/vuepic-vue-datepicker-8y1ew1?file=src/components/Playground.vue

**Expected behavior**
The calendar should default to showing the month of the minDate.

**Screenshots**
<img width="273" alt="Screenshot 2022-09-27 at 17 12 35" src="https://user-images.githubusercontent.com/495114/192579437-a563b2a8-3cde-45a1-a383-c4c46c791984.png">

**Desktop & mobile (please complete the following information):**
 - Google Chrome 105.0.5195.125 (Official Build) (x86_64)
 - v3.4.8

**Comment by Jasenkoo** [comment]
It is ok, you have set the date to 31st September, which has 30 days and it switched to October 1st.

**Comment by simonda86** [comment]
@Jasenkoo thank you for getting back to me so quickly, sorry I think I didn't click save on the example. Please see updated version.

https://stackblitz.com/edit/vuepic-vue-datepicker-8y1ew1?file=src/components/Playground.vue

**Comment by Jasenkoo** [comment]
@simonda86 That is expected behaviour.

**Comment by simonda86** [comment]
Thanks @Jasenkoo I thought this might be the case. Is there a prop or another way I can change the active month to next month to fix this for us?

**Comment by simonda86** [comment]
Thanks so much, that has resolved my issue!
