### ISSUE TITLE
autoApply, enableTimePicker="false" and modelType not working with range

### ISSUE THREAD

**Issue by ilia-kolesnikov** [Vuepic/vue-datepicker#157]
When I pick range type all of this settings doesn't work:

`<Datepicker
    v-model="date" 
    :enableTimePicker="false" 
    :format="'dd.MM.yyyy'" 
    autoApply 
    modelType="yyyy-MM-dd" 
    range>
</Datepicker>
`

**Comment by Jasenkoo** [comment]
Everything looks fine https://stackblitz.com/edit/vuepic-vue-datepicker-uabzon?file=src%2Fcomponents%2FPlayground.vue
