### ISSUE TITLE
Validation via functions doesn't work for disabledDates.

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [Vuepic/vue-datepicker#158]
Both `:disabledDates="[() => true]"` and `:disabledDates="[() => false]"` result in all dates being disabled.

Also docs state that prop type is `Type: Date[] | string[] | (date: Date) => boolean` but when I try to pass single function instead of array it results  in prop type warning and exception upon input.

**Comment by Jasenkoo** [comment]
You need just to pass the function, here is an [example](https://stackblitz.com/edit/vuepic-vue-datepicker-wpuedj?file=src%2Fcomponents%2FPlayground.vue).
