### ISSUE TITLE
proper horizontal scroll handling

### ISSUE THREAD

**Issue by Dumokaka** [Vuepic/vue-datepicker#160]
**Describe the bug**
at the moment date picker calendar doesn't seem to handle horizontal page scrolling offset properly and I’d like to check whether it’s bug

**To Reproduce**
1. create layout where date picker parent element is wider than currently available viewport width
2. scroll html root element a bit right
3. click on date input element
4. calendar opens aside of date input element

**Expected behavior**
calendar opens right below date input element

**Desktop & mobile (please complete the following information):**
 - chrome Version 105.0.5195.127
 - Library version 3.4.5
 
 **possible implementation**
looks like you already have a variable calculated with regards to current browser horizontal scroll but it is not seem to be used anywhere `src/VueDatePicker/components/composition/position.ts line: 35`
So could this value be used to determine calendar `left` attribute?

**Comment by Jasenkoo** [comment]
Could be, will have to check
