### ISSUE TITLE
I can't click on month and year in datepicker (monthPicker)

### ISSUE THREAD

**Issue by LisunovYurii** [Vuepic/vue-datepicker#161]
![111](https://user-images.githubusercontent.com/106733655/194011019-1cc55287-475d-4314-b97c-a63a67273c63.png)
Also current month are not highlighted. Please help.

**Comment by Jasenkoo** [comment]
@LisunovYurii Can you provide some additional context?

**Comment by LisunovYurii** [comment]
> @LisunovYurii Can you provide some additional context?

This is my component code. When I insert it it stackblitz, everything works fine, however in my application I see something like on the screenshot above.

<template>
    <div>
        <Datepicker
            :model-value="month"
            @update:model-value="setDate"
            month-name-format="long"
            :year-range="[2020, 2030]"
            month-picker
        >
        </Datepicker>
    </div>
</template>

<script>
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

export default {
    name: 'AAA',
    components: {
        Datepicker,
    },
    data() {
        return {
            month: { month: new Date().getMonth(), year: new Date().getFullYear() },
        };
    },
    methods: {
        setDate(value) {
            this.month = value;
        },
    },
};
</script>

**Comment by Jasenkoo** [comment]
Checked locally, and everything is ok with the picker, I can't help you much. Could be that you have some blocking code in `setDate` function, otherwise, everything is ok.
