### ISSUE TITLE
Vue 3 datepicker with CDN

### ISSUE THREAD

**Issue by lefterisgiannaros** [Vuepic/vue-datepicker#168]
Hello! I'm new to vue and i'm trying to use the datepicker with CDN.
Currently i only got it working by using a template in the main js file.
Is this the right way? Is there a better way to use it?
Thanks in advance!

[Codesandbox](https://codesandbox.io/s/priceless-water-2j8rw3?file=/index.html)

**Comment by Jasenkoo** [comment]
@lefterisgiannaros Hello, if you use some bundler, using it as a `npm package` is recommended way.

What you want to check is [local installation](https://vue3datepicker.com/installation/#local). You can check the tabs, depending on your needs.

**Comment by lefterisgiannaros** [comment]
@Jasenkoo Thank you for your fast reply!
I used the resources above but `multiCalendars :multiStatic="false"` isn't working.
[Codesandbox](https://codesandbox.io/s/priceless-water-2j8rw3?file=/index.html)
