### ISSUE TITLE
Be able to instanciate calendar inside shadowDom

### ISSUE THREAD

**Issue by theopaolo** [Vuepic/vue-datepicker#170]
First of all thanks for this great component !

My issue is that I'm building a web component using vue custom element.
The actual behavior appends the calendar at the end of the DOM, outside my custom element shadow dom.

**Describe the solution you'd like**
Id like to be able to use teleport to indicate the calendar to be appended inside the shadow dom

**Describe alternatives you've considered**
Well the main issue is with inline styling, I consider adding the calendar styling directly in the head of the page, but I loose the advantage of having a shadow dom that wont collide with the website styling.

Thanks a lot in advance for any input, workaround,

Best regards 
Théo Paolo G.

**Comment by Jasenkoo** [comment]
Create a container element in the shadow dom and add an `id` to it, then in the teleport you can pass that `id`

**Comment by theopaolo** [comment]
Hi @Jasenkoo, 

Thanks for the quick reply. I did tried the teleport before, but the result I got was a TypeError : (some letter) is null. 
Maybe it's related to how vite builds up the custom element. I'll try with another build process.

Thanks again for you help.

Théo Paolo G.

**Comment by larryval** [comment]
got entire Vue App loaded in an ShadowRoot element, well the new type of the props `:teleport` doesn't work fo this kind of use. 
I've tried what @Jasenkoo writes with an id, but I think vue-datepicker component code (querySelector) won't find the element has is hidden in shadowdom.
I'm stick with version **V3.5.2**, and it's working, but I miss the updates ...
What I've done, I create a new component embeding vue-datePicker component with template-ref definition, something like :
```vue
<template>
  <div ref="myWrapperEl">
     <Datepicker :teleport="myWrapperEl"/>
 </div>
</template>
```
