### ISSUE TITLE
When using prop "inline" the modal doesn't dissapear when clicking Select

### ISSUE THREAD

**Issue by thomaswre** [Vuepic/vue-datepicker#172]
**Describe the bug**
When using the inline prop, the date modal doesn't dissapear when clicking select. The date gets updated but the modal when used default or with other props goes away.

**Desktop & mobile (please complete the following information):**
Only tried on desktop with Chrome and Firefox so far. Same behavior on both.

**Comment by Jasenkoo** [comment]
That is the point of `inline`, it is always shown, if you want to hide it, wrap it in a parent `div` and show/hide when needed

**Comment by thomaswre** [comment]
It was not clear from the documentation that this was the expected behavior. Please update the documentation?
