### ISSUE TITLE
multiCalendars attribute doesn't works

### ISSUE THREAD

**Issue by thomaskanzig** [Vuepic/vue-datepicker#176]
multiCalendars attribute doesn't works for me.
I did this:

```HTML
<Datepicker v-model="selectedDates" range multiCalendars/>
```

but comes only a single calendar.

![image](https://user-images.githubusercontent.com/1820440/198376944-cccbf8ad-0544-4464-b16b-5a5127afb387.png)

Please help.

**Comment by Jasenkoo** [comment]
Can't help you much with it, if you are using the `browser` build, use `-` for multi-word props, like `multi-calendars`

**Comment by thomaskanzig** [comment]
@Jasenkoo It works with `:multi-calendars="true"`. Thanks.

In the [documentation](https://vue3datepicker.com/api/props/#multicalendars) looks not clear, acoording with the example described:
```javascript
<template>
    <Datepicker v-model="date" range multiCalendars />
</template>
```
