### ISSUE TITLE
Is there an event for when the select button is pressed?

### ISSUE THREAD

**Issue by pamirsawar** [Vuepic/vue-datepicker#177]
I want to call function with parameter when the user presses on the select button on my timepicker

**Comment by Jasenkoo** [comment]
There are 2 events

1. `@update:modelValue` - when the value is valid and selected
2. `@invalidSelect` - when the button is clicked but value is invalid

**Comment by pamirsawar** [comment]
![image](https://user-images.githubusercontent.com/53907015/198811714-9f1669b7-fbec-4b15-8adc-d04a732c1cc5.png)

I have a scenario where I needed to call this function with parameters when the value of the timepicker is changed. Is there any way I can add/send parameters to the function on the @update event. 
Or it will be great is there was an 'change' event for the date/timepicker.
