### ISSUE TITLE
Disable custom hours in custom component 

### ISSUE THREAD

**Issue by hossein439** [Vuepic/vue-datepicker#178]
Hi I hope you are well.
I created custom component for timepicker part like this
![Screenshot from 2022-10-29 10-38-53](https://user-images.githubusercontent.com/69785388/198818961-55198800-d118-459d-933d-7c143aab32ed.png)
I wanted to disable one of those six slots, what should I do? 
for example I want to disable 10:00
thanks

**Comment by Jasenkoo** [comment]
Well, you handle it internally in the component, if you need some condition, you can use `customProps` prop or use `provide` and `inject` from `vue`
