### ISSUE TITLE
Dynamic Timezone

### ISSUE THREAD

**Issue by dgolosov** [Vuepic/vue-datepicker#185]
First of all, thanks to everyone who worked on this repo, it's a really nice job 👍

**Is your feature request related to a problem? Please describe.**
We've got a need to change the user's timezone dynamically, ignoring the system's timezone.
We'd like:
- “today” is displayed according to the custom timezone
- the default month view displays the month and year according to the custom timezone
- display enabled/disabled dates and times
- etc.

**Describe the solution you'd like**
I'd like to clarify what is the most optimal way to implement this.
Is it possible to add the functionality of working with timezones similar to [VCalendar](https://vcalendar.io/timezones.html)?

**Describe alternatives you've considered**

- with this component: transform all dates through a wrapper and replace some of the representations through slots to get the desired look.
- use another component: [VCalendar](https://vcalendar.io/timezones.html)

**Additional context**
User story (or something like it):
Ben travels extensively in different time zones. His devices automatically update time zone. However, using app X, Ben wants to see all dates in timezone T. Ben wants to specify a timezone T in the X application settings so that the entire application interface uses it.

**Comment by nmarsh92** [comment]
I managed to create a work around for choosing a timezone by wrapping the component and treating the date it provides as my specified timezone. My component inputs a UTC string and outputs a UTC string, but the inbetween is treated as a specified TZ

`const convertedDateTime = computed(() => {
  return props.modelValue ? moment(props.modelValue).tz(props.timezone) : null;
});
const date = ref({});
const setDate = () => {
  date.value = convertedDateTime.value
    ? convertedDateTime.value.format("MM/DD/YYYY hh:mm:ss:a")
    : null;
};

const getDateAsUtcString = (date) => {
  let updatedUTCFormattedDate = null;
  if (date) {
    updatedUTCFormattedDate = moment
      .tz(
        [
          date.getFullYear(),
          date.getMonth(),
          date.getDate(),
          date.getHours(),
          date.getMinutes(),
          0,
          0,
        ],
        props.timezone
      )
      .utc()
      .format();
  }
  return updatedUTCFormattedDate;
};

//handlers
const onDateUpdate = (date) => {
  const updatedUTCFormattedDate = getDateAsUtcString(date);
  emit("update:modelValue", updatedUTCFormattedDate);
};

const onInternalModelChange = function (internalModel) {
  const utcDateString = getDateAsUtcString(internalModel);
  emit("internalModelChange", utcDateString);
};`

**Comment by youyi1314** [comment]
Hi,

May i know how can i use this feature? 
and is it using timezone="UTC+3" after apply this patch?

**Comment by Jasenkoo** [comment]
The feature is available under [`3.6.0-alpha.1`](https://www.npmjs.com/package/@vuepic/vue-datepicker/v/3.6.0-alpha.1), currently, only range and single pickers are supported and the date input date has to be UTC date, however, this is still early stage and some bugs may occur.

**Comment by davidfishlock** [comment]
@Jasenkoo is timezone supposed to work in range mode (specifically trying this with week). Seems to just be using client timezone with my testing.

**Comment by Jasenkoo** [comment]
@davidfishlock It is supposed to work with single and range modes. Weekpicker is not supported right now. If you suspect there is an issue on regular range select, feel free to open one.

**Comment by roberthand9** [comment]
Hey @Jasenkoo is it expected to be able to use UTC preserve and timezone together?

I'd like the v-model date to contain UTC, but the formatted date to be displayed based on the timezone prop. Currently it seems to  ignore the given timezone and uses whatever the browsers is for formatting
