### ISSUE TITLE
startDate is not working when monthPicker is enabled

### ISSUE THREAD

**Issue by Coldsewoo** [Vuepic/vue-datepicker#186]
**Describe the bug**

When monthPicker prop is provided, DatePicker does not reflect startDate for initial month and year.

**To Reproduce**

[stackblitz link](https://stackblitz.com/edit/vuepic-vue-datepicker-79hppv?file=src/components/Playground.vue)

**Expected behavior**

It should use startDate as starting point when monthPicker option is enabled.

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Browser : Google Chrome
 - OS: Ubuntu 20.04
 - Library version: 3.5.2 in reproduction, but it also didnt work for latest version.

**Comment by Jasenkoo** [comment]
Fix is available under [`3.6.0-alpha.1`](https://www.npmjs.com/package/@vuepic/vue-datepicker/v/3.6.0-alpha.1)
