### ISSUE TITLE
minRange="1" with range doesn't work as logical common sense expects it to

### ISSUE THREAD

**Issue by jmichaelterenin** [Vuepic/vue-datepicker#187]
Great work on this package, I do know and understand how difficult it is to provide a product such as a DatePicker and expect it to be robust and flexible to meet the needs of everyone. 

minRange="1" should clearly mean that selecting November 8 and then November 8 again shouldn't be allowed. And that selecting November 8 and November 9 should be allowable. But it's just the opposite. And setting minRange="2" prevents November 8 / November 8, but prevents November 8 / November 10, although it satisfies the constraint of being 2 days apart. It doesn't allow until you choose November 8 / November 11. 

**To Reproduce**
```
<Datepicker v-model="value" range minRange="1" />
<Datepicker v-model="value" range minRange="2" />
```

**Expected behavior**
Setting minRange to be >= 1 should prevent any same day range selections
Setting minRange="1" should allow a gap of 1 day between dates (ie Nov 8 / Nov 9) as it clearly satisifies the constraint

**Screenshots**

**Desktop & mobile (please complete the following information):**
 -  I am working on desktop, although I would imagine the issue is not device related
 - Library version [e.g. 3.5.3] latest at the time of this write-up

**Comment by Jasenkoo** [comment]
Fix is available under [`3.6.0-alpha.1`](https://www.npmjs.com/package/@vuepic/vue-datepicker/v/3.6.0-alpha.1)
