### ISSUE TITLE
textInputOptions.format to update the input value on focus

### ISSUE THREAD

**Issue by greendrake** [Vuepic/vue-datepicker#190]
**Is your feature request related to a problem? Please describe.**
Using `textInput`, the user wants to edit the date value by manual typing. When they focus the input, the value remains in the original `format`, whereas the user expects it to be in `textInputOptions.format` for editing.

**Describe the solution you'd like**
On focus, automatically re-format the input value in `textInputOptions.format`. On blur, format it back to `format`. That said, `textInputOptions.format` should not just be used for parsing what the user inputs, but also for presenting what is already in the input when it is focused.

**Describe alternatives you've considered**
Allow to change the `format` dynamically. That said, if I provide a ref in the `:format` property, changing the value of that ref must reflect on the date picker.

**Comment by Henxed** [comment]
In addition to this, I would like to have something like a mask when entering. After all, the user does not know in what format to enter. Is it possible to implement as in the standard input type="date"?

**Comment by iwasherefirst2** [comment]
Has this really been completed? Because I don't understand how I can allow the user to edit the input manually. Adding `         :input-props="{ readonly: false }"` did not work.

**Comment by Jasenkoo** [comment]
@iwasherefirst2 You need to pass [`text-input`](https://vue3datepicker.com/props/modes/#text-input) prop.
