### ISSUE TITLE
start time takes no effect when seting "range" attribute

### ISSUE THREAD

**Issue by felixniemeyer** [Vuepic/vue-datepicker#192]
**Describe the bug**
I'm using the `startTime` attribute in order to choose a default time for when the user selects a date. 
In a date range selctor situation, Datepicker ignores the `startTime` and set's the current time instead. 
When removing the `range` attribute clicking on a date will set the time according to the `startTime` as expected.  

**To Reproduce**
`startTime` works without `range`: 
```
    <Datepicker 
      v-model="newBooking.dateRange" 
      model-type="timestamp" 
      dark
      enable-seconds
      is24
      :start-time="{hours: 12, minutes:0, seconds: 0}"
      @change=getQuote()
      text-input />
```
`startTime` has no effect with `range`
```
    <Datepicker 
      v-model="newBooking.dateRange" 
      model-type="timestamp"
      range 
      dark
      enable-seconds
      is24
      :start-time="{hours: 12, minutes:0, seconds: 0}"
      @change=getQuote()
      text-input />
```

**datepicker version 3.5.3, trying on a recent firefox**

**Comment by Jasenkoo** [comment]
Sorry for the late response, it is not an issue, you have to provide the array when using the `range` prop. Here is the [example](https://stackblitz.com/edit/vuepic-vue-datepicker-dwhxrc?file=src%2Fcomponents%2FPlayground.vue)
