### ISSUE TITLE
Usability improvement for datetime picker

### ISSUE THREAD

**Issue by Marcel-Sass** [Vuepic/vue-datepicker#194]
**Is your feature request related to a problem? Please describe.**
In our Project the users are often confused because they don't see that they have to click the clock icon to select a time after selecting a date.

**Describe the solution you'd like**
I think a property to display both the date picker and the time picker at the same time would be good.

**Comment by Jasenkoo** [comment]
Please refer to [custom time picker component](https://vue3datepicker.com/api/components/#timepickercomponent) or implement your own solution via left or right sidebar slots
