### ISSUE TITLE
Prop enableTimePicker not working in browser version

### ISSUE THREAD

**Issue by limsbeheer** [Vuepic/vue-datepicker#196]
**Describe the bug**
Prop :enableTimePicker not working in browser version.

**To Reproduce**
Minimal code in html page:

```
<script src="https://unpkg.com/vue@latest"></script>
<script src="https://unpkg.com/@vuepic/vue-datepicker@latest"></script>
<link rel="stylesheet" href="https://unpkg.com/@vuepic/vue-datepicker@latest/dist/main.css">

<div id="app">
	<vue-date-picker :enableTimePicker="false" />
</div>

<script>
	Vue.createApp({
		components: {
			VueDatePicker
		}
	}).mount('#app');
</script>
```

**Expected behavior**
No clock button.

**Screenshots**
![bug](https://user-images.githubusercontent.com/10769571/203057453-25c4a409-52db-4b54-84d7-f2f094e231ab.png)

**Desktop & mobile (please complete the following information):**
 - Browser Chrome 107.0.5304.107 (64-bits) (cohort: Stable)
 - Library version Latest

**Comment by Jasenkoo** [comment]
Specify props as `enable-time-picker` instead of `enableTimePicker`  when using in a browser.

**Comment by limsbeheer** [comment]
I'm sorry, I forgot to tell I also tried both just `enableTimePicker` (without `:`) and `enable-time-picker`. Still no success:

```
<script src="https://unpkg.com/vue@latest"></script>
<script src="https://unpkg.com/@vuepic/vue-datepicker@latest"></script>
<link rel="stylesheet" href="https://unpkg.com/@vuepic/vue-datepicker@latest/dist/main.css">

<div id="app">
	<vue-date-picker enable-time-picker="false" />
</div>

<script>
	Vue.createApp({
		components: {
			VueDatePicker
		}
	}).mount('#app');
</script>
```

Yields the same screenshot.
