### ISSUE TITLE
Don't prevent page scroll when monthChangeOnScroll is false (for mobiles)

### ISSUE THREAD

**Issue by AlexeyYar** [Vuepic/vue-datepicker#197]
Page doesn't scroll up/down on mobile when I touch and scroll area of the calendar. 

I expect: main page scrolls up or down even if I started to scroll from calendar element.

monthChangeOnScroll is set to "false"

How can I fix this?

It is related to this ticket:
https://github.com/Vuepic/vue-datepicker/issues/70

**Comment by Jasenkoo** [comment]
Can be related to touch listeners, can you try setting the `no-swipe` and see if it works?
