### ISSUE TITLE
Prop enable-time-picker not working in browser version

### ISSUE THREAD

**Issue by limsbeheer** [Vuepic/vue-datepicker#198]
**Describe the bug**
Prop enable-time-picker not working in browser version.
Related to issue #196.

**To Reproduce**
See [jsfiddle](https://jsfiddle.net/8xwhcza1/)

```
<script src="https://unpkg.com/vue@latest"></script>
<script src="https://unpkg.com/@vuepic/vue-datepicker@latest"></script>
<link rel="stylesheet" href="https://unpkg.com/@vuepic/vue-datepicker@latest/dist/main.css">

<div id="app">
	<vue-date-picker enable-time-picker="false" />
</div>

<script>
	Vue.createApp({
		components: {
			VueDatePicker
		}
	}).mount('#app');
</script>
```

**Expected behavior**
No clock button.

**Desktop & mobile (please complete the following information):**
 - Browser Chrome 107.0.5304.107 (64-bits) (cohort: Stable)
 - Library version Latest

**Comment by Jasenkoo** [comment]
It is working, you are just passing the wrong prop type, it should be boolean `false` but you are passing it as a string `'false'`. Working [jsfiddle](https://jsfiddle.net/6ysfc4rq/2/)

**Comment by limsbeheer** [comment]
Yes! It is working now.
Thank you.
