### ISSUE TITLE
Time picker toggle error

### ISSUE THREAD

**Issue by cpkuo** [Vuepic/vue-datepicker#20]
I'm using the browser installation mode using the latest version. When I click the clock icon to switch to time picker mode, I get the following console errors:
![datetimepickertimeclock](https://user-images.githubusercontent.com/8570488/163676141-09f21c4a-c912-475d-ac37-28c0e65304aa.png)

**Comment by Jasenkoo** [comment]
Thx for screenshot, will check what is going on, also for event listeners

**Comment by Jasenkoo** [comment]
@cpkuo Can you please provide what props have you passed to the component

**Comment by cpkuo** [comment]
Here is my usage. Btw, when I use 3.0.0 it appears to work fine, I just dont get the new features like ariaLabels and transitions.

`<Datepicker v-model="value"
								:teleport="teleportId"
								:altPosition="positionMenu"
								:inline="inline"
								:locale="locale"
								:placeholder="placeholder"
								:cancelText="cancelText"
								:selectText="selectText"
								:autoApply="autoApply"
								:noToday="noToday"
								:enableTimePicker="enableTimePicker"
								:is24="is24"
								:hoursIncrement="hoursIncrement"
								:minutesIncrement="minutesIncrement"
								:transitions="false"
								:ariaLabels="ariaLabels"
								@focus="onFocus"
								@blur="onBlur">
						<template #input-icon>
							<svg style="width:20px; height:20px" viewBox="0 0 24 24">
								<path d="M19,4H18V2H16V4H8V2H6V4H5C3.89,4 3,4.9 3,6V20A2,2 0 0,0 5,22H19A2,2 0 0,0 21,20V6A2,2 0 0,0 19,4M19,20H5V10H19V20M19,8H5V6H19V8Z" />
							</svg>
						</template>
						<template #clear-icon="{ clear }">
							<button v-if="value !== null" class="clear-icon" type="button" @click="clear" :aria-label="ariaLabelClear"></button>
							<div v-else class="chevron-icon"></div>
						</template>
					</Datepicker>`

**Comment by Jasenkoo** [comment]
Ok, detected the issue, I don't know how your `ariaLabels` prop looks, but it looks like you have passed the invalid type for increment value.

This object is simply to translate the accessibility labels for the HTML `aria-label` attribute. The provided object is merged with the default one.

In the documentations, there is type describe like

```ts
interface AriaLabels {
  toggleOverlay?: string;
  menu?: string;
  input?: string;
  calendarWrap?: string;
  calendarDays?: string;
  openTimePicker?: string;
  closeTimePicker?: string;
  incrementValue?: (type: 'hours' | 'minutes' | 'seconds') => string;
  decrementValue?: (type: 'hours' | 'minutes' | 'seconds') => string;
  openTpOverlay?: (type: 'hours' | 'minutes' | 'seconds') => string;
  amPmButton?: string;
  openYearsOverlay?: string;
  openMonthsOverlay?: string;
  nextMonth?: string;
  prevMonth?: string;
}
```

In case you are not familiar with the typescript type declaration, it just specifies the object properties, `?` means it is an optional parameter.

In your case, for the `incrementValue`, you provided something that is not a function, so when the function is called on non-function, it throws an error.

To explain:

` incrementValue?: (type: 'hours' | 'minutes' | 'seconds') => string;`

This means that `incrementValue` is a function that will receive one parameter of type string, which can be 'hours', 'minutes', or 'seconds' depending on when it is called. This function has to return a string, aka, some value that will be added to the `aria-label` attribute.

So  `incrementValue`, `decrementValue` and `openTpOverlay` are functions, others are strings.

For example, to change the `aria-label` on time picker increment arrows, and toggle overlay button we provide something like this

```vue
<template>
  <Datepicker :aria-labels="ariaLabels">  />
</template>

<script setup>
import { computed } from 'vue'

const ariaLabels = computed(() => ({
    incrementValue: (type) => {
       if (type === 'hours') return 'Hello hours';
       if (type === 'minutes') return 'Hello minutes';
       return 'Hello seconds';
    }, 
    toggleOverlay: 'Just a regular string'
}))
</script>
```

**Comment by cpkuo** [comment]
Thank you!
