### ISSUE TITLE
Month and year additional windows do not display

### ISSUE THREAD

**Issue by altrof** [Vuepic/vue-datepicker#201]
Hello, everybody! 
I decided to choose your vue component Datepicker. I installed package and added import css to globally (main.js file).
When I added Datepicker, then I saw, that month and year additional windows are not displayed.

My using of Datepicker:
```
            <Datepicker
              v-model="date"
              :format="format"
              :id="key"
              v-if="header.includes('Date')"
              class="w-40"
              :enable-time-picker="false"
              @update:model-value="updateDate(key)"
            />
```

package.json:
```
    "@vuepic/vue-datepicker": "^3.6.0",
     "vue": "^3.2.45",
```

I tried to remove all props excluded `v-model="date"` to check, that maybe some props broke this. But no.

Expected:
![image](https://user-images.githubusercontent.com/57635329/205149684-9d638b9c-e5bc-4037-a8c8-2b14572c0ee2.png)

Actual result:
![image](https://user-images.githubusercontent.com/57635329/205147851-ebd578d0-85f4-4c60-8232-d2fb765ea0c2.png)
![image](https://user-images.githubusercontent.com/57635329/205147941-eea93e03-3a89-470b-bc6c-32e266f81d25.png)

**Comment by Jasenkoo** [comment]
@altrof Can you check if you have something like this in your global styles

```css
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  position: relative;
  font-weight: normal;
}
```

This is added by default in base.css when creating a Vue 3 app. If you have, just remove the `position: relative;` line.
