### ISSUE TITLE
Unable to start Vue3 app after installing vue-datepicker (console error 'utcToZonedTime')

### ISSUE THREAD

**Issue by titusdecali** [Vuepic/vue-datepicker#202]
**Describe the bug**
App will not load after installing and importing Vue-Datepicker globally via main.js and the following console error is shown:

![SHOT 14 51 43@2x](https://user-images.githubusercontent.com/4532534/205224567-ddcf7c28-be1d-432b-8ec6-b55a45a15678.jpg)

**In error file:**
![SHOT 14 54 38@2x](https://user-images.githubusercontent.com/4532534/205224884-d990ac5f-0012-4c44-af97-77b948b2b198.jpg)

**To Reproduce**
1.    "vue": "^3.2.40",
2.    install "@vuepic/vue-datepicker": "^3.6.0",
3.    start the app

**Comment by uzianhar** [comment]
same error today, I revert to yesterday deployment work fine.

"vue": "^3.1.5"
"@vuepic/vue-datepicker": "^3.5.3"

I got this new on package-lock

<img width="884" alt="image" src="https://user-images.githubusercontent.com/19420572/205273698-25ecad7e-94ad-4134-984e-9ce1af86d6e4.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/19420572/205273820-0001c820-61d8-428c-b99c-5dd7299cbd09.png">

**Comment by Jasenkoo** [comment]
@titusdecali @uzianhar Are you using `@vue/cli`?

**Comment by uzianhar** [comment]
> @titusdecali @uzianhar Are you using `@vue/cli`?

yes
@vue/cli 5.0.4

**Comment by Jasenkoo** [comment]
The picker will work appropriately on `vue >= 3.2` since prev versions were still in beta and there are some breaking changes.

Furthermore, it appears to be working fine, try a clean install of `node_modules`, or reinstalling the picker. If not try adding `date-fns-tz` separately.
