### ISSUE TITLE
Fulltext search 404 page not found

### ISSUE THREAD

**Issue by CODE-BR3AKER** [Vuepic/vue-datepicker#204]
**Describe the bug**
I guess the new update caused the paths in the documentation to change yet the fulltext search is still indexing the old paths therefore 404 page not found...

**To Reproduce**
1. Go to https://vue3datepicker.com/
2. Click on CTRL+K
3. Search "input" (for example) & click on a result
4. See error 404

**Comment by Jasenkoo** [comment]
Yeah, let's give it a few days to update the indexes. Tnx for the notice.

**Comment by Jasenkoo** [comment]
The search is working again now.
