### ISSUE TITLE
Nuxt 3 : [Vue warn]: Failed to resolve component: Datepicker If this is a native custom element,

### ISSUE THREAD

**Issue by kaboume** [Vuepic/vue-datepicker#205]
Hi,
I'm using Nuxt 3.
I have installed the package : 
`npm install @vuepic/vue-datepicker`
And I changed the nuxt.config.js like that : 
```
build: {
    transpile: ['vuetify', '@vuepic/vue-datepicker'],
  },
```
And in my component : 
```
<v-card-text class="pa-0 ma-0">
      <Datepicker v-model="date" range />
    </v-card-text>
```

But the datepicker doesn't display and in the console there is the message : 

[Vue warn]: Failed to resolve component: Datepicker
_If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement._

**Comment by Jasenkoo** [comment]
Did you import the component?

**Comment by Jasenkoo** [comment]
Related to #202

**Comment by Jasenkoo** [comment]
Closing this one, will be handled in #210
