### ISSUE TITLE
Add calendar props for year selection

### ISSUE THREAD

**Issue by skatesham** [Vuepic/vue-datepicker#207]
**Is your feature request related to a problem? Please describe.**
Long time to select old years as birthdate input.

**Describe the solution you'd like**
One new property Calendar Props (ex: year-selection: true),  
 to allow click on year and start a year selection.

**Describe alternatives you've considered**
Don't use vue-datepicker, and just use a simple input with personal validations

**Additional context**
:smile:

**Comment by Jasenkoo** [comment]
Not sure what you mean exactly, but you can always implement your own solution using [`month-year`](https://vue3datepicker.com/slots/components/#month-year) slot.
