### ISSUE TITLE
Search in website doesn't work

### ISSUE THREAD

**Issue by delinext** [Vuepic/vue-datepicker#21]
**Quick search in https://vue3datepicker.com/ doesn't work... i saw console in dev tools and got this message error (Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com.)**

1. Go to https://vue3datepicker.com
2. Click on Cmd + K (on mac)
3. Type something in search bar 

**Expected behavior**
Working search to easily navigate in website

**Screenshots**
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/99867002/163734938-b498170e-429e-4a55-9546-dcaf8fdfc32f.png">

**Desktop & mobile (please complete the following information):**
 - Chrome
 - Mac OS

**Comment by Jasenkoo** [comment]
Tnx for notice, will check what is going on
