### ISSUE TITLE
3.6.0 : warning compiled with 1 warning 4:12:23 pm warning in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js "export 'default' (imported as 'yn') was not found in 'date-fns-tz'

### ISSUE THREAD

**Issue by Guillaume35** [Vuepic/vue-datepicker#210]
**Describe the bug**

After updating to version 3.6.0, datepicker makes my app fail to execute.

`npm run serve` display a warning in the terminal :

```
 WARNING  Compiled with 1 warning

 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js

"export 'default' (imported as 'Yn') was not found in 'date-fns-tz'
```

When I try to start the app in the browser, console displays this error :

```
vue-datepicker.js?5141:218 Uncaught TypeError: Cannot destructure property 'utcToZonedTime' of 'date_fns_tz__WEBPACK_IMPORTED_MODULE_2__.default' as it is undefined.
```

**Proposal, search for solution**

Seems the problem is located in this file date-fns-tz [src/VueDatePicker/components/composables/utils.ts](https://github.com/Vuepic/vue-datepicker/blob/cd2b8b7541bddf38ed9aaaaeaf66fa77e972050f/src/VueDatePicker/components/composables/utils.ts) :

Line 22 to 24

```
import dateFnsTz from 'date-fns-tz';

const { utcToZonedTime, zonedTimeToUtc } = dateFnsTz;
```

The import statement refer to a module which has no `export default`.

Import should probably be something like :

```
import { utcToZonedTime, zonedTimeToUtc } from 'date-fns-tz';
```

**Temporary solution**

Downgrading to 3.5.3 in my package.json

**Comment by linggadirgan** [comment]
same issue

**Comment by pingumen96** [comment]
same issue here

**Comment by sebj54** [comment]
I believe I have the same issue since I updated with latest version. The error message is different though:

```
SyntaxError: ambiguous indirect export: default
```

**Comment by Jasenkoo** [comment]
Will publish a fix later today.

**Comment by Jasenkoo** [comment]
The fix is published and should be good now, let me know if the issue still persists.
