### ISSUE TITLE
Disable specific Months in Monthspicker

### ISSUE THREAD

**Issue by nvima** [Vuepic/vue-datepicker#214]
Hello, I would like to set the month picker so that I can deactivate individual months of a year. But for each year differently.
E.g. All months before January 2021 deactivate, and all months after December 2022 (I have already solved with min-date and max-date). And then e.g. the March in 2021 and the November in 2022, without that in the other years also are disabled, like e.g. with filter. I have tried it with disabled-dates. but that does not seem to work with the months picker?
Is there such a function with which I could do this?

**Comment by Jasenkoo** [comment]
Hmm, not right now, I will make it use the disabled dates, in the meantime, as a workaround you can use filters, and watch `internalModelChange` or `updateMonthYear` to get the year and update the filter.

**Comment by jens3911** [comment]
> Hmm, not right now, I will make it use the disabled dates, in the meantime, as a workaround you can use filters, and watch `internalModelChange` or `updateMonthYear` to get the year and update the filter.

That's exactly what I needed, thank you :)
