### ISSUE TITLE
Two Input Fields for Daterange

### ISSUE THREAD

**Issue by admix1** [Vuepic/vue-datepicker#215]
Hello,
is it possible to show two Input fields with start- and enddate when i use range-mode. Both Input-Fields should open the same Picker. It were possible if dp-input value has an Array with the two Dates

here is an example:
![image](https://user-images.githubusercontent.com/120565700/207580161-8401e815-99d5-41f2-b651-83efb5f95d47.png)

**Comment by Jasenkoo** [comment]
Technically, you can do it on your own, either, set `[min/max]-date` on 2 separate pickers, without using the range, or bind them both to the same v-model and format display value depending on the picker.

**Comment by urbgimtam** [comment]
@admix1 It's late, but for reference here goes what I've done :) 

Using the `<template>` and `<input>`, you can change the *value* input attribute to display directly the first (start) or second (end) values of the range array, with `:value="range[0]"` (first field - start of range) and `:value="range[1]"` (second field - end of range).

You should note that the range array contains the date in date format as a String. I'm formatting it using dateFns.

Hope it helps.

```
<template>
<div>
<!-- First field -->
<VueDatePicker  v-model="range" range min-range="1" :min-date="arrivalMin" :max-date="departureMax" no-disabled-range :enable-time-picker="false" >
  <template #dp-input="{ value, onInput, onEnter, onTab, onClear }">
    <input type="text" :value="formatISO(new Date(range[0]), { representation: 'date' })" />
  </template>
</VueDatePicker>

<!-- Second field -->
<VueDatePicker  v-model="range" range min-range="1" :min-date="arrivalMin" :max-date="departureMax" no-disabled-range :enable-time-picker="false" >
  <template #dp-input="{ value, onInput, onEnter, onTab, onClear }">
    <input type="text" :value="formatISO(new Date(range[1]), { representation: 'date' })" />
  </template>
</VueDatePicker>
</div>
</template>

<script setup>
import { addDays, parseISO, formatISO } from "date-fns"
import VueDatePicker from "@vuepic/vue-datepicker"
import "@vuepic/vue-datepicker/dist/main.css"

const arrival = ref(addDays(new Date(), 1))
const departure = ref(addDays(new Date(), 2))
const range = ref([arrival.value, departure.value])
const arrivalMin = formatISO(addDays(new Date(), 1), { representation: "date" })
const departureMax = formatISO(parseISO("2023-04-30T00:00:00"))


</script>

```
