### ISSUE TITLE
Range picker multi calendar: changing the year on the right calendar changes the year on the left one after clicking a day

### ISSUE THREAD

**Issue by emmanuel-franc** [Vuepic/vue-datepicker#216]
**Describe the bug**
In a range multi calendar, whenever I change the year of the right calendar it changes the year of the left one after clicking a day on the left calendar.
I noticed a different behaviour when we first select a day on le left calendar then select a year on the right one (which is the behaviour I would like to reproduce in my project).

**To Reproduce**
1. click on the year selection of the right calendar and select a date
2. click on a day of the left calendar
3. the year of the right calendar will be the year of the left one + 1 year

**Expected behavior**

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Browser chrome
 - Library version 3.6.3
 

Anyway, thank you for the hard work 👍 this datepicker is really good.

**Comment by Jasenkoo** [comment]
Tnx, looks like it is broken from the v3.6.0, you can downgrade to v3.5.3 for now, it should work as expected, [demo](https://stackblitz.com/edit/vuepic-vue-datepicker-fudyfl?file=src%2Fcomponents%2FPlayground.vue)

**Comment by emmanuel-franc** [comment]
Hi @Jasenkoo, thanks for the answer. I'll downgrade to keep consistency.

However, when I select a year on one calendar it automatically changes the year of the other one. How could I prevent this behaviour ?

To be clear, I would like to be able to select 2022 in the first calendar and 2030 in the second one.
