### ISSUE TITLE
When selecting a range, the end time will always be the user's current time

### ISSUE THREAD

**Issue by kochrt** [Vuepic/vue-datepicker#217]
You've got a very thorough and well documented library here, the customizability and feature set are amazing!

**Describe the bug**
I would think the default for a range's end time could/should be midnight, or whatever the user entered previously.

**To Reproduce**
Go to https://vue3datepicker.com/props/modes/
Click the range example
Choose a range
The selected end time will be your current time. 

If you change the date, the end time will be reset to the current time.

**Expected behavior**
I would expect the end time to be some reasonable or idempotent default, like midnight or noon or something, or whatever the user entered previously.

**Screenshots**
<img width="718" alt="Screen Shot 2022-12-14 at 12 12 49 PM" src="https://user-images.githubusercontent.com/10823320/207663267-78635837-5636-4b2c-a6bf-a22db8a8fb93.png">

**Desktop & mobile (please complete the following information):**
 - 3.6.3

**Comment by kochrt** [comment]
It's also possible that I missed how to set this in the documentation. Or maybe I can listen to an event and reset the time to something else I want (that is, when they're using the **calendar** and not explicitly picking the time using the **time picker**)?

**Comment by Jasenkoo** [comment]
It is an issue, tnx

**Comment by minipisame** [comment]
Hello , i am trying use the directive start-time in a Range-picker and the second date that i pick always put the current hour intead the hour i pass in the start-time . Is the problem solved?
![image](https://user-images.githubusercontent.com/44228797/209813130-a07d3fc1-ec33-4a5d-b47e-f72e45f2bb82.png)
![image](https://user-images.githubusercontent.com/44228797/209813202-9dd04a27-d627-4ff8-b551-03d704ecc04a.png)

I try to use the version  "@vuepic/vue-datepicker": "3.5.3" and this work , but in the 3.6 didn't work

**Comment by Jasenkoo** [comment]
Yes, fix will be included in the next version
