### ISSUE TITLE
Slots component not working

### ISSUE THREAD

**Issue by nurhazbiy** [Vuepic/vue-datepicker#221]
**Describe the bug**
I want to implement slots feature, but just how do i add this? i implement below code but it's not working
here is my code, I implement it without making component out of it though

```
<Datepicker
  v-model="form.date" :enable-time-picker="false"
  :highlight-week-days="[1,2,3,4,5]"
  :preset-ranges="preset"
  auto-apply date-picker
  format="dd/MM/yyyy" multi-calendars multi-calendars-solo
  placeholder="Select Date Filter" range utc
>
  <template #left-sidebar>
    <div>Custom content</div>
  </template>
  <template #right-sidebar>
    <div>Custom content</div>
  </template>
</Datepicker>
```

**To Reproduce**
1. Init Inertia laravel vue
2. implement Vue Datepicker

**Expected behavior**
Left and Right side menu is showing

**Screenshots**
![image](https://user-images.githubusercontent.com/34585999/209578999-0c47339d-441b-4b1f-8bd5-fb1b60402c00.png)

**Desktop & mobile (please complete the following information):**
 - Chrome
 - Library version 3.3.1

**Comment by Jasenkoo** [comment]
It does work, here is a simple [demo](https://stackblitz.com/edit/vuepic-vue-datepicker-hlvltk?file=src%2Fcomponents%2FPlayground.vue). `components` is just a category, if you used it as a slot name, perhaps that is why it doesn't show up.
