### ISSUE TITLE
No need to lay two button there, WYSWYG will be better.

### ISSUE THREAD

**Issue by adoin** [Vuepic/vue-datepicker#222]
Choose on picker, directly implements to model value. Hope use this behavious.

**Comment by Jasenkoo** [comment]
You can achieve this behavior with passing `auto-apply` prop

**Comment by adoin** [comment]
> You can achieve this behavior with passing `auto-apply` prop

Thank you for you reply, but auto-apply is not a good result for multi dates. In this mode we want pick days for once modal display, but auto-apply causing that each time pick one day, modal hides. I don't think it's a good way.
