### ISSUE TITLE
getting startDate and endDate data in seperate arrays using range picker

### ISSUE THREAD

**Issue by chrisjarn** [Vuepic/vue-datepicker#224]
const date = ref(); is displaying both startDate and endDate. Can i seperate this into 2 arrays with one just displaying startDate and the other displaying endDate. Much appreciated

```
<template>

  <Datepicker v-model="date" :enable-time-picker="false" no-today  @update:modelValue="handleDate"  :month-change-on-scroll="false" range inline auto-apply />

</template>

<script setup>
 const date = ref();

  onMounted(() => {
            const startDate = new Date();
            const endDate = new Date(new Date().setDate(startDate.getDate() + 3));
            date.value = [startDate, endDate];
    
   })

</script>
```

**Comment by Jasenkoo** [comment]
Why would you do that? If you need you can map data separately, or if you need it for 2 pickers, you can use initial array `[null, null]` and `v-model="array[0 | 1]"`  or something like that
