### ISSUE TITLE
Ability for inline calendars to go to new month view when date value changes

### ISSUE THREAD

**Issue by cabeeb** [Vuepic/vue-datepicker#227]
I have an [inline-with-input](https://vue3datepicker.com/props/modes-configuration/#inline-with-input) calendar view - the calendar is always visible next to a text input field. When the date is changed in the text input, the model-value is updating correctly, but the calendar view does not change to the new month, so it just looks as though nothing is selected on the calendar until the user manually navigates to the month of the newly selected date.

I've tried multiple approaches, such as calling .closeMenu and .openMenu to attempt to get it to re-render, but those methods just hide the static calendar.

Two possible solutions that come to mind are:
* A method on the calendar to programmatically change the view to the currently selected month
* An option on a calendar instance to automatically go to the new month every time the date value changes

**Comment by snygard** [comment]
I'd need this too!

**Comment by cabeeb** [comment]
@Jasenkoo Thanks so much for the quick turnaround on this feature! It is greatly appreciated! 🙌
