### ISSUE TITLE
Couldn't access disable state of the action select

### ISSUE THREAD

**Issue by akram-sq1** [Vuepic/vue-datepicker#228]
When I override the #action-row template, there should be a way to apply disable state in the template, I went through documentation and couldn't find a way to solve this issue. I checked your source code and currently its being applied using following computed property css:

`    const selectClass = computed(() => ({
...
        dp__action_disabled: !isTimeValid.value || !isMonthValid.value || !validDateRange.value,
    }));`

can you suggest me a correct way of doing this, so that my custom button get disabled when the date/time is out of min/max dates. I see that I can hook into `@internal-model-change` event, and re write the validation in my component, if there is an easy way, please let know.

**Comment by DMOAbove** [comment]
I've the same problem, I am using action select but I cannot access the disable state :(
