### ISSUE TITLE
Time section not display - npm package

### ISSUE THREAD

**Issue by StevenHeven** [Vuepic/vue-datepicker#231]
**Describe the bug**
I built application with Vue 3 with Compositon API. I install with npm your datepicker, but I've got problem with time section with display trouble : the time section ot appear in full width like your exemple.
I see this issue : [ Time sections doesn't overlay #36  ](https://github.com/Vuepic/vue-datepicker/issues/36) but with npm package, impossible to overwrite style.
I tried also to @import method in style part, but I've got : `Error: Missing "./src/VueDatePicker/style/main" export in "@vuepic/vue-datepicker" package`

I code in TypeScript for information.

**To Reproduce**
My DatePrickerComponent.vue : 
```
<script setup lang="ts">
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

const date = ref<Date>(new Date());
</script>

<template>
  <Datepicker class="mol-date-picker" v-model="date" auto-apply></Datepicker>
</template>
```

**Expected behavior**
How can I overwrite `ds__calendar { position : relative } ` because it seems that cause

**Screenshots**
You can see the bug with this GIF : 
![Bug Gif](https://medias.andromede.pics/img/bcb54040-8d18-11.gif))

**Comment by Jasenkoo** [comment]
Find what is causing global `relative` position, in an empty project it looks something like this:

```css
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  position: relative; <- remove this line
  font-weight: normal;
}
```

**Comment by StevenHeven** [comment]
I see this css fix, but with npm package, I can't remove native CSS rules... and I can't apply this in my all code :/ So you have no any solution ?

**Comment by Jasenkoo** [comment]
What do you mean you can't remove it, it should be in project global CSS, this has nothing to the with the library. Something in your project is causing it to have a relative position.

You can inspect the element and see which one is overriding the position absolute,

**Comment by StevenHeven** [comment]
Oh sorry, I didn't understand ^^ Thx ;)
