### ISSUE TITLE
Timepicker with :model-value="date" does not displays correct time 

### ISSUE THREAD

**Issue by rendomnet** [Vuepic/vue-datepicker#239]
**Describe the bug**
Datepicker with :time-picker="true" do not display correct time when date object is changed.
The date object is changed but datepicker displays "current time" and not date object time.

Datepicker  without :time-picker="true" is working correctly.

**To Reproduce**
`Datepicker :time-picker="true" :model-value="date" @update:modelValue="handleTimeChange"`
change date object to different time and Datepicker will show incorrect time

**Expected behavior**
Sets correct time

**Screenshots**

**Desktop & mobile (please complete the following information):**
Chrome, 
"@vuepic/vue-datepicker": "^3.6.4",

**Comment by Jasenkoo** [comment]
When using `time-picker`, `v-model` is `{ hours: number; minutes: number }`, not a date.
