### ISSUE TITLE
Highlight selected week in weekPicker

### ISSUE THREAD

**Issue by olahp** [Vuepic/vue-datepicker#24]
First of all; great plugin! Easily the most customizable and simple-to-use datepicker for vue3 👍 

I use the datepicker in several modes; day, week and month, and I would like to request a slight improvement to the weekPicker-mode. I would be very nice if the currently selected week could be highlighted in some way (I can't seem to find this in the current version). The selected day is highlighted, but when in week-mode it would be nice if either all days in the week get an additional class, or the row-wrapper gets an addition class in some way. That way it's easier to show what week is currently selected. The hover works fine, but the I can't find any way to style the currently selected week. Would be a nice feature 💯

**Comment by Jasenkoo** [comment]
Tnx, will see to add it

**Comment by PiotrBaczkowski** [comment]
Hello, it's great work, also, it would be nice if we could get calendar to auto focus on selected week.
