### ISSUE TITLE
Can't bind style

### ISSUE THREAD

**Issue by qxygene** [Vuepic/vue-datepicker#244]
```
<script setup>
const colorFromScriptSetup = '#ff0000';
</script>

<style>
//not working
.dp__today {
  background: v-bind('colorFromScriptSetup');
}
//works
.custom-class {
  background: v-bind('colorFromScriptSetup');
}
</style>
```

**Comment by Jasenkoo** [comment]
Sadly this is not supported, you can use theme classes to override the values. 

More info [here](https://learnvue.co/tutorials/reactive-styles-vue-3#css-variables-are-not-available-in-the-child-component)
