### ISSUE TITLE
auto-apply does not work if you use month or year picker

### ISSUE THREAD

**Issue by NeilMcEachin** [Vuepic/vue-datepicker#245]
**Describe the bug**
If I move months or years with month and year picker and then select a date the date does not get auto-applied. it just stays selected.

**To Reproduce**
1. Create a datepicker with auto apply
2. select a new month or year using the month or year picker
3. Select a date
4. Notice the overlay stays open and the date is not selected

**Expected behavior**
If I use the arrows to switch months and click a day it auto applies. When I use month or year picker then select day it should also auto apply

https://stackblitz.com/edit/vuepic-vue-datepicker-narrrl?file=src/components/Playground.vue

**Desktop & mobile (please complete the following information):**
 - Firefox v108, Linux Desktop
 - Library version [3.6.5]

**Comment by kskrlinnorth2** [comment]
I have same issue, and I realized it doesn't work on official page https://vue3datepicker.com/props/general-configuration/#auto-apply

**Comment by zozulinskyi** [comment]
Hi there. I also have this problem.
Package version: 3.6.5

`<datepicker
            uid="dateTo"
            v-model="form.date_to"
            placeholder="Date to"
            :enable-time-picker="false"
            :month-change-on-scroll="false"
            model-type="dd.MM.yyyy"
            auto-apply
            clearable
          >
            <template #input-icon>
              <nuxt-icon name="calendar" filled />
            </template>
</datepicker>`

**Comment by mateusavila** [comment]
I have the same issue here as well.

<Datepicker 
    locale="pt-BR"
    :partial-range="false"
    :month-change-on-scroll="false"
    :format="format"
    placeholder="Selecione o intervalo"
    :auto-apply="true"
    :enable-time-picker="false"
    :day-names="getDayNames"
    :preset-ranges="presetRanges"
    v-model="date"
    range
    >
    <template #yearly="{ label, range, presetDateRange }">
      <span @click="presetDateRange(range)">{{ label }}</span>
    </template>
  </Datepicker>

**Comment by mateusavila** [comment]
I make a workaround using onMounted and setting the v-model to a Date. It's not perfect, but it's running well.

`const date = ref<Date[]>()
onMounted(() => {
  date.value = [new Date(), new Date()]
})`

**Comment by kskrlinnorth2** [comment]
I just use older version `v3.5.2` until it is fixed.

**Comment by kitisak053** [comment]
I have the same issue @Jasenkoo  thank!!  i'm waiting for new releases version

**Comment by gtmassey** [comment]
Doesn't look like it has been fixed yet as of `v3.6.5`.

**Comment by carlosjurzal** [comment]
It is still failing in v3.6.5

**Comment by joaobarcia** [comment]
It is also affecting us. I see there is already a proposed fix. Just posting for the notifications and to say thanks for committing a fix quickly :)

**Comment by AlperGuven** [comment]
still can't select date with auto apply after select year
