### ISSUE TITLE
Cant select date with auto apply after select year

### ISSUE THREAD

**Issue by FrontDev07Axas** [Vuepic/vue-datepicker#246]
**Describe the bug**
I updated the component version from 3.4.1 to the latest for now and noticed the following error which is also on https://vue3datepicker.com/props/general-configuration/#auto-apply
After selecting the month/year in the calendar, auto-apply stops working. Those with a hidden "select" button (as in my case) there is no way to select a date.

**To Reproduce**
1. Go to https://vue3datepicker.com/props/general-configuration/#auto-apply
2. Click on  input
3. Click on year or month and select it

**Comment by Jasenkoo** [comment]
Fix will be included with #245
