### ISSUE TITLE
Buddhist year format

### ISSUE THREAD

**Issue by kitisak053** [Vuepic/vue-datepicker#247]
https://github.com/Vuepic/vue-datepicker/issues/8#issuecomment-1080606901
> @gapgag55 You can pass `yearRange` and set the range you need

@Jasenkoo hi! i try this answer. but next year(2024) February have 29 day, if pass yearRange like the answer, next year 2024 + 543 = 2567 it is year of (Christian-Era (C.E.)) not (Buddhist-Era (B.E.))  , **can i overwrite year select text** from 2024 to 2567 for showing user select?

**Comment by Jasenkoo** [comment]
Yes you can, use [`year-overlay-value`](https://vue3datepicker.com/slots/overlay/#year-overlay-value) slot.

**Comment by kitisak053** [comment]
> Yes you can, use [`year-overlay-value`](https://vue3datepicker.com/slots/overlay/#year-overlay-value) slot.

i try to follow your example but it doesn't work. what i do wrong
![image](https://user-images.githubusercontent.com/61728619/213915157-06f927ee-2f46-42c2-bb96-dc337714cf38.png)

**Comment by kitisak053** [comment]
Im already like this way. thank you so mach!! ♥️
<img width="431" alt="image" src="https://user-images.githubusercontent.com/61728619/213922506-0c71a5a5-72ed-472e-ac37-f2d0fc42367d.png">

**Comment by kitisak053** [comment]
Im already by this way. thank you so mach!! ♥️

<img width="431" alt="image" src="https://user-images.githubusercontent.com/61728619/213922747-2c4ab0dd-e030-4f65-b048-a73dc2efcd58.png">

**Comment by Jasenkoo** [comment]
@kitisak053 Nice catch, I'll fix it in the docs.

**Comment by maprangsoft** [comment]
@Jasenkoo @kitisak053 thank you.

**Comment by kitisak053** [comment]
[like]  KITISAK YAMANO reacted to your message:
________________________________

**Comment by pantoffski** [comment]
I can't make **year-overlay-value** work, please help. Thanks
![image](https://github.com/Vuepic/vue-datepicker/assets/20040006/cd250d4d-cd66-4a34-a45a-f8dbf61854db)
**year** slot work fine.
![image](https://github.com/Vuepic/vue-datepicker/assets/20040006/dbd29325-f8ce-4334-ae0e-0d92a852dc8d)
but, when I click the year , the selectionOverlay is not working as expected.
![image](https://github.com/Vuepic/vue-datepicker/assets/20040006/9291ffda-3368-413e-bfa1-aa47dccc3f1a)

@vuepic/vue-datepicker version 6.1.0

and https://vue3datepicker.com/slots/overlay/#year doesn't show the year ( Chrome 117 , Ubuntu )

**Comment by Jasenkoo** [comment]
@pantoffski Looks like a misspelled slot name, will fix it in the next release, in the meantime, you can use it as `year-overlay-val`

**Comment by pantoffski** [comment]
thanks a lot
