### ISSUE TITLE
Set month view to first allowed-date

### ISSUE THREAD

**Issue by camaech** [Vuepic/vue-datepicker#250]
**Is your feature request related to a problem? Please describe.**
If I set allowed-dates to a future range, it would be nice if the calendar view would auto open to the proper month.

**Describe the solution you'd like**
Allow calendar to open at a specific month.

**Additional context**
Here's a quick gif of how it works, showing the user has to manually go to the next month.
![2023-01-24 15 39 06](https://user-images.githubusercontent.com/977957/214427215-ffd7f02f-59a2-4936-a210-509a4f4c4356.gif)

**Comment by Jasenkoo** [comment]
If you want to preset the view, you can use [`start-date`](https://vue3datepicker.com/props/calendar-configuration/#start-date) prop.
