### ISSUE TITLE
reactive v-model change to a different month does not change visible month/year in inline mode

### ISSUE THREAD

**Issue by gerritvanaaken** [Vuepic/vue-datepicker#256]
If somewhere else the v-model is changed to a different month, like from Jan 27 to June 6th, the inline Datepicker does not jump to the new Month/Year view.

You can test this on the playground, see below.
I use "setMonthYear()" manually to fix the problem, but that shouldn’t be necessary!

`````
<template>
  <button @click="setDate">Change date to June 6th</button>
  <div>
    <Datepicker v-model="date" inline ref="pickerEl" />
  </div>
</template>

<script setup>
import { ref } from 'vue';
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

const date = ref();
const pickerEl = ref(null);
const setDate = () => {
  date.value = new Date('2023-06-12T23:50:21.817Z');
  //pickerEl.value.setMonthYear({ month: 5, year: 2023 });
};
</script>

`````

**Comment by gerritvanaaken** [comment]
syncing with (custom) timepicker also doesn’t work.
Problem came with version 3.6.4 – 
in 3.6.3 everything was fine.

**Comment by DMOAbove** [comment]
I do have the same problem with 3.6.5.

I am using preset ranges and multi-calendar, and when I click on a preset range to select a specific range, on the calendar it doesn't sync with that date. So if I am seeing January and February 2023 and click on a preset with 10 December-20 December 2022, it still keeps the calendar on the same months. It should keep track and automatically set the correct Month and Year.
