### ISSUE TITLE
max-navigation on arrows

### ISSUE THREAD

**Issue by DMOAbove** [Vuepic/vue-datepicker#258]
**Describe the bug**
Dunno if its a bug or intended. But if I've max-navigation set, I am not able to go to max dates I select using the months, years, BUT if I click on the arrows I am able to navigate and see the calendar onwards. Shouldnt block the arrow too?

Using last version

**Comment by Jasenkoo** [comment]
You can use [`prevent-min-max-navigation`](https://vue3datepicker.com/props/calendar-configuration/#prevent-min-max-navigation) prop.

**Comment by DMOAbove** [comment]
I am using it... But as I said, doesn't apply to the arrows...

**Comment by Jasenkoo** [comment]
@DMOAbove Can you show me what props are you using?

**Comment by DMOAbove** [comment]
Sure, @Jasenkoo 
```
      ref="dp"
      v-model="date"
      @update:modelValue="handleDate"
      range
      :preset-ranges="presetRanges"
      :enableTimePicker="true"
      :format-locale="locale"
      format="P"
      locale="en"
      :placeholder="$translate('PlaceholderText')"
      monthNameFormat="long"
      hideInputIcon
      :cancelText="$translate('CancelButton')"
      :selectText="$translate('AcceptButton')"
      multi-calendars
      :markers="markers"
      :day-names="weekDays"
      :max-date="futureDate"
      prevent-max-navigation
```

**Comment by Jasenkoo** [comment]
@DMOAbove The prop is called `prevent-min-max-navigation` (basically works on both ways) instead of `prevent-max-navigation`, updated your [sandbox](https://codesandbox.io/s/vue3-datepicker-forked-8bdimj)

**Comment by DMOAbove** [comment]
Facepalm -.- And I look into it more then once.

Thanks for pointing the obvious. Appreciated. All good :)
