### ISSUE TITLE
Setting flow on monthYear component 

### ISSUE THREAD

**Issue by delinext** [Vuepic/vue-datepicker#26]
I need to use only year picker but if selected year is equal to current year user can select month too. So I used `monthYearPicker` and then i got a problem with setting flow. I used `:flow="['year', 'month']"` props but picker adding calendar date selection too.
how can I find solution?

Month picker flow sets in the right way if i add `monthYearPicker` and `flow` there have to be only month and year selection

**Comment by Jasenkoo** [comment]
WIll check, didn't test with specific modes

**Comment by Jasenkoo** [comment]
Changed tag to enhancement, since it is not added for specific modes.
