### ISSUE TITLE
SyntaxError: ambiguous indirect export: default

### ISSUE THREAD

**Issue by zozulinskyi** [Vuepic/vue-datepicker#260]
**Describe the bug**
I have some problem after update to v.3.6.6
I don't know whats happen but I see this error in console after update.
Maybe some problems with update date-fns in your package.

I was try to reproduce this error on stackblitz
At previous version all be fine.

**To Reproduce**
https://stackblitz.com/edit/nuxt-starter-evtvmi

**Comment by Jasenkoo** [comment]
Ah, this is supposed to be fixed by the `date-fns-tz`, will publish a patch in a bit

**Comment by zozulinskyi** [comment]
@Jasenkoo thank you for your job. It helped me.
