### ISSUE TITLE
Preselected value on "only timePicker" mode is not working properly

### ISSUE THREAD

**Issue by geek-monkey** [Vuepic/vue-datepicker#268]
**Describe the bug**
when trying to define a preselected value for the timePicker it doesn't work and the result value is always the current time

**To Reproduce**
1. Configure the datepicker to be on timepicker only (time-picker)
2. Define a preselected value (in my case I defined a value for the binded variable in mounted()
4. We see the current time preselected on page load instead of the defined time

**Expected behavior**
On page load we should see the defined value in mounted() preselected. 
Note that I tested this with the datetime picker and only datepicker and it works perfectly

**Desktop & mobile (please complete the following information):**
 - Browser:  Chrome
 - Library version 3.6.7

**Comment by Jasenkoo** [comment]
How does your `v-model` looks?

**Comment by geek-monkey** [comment]
@Jasenkoo, this is what my configuration looks like :
```
<Datepicker
        timezone="Europe/Brussels"
        format="'HH:mm'"
        model-type="format"
        locale="fr"
        auto-apply
        hide-input-icon
        time-picker
        :date-picker="false"
        v-model="value"
        @update:modelValue="handleTime($event)"
  > </Datepicker>
```

I found out the problem. 
I made a computed that returns a formatted time string from the returned object ( value returned by Vuepic Datepicker {hours:HH, minutes:mm, seconds:ss)} and I transform it to HH:mm)
```
let date = moment();
date.set('hour', this.value.hours);
date.set('minute', this.value.minutes);
return date.format('HH:mm');
```
The issue is that when setting a preselected value I passed directly a formatted string for exemple 12:30 instead of passing an object. So what is missing is the opposite workaround to transform the formatted string to an object.

So the question is, is there a way to configure the timepicker to return directly a formatted string ?

**Comment by Jasenkoo** [comment]
Ok, tnx, yes this should be achievable with `model-type`, will add this feature.
