### ISSUE TITLE
Duplicated mounth in inline mode

### ISSUE THREAD

**Issue by tokarskadiana** [Vuepic/vue-datepicker#27]
**Describe the bug**
The same month is displayed on both sides of the datepicker when the date range is selected on the right-side calendar. The issue occurs when using datepicker with such options constellation: `inline range multiCalendars`.

**To Reproduce**
1. Set these options to datepicker: `inline range multiCalendars`
2. Select the date range on the right-side calendar
4. See the error

**Screenshots**
![chrome-capture-2022-3-21](https://user-images.githubusercontent.com/18469065/164513288-cddc515e-b8b3-4966-aa15-047b0adcf957.gif)

**Desktop & mobile (please complete the following information):**
 - Browser - Chrome
 - Lib ver - 3.1.1

**Comment by noah-osso** [comment]
I just came to log the same issue :). Is there a way we can have it work same as the example here, i.e. just show selection in interacted calendar and not affect the other calendars?

http://www.daterangepicker.com/#examples

**Comment by Jasenkoo** [comment]
Yes, it will be handled, already working on it
