### ISSUE TITLE
Performance problem with disabled-dates

### ISSUE THREAD

**Issue by francoromanol** [Vuepic/vue-datepicker#271]
Hi, I'm having a performance issue when `disabled-dates` receives a large amount of dates (+500). [See an example](https://king-prawn-app-2ab7q.ondigitalocean.app/huis-ibiza/casa-dalias/#availability) of one site I am working on.

**To Reproduce**
1. Create an array with > 500 dates and use range mode.
2. Change months or select a range of dates.

**Expected behavior**
When receives fewer dates, it works as expected. [See example](https://king-prawn-app-2ab7q.ondigitalocean.app/huis-ibiza/algarroba/#availability).

**Desktop & mobile (please complete the following information):**
 - Browser: tested in Chrome and Safari.
 - Library version: 3.6.5

Thank you

**Comment by Jasenkoo** [comment]
Because it has to check for other things and perform validation. 

My suggestion is to use a function instead of providing an array:

`(date: Date) => boolean`, basically, you will get the date that is being checked and you return `true` if it is disabled, otherwise `false`

**Comment by franco-onevillas** [comment]
That worked as expected, thanks mate!
