### ISSUE TITLE
Auto apply and month/year tabs

### ISSUE THREAD

**Issue by snakeislong** [Vuepic/vue-datepicker#273]
**Describe the bug**
When you click on month or year tabs and pick a date, auto apply mode doesn't work and you need to quit and choose month by arrows. It doesn't work on chrome - on safari, firefox it works properly

**To Reproduce**
1. Turn on auto-apply mode
2. Click on datepicker
3. Click on month or year tabs and choose them
4. Now you can't pick a date

**Desktop & mobile (please complete the following information):**
 - Browser [chrome 109.0.5414.119 (Official Build) (arm64) ]
 - Library version [3.6.7]

**Comment by Jasenkoo** [comment]
Are you sure you updated the component? This was already fixed, try reinstalling.

**Comment by snakeislong** [comment]
> Are you sure you updated the component? This was already fixed, try reinstalling.

Great thanks! I've cleared the cache and it works fine)
