### ISSUE TITLE
Scoped styles not working due to v-if on teleport.

### ISSUE THREAD

**Issue by SvetoslavHalachev** [Vuepic/vue-datepicker#274]
**Describe the bug**
I'm trying to override with scoped styles to match my design, but I saw that the teleport has `v-if`  which I think is preventing the scoped styles feature to apply the correct data attributes.

**To Reproduce**
Here is an example with scoped styles: [https://codesandbox.io/s/distracted-morning-nhjj0l?file=/src/App.vue](https://codesandbox.io/s/distracted-morning-nhjj0l?file=/src/App.vue)

You can see that the red background is applied only to the input but not the Datepicker dropdown itself, due to having `v-if` on the teleport [here](https://github.com/Vuepic/vue-datepicker/blob/main/src/VueDatePicker/VueDatePicker.vue#L22).

Here is also an example if the codesandbox url does not work:

```
<template>
  <Datepicker v-model="date"></Datepicker>
</template>

<script setup>
import { ref } from "vue";
import Datepicker from "@vuepic/vue-datepicker";
import "@vuepic/vue-datepicker/dist/main.css";

const date = ref();
</script>

<style scoped>
.dp__theme_light {
  --dp-background-color: red;
}
</style>
```

**Expected behavior**
After applying the following:

```
<style scoped>
.dp__theme_light {
  --dp-background-color: red;
}
</style>
```

The red background to be applied to all the places that have `.dp__theme_light` classname, in our case to both input and Datepicker dropdown.

**Screenshots**
# Issue:

![image](https://user-images.githubusercontent.com/31817561/217397909-a241be58-e6b7-4361-8ee0-1d5f73609b70.png)

# How it should be(for example when we remove scoped it works as expected or if we use inline property the scoped styles will work because the datepicker does not have `v-if`):
![image](https://user-images.githubusercontent.com/31817561/217398016-6ebd7ca2-269d-46e2-9b3c-51ff89c65d82.png)

**Desktop & mobile (please complete the following information):**
 - Browser `Version 109.0.5414.119 (Official Build) (x86_64)`
 - Library version `"@vuepic/vue-datepicker": "^3.6.7"`

**Comment by Jasenkoo** [comment]
@SvetoslavHalachev You can use `deep` selector in css. Working [example](https://stackblitz.com/edit/vuepic-vue-datepicker-ky9wtd?file=src%2Fcomponents%2FPlayground.vue).

**Comment by arslanakhtar61** [comment]
@Jasenkoo `deep` selector in css is not working for the latest release v7.4.1. Could you please update the example supporting the latest version
