### ISSUE TITLE
hide-navigation prop does nothing

### ISSUE THREAD

**Issue by kskrlinnorth2** [Vuepic/vue-datepicker#277]
**Describe the bug**
There is hide-navigation prop in documentation that (as I understood) should hide navigation buttons for specified areas. If we, for example, set `['year']` as prop then there shouldn't be navigation button to select year in datepicker.

**To Reproduce**
https://vue3datepicker.com/props/general-configuration/#hide-navigation

Here is example in documentation, but it also doesn't change anything visually.

**Expected behavior**
To be able to hide year button in datepicker and have only month picker in top navigation.
(I could hide it with css, but there is no difference in month and year html, other than aria-label which is not something I would use to style element)

**Desktop & mobile (please complete the following information):**
 - Browser latest chrome
 - Library version 3.5.2 (not using latest version because it has some bugs mentioned in issues)

**Comment by Jasenkoo** [comment]
@kskrlinnorth2 As you can see in the description it says that it hides the buttons from overlays, useful if you use `flow` prop.
