### ISSUE TITLE
The installation example code displays an eslint error 

### ISSUE THREAD

**Issue by dakaii** [Vuepic/vue-datepicker#278]
![Screenshot 2023-02-10 at 12 21 46 AM](https://user-images.githubusercontent.com/8836096/217855169-5a93555d-ce0a-498d-a676-401990e74d6a.png)

I copied and pasted the chunk of code shown in Readme and got a `multi-word-component-names` warning.
https://eslint.vuejs.org/rules/multi-word-component-names.html

What do you think about changing the imported variable name to `DatePicker`? (I already made the necessary changes in my local repo)
https://github.com/dakaii/vue-datepicker/tree/warning/multi-word-component-names

**Comment by Jasenkoo** [comment]
@dakaii You can name the component however you want. I'll change it in the example to be more up-to-standard.

**Comment by dakaii** [comment]
@Jasenkoo Cool! Thanks!
