### ISSUE TITLE
Functionality to shift tab back to the previous field

### ISSUE THREAD

**Issue by spencerhines57** [Vuepic/vue-datepicker#28]
**Is your feature request related to a problem? Please describe.**
Currently creating a form that has multiple inputs. Trying to allow to user to tab/ shift-tab back and forth throughout the fields so they do not have to use a mouse if they choose not to.

**Describe the solution you'd like**
The ability to press shift+tab, and have the focus be moved to the previous input field. Currently works for tabbing forward, but appears that shift+tab t move backwards is disabled by default.

**Describe alternatives you've considered**
Had a work around partially working but it required me to hard code what each previous field was going to be, ideally I wanted to use this generically.

**Comment by Jasenkoo** [comment]
Will check

**Comment by Jasenkoo** [comment]
This is kinda tricky to handle since the menu is not in the native HTML order, but added to the body via teleport. What I will do is handle the logic and emit the event when `shift+tab` is pressed. It is up to the devs to handle which element to focus afterwards.
