### ISSUE TITLE
auto-apply is not working with in calendar

### ISSUE THREAD

**Issue by HariKathem** [Vuepic/vue-datepicker#280]
**Describe the bug**
**Actual** :
If we use auto-apply attribute in the datepicker am not able to see the Driver Pool custom button.

link is added below you can see that issue :
https://stackblitz.com/edit/vuepic-vue-datepicker-ksehzs?file=src%2Fcomponents%2FPlayground.vue

**Expected behavior**
If we use auto-apply attribute in the datepicker i should see the Driver Pool custom button.

**Screenshots**

![image](https://user-images.githubusercontent.com/119420817/218015912-70e28f03-0733-400c-a96b-b04172b4a4fc.png)
![image](https://user-images.githubusercontent.com/119420817/218016491-f5d16d2d-a7f0-40ed-8cf7-2d0ee71a9f22.png)

**Comment by Jasenkoo** [comment]
@HariKathem This is intended since `auto-apply` will hide the action row. You can pass [`keep-action-row`](https://vue3datepicker.com/props/general-configuration/#keep-action-row) prop to keep it.
