### ISSUE TITLE
Unhandled "useContext() called without active instance." during setup

### ISSUE THREAD

**Issue by hielkedehaan** [Vuepic/vue-datepicker#281]
**Describe the bug**
After following the installation manual the datepicker is not loading.
Vue 3 with script setup.

**To Reproduce**
Install using steps on: https://vue3datepicker.com/installation/
after adding the     <Datepicker v-model="date"></Datepicker> the page crashes.
also tried without v-model="date".

**Expected behavior**
I expected the date picker to show on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/76853388/218106419-da975c04-2085-462b-b179-54545399ab8e.png)

**Desktop & mobile (please complete the following information):**
 - chrome

**Comment by Jasenkoo** [comment]
@hielkedehaan Can you provide more context, like, vue version, node version, cli/nuxt/vite builds, global or per component import?

**Comment by hielkedehaan** [comment]
Thanks for responding so quickly!

Here are the version which I am currently running:
Vue: v3.2.45
Node: v19.1.0
Vuetify: v3.0.3
Vite: v3.2.4

Imported per component using the <script setup>method.

I reduced my component to just include the DatePicker, the problem still persists.

I hope this helps a bit!

**Comment by Jasenkoo** [comment]
Ok, this seems kinda rather specific to a project. Try using node 18. Are you sure that after removing the Datepicker the error warning is still present?
