### ISSUE TITLE
utc

### ISSUE THREAD

**Issue by qxygene** [Vuepic/vue-datepicker#284]
**Describe the bug**
Setup is;

          <Datepicker
            v-model="date"
            inline
            :transitions="false"
            :enable-time-picker="false"
            auto-apply
            range
            min-range="1"
            multi-calendars
            hide-offset-dates
            prevent-min-max-navigation
            :month-change-on-scroll="false"
            :utc="false"
          >

Still giving utc time. [v3.6.6] has no issue.

**Comment by Jasenkoo** [comment]
If you try to directly print the array to HTML, it will show as it is in the UTC, however, if you inspect each date or log the array, it is in the correct timezone.

**Comment by qxygene** [comment]
unfortunately log also shows UTC

**Comment by Jasenkoo** [comment]
@qxygene Can you post a screenshot of how it looks like?

**Comment by Jasenkoo** [comment]
You can see that it is displaying correct dates [here](https://stackblitz.com/edit/vuepic-vue-datepicker-ca5nik?file=src%2Fcomponents%2FPlayground.vue), also `:utc="false"` is redundant since it is disabled by default.

**Comment by qxygene** [comment]
https://pasteboard.co/DYXOK4eaz0IZ.png current time here is 15:23

**Comment by Jasenkoo** [comment]
@qxygene That is ok because it is a string representation. If you do it in the code, like `console.log()` you can see that it has the timezone appended.

**Comment by qxygene** [comment]
console shows same.

**Comment by cn-2k** [comment]
> Issue is with range mode, default calendar works fine. **Solved** by using utc="preserve" with range mode.

This solved my problem. My calendar was starting one day short.
