### ISSUE TITLE
fixed-start ignores min-range

### ISSUE THREAD

**Issue by qxygene** [Vuepic/vue-datepicker#287]
**Describe the bug**
Fixed-start ignores min-range, also needs to disable select date before start date (it selects but not effecting) and not applying .dp__range_between class on hover.

```
      <VueDatePicker
        v-model="date"
        inline
        auto-apply
        range
        min-range="1"
        fixed-start
        hide-offset-dates
        multi-calendars
        :month-change-on-scroll="false"
        :transitions="false"
        :enable-time-picker="false"
        :min-date="new Date()"
      />
```

**Comment by Jasenkoo** [comment]
Fixed in 718ea724321057d834867dc01491c88c55209ce5 , will be included in the next version, missing #, adding a comment for reference.
