### ISSUE TITLE
minutes-grid-increment issue with version 4.0.1

### ISSUE THREAD

**Issue by kkino0110** [Vuepic/vue-datepicker#288]
When select the minutes, will show "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')"
if delete minutes-grid-increment="30", it's work.

                      <datepicker
                        v-model="open_time"
                        :clearable="false"
                        timePicker
                        minutes-grid-increment="30"
                        auto-apply
                        @update:modelValue="update_time()"
                        textInput
                      />

**Comment by kkino0110** [comment]
it's still not work after i follow your solution, will be fine in next version? @Jasenkoo

**Comment by starker-xp** [comment]
Hello when is the next merge planned?

**Comment by Jasenkoo** [comment]
Sometime during the next week
