### ISSUE TITLE
New DOM Order Popup Doesn't Work with Overflow Hidden Container

### ISSUE THREAD

**Issue by nruffing** [Vuepic/vue-datepicker#290]
**Describe the bug**
With the move to placing the popup directly next to the input in the DOM this causes issues based on the position and overflow values of the inputs ancestors.

I am currently trying to use the date picker in a table/grid header that is nested in several ancestors with an overflow value of hidden. This causes the calendar popup to appear cutoff. I unfortunately don't have much control over the markup and the styles are brittle. 

This worked prior to v4 with the teleport.

**To Reproduce**
I made a very simple recreation [here](https://codesandbox.io/s/strange-architecture-h9gtdq?file=/src/main.vue).

**Expected behavior**
A couple of options come to mind
* Should teleport vs DOM order be an option?
* Would something like [Floating Vue](https://floating-vue.starpad.dev/) be a good option to handle all cases and leverage how much it can be customized?
* Could just the contents of the calendar popup be abstracted to a component and exported so that consumers could put it into something like Floating Vue?

**Screenshots**
![image](https://user-images.githubusercontent.com/30451189/220487292-3ba1fae7-f55e-4987-b51b-aba01e377152.png)

**Desktop & mobile (please complete the following information):**
 All
 - Library version [e.g. 3.0.0]
4.0.1

**Comment by Jasenkoo** [comment]
Yes, I know this can be an issue, however, some component libraries like `headless-ui` don't like when the components are in the teleport because it also uses teleport. Anyway, I'll return the teleport functionality alongside the dom order.

**Comment by rogyvoje** [comment]
Encountered the same issue when updating to the latest, read the changelog and saw that the default way is changed, which is good, but It would be good to have it as an option to teleport to body, because it is a very useful feature to have especially with overflow hidden

**Comment by anton-liam** [comment]
hi, Does this feature have release time. cause I need it now. thanks

**Comment by Jasenkoo** [comment]
@anton-liam Wednesday
