### ISSUE TITLE
Calendar not showing when opening the datepicker

### ISSUE THREAD

**Issue by arnelpayongayong** [Vuepic/vue-datepicker#291]
Mac (Safari)

**Comment by nico-clbr** [comment]
I've been getting the same problem (I think).

![image](https://user-images.githubusercontent.com/41972243/220693146-08e9970e-fb5a-4042-a3bf-8be358ddf2bb.png)

vue: 3.2.47
@vuepic/vue-datepicker: 4.0.1

Tried with and without custom styles, and no change.

**Comment by Jasenkoo** [comment]
Do you have issues with `v3.6.8`?

**Comment by nico-clbr** [comment]
> 

Tried with v3.6.8, but got similar result.

![image](https://user-images.githubusercontent.com/41972243/220709416-bbcb56ce-c344-44fd-bae4-65d6119c789d.png)

**Comment by Jasenkoo** [comment]
This might be caused byseparate background color, I couldn't reproduce it on safari. If the problem still occurs, please create a demo so I can check it in more detail
