### ISSUE TITLE
Auto-apply aplied on last flow and not for all

### ISSUE THREAD

**Issue by StevenHeven** [Vuepic/vue-datepicker#295]
**Describe the bug**
When auto-apply props is implemented, it's apply for the last flow. It will be apply on every step.

**To Reproduce**
My simplified component : 
```
<template>
  <div>
    <Datepicker
      v-model="date"
      format="yyyy-MM-dd HH:mm"
      keepActionRow
      auto-apply
      enableTimePicker
      :flow="flowStep"
      :text-input="true"
      :text-input-options="{ format: 'yyyy-MM-dd HH:mm' }"
    />
  </div>
</template>

<script setup>
import { ref } from 'vue';
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

const date = ref();
const flowStep = ref(['calendar', 'time']);
</script>
```
You have playground here : [Playground](https://stackblitz.com/edit/vuepic-vue-datepicker-mzb8gm?file=src%2Fcomponents%2FPlayground.vue)

**Expected behavior**
With my example, I want to update value when I select Date AND select time. For the moment, it's only when we select time. The user can be edit just the date and not the time. 

**Screenshots**
![Auto-apply-bug](https://zupimages.net/up/23/09/e8xx.gif)

**Desktop & mobile (please complete the following information):**
DatePicker version : 4.0.1

**Comment by Jasenkoo** [comment]
This is not a bug, it is expected behavior, I can add another prop to allow date selection even if the flow is not on the last step.

**Comment by StevenHeven** [comment]
I hesitate to decide if it's bug or wants feature ^^ 
Perfect, I tried when you push it ^^ 
Tell me how to implement that ;) 
Thx for your quick answer and patch ;)

**Comment by StevenHeven** [comment]
Thx for your fix, but if you have `textInput` props, the last flow not has not autoApply. 

[Playground here](https://stackblitz.com/edit/vuepic-vue-datepicker-mzb8gm?file=src%2Fcomponents%2FPlayground.vue)

**Comment by StevenHeven** [comment]
@Jasenkoo did you see the last message ?

**Comment by StevenHeven** [comment]
I don't talk if we write value on input, I mean your fix works to apply at every step if we have not `text-input` specified to true. Try on Playground to select date in calendar and also time after .... the auto-apply on selection in calendar works but not after in time selection.

Try here [Playground](https://stackblitz.com/edit/vuepic-vue-datepicker-mzb8gm?file=src%2Fcomponents%2FPlayground.vue)

**Comment by Jasenkoo** [comment]
I see, reopening
