### ISSUE TITLE
Possible DOM memory leak?

### ISSUE THREAD

**Issue by lightwalker01** [Vuepic/vue-datepicker#302]
**Describe the bug**
When VueDatePicker component is added to and then removed from DOM, many detached objects remain even after GC.

**To Reproduce**
1. Go to [this NPM Playground](https://codesandbox.io/s/npm-playground-forked-mjwgn5?file=/index.html)
2. Open browser DevTools (i'm using Edge) and select "Detached Objects" tab
3. Select app target 
![image](https://user-images.githubusercontent.com/7263833/222747035-b0c441e4-5afc-487f-9f88-6ca64715666d.png)
4. Get detached elements 
![image](https://user-images.githubusercontent.com/7263833/222747507-d8e4f084-b238-4354-b5b7-f552a9b09988.png)
5. Click the "clickme" button inside the playground to see the calendar 
![image](https://user-images.githubusercontent.com/7263833/222747811-fefeb344-d5e2-46f0-a2d8-d821ea9ef203.png)
6. Click another time to hide the calendar
7. Launch GC 
![image](https://user-images.githubusercontent.com/7263833/222748034-f6e940ef-95dc-43f3-94ef-79a197f79018.png)
8. Get detached elements 
![image](https://user-images.githubusercontent.com/7263833/222748206-4fddde0f-5102-4ffa-980f-33fa0de57efc.png)

**Expected behavior**
There are no DOM detached objects

**Desktop & mobile (please complete the following information):**
 - M$ Edge 110.0.1587.57
 - Vue 3.2.47
 - VueDatePicker 4.1.0

**Comment by Jasenkoo** [comment]
@lightwalker01 Nice catch, thank you for reporting this After some investigation, discovered that the actual cause for this are SVG icons. Will need to investigate a little why this is happening.

**Comment by lightwalker01** [comment]
@Jasenkoo I thought it was because of “click outside” directive or something like that…
Thanks for your very fast resolution!
Next Monday I will update the package on my project.
