### ISSUE TITLE
How to focus picker with ref

### ISSUE THREAD

**Issue by Marcel-Sass** [Vuepic/vue-datepicker#306]
**Describe the bug**
How do i focus the input field. I tried to set a ref to the component and i set the uid prop but still no results when i look into the refs.

I am trying to forcus the input field when my validation fails (it fails when no date was selected)

The documentation does not provide a good example

**To Reproduce**
1. set uid and ref prop to something like "datepicker"
2. try to call this.$refs["datepicker"].input.focus(); or this.$refs["datepicker"].["datepicker"].focus();

**Expected behavior**
I want the field to be focused like any other field so the user sees which field he has missed to fill

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by Jasenkoo** [comment]
You can't use the `ref`, I mean theoretically, you can but would require drilling down the object tree to get the input. The easiest way is to provide `uid` prop and do the javascript select

```js

const inputEl = document.getElementById(`dp-input-${uid}`)
inputEl.focus()

```
