### ISSUE TITLE
Time picker is collapsed when clicking time 'icon'

### ISSUE THREAD

**Issue by daniel-res** [Vuepic/vue-datepicker#308]
**Bug**

When enabling a time picker along with date picker, the time picker does not transition fully. It remains collapsed with scroll bars and a very tiny height (see gif)

**To Reproduce**
Code is as follows
```html
      <VueDatePicker
        v-model="dateTimeRange"
        :dark="true"
        range
        six-weeks
      >
```

**Expected behavior**
Time picker expands / calendar is hidden

**Screenshots**
![pet](https://user-images.githubusercontent.com/123706002/223794440-13d65fd4-3527-4fe3-b97a-f841bb1d7e31.gif)

**Desktop & mobile (please complete the following information):**
 - Desktop, Chrome
 - Library version:  "@vuepic/vue-datepicker": "^4.2.0"

**Comment by Jasenkoo** [comment]
If you initialized a new project using vite, go in the global `CSS` file and find global selection `*` and remove `position: relative`

**Comment by gyuudon3187** [comment]
> If you initialized a new project using vite, go in the global `CSS` file and find global selection `*` and remove `position: relative`

@Jasenkoo Can you please share with us exactly which class that is affected by `position: relative`? Unfortunately removing `position: relative` entirely from the global selection is not an option for me as it causes me other layout issues.
