### ISSUE TITLE
Question: Using ISO8601 string format 

### ISSUE THREAD

**Issue by Kingside88** [Vuepic/vue-datepicker#309]
Hi,
i try to use it inside a nuxt application. 
How to work with string values? It looks like it only accepts Date objects.
But in the real world you get data from your'e api in ISO8601 string format.
Can vue-datepicker handle it?
What I tried so far:

```
import VueDatePicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css'

let time = ref<string>("08:30:00")

<template>
            <VueDatePicker 
                format='HH:mm:ss' 
                v-model="time" 
                time-picker 
                :is-24="true" 
                text-input.bool='true' 
                dark
                :text-input-options="{ 'format': 'HH:mm' }"
                />
</template>
```

**Comment by Jasenkoo** [comment]
@Kingside88 Please refer to [`model-type`](https://vue3datepicker.com/props/general-configuration/#model-type) prop.

In your case, you can just add `:model-type="'format'"` or provide a custom pattern.
