### ISSUE TITLE
Calendar becomes unresponsive after trying to change the v-model variable

### ISSUE THREAD

**Issue by cxammar** [Vuepic/vue-datepicker#311]
**Describe the bug**
I'm trying to set the calendar value from a Date object. In my code I play with the Date variable back and forth being this variable modified both by the vue datepick component and by outside components.
The console is clear from errors but the Vue Datepick component stops updating the value and responding to changes on the v-model variable after this variable is modified from an outside component.

**To Reproduce**
1. I'm trying to create a process of giving appointments
2. If the user tries to access a day where now timeslots are available (i.e the day is fully booked) I change "Date" (the v-model variable) to the next available day through an external piece of code
3. After doing this the calendar stops responding to clicks on the day which was moved out of (the day that was full)

**Expected behavior**
I expected the calendar to remain responsive.

**Screenshots**
1. After trying to access a fully booked day I move the user to the next day (in the screenshot the 10th). After doing so the day that was originally trying to be accessed turns light gray (like it was on hover even though it's not anymore) [Screenshot 1](https://i.ibb.co/1QNGPdC/Screenshot1.png)
2. If we click away to another date and try to click back on the day that was fully booked (9th) the day turns blue and does nothing (as you can see the columns on the right are not updating anymore). [Screenshot 2](https://i.ibb.co/JB5yscr/Screenshot2.png)
3. That day is unresponsive until a full page reload and no error show up on the console.

**Desktop & mobile (please complete the following information):**
 - Vue 3

**Comment by Jasenkoo** [comment]
@cxammar Please update this [playground](https://stackblitz.com/edit/vuepic-vue-datepicker-vzxkg7?file=src%2Fcomponents%2FPlayground.vue) with your config, otherwise this will be closed. As you can see in the example, an externally modified `v-model` has no effect on the date picker. The value is updated accordingly.
