### ISSUE TITLE
Wrong date when using text-input

### ISSUE THREAD

**Issue by gustavjh** [Vuepic/vue-datepicker#312]
Hi. 
When I select a date with mouse in the calendar (22/03/2023), I get this date: `2023-03-22T10:58:00.000Z`. However, when I use text-input and select the exact same date (22/03/2023) I get this date `2023-03-21T23:00:00.000Z`. So it goes from the 22nd, to 21st. My guess is that it is the time that affects the date. 

My date picker code
```ts
<vue-date-picker
        v-model="selectedDate"
        :enable-time-picker="false"
        placeholder="Add inspection date"
        auto-apply
        text-input
        :text-input-options="{ format: 'dd/MM/yyyy' }"
        :disabled="props.disabled"
        hide-input-icon
        :format="formatDateForPreview"
        input-class-name="dp-custom-input"
        calendar-cell-class-name="dp-custom-cell"
        @update:model-value="handleUpdate"
        @cleared="clearDatepicker"
        @closed="datepickerInputIsHovered = false"
        @mouseenter="datepickerInputIsHovered = true"
        @mouseleave="datepickerInputIsHovered = false"
     />
```
Because I have disabled time picker, is there a way to set a "default" time?

**Comment by Jasenkoo** [comment]
@gustavjh Yes, this is what it looks like when you stringify the date object, it is the same date. You can use the `startTime` prop, however, it will have no effect on the `text-input` date, will have to fix that.

**Comment by gustavjh** [comment]
@Jasenkoo thank you for looking into it. How do I use your change in https://github.com/Vuepic/vue-datepicker/commit/9fdf01ac342b34a7dd697f0f554bd1a20d8d24b8?
