### ISSUE TITLE
month-view doesn't fade

### ISSUE THREAD

**Issue by Claiyc** [Vuepic/vue-datepicker#313]
**Describe the bug**
When switching from the month-selector to the time-selector, the month-selector doesn't fade. This results in the time-selector being wrapped inside the small field reserved for the button (see screenshot below).

It is probably an issue on my side as I don't expect that I'm the first to discover an issue like that, however I have no idea what it could be.
I use vuetify, however I didn't notice any css overwriting anything of the component.
I did however notice that the 'flow-step' attribute of the 'dp__calendar' div jumps to '-1' when clicking the button for the time-selector. That looks kind of odd to me...

**To Reproduce**
Default config

**Expected behavior**
month selector should fade, giving the time-selector enough space

**Screenshots**
![grafik](https://user-images.githubusercontent.com/58397976/225156448-eda4fc5f-f411-4752-8f0f-2c42ccf509a4.png)

**Desktop & mobile (please complete the following information):**
tested with edge and firefox

**Comment by Jasenkoo** [comment]
Please check this [comment](https://github.com/Vuepic/vue-datepicker/issues/308#issuecomment-1460706050).

**Comment by Claiyc** [comment]
> Please check this [comment](https://github.com/Vuepic/vue-datepicker/issues/308#issuecomment-1460706050).

Thanks, that did the trick!
