### ISSUE TITLE
there has any whay to change the input class style  ?

### ISSUE THREAD

**Issue by murilolivorato** [Vuepic/vue-datepicker#316]
there has any whey to change the input class style  ?
this one ?

[https://i.ibb.co/0yqGHgx/input.png](url)

could I make lsomething like this ? 

```
 <VueDatePicker v-model="date" range :partial-range="false"  class="form-control" />

or

 <VueDatePicker v-model="date" range :partial-range="false"  class-input="form-control" />

```

**Comment by baturali** [comment]
I think you can add a classname to the input element with `input-class-name` and then style it as you want

**Comment by Jasenkoo** [comment]
As @baturali answered, use [`input-class-name`](https://vue3datepicker.com/props/look-and-feel/#input-class-name)

**Comment by Thuytran79** [comment]
Question:
I try to used [input-class-name](https://vue3datepicker.com/props/look-and-feel/#input-class-name)
but it's not worked 
It like:
input-class-name="dp-custom-input"
.dp-custom-input {
    height: 18px;
 }

**Comment by amit-soni7** [comment]
> input-class-name
I am using like follwing.
hope this might help you
 ```
 <VueDatePicker
      input-class-name="bg-background border-x-0 border-t-0 border-b focus:border-b-2 focus:ring-0 border-blue-700 rounded-none "
      v-model="form.dob"
 >
 </VueDatePicker>
```
