### ISSUE TITLE
Select multiple months like multi-dates from month-picker type calendar

### ISSUE THREAD

**Issue by baturali** [Vuepic/vue-datepicker#318]
**Is your feature request related to a problem? Please describe.**
The problem is that I have a table which holds some data for each and every different month and in my table months are comparible side by side. So the user should be able to add 2 or more columns to compare by month. 

**Describe the solution you'd like**
In order to solve that, user should have the option to select multiple months on month-picker type calendar.

**Describe alternatives you've considered**
Two Multi-calendar in the beginning, then user add more and select one month from per calendar.

**Additional context**
I tried to enable it with `:month-picker="true"`and `:multi-dates="true"` but as expected it does not work.

**Comment by Jasenkoo** [comment]
I will have to check the amount of code required for something like this, to see if it is worth it.

**Comment by baturali** [comment]
Many thanks @Jasenkoo, please let me know if I can contribute for that.
