### ISSUE TITLE
Range picker question/request.

### ISSUE THREAD

**Issue by kovaletsyurii-hue** [Vuepic/vue-datepicker#319]
Hello! Thanks for the great date picker, it works perfectly fine. But I haven't found a way to select only "end date" using range selector. Whenever I select a date it is automatically selected as the start date. Is it possible to select only the end date in a range selected by e.g. multiple calendars?

**Comment by Jasenkoo** [comment]
Take a look at [`fixed-start`](https://vue3datepicker.com/props/modes-configuration/#fixed-start) prop.

**Comment by kovaletsyurii-hue** [comment]
@Jasenkoo thanks for answer. 
This is not exactly what i need. I would like to be able to choose only end_date when start_date is empty and vice versa, so I would like to get a ranges like [2023-03-22, null] or [null, 22-03-2023], with only one date specified in the entire range. this would be very useful in situations where you need to specify an exact date range, or only the start date, or only the end date.
