### ISSUE TITLE
Format && utc: false

### ISSUE THREAD

**Issue by SHrebeniuk** [Vuepic/vue-datepicker#320]
Hello!
I wanna get a `String` by  `:format` 
I saw `preserve the original UTC time.` description, but it will be really cool and look more logical if `utc: false` - block UTC convertation

**Comment by Jasenkoo** [comment]
@SHrebeniuk You don't have to provide the `utc` prop at all, and just use [`model-type`](https://vue3datepicker.com/props/general-configuration/#model-type) prop with the desired string output
