### ISSUE TITLE
day-class does not work

### ISSUE THREAD

**Issue by micskubence** [Vuepic/vue-datepicker#322]
i cant get day class attribute to work i do everything as the documentation says even just creating a function which returns a class without any validation does not work calling it like :day-class="'bg-red'" does not work calendar-cell-class-name meanwhile works fine.

**Comment by Jasenkoo** [comment]
These are 2 different types of props, `day-class` accepts a function:

```vue
<template>
  <VueDatePicker :day-class="dayClass" />
</template>

<script setup>
const dayClass = (day) => {
    /**
    * if (day === myDate) return "my-class"
    * return undefined;
    * or always return a string if you want a class applied on all dates
    */
}
</script>
```
