### ISSUE TITLE
MonthPicker with max-date option

### ISSUE THREAD

**Issue by umang1995** [Vuepic/vue-datepicker#323]
**Describe the bug**
I am trying to use the component and its really good. 
While validation, I observed that If i am keeping It as monthpicker and applying max-date = new Date() its not enabling the select button at all. I am using OptionsAPI in vue 3.
Code Below : 
<VueDatePicker
        v-model="date"
        range
        :month-picker="isMonth"
        :year-picker="isYear"
        @open="updated_duration"
        @close="getGroupsVehicles"
        ref="myDatesPicker"
        :format="formatDate"
        :partial-range="false"
        :no-today="true"
        :multi-calendars="!isMonth && !isYear"
        :clearable="false"
        :enable-time-picker="false"
        :prevent-min-max-navigation="true"
        :ignoreTimeValidation="true"
        :disableTimeRangeValidation="true"
      ></VueDatePicker>

**To Reproduce**
1. Initialize the picker in month range mode.
2. Feed it max-date
3. Try to open the picker

**Expected behavior**
If the dates are selected properly, Select button should be enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/17137778/226376081-2d70926f-ee84-4294-b02a-2a5b614c626b.png)

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by umang1995** [comment]
Okay an update, after checking various scenarios - 
if we keep below conditions - 
1. partial range is false
2. month picker
3. enable time picker as false
4. ignore time validation true
5. disable timerange validation true
6. selected date is feb 2023-feb 2023.

And keep maxDate as 31st march then its **working as expected**,
but when we change maxDate to 1st march then it behaves weirdly, and does not pass any validations.

**Comment by Jasenkoo** [comment]
Fixed in 76507d2d0a3894239f922ec58de1d4247c2c6577, adding as reference

**Comment by umang1995** [comment]
@Jasenkoo  Great man. You are Amazing. By when would this be released??

**Comment by Jasenkoo** [comment]
Published, closing now.
