### ISSUE TITLE
multi-calendars not reactive

### ISSUE THREAD

**Issue by qxygene** [Vuepic/vue-datepicker#327]
**Describe the bug**
`:multi-calendars="$vuetify.display.mdAndUp ? true : false"`

![clipboard](https://user-images.githubusercontent.com/2819611/227937394-99e5ec40-dc29-41f1-9c73-171240836516.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by Jasenkoo** [comment]
@qxygene what props are you using?

**Comment by qxygene** [comment]
```
        v-model="date"
        inline
        auto-apply
        range
        min-range="1"
        hide-offset-dates
        :multi-calendars="$vuetify.display.mdAndUp ? 1 : false"
        utc
        :locale="locale"
        :month-change-on-scroll="false"
        :transitions="false"
        :enable-time-picker="false"
        :min-date="new Date()"
        prevent-min-max-navigation
        :dark="sessionStore.theme === 'dark' ? true : false"
```

**Comment by qxygene** [comment]
thank you for fast fix.
