### ISSUE TITLE
Add possibility to clear/update only 1 value [start or end] of picked range

### ISSUE THREAD

**Issue by kprotasevich** [Vuepic/vue-datepicker#328]
**Is your feature request related to a problem? Please describe.**
Hello, first of all, thanks for a great extension.

My issue is: I would like to have a way to clear/update only 1 value of a chosen range. Currently I can only clear both of them together.
For example: I select range [28.02.2023 - 27.03.2023] on the calendar. Then I want to clear/update only first value - [28.02.2023]  make calendar to await for user to select a new value instead of old (or empty) one. Just one click and that's it.
(Just like when you pick start date and move your mouse to pick the second one - hover effects on days and everything). If the date is not picked (calendar closed/cancelled) - just return old value or 1 value (if multi-calendar is enabled) or null, since range is not filled properly (it's up to you and depends on logic).
The same thing if you want to clear/update the end date of the range - start date remains selected and the end is awaiting for user
_To clear start date and end date at the same time **clearValues/updateInternalModelValue([null, null])** work fine)_ 

**Describe the solution you'd like**
Update updateInternalModelValue method somehow with additional arguments would be nice
Or if there is an option how to implement this scenario using existing code base - I would appreciate your hint.
Currently you have to select first and last day. And if you notice miss click on the first day, you need to click on the first day and after that on the last day to confirm range. But to change only first day would be enough

**Comment by Jasenkoo** [comment]
This is an edge case that requires a lot of checks to be done. You can check `partial-range`, `fixed-start`, and `fixed-end` props to make this work, watch for `internalModelChange`, and update `fixed-[start/end]` based on it for example.
