### ISSUE TITLE
Can't prevent user from typing disabled dates into text input

### ISSUE THREAD

**Issue by YusufcanY** [Vuepic/vue-datepicker#33]
**Describe the bug**
Can't prevent user from typing disabled dates into text input.

**To Reproduce**
1. Disable a date
2. Enter that date to input
3. Then click enter

**Expected behavior**
Maybe dont set set the model value or set date the last successful date.

**Screenshots**
![image](https://user-images.githubusercontent.com/55593600/165284795-ac3f0401-e041-4b60-a6b0-7f2a08666806.png)

**Comment by Jasenkoo** [comment]
I will see to include it in the next version, validation on the text input is not implemented.

**Comment by Jasenkoo** [comment]
You can use max or min date as usual, if the date is not valid, it will not be selected

**Comment by YusufcanY** [comment]
Okayy, what about disabled and allowed dates?

**Comment by Jasenkoo** [comment]
Agh, forgot about the allowed dates, disabled dates should work. Will add the allowed dates also in the next patch

**Comment by YusufcanY** [comment]
Nice but i couldn't work with disabled dates either.

**Comment by Jasenkoo** [comment]
Ok, I will see what is going on

**Comment by Jasenkoo** [comment]
@YusufcanY Here is an [example](https://stackblitz.com/edit/vuepic-vue-datepicker-svj8f3?file=src%2Fcomponents%2FPlayground.vue) with disabled dates, works as expected. What is the diff between the example and your code?
