### ISSUE TITLE
Docs are not accurate for deconstructing v-model

### ISSUE THREAD

**Issue by cwbombora** [Vuepic/vue-datepicker#332]
**Describe the bug**
The documentation here: https://vue3datepicker.com/methods-and-events/events/#update-model-value does not match the available properties on the component itself.

**Expected behavior**
The code example should read: 

`
<VueDatePicker :modelValue="date" @update:model-value="handleDate" />
`

The correct property is `modelValue` not `value`

**Comment by amav96** [comment]
i had the same issue with  <VueDatePicker :value="date" @update:model-value="handleDate" />
the correct code is  <VueDatePicker :modelValue="date" @update:model-value="handleDate" />
