### ISSUE TITLE
Clicking year, month and time the content is not showing in Nuxt3.

### ISSUE THREAD

**Issue by vincent-dante** [Vuepic/vue-datepicker#334]
**Describe the bug**
When clicking year, month and time the content is not showing in Nuxt3.

**Expected behavior**
Datepicker should be showing Year, Month, Time
**Actual behaviour**
Datepicker is not showing Year, Month, Time
**Screenshots**

![Capture1](https://user-images.githubusercontent.com/32755874/229067223-f786cced-0b8e-4a80-9f85-1c9fd27fbab0.PNG)

I check the DOM and it's not setting the height properly.
![Capture2](https://user-images.githubusercontent.com/32755874/229067548-e9949e75-0091-4820-8472-f769abd2c23e.PNG)

**To Reproduce**
1. Click year
2. Click month
3. Click time icon

**Desktop & mobile (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Library version 4.2.3

**Comment by Jasenkoo** [comment]
Please refer to this [comment](https://github.com/Vuepic/vue-datepicker/issues/308#issuecomment-1460706050).
