### ISSUE TITLE
Wrong value when using @update:model-value

### ISSUE THREAD

**Issue by apias88** [Vuepic/vue-datepicker#335]
I don't quite know how to solve this one. I'm calling `setFilters()` function when the value is selected from the datepicker and expect this value to be sent along with other filters via api to request new data. But, for some reason it always sends the previously picked value instead of the new one. I tried using `@internal-model-change`, but that's even worse - api gets called twice, first time on clicking the input and second time on leaving it. 

I'm using the following settings:
`<Datepicker @update:model-value="setFilters()"  v-model="filter_eta" :multiStatic="false" :auto-apply="true" :enable-time-picker="false" model-type="dd-MM-yyyy" format="dd-MM-yyyy" locale="pl"></Datepicker>`

```
<script src="https://unpkg.com/vue@3.2.47/dist/vue.global.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js'></script>
<script src="https://unpkg.com/@vuepic/vue-datepicker@latest"></script>
<link rel="stylesheet" href="https://unpkg.com/@vuepic/vue-datepicker@latest/dist/main.css">
<script>

  const app = Vue.createApp({
    components: {
      Datepicker: VueDatePicker
    },
    data() {
      return {
        orders: [],
        baseurl: baseurl,
        page: 0,
        loaderid: 0,
        filter_id: '',
        filter_label: '',
        filter_category: '',
        filter_subcategory: '',
        filter_eta: '',
        filter_assigned_to_me: '',
        noresults: false,
        endresults: false,
        categories: [],
        subcategories: [],
        fav_only: 0,
        days: 360,
        sort_by: 'created_at',
        sort_type: 'SORT_DESC',
      }
    },
    methods: {
      setFilters() {
        this.loaderid++;
        this.page = 0;
        this.noresults = false;
        this.endresults = false;
        this.orders = [];
        this.load();
      },
    
      load() {
        if (this.noresults == false && this.endresults == false) {
          axios.get(apiurl + "/partner/orders/get?page=" + this.page + "&sort=" + this.sort_by + "&token=" + token + "&days=" + this.days + "&fav_only=" + this.fav_only + "&filter_id=" + this.filter_id + "&filter_label=" + this.filter_label + "&filter_category=" + this.filter_category + "&filter_subcategory=" + this.filter_subcategory + "&filter_eta=" + this.filter_eta + "&filter_assigned_to_me=" + this.filter_assigned_to_me)
        }
      },
    },
  })
  app.mount('#app');
  AOS.init();
</script>
```

Assuming that I simply want to use v-model, what event should I call to simply allow on-change event to happen once? Similar to how `@change` works for inputs?

**Comment by Jasenkoo** [comment]
The `@update:model-value` is the event that updates `v-model` value. It is logical that when you listen to that event, it will be called before the actual value is updated. To get the value that is going to be updated, you need to get the value from the function param instead of the v-model

```js
setFilters(date) {
          // ^ this date param is the actual value you want to use
  this.filter_eta = date;
},
load() {
// the filter_eta will be in correct value now
}

```
