### ISSUE TITLE
Datepicker behavior after build

### ISSUE THREAD

**Issue by Stephax** [Vuepic/vue-datepicker#339]
Hey, 
i found a weird behavior of datepicker. When i run dev environment, datepicker works like this 
-> After remove value of datepicker, and cancel focus on it, value appear instantly again. It is wanted behavior. 
But when i run npm run build, and npm run serve it works like this
 -> After remove value of datepicker, and cancel focus on it, value dont appear. It appear only when i again click on datepicker. 
I dont have clue where can be problem. 

I setting value of datepicker on launch my application with `dateFrom = formatDateToString(new Date());`, where formatDateToString is easy formatter `export const formatDateToString = (date: Date) => format(date, 'yyyy-MM-dd');`

And this is my component 
```
          <Datepicker
            :model-value="modelValue"
            :placeholder="DATE_FORMAT"
            auto-apply
            text-input
            :close-on-scroll="true"
            :inline-with-input="true"
            model-type="yyyy-MM-dd"
            locale="sk"
            :format="DATE_FORMAT"
            :min-date="minDate"
            :max-date="maxDate"
            :prevent-min-max-navigation="true"
            :enable-time-picker="false"
            :text-input-options="textInputOptions"
            :clearable="true"
            :disabled="disabled"
            :uid="id"
            @update:model-value="$emit('update:modelValue', $event)"
          />
```

And this is how i use it
```
    <DatepickerBox v-model="dateFrom" :min-date="minDateFrom" :max-date="maxDateFrom" :errors="[]" id="dateFrom">  </DatepickerBox>
```

I really cant explain where is problem. I dont know if it is problem with datepicker, or with setting of my vue app.
Thanks for answer!

**Comment by Jasenkoo** [comment]
@Stephax I tried to reproduce. There is a misconfiguration in your props, I see you are using `inline-with-input` without the `inline` prop, don't know if is supposed to be there or not.

Also when using `auto-apply` and clearing input value, the value should be auto-updated as you type. However I managed to reproduce part of it, without passing the `inline` and `auto-apply` prop, where the removed value is not shown when the focus is lost, but instead on refocus. 

To summarize:

> After remove value of datepicker, and cancel focus on it, value appear instantly again. It is wanted behavior.
But when i run npm run build, and npm run serve it works like this

This is only possible if you are not using `auto-apply`, however, you might encounter partial parsing, for example if you just remove the day part of the date.

>  After remove value of datepicker, and cancel focus on it, value dont appear. It appear only when i again click on datepicker.
I dont have clue where can be problem.

This part I managed to reproduce and will be fixed. However, this applies only when **not** using the `auto-apply` prop.

Let me know If I got it correctly. If you are able to create some playground code to see what you are facing, it would be easier for me to detect where is the issue.

**Comment by Stephax** [comment]
Hey,
I dont find any playground which be able run just dev environment :/.. It doesnt seems that `inline` have to be used with `inline-with-input`. 

If i understand correctly -> I can't use `auto-apply` when i want to get right behavior for me. 

What release will fix this, please? I see that u commit fix, but when release? :)
