### ISSUE TITLE
Customization without sass

### ISSUE THREAD

**Issue by Xeyos88** [Vuepic/vue-datepicker#340]
How can I customize the appearance if I don't use sass in my project?

From guide you need to import :
```css
@import '@vuepic/vue-datepicker/src/VueDatePicker/style/main.scss';
```
and then modify variables, but this forces you to add dependencies.

**Comment by Jasenkoo** [comment]
I have in plan to add css variables

**Comment by sevillaarvin** [comment]
Thanks! Works like a charm.

```css
body {
  --dp-input-padding: 11px 12px;
}
```
