### ISSUE TITLE
Design with excessive space when it is only a few years range

### ISSUE THREAD

**Issue by elalekey** [Vuepic/vue-datepicker#343]
**Describe the bug**
They say a picture is worth a thousand words. <3

![image](https://user-images.githubusercontent.com/41456459/231201746-f4f0381b-7055-4dd9-8416-5a7a96d7053d.png)

Here is another example with another year-range:

![image](https://user-images.githubusercontent.com/41456459/231207280-1d364a55-56a4-43ce-9b3c-cbdf98c4281d.png)

**To Reproduce**
<VueDatePicker
    ref="datepicker"
    model-type="format"
    auto-apply
    reverse-years
    locale="es-ES"
    format="yyyy-MM-dd"
    :start-date="props.maxDate"
    :value="props.value"
    :year-range="[2020, 2023]"
  />

I use these custom props but using the specified flow and year-range should be enough to replicate the error:

![image](https://user-images.githubusercontent.com/41456459/231202760-19f1746a-d3b4-4f6a-9634-8d487b6e0b0a.png)

**Expected behavior**
It should have a cleaner design and without so much spacing, it would also be great to be able to control this spacing in a much simpler way, only when there are few elements.

**Screenshots**
![image](https://user-images.githubusercontent.com/41456459/231207209-4e7b174e-6151-48fb-a2da-8cdaa53d62c2.png)

![image](https://user-images.githubusercontent.com/41456459/231201746-f4f0381b-7055-4dd9-8416-5a7a96d7053d.png)

**Desktop & mobile (please complete the following information):**
 - Browser: All
 - Library version: 4.3.0

**Comment by Jasenkoo** [comment]
I am not sure how to design this. Perhaps, I can introduce on col per row layout if the number of years < 10 for example.

**Comment by elalekey** [comment]
@Jasenkoo Maybe something like this:

flex: 0
align-items: flex-start

![image](https://user-images.githubusercontent.com/41456459/231383862-7d5bff97-84f0-4898-b84d-91fca193ce7c.png)
