### ISSUE TITLE
`disabled-dates` callback disables wrong value

### ISSUE THREAD

**Issue by notramo** [Vuepic/vue-datepicker#344]
The value returned from the callback disables the next day. E.g. the callback gets today as its argument, returns `true`, but tomorrow is disabled in the calendar.

Sample code to reproduce:
```javascript
// this function returns `true` for today
const dateDisabled = () => date.toISOString().slice(0, 10) == (new Date()).toISOString().slice(0, 10);
```
If this sample function is specified, it should disable today in the calendar, but it disables tomorrow instead.

**Comment by Jasenkoo** [comment]
@notramo This is not a bug. You are trying to compare date object with reset time to a current date with time in `UTC` zone. For example, if you try to select today from the calendar you won't be able to do so because the selected value will match `new Date()`.

To fix this, just reset the time on `new Date()`

```ts
    const dateDisabled = (date: Date) => {
        const today= new Date();
        today.setHours(0);
        today.setMinutes(0);
        today.setSeconds(0);
        today.setMilliseconds(0);
        return date.toISOString().slice(0, 10) == today.toISOString().slice(0, 10);
    };
```

**Comment by notramo** [comment]
@Jasenkoo this happens when the compared object is not a `new Date()` but instead a string.
```javascript
const dateDisabled = () => date.toISOString().slice(0, 10) == '2023-04-16' // disables 2023-04-17
```

**Comment by Jasenkoo** [comment]
When you do `toISOString` you convert it. Try printing the date, when this condition is true, you will see that the original date object is indeed 16th.
