### ISSUE TITLE
Reformat method

### ISSUE THREAD

**Issue by DellanX** [Vuepic/vue-datepicker#345]
**Is your feature request related to a problem? Please describe.**
My code changes format depending on which mode is being used (month, week, date).
Since the method isn't reactive, to which there isn't a way to force the datepicker to realize this.
(further `$forceUpdate()` doesn't work)

**Describe the solution you'd like**
When the methodology changes, be able to call a reformat method when the format method changes.

**Describe alternatives you've considered**
Current method is multiple duplicates of the datepicker with the same parameters.
Each conditionally renders based upon the view to load.

**Additional context**

**Comment by Jasenkoo** [comment]
@DellanX do you mean just input format or actual `$forceUpdate`?
