### ISSUE TITLE
Display Issue on Mobile and Desktop

### ISSUE THREAD

**Issue by blockiyt** [Vuepic/vue-datepicker#350]
**Describe the bug**
The UI of the datepicker is buggy on mobile phones

**To Reproduce**
Build the picker into your website, and view it on mobile.

**Expected behavior**
Working and good looking datepicker

**Screenshots**
![IMG_8582](https://user-images.githubusercontent.com/65811753/232209318-85ca5dbe-31a7-4d55-865a-cc724f2ca0a1.jpg)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome & Safari
 - Library version: 4.3.0

**Comment by blockiyt** [comment]
To add: It now also doesn't work on desktop.

**Comment by Jasenkoo** [comment]
Please include css import in your app:

`import '@vuepic/vue-datepicker/dist/main.css'`
