### ISSUE TITLE
Incorrect time displayed when properties has both `range` and `time-picker`

### ISSUE THREAD

**Issue by jedymatt** [Vuepic/vue-datepicker#351]
**Describe the bug**
Incorrect time displayed in time picker with range

Input
```js
const timeRange = ref([
  '2023-04-18T09:30:00.000000Z',
  '2023-04-18T11:00:00.000000Z',
]);
```

Rendered output
![image](https://user-images.githubusercontent.com/54795428/232326021-0a43a1b8-8bab-4a45-8dfa-de89e0ebcb20.png)

The value is displayed based on the client's current time.

**To Reproduce**
1. Go to https://stackblitz.com/edit/vuepic-vue-datepicker?file=src%2Fcomponents%2FPlayground.vue
2. Modify the component by adding `range` and `time-picker` and change the `date` with `timeRange`
    ```vue
    <Datepicker v-model="timeRange" range time-picker />
    ```
4. Rename the `date` variable with:
    ```js
    const timeRange = ref([
      '2023-04-18T09:30:00.000000Z',
      '2023-04-18T11:00:00.000000Z',
    ]);
    ```
6. See output

**Expected behavior**
The output should be 09:30 - 11:00 based on the input example

**Desktop & mobile (please complete the following information):**
 - Chrome, Firefox (Desktop)
 - v4.4.0

**Comment by Jasenkoo** [comment]
You are providing the wrong `v-model`.

Check this [example](https://stackblitz.com/edit/vuepic-vue-datepicker-znmf15?file=src%2Fcomponents%2FPlayground.vue).

Additional info on [v-model](https://vue3datepicker.com/props/general-configuration/#model-value) types. If you want to use a different config, you can also check the [model-type](https://vue3datepicker.com/props/general-configuration/#model-type).

**Comment by jedymatt** [comment]
Thanks. In my case I want to retain the format even when the value is changed. 

 I can do something like [this](https://stackblitz.com/edit/vuepic-vue-datepicker-crlsdn?file=src/components/Playground.vue).

I added `model-type="format"` with `utc="preserve"`. With `utc` the value is somehow converted to  `[ "2023-04-18T09:30:00.000Z", "2023-04-18T11:00:00.000Z" ]` otherwise converted like this `[ "02:07 AM", "02:07 AM" ]` .

**Comment by Jasenkoo** [comment]
@jedymatt rechecked this, basically when you set `utc` prop it will always work with a string as per current limitations. What you can do is instead of providing `utc="preserve"` prop, remove it, and add `timezone="UTC"`. Now you will be able to set proper `model-type` if needed.
