### ISSUE TITLE
Prevented interact with inputs inside slot sidebar

### ISSUE THREAD

**Issue by rdmitrievsky** [Vuepic/vue-datepicker#356]
**Describe the bug**
I added inputs to the right sidebar, so users would have options to simply type dates, yet I just can't set focus on these inputs by clicking. If I add @click="$event.target.focus()", it'll set focused but I still cant move caret with arrow keys.
Options such as _keys.month-change-on-arrows="false"_ and _arrow-navigation="false"_ doesn't make any differences.

A simple example
```
<template>
  <VueDatePicker
    v-model="date"
    range
    @update:model-value="handleDate">
    <template #right-sidebar>
      <input type="text" v-model="startDate" />
      <input type="text" v-model="endDate" />
    </template>
  </VueDatePicker>
</template>

<script setup>
import VueDatePicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';
import { ref, computed } from 'vue';

const date = ref(null);
const startDate = ref();
const endDate = ref();

function handleDate(e) {
  console.log(e);
  if (!e) {
    return;
  }
  startDate.value = new Date(e[0]).toLocaleString();
  endDate.value = new Date(e[1]).toLocaleString();
}
</script>
```

**Desktop & mobile (please complete the following information):**
 - Browser chrome and safari @ macOs
 - Library version [e.g. 4.2.2]

**Comment by Jasenkoo** [comment]
@rdmitrievsky Just pass the `text-input` prop as `true`
