### ISSUE TITLE
datepicker does not accept incoming time in any format

### ISSUE THREAD

**Issue by dhallX** [Vuepic/vue-datepicker#357]
**Describe the bug**
as I try to update my state on a onMounted hook i find when i assign a new time value, the value does not show or  shows the current time. does not take any incoming data.

![image](https://user-images.githubusercontent.com/106660145/233615332-7b428ae6-1eb7-4ce9-b8bd-081f65e88da2.png)

**Comment by Jasenkoo** [comment]
@dhallX You are using the wrong type for [`v-model`](https://vue3datepicker.com/props/general-configuration/#model-value). The default type is `{ hours: string | number; minutes: string | number }`;  In your case you can adjust it a little:

```js
onMounted(() => {
   const time = '11:56';
   const [hours, minutes] = time.split(':');
   date.value = { hours , minutes };
});
```

Also, you can provide a manual type by setting up [`model-type`](https://vue3datepicker.com/props/general-configuration/#model-value)
