### ISSUE TITLE
Can't import "src/VueDatePicker/style/main.scss" due to export problem

### ISSUE THREAD

**Issue by genesi5** [Vuepic/vue-datepicker#359]
**Describe the bug**
I am trying to import additional `./src/VueDatePicker/style/main.scss` file for further style tuning, but instead i have this problem:

```
Syntax Error: Error: Package path ./src/VueDatePicker/style/main.scss is not exported from package /home/genesi5/dev/release-tracker/ui/release-tracker/node_modules/@vuepic/vue-datepicker (see exports field in /home/genesi5/dev/release-tracker/ui/release-tracker/node_modules/@vuepic/vue-datepicker/package.json)
 ```
According to `package.json` of the project, `./src/VueDatePicker/style/main.scss` is supposed to be exported, but giving error instead. 
File `@vuepic/vue-datepicker/dist/main.css`, also given in `package.json`, is imported just fine.

**To Reproduce**
Just follow the [instruction for local installation](https://vue3datepicker.com/installation/) of package 

**Expected behavior**
`./src/VueDatePicker/style/main.scss` file import and dev server build without errors

**Desktop & mobile (please complete the following information):**
**nodejs**: `18.16.0`
**npm**: `9.5.1`
**vue**: `3.2.13`
**@vuepic/vue-datepicker**: `4.4.0`
**@vue/cli-service**: `5.0.0`

**Comment by Jasenkoo** [comment]
You are using the wrong import for `scss`, 
the correct path is `@import '@vuepic/vue-datepicker/src/VueDatePicker/style/main.scss';
`

**Comment by genesi5** [comment]
I'm sorry, but...
![image](https://user-images.githubusercontent.com/25093320/233795274-830ce2c8-69e9-4cfd-883e-e81084838e27.png)

**Comment by Jasenkoo** [comment]
It is exported, I can't be sure what needs to be done, but this is something related to the CLI. Try changing the import with a relative or absolute path and see if it recognizes it that way.

**Comment by soorajsprakash** [comment]
Any update on this? I'm facing this issue now

**Comment by genesi5** [comment]
@soorajsprakash my fault was that i was importing it in Vue file wrong way or something like that

**Comment by soorajsprakash** [comment]
ohk, i did it too, i tried importing css file within style section. 
Now working fine

**Comment by genesi5** [comment]
@soorajsprakash Try to play with style scope or file definition (extension)
