### ISSUE TITLE
Time sections doesn't overlay

### ISSUE THREAD

**Issue by TomVanHove** [Vuepic/vue-datepicker#36]
When selecting a date, I want to select a time, but the time sections doesn't overlay the calendar. 

I'm using the [range picker mode](https://vue3datepicker.com/api/props/#range) code from the website. 

<img width="801" alt="image" src="https://user-images.githubusercontent.com/43343745/165799229-f1ed50ec-f807-4f53-874b-7f956353163f.png">

Using VUE-3

Thanks for your reply in advantage.

**Comment by Jasenkoo** [comment]
@TomVanHove Hmm this is strange, can you show me what props are you passing additionally if any? Also, are you using some CSS framework? Or did you modify some of the original styles?

**Comment by Jasenkoo** [comment]
Ok, will check

**Comment by Jasenkoo** [comment]
Checked, can't reproduce, what version of Vue and Node are you using? Are you using some bundlers like Vite or vue-cli?

**Comment by TomVanHove** [comment]
I'm using VUE-3 and Node ```v16.14.2```

Also using Vite ...

**Comment by Jasenkoo** [comment]
@TomVanHove Ok, found it, did it on a clean Vite project. Find in your `base.css` file the following statement

```css
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  position: relative;
  font-weight: normal;
}
```

Either remove the whole block or this line `position: relative;`

**Comment by TomVanHove** [comment]
This solved the problem ! Thank you a lot !!

**Comment by Jasenkoo** [comment]
No problem 😄
