### ISSUE TITLE
WARN: [vite:css] end value has mixed support

### ISSUE THREAD

**Issue by PABERTHIER** [Vuepic/vue-datepicker#361]
Since using Nuxt 3.4, this warning appeared.
The justify-content property only allowed flex-start and flex-end for this case.

To Reproduce: I go this by executing the following command to launch my projet -> nuxt dev.

I tried to correct it and to push it on a bugfix branch, but my access are denied.
Here is what I did:
![image](https://user-images.githubusercontent.com/39381248/233849313-2ffbee58-e085-45de-9db5-91c2c13b2178.png)
And same thing for this file:
vue-datepicker\docs\assets\style.6cc160ac.css
![image](https://user-images.githubusercontent.com/39381248/233849367-01718380-44fa-457c-b127-f9643eb82537.png)

**Comment by AnthonyRuelle** [comment]
Same issue here :/ 
Someone did the fix: https://github.com/Vuepic/vue-datepicker/pull/362

Merge please 🥇

**Comment by jontybrook** [comment]
Also seeing this.... please merge :)
