### ISSUE TITLE
accessible labels are broken in mac voice over

### ISSUE THREAD

**Issue by arrocke** [Vuepic/vue-datepicker#367]
**Describe the bug**
I'm a little confused why the wrapper div has the textbox role and aria attributes instead of the input element? As you can see in the dev tools, this causes two textboxes to be added to the accessibility tree. In mac voice over when using Ctrl+Alt to navigate, the label is read to me, but when tabbing through a form, it is not because the wrapper div that has the label is not focusable, and the focusable input has no label.

**To Reproduce**
You can see this problem on most of the demos in the docs.

**Expected behavior**
I would expect the aria attributes to be on the input, and the wrapper div to not have a role. It would also be nice if I could give the input an `id` without the `dp-input-` prefix so that I could connect a label element with the `for` attribute.

**Screenshots**
![Screenshot 2023-04-27 at 3 11 44 PM](https://user-images.githubusercontent.com/11968925/234980366-5cf3f771-df62-4814-84c0-b0185b17f786.png)

**Desktop & mobile (please complete the following information):**
 - Browser: chrome/edge
 - Library version: 4

**Comment by arrocke** [comment]
I'm willing to open a PR to help resolve this, but I want to make sure I'm not missing something before I do

**Comment by Jasenkoo** [comment]
@arrocke Feel free to create a PR if you want, all clear.
