### ISSUE TITLE
Dates are offset by one day

### ISSUE THREAD

**Issue by manjunathpadolkar** [Vuepic/vue-datepicker#37]
**Describe the bug**
calendar dates are offset by a day. Please see the screenshot. Timezone on my mac was set to Toronto/Canada

**To Reproduce**
1. Go to official documentation and see any of the example

**Expected behavior**

**Screenshots**
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/15189529/165856757-5022d5a5-4fe3-42bc-a0cd-a7f1e6ac1542.png">

**Desktop & mobile (please complete the following information):**
 - Browser Firefox, Chrome
 - Library version  latest

**Comment by Jasenkoo** [comment]
This is not an issue, you have the first day as Sunday (system calendar), and on the component, it is set to Monday. Days are matching.
