### ISSUE TITLE
New buttons are submitting the form they are placed in

### ISSUE THREAD

**Issue by scottshannon24g** [Vuepic/vue-datepicker#374]
**Describe the bug**
With the 5.0.0 release, the refactor of `<div role="button">` to `<button>` are causing `<form>` to submit when they are clicked. Looks like [HTML Buttons](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element) default to a "submit" action.

**To Reproduce**
This playground has a form with a submit event that shows an alert.
https://stackblitz.com/edit/vuepic-vue-datepicker-u7qfy5?file=src%2Fcomponents%2FPlayground.vue

1. Click on any of the new buttons and it will popup the submit alert.

**Expected behavior**
Form should not be submitted when clicking on the UI buttons.

**Comment by sstenn** [comment]
Correct me if I'm wrong, but it seems that this bug isnt't fixed in `SelectionOverlay.vue`
