### ISSUE TITLE
input-class-name with object not working

### ISSUE THREAD

**Issue by HelfanzaNanda** [Vuepic/vue-datepicker#376]
:input-class-name="{'error' : true}"

![image](https://user-images.githubusercontent.com/35588271/236364799-f7e785bb-d0eb-4be8-8be0-df865ca2eb4e.png)

![image](https://user-images.githubusercontent.com/35588271/236364874-70ab1fae-a687-4df0-9c44-16d7ba20bd90.png)

**Comment by Jasenkoo** [comment]
`input-class-name` accepts only string for now. I don't think there will be support for a different type anytime soon.
