### ISSUE TITLE
MInutes are not selectable when using both min-time and max-time on 12h setting

### ISSUE THREAD

**Issue by scorpanog** [Vuepic/vue-datepicker#379]
**Describe the bug**
Using this props 
                  :min-time="{ hours: 5, minutes: 0 }"
                  :max-time="{ hours: 6, minutes:55 }"
                  :is-24="false"
                  minutes-increment="30"
                  partial-flow
                  :flow="['calendar', 'time']"
does not let me choose minutes, all selections are disabled. 
As it seems to work for AM time,  I wonder how to set it for PM times. Docs have no indication of that.

**To Reproduce**
Steps to reproduce the behaviour:

1. Set those props
2. try to open the datepicker
3. select the date
4. click on minutes.
5. all of them are disabled

**Expected behaviour**
I would assume that I should be able to pick time in the specified interval.

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Browser [e.g. chrome, safari] Firefox, MacOs Ventura 13.3.1
 - Library version [e.g. 3.0.0] 5.0.1
<img width="264" alt="Screenshot 2023-05-07 at 11 14 20 PM" src="https://user-images.githubusercontent.com/16922716/236725852-d1c4822d-0568-450b-812c-6b98fe3bc327.png">

**Comment by Jasenkoo** [comment]
You have set the value to `PM`. Where if you set the value to `6 PM` for example, the code sees it like `18:00`. I can add an event for button click and you can then adjust the time validation from `6` to `18`
