### ISSUE TITLE
Range Date Picker

### ISSUE THREAD

**Issue by airtonctj** [Vuepic/vue-datepicker#38]
Hello good Morning,

how to format the date when the range is true.
format example: dd/MM/yyyy

thanks

**Comment by Jasenkoo** [comment]
Hi, there are 2 ways you can format the date.

1. By providing a string in an appropriate format with [valid codes](https://date-fns.org/v2.28.0/docs/format) . Keep in mind that we are proving here a format for a single date, e.g. `format="dd/MM"`, the library will then use that format and show selected dates as `dd/MM - dd/MM`

2. By using a format function. In range mode, the function will provide a param of `Array` type with selected dates. Code would look something like this

```ts
const dateFormatter = (date: Date): string => {
  const day = date.getDate();
  const month = date.getMonth() + 1;
  const year = date.getFullYear();

  return `${day}/${month}/${year}`;
}

// Note: if partial range is enabled, second date can be null
const format = (dates: [Date, Date?]) => {
    if (dates[0] && dates[1]) {
      return `${dateFormatter(dates[0])} - ${dateFormatter(date[1])}`       
    }
    if (date[0]) {
       return `${dateFormatter(dates[0])}`
    }
    return ''
}

``` 

Then on the component reference you pass it as a prop

```html
<Datepicker :format="format" />
```
