### ISSUE TITLE
Property auto-apply not working consistently in combination with property text-input

### ISSUE THREAD

**Issue by limsbeheer** [Vuepic/vue-datepicker#380]
**Describe the bug**
When you apply both the properties `auto-apply` and `text-input` you sometimes have to click twice on the day number to force a change in the date.

**To Reproduce**
1. Open in the browser a page with the following HTML (or see [jsfiddle](https://jsfiddle.net/d3zh819r/))
```
<script src="https://unpkg.com/vue@latest"></script>
<script src="https://unpkg.com/@vuepic/vue-datepicker@5.0.1"></script>
<link rel="stylesheet" href="https://unpkg.com/@vuepic/vue-datepicker@latest/dist/main.css">

<div id="app">
  <vue-date-picker v-model="date" auto-apply text-input></vue-date-picker>
</div>

<script>
Vue.createApp({
  components: {
    VueDatePicker
  },
  data(){
    return {
     date: new Date
    }
  }
}).mount('#app');
</script>
```
2. Click on the date to open the menu and click on a day number, other than today. The menu is closed and the date has changed.
4. Again open the menu and click a another day number: no change, only after a second try.

**Expected behavior**
A click on the day number should always directly force a change in the date.

**Desktop & mobile (please complete the following information):**
 - Browser Google Chrome 112.0.5615.139
 - Library version 5.0.1

**Comment by crandall-endeavor** [comment]
I'd just like to report that we're seeing the same thing. :)

**Comment by ffeynmann** [comment]
I have the same problem when using auto-apply and text-input attributes

**Comment by Dodje** [comment]
Same thing. Even more.
Actually it is a bug when the date selection popup closes after the click on any place in it. That's why the date is not being selected after the click.

**Comment by limsbeheer** [comment]
Thanks for fixing this!

**Comment by crandall-endeavor** [comment]
Thanks!
