### ISSUE TITLE
Uncaught (in promise) Error: "range" prop must be enabled!

### ISSUE THREAD

**Issue by CharlesSAUVAT** [Vuepic/vue-datepicker#382]
Hello, 

I have this error, with this code (Uncaught (in promise) Error: "range" prop must be enabled!) on confirm click button.
`<VueDatePicker
                    v-model="sort.date"
                    range
                    locale="fr"
                    cancelText="Annuler"
                    selectText="Confirmer"
                    @update:model-value="sortArray()"
                  >
                    <template #trigger>
                      <i class="fa-regular fa-calendar tableIcon"></i>
                    </template>
                  </VueDatePicker>`

**Comment by Jasenkoo** [comment]
@CharlesSAUVAT What does `sort.date` looks like and the method `sortArray()`?

**Comment by Jasenkoo** [comment]
I tried to replicate it, but couldn't. Also, you should not call `sortArray` when passing, just provide the function definition. One more note, keep in mind that `@update:model-value` is called before the `v-model` gets updated if you manipulate the data in it.

**Comment by BetonZM** [comment]
I have same error and I am not using any props...

Ver. 5.1.0

**Comment by Jasenkoo** [comment]
This error comes from 2 possible scenarios, either you are providing an array of `length === 0` with range, or using an array without specifying `range` mode.
