### ISSUE TITLE
Showing date and time in the same panel

### ISSUE THREAD

**Issue by abumalekFayed** [Vuepic/vue-datepicker#388]
showing date and time in the same panel will be pretty for quick selection without additional click on time icon 
![image](https://github.com/Vuepic/vue-datepicker/assets/47514686/4249b269-95e6-45c2-bcc5-6223a1d90da3)

**Comment by Jasenkoo** [comment]
I'll leave this open for now, to see what other people think of it. Right now you can use a custom slot and add a custom time picker. [example](https://vue3datepicker.com/slots/components/#time-picker).

**Comment by 3essame** [comment]
Yes this will be v good and more applicant.

**Comment by abumalekFayed** [comment]
Thank you 3ssam.

**Comment by nitishswipezbriq** [comment]
very good it will save user one step to update time 👍

**Comment by Vladoker** [comment]
is there an opportunity to do so ?
![image](https://github.com/Vuepic/vue-datepicker/assets/45948200/6452cca5-3dcf-4183-8d79-9c93a171e5cf)

**Comment by abumalekFayed** [comment]
Dou you mean minimize view or multiple date selection

**Comment by abumalekFayed** [comment]
Thank you v much for this powerful addition to your amazing date picker

**Comment by eneeio-nm** [comment]
@Jasenkoo just wanted to say thanks for implementing this 👍
