### ISSUE TITLE
Rane Date Picker

### ISSUE THREAD

**Issue by jaromanda** [Vuepic/vue-datepicker#39]
**Describe the bug**
When setting a minDate you can not navigate to that month from the next month - e.g. minDate set to 1 May 2022, if you open the calendar and go to the next month, you can no longer navigate back to May 2022

**To Reproduce**
1. Set minDate to today
2. Open Calendar
3. Navigate to next month
4. Can no longer navigate to this month

**Expected behavior**
You should be able to navigate to this month

**Desktop & mobile (please complete the following information):**
 - Browser, Chrome 101 and Firefox 99 and 100
 - Library version 3.2.0

This worked fine in 3.1.1

**Comment by Jasenkoo** [comment]
Hmm, do you have enabled `preventMinMaxNavigation`?

**Comment by jaromanda** [comment]
Yes, I have enabled `preventMinMaxNavigation`
