### ISSUE TITLE
How can i hide time picker in DatePicker

### ISSUE THREAD

**Issue by nitishswipezbriq** [Vuepic/vue-datepicker#394]
can u plz help how can i hide timepicker and time in datepicker
if i need only date in datepicker

![Uploading Screenshot 2023-05-18 at 12.15.12 PM.png…]()

**Comment by abumalekFayed** [comment]
set enable-time-picker to false will hide time icon

**Comment by nitishswipezbriq** [comment]
not working
plz check below example:
https://stackblitz.com/edit/vuepic-vue-datepicker-v1eafw?file=src%2Fcomponents%2FPlayground.vue

**Comment by abumalekFayed** [comment]
:enable-time-picker not enable-time-picker

**Comment by nitishswipezbriq** [comment]
thanx working now

**Comment by abumalekFayed** [comment]
Please give your opinion for this
https://github.com/Vuepic/vue-datepicker/issues/388
