### ISSUE TITLE
An option to show the timepicker after a date is selected

### ISSUE THREAD

**Issue by mark1502** [Vuepic/vue-datepicker#395]
If this option is enabled, when the user clicks on a date, the time overlay then appears without the user needing to click on the time icon.  Basically, one click on a date selects the date and then also operates as a click on the time icon.

Another datepicker (Tempus Dominus) has options for this called 'promptTimeOnDateChange' and 'promptTimeOnDateChangeTransitionDelay'.

But the Vue-datepicker is much better for Vue applications, so it would be great if you could add this type of feature.

Thanks

**Comment by abumalekFayed** [comment]
You can use flow prop to automatically open time picker after date selection 
Use :flow ="['calendar','time']"

**Comment by mark1502** [comment]
That’s great, I’ll give a try!  Thanks!
