### ISSUE TITLE
toogle menu open and close when input is empty

### ISSUE THREAD

**Issue by Dois3d** [Vuepic/vue-datepicker#397]
Hello!

I trying to use that component in a  vue web component created with vue 3.2 and build with vite. When the input is empty and i click the menu is show and when i click again, the menu dind't close.  my expectetion is the same behavior when the input have data. 

second problem:

Using in a modal, i'm facing problems with the menu. He is hiding under the footer and cutting the left side.

![image](https://github.com/Vuepic/vue-datepicker/assets/61029774/02dc1c3b-6299-4230-986a-c09e90ddd071)

third problem is,  when i build as a web component, because of the shadowroot, the css is lost even when i import on the component. Localy works

can some one help?

**Comment by abumalekFayed** [comment]
please write your code.

**Comment by Dois3d** [comment]
here a partial problem repro.

by removing the date, the toggle does not happen.

https://codesandbox.io/p/sandbox/vue-date-picker-phwql1

In codesandbox the menu open using teleport, but with some strange behavior, but in my application, teleport makes the menu appear at the bottom of the page.
