### ISSUE TITLE
Start date is not used if v-model is filed

### ISSUE THREAD

**Issue by Tyki** [Vuepic/vue-datepicker#398]
**Describe the bug**
I'm providing startDate & v-model in a multi-calendar 

Lets say we are in may and you are selecting a date in June, you can't go back to may even if the startDate is set to 2023 may

**To Reproduce**
```
<Datepicker
    ref="datepicker"
    :model-value="modelValue"
    :enable-time-picker="false"
    :min-date="minRangeDate"
    :auto-apply="autoApply"
    :max-range="DATE_PICKER_MAX_RANGE"
    :min-range="minimumStayDuration"
    :max-date="maxRangeDate"
    :inline="true"
    hide-offset-dates
    keep-action-row
    month-name-format="long"
    :multi-calendars="count" // 13
    prevent-min-max-navigation
    :month-change-on-arrows="false"
    :month-change-on-scroll="false"
    :space-confirm="false"
    :start-date="currentDate()"    // new Date()
```

**Expected behavior**
Start at the date provided and not the v-model value since the v-model value is the user selected but not the configuration of the calendar L125-126

Issue probably comes from calendar.ts https://github.com/Vuepic/vue-datepicker/blob/30650ae5711c981a7ad24688dcf81cf4a466c564/src/VueDatePicker/composables/calendar.ts#L125

**Comment by Jasenkoo** [comment]
it is not a bug, it is intended behavior. I'll tag this as a feature
