### ISSUE TITLE
minutesIncrement from grid

### ISSUE THREAD

**Issue by Ceyar** [Vuepic/vue-datepicker#4]
Hello,  i am trying to use the minutesIncrement functionality. It works but not as expected for my case.

If I set `minutesIncrement="5"` ad I click on the date Picker when it's `08:06` and then increment the value of the minute by `5`, I get `08:11, 08:16, 08:21 ...` and so on. Would be nice if we would get a param to say that it should take the the increment like the grid for example:

If it is `08:06` and I increment the value, the next value should be `08:10` (the next multiple of 5 in this case) and not `08:11`.

Maybe there is a workaround?

So thank you for your help and your great plugin, I hope the explanation is clear.

Cheers

**Comment by Jasenkoo** [comment]
Will adjust

**Comment by Jasenkoo** [comment]
After some investigation, this is a rather specific case to handle in the component, however, you can adjust it yourself:

1. Set `startTime` to `{ minutes: 0 }`, this way it will always start minutes from 0 and will increment properly in your case

Or

2. Create a computed property that will round minutes to the round number:

```vue
<template>
  <Datepicker v-model="date" :startTime="{ minutes: roundMinutes }" minutesIncrement="5" />
</template>

<script lang="ts" setup>
import { computed, ref } from 'vue';

const date = ref();

const roundMinutes = computed(() => {
    const minutes = new Date().getMinutes();
    return minutes - (minutes % 5);
});
</script>
```

Hope it will do the job.

**Comment by Ceyar** [comment]
Hey @Jasenkoo ho sure that make sense. Thank you for your time.

Cheers
