### ISSUE TITLE
autoApply with range

### ISSUE THREAD

**Issue by csbszb** [Vuepic/vue-datepicker#40]
@Jasenkoo nice plugin!

Wanted to ask real quick whether it would be possible to use the autoApply option with the range option without having to open the date selector twice.
Right now when I select a start date, the popup is closed because of the autoApply and need to open the date selector again to be able to select the end date as well.

Thanks!

**Comment by Jasenkoo** [comment]
Thank you. Can you try disabling the [partialRange prop](https://vue3datepicker.com/api/props/#partialrange) and tell me if it works. Also, you can disable auto-closing but keep `auto-apply` with [closeOnAutoApply prop](https://vue3datepicker.com/api/props/#closeonautoapply)

**Comment by csbszb** [comment]
I think I have an edge-case here as I'm using the monthPicker.
When I use the regular date picker the range selector is working fine.

**Comment by Jasenkoo** [comment]
Ok, will fix it, should not close after the first selection
