### ISSUE TITLE
minutes-grid-increment get error

### ISSUE THREAD

**Issue by mukiwu** [Vuepic/vue-datepicker#401]
here is my code, it's work:

```
<VueDatePicker v-model="dimensionRange" minutes-increment="3" time-picker range />
```

but if I add ` minutes-grid-increment="3" `, get something error:

![截圖 2023-05-23 18 13 46](https://github.com/Vuepic/vue-datepicker/assets/3794103/a3304d3c-7d92-47a5-8041-483ec0c2317c)

**Comment by thammer67** [comment]
I am seeing the same error using the same setup:

`<VueDatePicker v-model="zeroTime" :start-time="zeroTime" time-picker minutes-increment="15" minutes-grid-increment="15" />`

**Comment by devstack-be** [comment]
still got the same error with     "@vuepic/vue-datepicker": "^5.2.0",

 <Datepicker
              v-model="form.start_time"
              :dark="isDark"
              minutes-increment="15"
              minutes-grid-increment="15"
              time-picker
              range
              :clearable="false"
              auto-apply
            >
