### ISSUE TITLE
Add option to select a range of all dates until a date

### ISSUE THREAD

**Issue by Sf298** [Vuepic/vue-datepicker#403]
**Is your feature request related to a problem? Please describe.**
Not related to a problem with the datepicker. But I have a situation where I would like the user to select all dates up to a given date. Essentially a partial-range, but for all dates before a date, rather than all dates after a date.

**Describe the solution you'd like**
I'm not sure if this is good enough for people to understand it intuitively, but my idea is a button just below the calendar that acts as selecting a 'null' date. It could be titled "dates up to" and "and after" before the 1st and 2nd clicks respectively.

**Describe alternatives you've considered**
I have thought about adding a clear date button on the left and right of the date picker to set their respective values to null, however I seem to get errors if the start date is 'null'.
I don't really have any other ideas to try.

**Additional context**
My end goal is to use this for record filtering, so that the user can filter records by date. they may at some point look for all items up to a certain date.

P.S.
I love this component, it seems to just work really well unlike other ones I've tried, well done everyone!

**Comment by Jasenkoo** [comment]
Checked the implementation, and it will require quite a modification to achieve this behavior, you can just use a single picker and disable before/after dates based on the selected date.
