### ISSUE TITLE
week-picker + multi-calendars display issues

### ISSUE THREAD

**Issue by hsmett** [Vuepic/vue-datepicker#405]
**Describe the bug**
With the `week-picker` option enabled, when enabling `range` + `multi-calendars`, weeks are not highlighted on hover anymore.

According to the documentation those options are compatible with each other, is it true?
https://vue3datepicker.com/props/modes/#multi-calendars

**To Reproduce**
Compare:
```
      <VueDatePicker inline week-picker range multi-calendars/>
```
With:
```
      <VueDatePicker inline week-picker/>
```

**Expected behavior**
We could expect the week we're hovering to be highlighted (class: dp__cell_auto_range)
We could also expect the selected week to be highlighted (the whole week, class: dp__range_between_week)

**Screenshots**
![Capture du 2023-05-24 11-44-13](https://github.com/Vuepic/vue-datepicker/assets/1230876/6346caca-cc86-4884-bde5-1cc120b5e800)
![Capture du 2023-05-24 11-44-17](https://github.com/Vuepic/vue-datepicker/assets/1230876/246afdeb-139d-4adc-80b0-7044efcdbb5c)

**Desktop & mobile (please complete the following information):**
 - Firefox 113.0.1 (64 bits)
 - Google Chrome Version 113.0.5672.63 (Build officiel) (64 bits)
 - Library version 4.2.2

Thank you very much for your outstanding work on this library, let me know if you need more information

**Comment by Jasenkoo** [comment]
There is actually a conflict here, I'll fix this as part of the #393 where `range` prop shouldn't be required anymore for `multi-calendars`
