### ISSUE TITLE
Menu reopening when using mask in text-input on range calendar

### ISSUE THREAD

**Issue by Condelamar** [Vuepic/vue-datepicker#408]
**Describe the bug**
When i use the v-mask to mask the field in date range, letting the user type the date without selecting it in the calendar, the menu keeps reopening when the date is selected and only closes on the blur event. Obs: I use the v-mask with the calendar and it works, but, it's the single calendar, not the range.

**To Reproduce**
1. Use v-mask in the date range
2. Use text-input prop in the date range
3. Use this mask on v-mask (v-mask="'##/##/#### - ##/##/####'")
4. Type a date and select it.

**Expected behavior**
It was expected that the calendar would close when selecting the date, without reopening and closing only in the blur.

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Chrome
 - 4.5.1 and 5.1.2

Video below:

https://github.com/Vuepic/vue-datepicker/assets/78701182/27e75370-2342-4e6b-a5a7-807ae9a68986

**Comment by kovaletsyurii-hue** [comment]
Same issue occurred with v-maska package while using single date mode

**Comment by kovaletsyurii-hue** [comment]
Found little tricky solution: Close date picker menu programmatically once mask is completed. I think there is an issue with v-maska library.
