### ISSUE TITLE
The current month of previous years selected when you change the year from year picker modal

### ISSUE THREAD

**Issue by baturali** [Vuepic/vue-datepicker#409]
**Describe the bug**
The last available or the current month of the year is selected after year selection, when the month-picker prop is true. Arrow left and arrow right works as expected (no preselected value when the year change), so the behaviour should be same whenever we select the year from year picker. 

**To Reproduce**
1. Use month-picker with any value
2. Try to select another year instead of current one in the year selector modal

**Expected behavior**
The year should be changed, but there should be no selected value for given year.

**Screenshots**
<img width="320" alt="Screenshot 2023-05-26 at 13 45 15" src="https://github.com/Vuepic/vue-datepicker/assets/20440419/a4c24723-1546-4287-b453-d65dad1e137a">
<img width="317" alt="Screenshot 2023-05-26 at 13 45 24" src="https://github.com/Vuepic/vue-datepicker/assets/20440419/4ef76503-92a4-49c4-b6e3-39edecaaff82">

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: "^4.3.0"

**Comment by Jasenkoo** [comment]
This was intended behavior, will see how to handle this correctly.
