### ISSUE TITLE
open calendar on input icon click

### ISSUE THREAD

**Issue by marcelruiter** [Vuepic/vue-datepicker#41]
I would like to show the datepicker by clicking on the calendar icon.
How can I make this happen?

The code below doesn't work.

`<template #input-icon="{ open }">
    <img class="input-slot-image" src="/logo.png" @click="open" />
</template>`

**Comment by Jasenkoo** [comment]
Do you mean icon in the input field or to replace input with just an icon?

> `<template #input-icon="{ open }"> <img class="input-slot-image" src="/logo.png" @click="open" /> </template>`

This will not work due to a blocking event from the parent, will have to do a little adjustment in order to make it work.
