### ISSUE TITLE
Can't set the height of the datepicker input - also cannot set focus to the datepicker input

### ISSUE THREAD

**Issue by mark1502** [Vuepic/vue-datepicker#412]
I cannot set the focus to a datepicker input.  After one date field is completed, I'd like it to go to the next date field and open the calendar.

I've tried using the focus() method with document.getElementByID,  but the datepicker does not receive the focus.

Thanks

**Comment by Jasenkoo** [comment]
@mark1502 Everything works as expected, take a look at this [playground](https://stackblitz.com/edit/vuepic-vue-datepicker-tnvmfh?file=src%2Fcomponents%2FPlayground.vue).
