### ISSUE TITLE
how do i set the time ?

### ISSUE THREAD

**Issue by Vladoker** [Vuepic/vue-datepicker#415]
Hello I have encountered the problem that the time picker does not have the ability to prohibit a certain hour or minute 

It is possible to set the hours from and to.

I want to be able to set certain hours as in the screenshot  
![image](https://github.com/Vuepic/vue-datepicker/assets/45948200/569c00b3-455d-44a4-ba45-c94d84fd734c)

**Comment by Vladoker** [comment]
my goal is to limit the appointment schedule and only display the allowed free time

**Comment by Jasenkoo** [comment]
You can use `min-time` or `max-time` props, combinations with `min-date` and `max-date`, in the next version, the new prop will be available `disabled-times` #406
