### ISSUE TITLE
Wrong style and not functionality with @vue/compat

### ISSUE THREAD

**Issue by Trojan13** [Vuepic/vue-datepicker#417]
**Describe the bug**
If you setup a new project with vite and @vue/compat the style is broken and the VueDatePicker does not update its value.

**To Reproduce**
1. Setup new project with `npm create vite@latest`
2. Add  @vue/compat to your depencencies following [this migration guide](https://v3-migration.vuejs.org/migration-build.html)
3. Add @vuepic/vue-datepicker according to the documentation
4. Add the datepicker to the `HelloWorld.vue`

Try it out:
[Codesandbox](https://codesandbox.io/p/github/Trojan13/vuepic-vue-datepicker-compat/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clibcbz33000b356nf185yprd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clibcbz33000d356n74sc1jwr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clibcbz33000b356nf185yprd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clibcbz33000a356n2g24gg3x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clibcbz33000b356nf185yprd%2522%252C%2522activeTabId%2522%253A%2522clibcbz33000a356n2g24gg3x%2522%257D%252C%2522clibcbz33000d356n74sc1jwr%2522%253A%257B%2522id%2522%253A%2522clibcbz33000d356n74sc1jwr%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clibcc54f007a356n7wdpb7zb%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clibcc6l900c3356np9z634qf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clibcc6l900c3356np9z634qf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**
The styling and the component should work. 

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/6168895/1ca928fd-b2cd-44fa-a891-9ce08ebef640)

**Desktop & mobile (please complete the following information):**
 - Browser Chrome
 - Library version latest

**Comment by Jasenkoo** [comment]
This will not be worked on, the component is vue 3.2+ only, with no backward compatibility.

**Comment by fanta759** [comment]
@Trojan13 A fix has been fussioned and will be available soon
