### ISSUE TITLE
'"@vuepic/vue-datepicker"' has no exported member named 'DatepickerInstance'. Did you mean 'DatePickerInstance'?ts(2724)

### ISSUE THREAD

**Issue by noda13** [Vuepic/vue-datepicker#419]
https://vue3datepicker.com/methods-and-events/methods/#closemenu

<img width="850" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/16859990/2dcca1f1-34d5-4c6e-88c2-3cba0ebbc84e">

**Comment by Jasenkoo** [comment]
it is `DatePickerInstance`, there is a typo in the docs

**Comment by noda13** [comment]
Thank you.
