### ISSUE TITLE
The value is not displayed on the iphone browser

### ISSUE THREAD

**Issue by WANNANANANA** [Vuepic/vue-datepicker#420]
**Describe the bug**
The computer browser displays normally，but in iphone browser，the value is not displayed.

**To Reproduce**
My code:
<VueDatePicker v-model="form.time" :enable-time-picker="false" range :clearable="false" :partial-range="false" locale="zh" format="yyyy-MM-dd" />

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Browser [iphone11/12/13 chrome, safari]
 - Library version [5.1.2]

**Comment by kg-pb** [comment]
I'm using version 5.2.1 and issue still there. Iphone 12 mini - Safari and Chrome..
