### ISSUE TITLE
Slots for month up/down buttons in vertical mode

### ISSUE THREAD

**Issue by Eterion** [Vuepic/vue-datepicker#428]
**Is your feature request related to a problem? Please describe.**
When [vertical](https://vue3datepicker.com/props/modes/#vertical) mode is enabled, it's hard to replace the up and down icons.

![image](https://github.com/Vuepic/vue-datepicker/assets/7584981/820863d0-6c51-483d-a23a-8b4ab0a05601)

**Describe the solution you'd like**
Add new slots for these icons.
Or, when the vertical mode is enabled, [arrow-left](https://vue3datepicker.com/slots/icons/#arrow-left) and [arrow-right](https://vue3datepicker.com/slots/icons/#arrow-right) slots should be used as up and down arrows instead.

**Describe alternatives you've considered**
Using the [month-year](https://vue3datepicker.com/slots/icons/#arrow-right) slot just to replace icons seems like overkill.

**Comment by Jasenkoo** [comment]
@Eterion There are [arrow-up](https://vue3datepicker.com/slots/icons/#arrow-up) and [arrow-down](https://vue3datepicker.com/slots/icons/#arrow-down) slots. In the docs they are displayed for the time picker, however, the same icons work for arrows in vertical mode.

Need to update the docs tho.

**Comment by Eterion** [comment]
@Jasenkoo I did try those slots, but those really work only as the documentation suggests. Here's a quick test.
https://stackblitz.com/edit/vuepic-vue-datepicker-ffrhht?file=src%2Fcomponents%2FPlayground.vue

```html
<Datepicker v-model="date" vertical>
  <template #arrow-up>Prev month</template>
  <template #arrow-down>Next month</template>
</Datepicker>
```

The up/down arrow in time picker get replaced. But calendar up/down in vertical mode are still default.
