### ISSUE TITLE
Changed date picker mode to select year only, it is crashing. Can you check it again for me? #yearPicker

### ISSUE THREAD

**Issue by trandinhhuong** [Vuepic/vue-datepicker#43]
![image](https://user-images.githubusercontent.com/68776351/167351088-702a4f75-5429-4a58-8d44-6894f4197f5a.png)

![image](https://user-images.githubusercontent.com/68776351/167351133-99c64ea8-edfc-40da-bf2e-a52805daa4dc.png)

**Comment by Jasenkoo** [comment]
Will check what is going on

**Comment by Jasenkoo** [comment]
@trandinhhuong Here is the [example](https://stackblitz.com/edit/vuepic-vue-datepicker-c4kjj2?file=src%2Fcomponents%2FPlayground.vue) and everything works fine.  Are you changing the mode programmatically? If you happened to change the code while the menu was still open, it may not work until the page reload, after that you should be good
