### ISSUE TITLE
action button style is broken

### ISSUE THREAD

**Issue by Thuytran79** [Vuepic/vue-datepicker#433]
I use vue 3 with pinina.
The style of the action buttons is broken, the width of the button is narrowed so the text on the button is displayed vertically.
How can I customize style in this case?

**Comment by Thuytran79** [comment]
![Screenshot_141](https://github.com/Vuepic/vue-datepicker/assets/86605918/24ecd6a3-a005-4894-9002-9d37aa42f6ed)

**Comment by Jasenkoo** [comment]
@Thuytran79 Looks like you have a specific button style for buttons in the parent app. You can just target the CSS directly and see what is causing the issue, it should auto-expand.
