### ISSUE TITLE
Value not updating on time change

### ISSUE THREAD

**Issue by extraordinarycanines** [Vuepic/vue-datepicker#437]
The model data doesn't update when the time is changed in the datepicker without the date also being changed.

**To Reproduce**
1. Select Date and Time with datepicker
2. Reopen datepicker and change the time only (keeping date the same)
3. Model value is not updated with new time / @update function not triggered

**Expected behavior**
Expect @update triggered by time changes and model value to be updated

 - Browser: Chrome
 - vue-datepicker v5.2.0
 - vue v3.3.2

**Comment by Jasenkoo** [comment]
It appears to be working as expected, please provide a reproduction link or which props you are using.
