### ISSUE TITLE
It is possible to have a minimized view (show only one week in datepicker)

### ISSUE THREAD

**Issue by juarezgerman** [Vuepic/vue-datepicker#438]
Hello,
I would like, if it's possible, to switch between month and week view to select a day, and, in the week view, display one week instead of all the days of the month.
May be it's something like six-week mode feature but with only one week.
I add a images to be more clear.
Thank you in advance and it's a really great component!!!!

![DatePicker_one-week-mode](https://github.com/Vuepic/vue-datepicker/assets/26276818/edf66e85-0183-49c0-b6eb-478c12f62013)

**Comment by juarezgerman** [comment]
Hello, thank you for the update! could you explain how to select the week or month view please? thank you.

**Comment by Jasenkoo** [comment]
@juarezgerman Take a look at [`calendar`](https://vue3datepicker.com/props/calendar-configuration/#calendar) prop, just filter out the needed week

**Comment by juarezgerman** [comment]
@Jasenkoo thanks very much!!!! 👍
