### ISSUE TITLE
Mode text-input for calendar

### ISSUE THREAD

**Issue by lealea401** [Vuepic/vue-datepicker#439]
**Bug**
I am using 

`<VueDatePicker v-model="dateTo" :min-date="dateFrom" :max-date="'2470-01-01'" :enable-time-picker="false" :format="dateFormat" :clearable="false" :year-range="[1900,2470]" auto-apply />`
where dateFormat is `MM/Dd/YYYY`
When I try to modify the date by typing in manually instead of picking from the calendar I get "Invalid Date"

In addition, when I go to the page  `https://vue3datepicker.com/props/modes/` and try the demo for the `text-input`, I type in a date but the date in the input box is restored to the default instead of keeping the date I insert. 
I am using VeuDatePicker version `5.2.0`

**Comment by Jasenkoo** [comment]
To use text input, you need to set `text-input` prop to `true`. The default pattern for a parsing date is the default format, `mm/dd/yyyy, hh:mm` (or `format` prop, will be ignored if the function is used). To use a custom format, you need to specify [`text-input-options`](https://vue3datepicker.com/props/modes-configuration/#text-input-options)
