### ISSUE TITLE
Change month number to text

### ISSUE THREAD

**Issue by tourlek** [Vuepic/vue-datepicker#44]
I want to change 05 to May How can i do it ?
![image](https://user-images.githubusercontent.com/82075950/167406413-30ad3bc7-988f-485b-82af-9ac432ace525.png)

**Comment by tourlek** [comment]
Oh i have a solution use https://vue3datepicker.com/api/props/#formatting

![image](https://user-images.githubusercontent.com/82075950/167407208-3ba5dde2-e0a0-4952-b435-91f6bfd2d7e0.png)

**Comment by Jasenkoo** [comment]
Hi, you can also use the `format="dd/MMMM/yyyy"`
