### ISSUE TITLE
support a multicalendar range picker feature for month

### ISSUE THREAD

**Issue by jwgo** [Vuepic/vue-datepicker#440]
Hello and thank you for creating such a great library.
I am using it very well, but there is one feature I need.

The month range does not work properly when in multicalendar mode, but it seems to be intended.
In the case of antd datepicker, there is a case of using month range like multicalendar (https://antdv.com/components/date-picker).

Would you be willing to add such a feature?

**Comment by Jasenkoo** [comment]
Will be handled in v6
