### ISSUE TITLE
Extend the usage of the `formatLocale` parameter

### ISSUE THREAD

**Issue by basil-gor** [Vuepic/vue-datepicker#443]
**Is your feature request related to a problem? Please describe.**
The business logic of the project I am currently working on requires custom localization for all texts. The logical solution was to use the `formatLocale` parameter. We redefined the `date-fns` library config and passed it to `formatLocale`, but this did not help to make a **full** translation of the component.
After looking into the source code of the library, I found out that you use the `locale` parameter and the function `Intl.DateTimeFormat()` for localization. But I don't see any obstacles in order to use translations from the `formatLocale` parameter, if it is passed.

**Describe the solution you'd like**
What I suggest:
In priority, use translations passed from the `formatLocale` parameter. To do this, in places where the `getDayNames` and `getMonths` methods are used, firstly try to get translations from `formatLocale`, otherwise do a fallback to the `Intl.DateTimeFormat()` usage.

**Describe alternatives you've considered**
As far as I understand, the current alternatives to throwing custom localizations by `slots`, but it seems to me an overhead inconvenient solution.

**Additional context**
If it is necessary to implement the solution in a pull request, then I think I can do it. But in any case, first, I would like to hear your opinions and arguments regarding the described problem.

Thank you very much!

**Comment by Jasenkoo** [comment]
Thx for the detailed explanation, it can be included, It won't require significant changes to make it work.

**Comment by basil-gor** [comment]
I made a PR related to this issue. Will be glad if you review it. Thanks!
