### ISSUE TITLE
Newline / <br> in format not respected

### ISSUE THREAD

**Issue by gizahNL** [Vuepic/vue-datepicker#444]
**Describe the bug**
I need to format my time/date field such that time is displayed on the top line, and date is on a new line below it. Unfortunately neither '\n' or '```<br>```' are respected as returned from my format function.
**To Reproduce**
Create a format function that returns a string containing one or more newlines.

**Expected behavior**
Newlines are respected

**Comment by Jasenkoo** [comment]
Due to security concerns this will not be added. You can use custom slots and override the format to your liking.
