### ISSUE TITLE
Time picked on the calendar can be negative (start time is after end time)

### ISSUE THREAD

**Issue by PaperbagLife** [Vuepic/vue-datepicker#448]
**Describe the bug**
Time picked on the calendar can be negative (start time is after end time)

**To Reproduce**
1. Go to this [link](https://play.vuejs.org/#eNqVUstuwjAQ/BXLF0AicVP6IoWKSu296hUjEcICKbFj2Q5thfLvXdtpAxKX5pDYO7OPmc2RPisVH2qgKZ2YXBfKEgO2Vk9cElIIVWlLjho2DdnoSpAeUnsn0Etm4a3I96BbfIYEVeQMP9EaQTwj6FJcVl5JY4nO5BbIlGDZ/uCRyw5RGrD7u8MNEuZHB7mnzFZQpmT5+pUJVQJZ1VtiCwGh1nL4y/PXlMwlfPrZ+sndw/0oSZLrcTIaD4bkHLhFxAOLtkKz4HLCghFoAV4sYENM8IZMykLuce5yyqmx3yWYHYDllOxQC8Z21iqTMlZLtd/GeSXYZT9mrqKxbF3gS2SFjHNjOA09Ok/DTIdIVGvf0qvjNISDi+GcBuMiHzPIPDWyTWBYfcL+5NAhDTuMRKbiD1NJ/AW837wFMDEl7QY4vSzEUf4h+yYexVdB9TmCA3Da7oBTF4820g/QVQcjYl1L1qGO33DZ0OYHkRrubw==)
2. Click on date picker, choose Example bug time range
3. Click on any date on the calendar twice
4. See the selected range has start timestamp > end timestamp

In general, any time range spanning across midnight, if you click on another date twice: 
1. the end timestamp's hour and minutes will stay the same but date will be set to the clicked date
2. the start timestamp's hour and minutes will also stay the same, but if it used to be a later point in the previous day, it will now be a later point in the currently selected date.
This is probably a bug, as we shouldn't allow for negative ranges being selected by the calendar.

**Expected behavior**
I expect either 
1. the range to auto swap, or 
2. correctly extend the end range to the next day
3. maybe disable clicking on the same date if the range is going to become negative with the current set of hours and minutes

It is probably easier to just swap the ranges, not sure what the expected behavior should be so its your call.
Brilliant work by the way!

It looks like the time range should be swapped in [this](https://github.com/Vuepic/vue-datepicker/blob/a916b6399ae2f4dd644d0b9b2aedd399698cb0ac/src/VueDatePicker/composables/calendar.ts#L474) function, unsure how to fix this.

**Screenshots**
<img width="470" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/43522930/f22cbb53-cc5f-4d23-b460-840eb8db8144">

**Desktop & mobile (please complete the following information):**
 - chrome, firefox

**Comment by Jasenkoo** [comment]
Nice catch, in fact, it has validation to prevent this behavior, however, looks like I missed a sport to check.
