### ISSUE TITLE
Start time for 'from' date and 'to' date should always be [ 00:00, 23:59 ] irrespective of timezone

### ISSUE THREAD

**Issue by nikhilkuruba** [Vuepic/vue-datepicker#452]
I am trying to override start time for from date and to date using @range-start and @range-end events. I am setting them to [ 00:00, 23:59 ]. However, when the timezone changes from time and to time are being calculated according to timezone which I want to avoid.

playground link: [https://stackblitz.com/edit/vuepic-vue-datepicker-tzmsww?file=src%2Fcomponents%2FPlayground.vue](url)

**Comment by Jasenkoo** [comment]
You can just remap the `date` when the selection changes. The events are not called when `v-model` is updated
