### ISSUE TITLE
Month picker bugs [v.5.3.0] - always shows the current month / does not show the month between two selected dates

### ISSUE THREAD

**Issue by massimiliano3100** [Vuepic/vue-datepicker#453]
Hi, i used the Datepicker and customized it for my App. I am using the Month-picker in range and inline mode.
I updated to version 5.3.0 today and there are two problems:

**Describe the bug**
1. Month-Picker in multi-dates mode will show the current month as selected item, no matter if v-model is empty or not . (no-today props does not work for month-picker). The v-model is still empty [],  but in Month-picker the current month will display with primary background. It should have all items the _dp__overlay_cell_ class when v-model is empty and no-today props is true.

**To Reproduce**
```
<Datepicker
            v-model="multiMonthPickerDate"
            locale="de"
            :year-range="[2022,  2028]"
            auto-apply
            no-today
            month-picker
            inline
            multi-dates
          >
 </Datepicker>
```

**Info**
I have temporarily fixed the problem in my app and simply set the Color for active items when v-model is empty equal to background. 
My temporary fix (maybe help by bugfix): I defined 2 classes and use if v-model is empty or not empty to give date-picker component:
```
<style scoped lang="scss">
.markNoItems :deep(.dp__overlay_cell_active) {
  background: var(--dp-background-color) !important;
  color: var(--dp-text-color) !important;
}
.markItems :deep(.dp__overlay_cell_active) {
  background: var(--dp-primary-color) !important;
  color: var(--dp-primary-text-color) !important;
}
</style>
```

**Describe the bug**

2. Month-Picker in range mode, does not show the month between two selected dates with gray background. **(This problem occurs in version 5.3.0. I have checked that this problem does not occur in version 5.2.1.)**

I have checked this. There is a class named _dp__cell_in_between_, when you select rang, it will assign the divs (dates) between the two selected dates. In normal mode (date picker) the class will assign when selecting two dates, but in the month picker in v-5.3.0 the class will not assign.

**To Reproduce**
```
<Datepicker
            v-model="monthPickerDate"
            locale="de"
            :year-range="[2022,  2028]"
            auto-apply
            no-today
            range
            partial-range
            month-picker
            inline
          >
</Datepicker>
```

**Screenshots**
Here is a screenshot of the problem, but as I said, I customized it for my app.
<img width="438" alt="Bildschirmfoto 2023-06-26 um 19 53 30" src="https://github.com/Vuepic/vue-datepicker/assets/44100867/67103f79-5b90-4963-8189-fb1f24d8078f">

**Desktop & mobile (please complete the following information):**
 - MacBook Pro - Chrome Version 114.0.5735.133 
 - Library version = 5.3.0

**Comment by Jasenkoo** [comment]
1. This is a current limitation because the picker needs to always have an internal reference to the month, that is why it is highlighted, even tho it is not selected. The method you use should cover the specific cases. This will be handled in v6 as it may introduce breaking changes.

2. This one will be fixed in the upcoming version.
