### ISSUE TITLE
Using arrows to pick year -- have to press 12x to change year

### ISSUE THREAD

**Issue by pw-ec** [Vuepic/vue-datepicker#454]
**Describe the bug**
In the calendar popup menu, if you click on the year, if you try to pick the year using the arrow keys (left/right are all that seem to work), you have to press the key 12x before it moves one year.

**To Reproduce**
1. Go to https://stackblitz.com/edit/vuepic-vue-datepicker?file=src%2Fcomponents%2FPlayground.vue
2. Click on the calendar control.  Then click on the year.  The click the right arrow -- after you press the arrow key 12 times the year will change

**Expected behavior**
I expected that for each arrow key pressed the year would change by one year

**Screenshots**
Here is the year view I'm having issues with: 
![image](https://github.com/Vuepic/vue-datepicker/assets/104465169/4dc98590-c9e1-493e-ac1f-4fc8c8e1118a)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome, Version 114.0.5735.134 (Official Build) (64-bit)
 - Library version ^5.3.0

**Comment by Jasenkoo** [comment]
The thing is, this was never intended behavior 😄 . What you see by pressing the arrow is a listener for changing months by 1 being called (for keyboard navigation), so when you press enough times, the year changes..

This makes it both bug and a feature.

**Comment by Jasenkoo** [comment]
Only the bug will be handled, for the arrow year switch, there is an arrow navigation instead (or use exposed methods), it requires unnecessary calculations to extract the data. It may be handled in some future release
