### ISSUE TITLE
Typing the date is not working

### ISSUE THREAD

**Issue by lealea401** [Vuepic/vue-datepicker#455]
Hello,

I cannot use smoothly the option text-input.
I am using VueDatePicker (5.2.0) like this:

```
<template>
  <div>
    <VueDatePicker :model-value="selectedDate" @update:model-value="handleDateUpdate" :clearable="false" :year-range="[1900,2470]" auto-apply text-input :text-input-options="textInputOptions" ></VueDatePicker>
  </div>
</template>

<script>
import VueDatePicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';


export default {
  components: {
    VueDatePicker,
  },
  data() {
    return {
      selectedDate: null,
      textInputOptions: {
        format: 'MM/dd/yyyy'
      },

    };
  },
  methods: {
    handleDateUpdate(newDate) {
      this.selectedDate = newDate;
    },
  }
};
</script>
```

<img width="451" alt="Text-Input" src="https://github.com/Vuepic/vue-datepicker/assets/51837829/38419615-c16d-4a4e-9e18-c08aa3f5b68f">

I am experiencing the following behavior:

 If I copy this code in https://stackblitz.com/edit/vuepic-vue-datepicker-3adsa8?file=src%2Fcomponents%2FPlayground.vue
and I try to change the date by hand, the date returns to the original date. It works if I pickup the date from the calendar

The expected behavior would be to type easily a date instead of picking it up from the calendar.
In my application it works with hiccups:
I need to enter the year then click outside to record it and then type a month then click outside, type a day then click outside otherwise the date gets back to the original one. If you try to modify all at once the date is not saved and you need to repeat these actions until you get it correctly..

Is this a bug in VueDatePicker or am I missing some configuration?

**Comment by Jasenkoo** [comment]
Copied your code to the [playground ](https://stackblitz.com/edit/vuepic-vue-datepicker-jdovsm?file=src%2Fcomponents%2FPlayground.vue) linked, I don't see the issue here. Keep in mind, since you provided a specific format for `format` and another one for `textInputOptions.format`, you need to you the one provided in the `textInputOptions.format`

Basically, you would type it like this (if we want to select 27th June 2023)  for `textInputOptions.format = "MM/dd/yyyy"`:

```
"06" + "/" + "27" + "/" + "2023"
```

Since the `auto-apply` is enabled, if you blur the input or press enter, the value in the input field will be

```
2023-06-27
```
when applied.

**Comment by lealea401** [comment]
But if you pick a date from calendar and then you want to change it, the date goes back to the original 
I tried modifying like this, adding a dateFormat.
1) Choose a date using the calendar
2) Modify the date by hand
3) Result: Date does not change
 
```
<template>
  <div>
    <VueDatePicker :model-value="selectedDate" @update:model-value="handleDateUpdate" :format="dateFormat" :clearable="false" :year-range="[1900,2470]" auto-apply text-input :text-input-options="textInputOptions" :enable-time-picker="false"></VueDatePicker>
  </div>
</template>

<script>
import VueDatePicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';


export default {
  components: {
    VueDatePicker,
  },
  data() {
    return {
      selectedDate: null,
      textInputOptions: {
        format: 'MM/dd/yyyy'
      },

    };
  },
  methods: {
       dateFormat(date) {
            const day = String(date.getDate()).padStart(2, '0');
            const month = String(date.getMonth() + 1).padStart(2, '0');
            const year = date.getFullYear();
             return `${day}/${month}/${year}`;
        },
    handleDateUpdate(newDate) {
      this.selectedDate = newDate;
    },
  }
};
</script>
```

**Comment by Jasenkoo** [comment]
You are right, it is not working as expected

**Comment by dropweb** [comment]
I worked around this by using  @text-submit="handleTextEnteredDate", and then setting the v-model to the entered dates.
