### ISSUE TITLE
Transitions don't appear to disable when passing false

### ISSUE THREAD

**Issue by jasonlewis** [Vuepic/vue-datepicker#462]
**Describe the bug**
When using `:transitions="false"` it appears as though it's not doing anything as the calendar still transitions in. Somewhat related is the fact that a calendar that would open outside of the screen bounds currently animates very awkwardly as it attempts to transition in outside the bounds and then snaps back into the window.

**To Reproduce**
This can be reproduced on the [transitions example in the docs](https://vue3datepicker.com/props/look-and-feel/#transitions) which is meant to be disabling the transitions.

**Expected behavior**
When `transitions` is `false` I would expect the calendar to appear without a transition. 

**Screenshots**
This video shows the transitioning behavior when a calendar is opening close to the edge of the screen.

https://github.com/Vuepic/vue-datepicker/assets/829059/9f170571-5f31-47a1-a7a9-6411594391a9

**Desktop & mobile (please complete the following information):**
 - Browser: Tested on latest Chrome and Edge
 - Library version: 5.3.0

**Comment by carlosvaldesweb** [comment]
I have the same proble, but i noticed that when i scroll down or up and the calendar is open and near of bounds, the calendar makes stranger movements.
