### ISSUE TITLE
Popup not properly closing when the Datepicker is inside label element

### ISSUE THREAD

**Issue by Agence-Evvi** [Vuepic/vue-datepicker#464]
**Describe the bug**
It's very specific bug, it appeared inside my app when updating from `3.6.4` to `5.4.0`
When the Datepicker is inside a label element, when clicking on select or cancel, the popup disappear for a moment and re-appear instantaneously, clicking outside still works.

**To Reproduce**
[Example Stackblitz](https://stackblitz.com/edit/vitejs-vite-mymusn?file=src%2FApp.vue)

**Comment by Jasenkoo** [comment]
Will see what is going on there, in the meantime you can see `:teleport="true"` for prior behaviour.

**Comment by Jasenkoo** [comment]
The fix is included in the released v6
