### ISSUE TITLE
auto-apply not working in custom flow mode

### ISSUE THREAD

**Issue by marco-gagliardi** [Vuepic/vue-datepicker#465]
**Describe the bug**
- Auto apply doesn't work when a custom flow (`['month', 'year', 'calendar']`) is provided after clicking on the toggle button:
- Calendar button overlaps with year content 

https://github.com/Vuepic/vue-datepicker/assets/2972151/482e7bfc-23ca-4bc9-889d-922bc2d3b00c

**To Reproduce**
Link to code: https://stackblitz.com/edit/vuepic-vue-datepicker-bvfxyf?file=src%2Fcomponents%2FPlayground.vue

1. provide a custom flow array and set auto apply property
2. click to open the overlay popup
3. click on the toggle button
4. click on a date
5. nothing happens and user is stuck

**Expected behavior**

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by Jasenkoo** [comment]
Somewhere mid August

**Comment by dathacky** [comment]
Its still not work :( @Jasenkoo 
https://www.awesomescreenshot.com/video/19966799?key=4e19f5ec5dff001e4c2a9275258cb6a8

**Comment by Jasenkoo** [comment]
@dathacky Are you calling a provided `onInput` function from the slot?

**Comment by dathacky** [comment]
> @dathacky Are you calling a provided `onInput` function from the slot?

yeah :( I tried using onInput and the value appears invalid date if my input value is null
@Jasenkoo

**Comment by Jasenkoo** [comment]
@dathacky This is a wrong issue, I added a [comment](https://github.com/Vuepic/vue-datepicker/issues/473#issuecomment-1682762396) to an original ticket

**Comment by marco-gagliardi** [comment]
hey @Jasenkoo FYI: I did a quick test [upgrading the version on the same example cod](https://stackblitz.com/edit/vuepic-vue-datepicker-bfhs7z?file=package.json)e and it looks like the bug is still happening

**Comment by Jasenkoo** [comment]
@marco-gagliardi This is intended behavior, you need to pass `partial-flow` too. [Example](https://stackblitz.com/edit/vuepic-vue-datepicker-3py6zz?file=src%2Fcomponents%2FPlayground.vue)

**Comment by marco-gagliardi** [comment]
> thanks @Jasenkoo. With `partial-flow` it actually sets the value when a day is clicked in your example, however the calendar box doesn't close automatically right after (as it would be expected to happen using `auto-apply`)
