### ISSUE TITLE
Calendar doesn't scroll when valueModel changed

### ISSUE THREAD

**Issue by alexhyriavets** [Vuepic/vue-datepicker#47]
**Describe the bug**
I'm trying to implement custom preset logic. When I select preset in my own input type="select", I change the value prop passed to the Datepicker component. Chosen range highlights in the calendar but there is no scroll to the start of that range.

**To Reproduce**
- create datepicker and pass following props: { inline: true, autoApply: true, range: true, multiCalendars: true }
- try to change valueModel programmatically to dates that are outside the current view

**Expected behavior**
View changes to the start of newly selected range (exactly as when using the existing presetRanges prop)

**Desktop & mobile (please complete the following information):**
 - Browser chrome
 - Library version 3.2.0
 
https://stackblitz.com/edit/vuepic-vue-datepicker-gh1jwr?file=src/components/Playground.vue

**Comment by alexhyriavets** [comment]
I made some research and find out that it reproduces only when *multiCalendar: true* otherwise works as expected

**Comment by Jasenkoo** [comment]
Ok, checked what is the issue. This was referenced here (#27), previous behavior was like you want it, I will how to handle both cases.
