### ISSUE TITLE
`minutes-grid-increment` results in `undefined`

### ISSUE THREAD

**Issue by sybrendotinga** [Vuepic/vue-datepicker#470]
**Describe the bug**
I get an error when using `minutes-grid`. I found this issue, but it looks like this hasn't been fixed. Or is it not been deployed yet? As far as I could see it was tagged in the 5.3.0 version.

Related issue: https://github.com/Vuepic/vue-datepicker/issues/401

**To Reproduce**

- Open the link (see "Screenshots")
- It should open `Playground.vue`
- Click on the time picker, it will open
- Click on the minutes-button, it results in this error (in console):

```
@vuepic_vue-datepicker.js?v=1f8080ac:7732 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
```

**Expected behavior**
No error 😄 

**Screenshots**
I've made a small Stackblitz: https://stackblitz.com/edit/vuepic-vue-datepicker-wrtjqj?file=src%2Fcomponents%2FPlayground.vue

**Desktop & mobile (please complete the following information):**
I am using v5.3.0:
```
  '@vuepic/vue-datepicker':
    specifier: ^5.3.0
    version: 5.3.0(vue@3.2.47)
```

**Comment by Jasenkoo** [comment]
The fix is included in the released v6

**Comment by sybrendotinga** [comment]
Thank you very much @Jasenkoo! It works like a breeze! Upgrading was also very easy, thank you!
