### ISSUE TITLE
text-input focussed field, doesn't replace text with new input

### ISSUE THREAD

**Issue by NielsJorck** [Vuepic/vue-datepicker#475]
**Describe the bug**
First off, I love this library to the moon. Best datepicker I've come across in a long time.
I'm not 100% sure this is a bug or intended, however I haven't found a way to work around it either.

When focussing a `text-input` enabled datepicker the text is highlighted.
Normally in an input field you would expect a keystroke would override the selected text.
In this case it opens the datepicker and removes the highlight.

While the datepicker is very good for general usage, superusers doesn't require the picker and often just want to write the date tabbing through a form.

**To Reproduce**

I made stackblitz with a minimal setup. Can be edited here: [Stackblitz](https://stackblitz.com/edit/vue-6ukup4)

1. Go to https://vue-6ukup4.stackblitz.io/ 
2. Hit tab on the page, field should now be in focus and text highlighted
3. Start writing the date.
4. Unexpected behavior is the modal opening and first keystroke is ignored while the rest is appended to the date.

**Expected behavior**
When the text is highlighted and text is entered, the text should replace the selection.

**Desktop & mobile (please complete the following information):**
 - Browser: chrome
 - Library version: 5.4.0

**Comment by Jasenkoo** [comment]
The fix is included in the released v6
