### ISSUE TITLE
input-class-name to change the input class style but it's not working?

### ISSUE THREAD

**Issue by Thuytran79** [Vuepic/vue-datepicker#477]
**Question:**
I try to used [input-class-name](https://vue3datepicker.com/props/look-and-feel/#input-class-name) for change input heigh or width,
but it's not worked
It like:
<template>
  <div class="date-picker">
    <VueDatePicker
    position="left"
    v-model="copyDate"
    placeholder="日付を選択"
    locale="ja"
    format="yyyy/MM/dd"
    auto-apply
    :enable-time-picker="false"
    @update:modelValue="emitSelectedDate"
    input-class-name="dp-custom-input">
    </VueDatePicker>
  </div>
</template>

<style scoped lang="scss">
.date-picker {
  .dp-custom-input {
    height: 18px;
  }
}
</style>

Can you help me?

**Comment by Jasenkoo** [comment]
Can you try without a scoped flag?

**Comment by Thuytran79** [comment]
yes. I tried without a scoped flag. It's working!
Thank you for your support.

**Comment by soorajsprakash** [comment]
Hi, 
same issue,
i tried adding custom menu-class-name,
the class gets applied successfully, but the styles declared in it wont apply, even if we add the "!important" tag.

So, Its possible that its the same for all custom classes.
