### ISSUE TITLE
Can't type date manually with flow and text-input props enabled [v5.4.0]

### ISSUE THREAD

**Issue by abdouthetif** [Vuepic/vue-datepicker#478]
**Describe the bug**
When flow is set, for example to `['year', 'month', 'calendar']`, and text-input is enabled, it's impossible to type manually the date. This bug is since version 5.4.0.

**To Reproduce**
1. Go to [playground](https://stackblitz.com/edit/vuepic-vue-datepicker-sbnqzy?file=src%2Fcomponents%2FPlayground.vue)
2. Click on the input
3. Try to type a date manually
4. See the inability to type the date

**Expected behavior**
The text-input should work with the datepicker flow mode. We should be able to type a date manually in the input in addition to the ability to select a date using the flow.

**Desktop & mobile:**
 - Browser [all]
 - Library version [5.4.0]

**Comment by Jasenkoo** [comment]
The fix is included in the released v6

**Comment by gdebrion** [comment]
@Jasenkoo thank you so much. Had the same problem, updated to v6.x and it's working perfectly!
