### ISSUE TITLE
Reduce bundle size or make package more treeshakable

### ISSUE THREAD

**Issue by minht11** [Vuepic/vue-datepicker#479]
**Is your feature request related to a problem? Please describe.**
Currently `vue-datepicker` bundle size is quite big.
**Describe the solution you'd like**
Find a way to reduce bundle size, or make library more treeshakable for example providing components with only subset of functionality.
**Describe alternatives you've considered**
Lazy importing, delays the problem, but doesn't solve it.

**Comment by Jasenkoo** [comment]
This is currently in progress for v6

**Comment by Jasenkoo** [comment]
Update regarding this, after various configurations, the tree shaking is not worth it as the component is packaged as SFC. Shaking is possible but only if pickers are provided externally. In this case `year-picker` configuration is the smallest and the savings are neglectable. Concluding that changing the configuration is not worth it in savings a few kb.
