### ISSUE TITLE
@recalculate-position event not working with inline property.

### ISSUE THREAD

**Issue by HuanVo** [Vuepic/vue-datepicker#480]
**Describe the bug**
@recalculate-position event not working with inline property.

**To Reproduce**
Set inline to Datepicker tag. recalculate-position event not working.

**Screenshots**
Refer to
https://stackblitz.com/edit/vuepic-vue-datepicker-ekycpt?file=src%2Fcomponents%2FPlayground.vue

**Comment by Jasenkoo** [comment]
It is not working because there is nothing to recalculate, the inline picker uses relative positioning.
