### ISSUE TITLE
hide-navigation doesn't work

### ISSUE THREAD

**Issue by ARM128bit** [Vuepic/vue-datepicker#481]
A hide-navigation prop does not work

1. Go to https://vue3datepicker.com/props/general-configuration/#hide-navigation
2. Click on a datepicker
3. See the datepicker has a year navigation for example

**Expected behavior**
Datepicker shouldn't have a year navigation

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/50628474/722c1b0f-cb6c-4015-99e7-f746f93c40a9)

 - Desktop Chrome 114.0.5735.199

**Comment by Jasenkoo** [comment]
This is more of a documentation/prop naming, it actually hides the back button from the overlay, intended for usage with `flow` prop.
