### ISSUE TITLE
Internal usage of JS Date converts time to users TZ & provides completely wrong result

### ISSUE THREAD

**Issue by apuatcfbd** [Vuepic/vue-datepicker#487]
**Describe the bug**
Automatically converts provided time to users timezone in the format function.

**To Reproduce**
provide initial value **11:00 am** (UK Time). Customize display using `format`, in this case for advanced case, using a `fn`.
I'm in BD & in the `format fn` it receives a date object & BAM... that object converted original time to my (BD) tz time.
The format fn gets (provided) **11:00 am** as **06:00 am**

**Expected behavior**
Format fn should get time as string so JS can't convert it. For my case I'm using Luxon, I could parse that use the input format (obviously provide the format in docs) & do the customization.

**Screenshots**
https://drive.google.com/file/d/1Yv-2HG0wnErAPiA_V22AQgiFIynzZX8t/view?usp=sharing

**Desktop & mobile (please complete the following information):**
 - Browser chrome
 - Library version 5.0.1

FYI:
following is my format fn
```javascript
/**
 * Formats display date in time input field
 * @param dt {Date[]}
 * @return {string}
 */
const formatDisplayTime = (dt) => {

  const start = DateTime.fromJSDate(dt[0], { zone: SITE_TIMEZONE });
  const end = DateTime.fromJSDate(dt[1], { zone: SITE_TIMEZONE });

  console.log({
    dtStart: dt[0],
    dtEnd: dt[1],
    start,
    end,
  });

  const start24 = start.toLocaleString(DateTime.TIME_24_SIMPLE);
  const start12 = start.toLocaleString(DateTime.TIME_SIMPLE);
  const end24 = end.toLocaleString(DateTime.TIME_24_SIMPLE);
  const end12 = end.toLocaleString(DateTime.TIME_SIMPLE);

  return (start24 === end24) || start24 === '00:00' // if start & end are same then show nothing
    ? ''
    : `${start24} - ${end24} ( ${start12} - ${end12} )`;
};
```

**Comment by Jasenkoo** [comment]
You can convert it back to the original time in your custom fn, tho, some re-work for timezones is planned in the next version
