### ISSUE TITLE
Select Button on Picker does not set background color correctly unless you hover over it

### ISSUE THREAD

**Issue by SimonHaenle2** [Vuepic/vue-datepicker#489]
**Describe the bug**
The select button of the datepicker seems unclickable and disabled because the background color is not set, until I mouse hover over it.
Screenshot of how the button looks:
![Bildschirmfoto 2023-07-17 um 11 16 40](https://github.com/Vuepic/vue-datepicker/assets/13623663/d5dbf41f-f549-476b-8f0d-9ed8a29ce776)
Screenshot of how the button looks with mouse-over:
![Bildschirmfoto 2023-07-17 um 11 16 58](https://github.com/Vuepic/vue-datepicker/assets/13623663/ee12078f-498e-4600-8521-1f71de4a2286)
We are using vue3 and use the default css of the picker without any style modifications.
`import "@vuepic/vue-datepicker/dist/main.css";`

**To Reproduce**
We are using this configuration of the picker.
`<VueDatePicker
                v-if="date[0] && date[1]"
                v-model="date"
                range
                utc
                :enable-time-picker="false"
                :partial-range="false"
                :fixed-start="hasFixedStart"
                @update:model-value="handleDateChange"
                :preset-ranges="presetRanges"
                :clearable="false"
              />`

**Expected behavior**
The button should always have a blue overlay around it, not only on mouse-hover.

**Screenshots**
![Bildschirmfoto 2023-07-17 um 12 05 43](https://github.com/Vuepic/vue-datepicker/assets/13623663/7c44b2e1-ee6d-4152-992a-eea685a96c4c)

![Bildschirmfoto 2023-07-17 um 12 07 20](https://github.com/Vuepic/vue-datepicker/assets/13623663/7ba2add9-43a7-4259-ab3a-bc966d69eca4)

**Desktop & mobile (please complete the following information):**
 - Chrome, Firefox
 - Library version 5.4.0
 - Vue 3

**Comment by Jasenkoo** [comment]
Hmm, is it possible that some parent CSS is overriding the style?
