### ISSUE TITLE
Date format does not work as expected

### ISSUE THREAD

**Issue by jbruni** [Vuepic/vue-datepicker#49]
**Describe the bug**

Code:

```html
<Datepicker
    autoApply
    v-model="meeting.date"
    locale="pt-BR"
    format="dd/MM/yyyy"
    previewFormat="dd/MM/yyyy"
    :enableTimePicker="false"
/>
```

The initial `meeting.date` value is `04/01/2022`, meaning **January 4th, 2022**, because the dates are in day/month/year format.

I tried all variations that  I could, using `:format="'dd/MM/yyyy'"`, `:previewFormat="'dd/MM/yyyy'"`, `:textInputOptions="{ format: 'dd/MM/yyyy' }"` and more.

All my attempts failed. No matter what I do, the initial `04/01/2022` is interpreted as "April 1st, 2022" - which is not the expected value, according to the informed format.

Note that, after the initialization, the calendar does behave as expected. For example, if I click at "March 9th, 2022" in the calendar, it will render as `09/03/2022`, as expected.

**To Reproduce**

See the description, above.

**Expected behavior**

See the description, above.

**Screenshots**

Not necessary.

**Desktop & mobile:**

- Desktop
- Browser **Chrome**
- Library version **3.2.0**

**Comment by Jasenkoo** [comment]
@jbruni `v-model` has to be `Date` object or a string representation of the date, e.g. `'2022-05-14T18:11:15.034Z'` that can be parsed with the `new Date()`

**Comment by oceangravity** [comment]
Hi @jbruni you need to set `model-type="dd/MM/yyyy"`, I hope it helps :)
