### ISSUE TITLE
Can't npm install with node version 18

### ISSUE THREAD

**Issue by DoE-Co** [Vuepic/vue-datepicker#492]
**Is your feature request related to a problem? Please describe.**
When trying to install with node version 18, I am unable to install because of a dependency not supporting this version.
**Describe the solution you'd like**
Would it be possible to upgrade this dependency to allow installation with node version 18
**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Vuepic/vue-datepicker/assets/95504952/fb142a0b-c17c-4a5d-bcf2-1ea341ca4978)

**Comment by Jasenkoo** [comment]
This is only a warning, an dit is coming from `node-ipc` package which is a completely different package.
