### ISSUE TITLE
presetRange causes unexpected width growth and breaks UI

### ISSUE THREAD

**Issue by frankli0324** [Vuepic/vue-datepicker#494]
**Describe the bug**

When enabling `preset-range` or `left/right-sidebar`, if the width of the added sidebars is small enough, this would happen:
![20230719114303_rec_](https://github.com/Vuepic/vue-datepicker/assets/20221896/633d737c-65f7-43d6-ba01-5dd8d2abb97b)

the reason is that https://github.com/Vuepic/vue-datepicker/blob/main/src/VueDatePicker/components/DatepickerMenu.vue#L248-L251 the calendar width is only calculated when neither `presetRanges` or sidebars is enabled, and https://github.com/Vuepic/vue-datepicker/blob/main/src/VueDatePicker/components/ActionRow.vue#L2 relies on this value to calculate the overflow:hidden behavior

**Expected behavior**

the calendar width should always been set, is there any reason it's not set?

**Desktop & mobile (please complete the following information):**

https://stackblitz.com/edit/vue-e4mx9u

**Comment by frankli0324** [comment]
the only temporary "fix" for this I think is only setting `display: none` on selection preview, since the width is dynamically calculated. unless someone want's to `document.querySelector` in vue...

**Comment by Jasenkoo** [comment]
The fix is included in the released v6
