### ISSUE TITLE
week in Vietnam is not correct

### ISSUE THREAD

**Issue by mukiwu** [Vuepic/vue-datepicker#496]
I use locale in Vietnam, but the "week name" is not correct

![截圖 2023-07-20 10 51 04](https://github.com/Vuepic/vue-datepicker/assets/3794103/e5efd777-c382-4f6f-990b-bc29faf6a675)

Monday is thứ Hai
Tuesday is thứ Ba
etc..

But it looks like only show previous 2 chracters

**Comment by Jasenkoo** [comment]
The picker uses default JS and slices names to 2 letters, in your case, it might be better to take a look at [`day-names`](https://vue3datepicker.com/props/localization/#day-names) prop
