### ISSUE TITLE
input fields lose focus when time-picker menu is opened.

### ISSUE THREAD

**Issue by Tom-Rohr** [Vuepic/vue-datepicker#499]
**Describe the bug**
When using the time-picker, my v-text-field loses focus when the menu is displayed.

**To Reproduce**
1. Wrap a text field in a VueDatePicker
2. Click on the text field on your page

**Expected behavior**
The time-picker menu is opened and the v-text-field remains focused so the user is able to manually enter times without having to click a second time.

**Screenshots**
![TimePicker-TextField-LosesFocus](https://github.com/Vuepic/vue-datepicker/assets/60917364/a9568b3f-760f-4275-adf7-6a36e04b3897)

below is how the VueDatePickers are configured for selecting start and end times. The component is named DatePicker.
![image](https://github.com/Vuepic/vue-datepicker/assets/60917364/f35d6efd-ca99-4c44-9e7f-842c2faea2c4)

Using the DatePickers for times only.
![image](https://github.com/Vuepic/vue-datepicker/assets/60917364/8cf0d8d9-3bfb-4843-b849-a169e2bf6e43)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome, Firefox.
 - Library version: 5.4.0

Sorry if this is the intended behavior and I submitted an illegitimate report. Any tips on how I might be able to maintain focus on the text field would be greatly appreciated!

**Comment by Jasenkoo** [comment]
It is a valid issue, similar thing reported on #475

**Comment by Jasenkoo** [comment]
The fix is included in the released v6
