### ISSUE TITLE
Multiple Datepicker instances in the same page?

### ISSUE THREAD

**Issue by HydroMoon** [Vuepic/vue-datepicker#50]
I have noticed if i have multiple Datepicker component in the same page only one of which will work like there is only one component.

Latest version 3.2.1
Vue 3.2.29

**Comment by mokalovesoulmate** [comment]
You need to specify different `v-model` to each other component.

**Comment by Jasenkoo** [comment]
@HydroMoon This is strange, can you provide some code? Here is the [example](https://stackblitz.com/edit/vuepic-vue-datepicker-3ybsas?file=src%2Fcomponents%2FPlayground.vue) on the same page

**Comment by HydroMoon** [comment]
Vue file:
```
<Teleport to="body">
        <div class="modal fade" id="queue_timing" tabindex="-1" aria-hidden="true">
			<!--begin::Modal dialog-->
			<div class="modal-dialog mw-600px">
				<!--begin::Modal content-->
				<div class="modal-content">
					<!--begin::Modal header-->
					<div class="modal-header">
						<!--begin::Modal title-->
						<h2>Save Queue Timing</h2>
						<!--end::Modal title-->
						<!--begin::Close-->
						<div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
							<!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
							<span class="svg-icon svg-icon-1">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
									<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="black" />
									<rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="black" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</div>
						<!--end::Close-->
					</div>
					<!--end::Modal header-->
					<!--begin::Modal body-->
					<div class="modal-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group fv-row fv-plugins-icon-container">
                                    <label for="start_time" class="required">Start Time</label>
                                    <Datepicker v-model="start_time" />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group fv-row fv-plugins-icon-container">
                                    <label for="end_time" class="required">End Time</label>
                                    <Datepicker v-model="end_time" />
                                </div>
                            </div>
                        </div>
					</div>
                    <div class="modal-footer">
                        <button ref="queue_timing" class="btn btn-yes" data-bs-dismiss="modal" @click="saveQTiming">Confirm</button>
                    </div>
					<!--end::Modal body-->
				</div>
				<!--end::Modal content-->
			</div>
			<!--end::Modal dialog-->
		</div>
    </Teleport>
```


Setup:
```
import Datepicker from '@vuepic/vue-datepicker'
import '@vuepic/vue-datepicker/dist/main.css'

    export default {
        components: {
            Datepicker,
        },
        setup() {


            const start_time = ref(new Date())
            const end_time = ref(new Date())
           // the rest is normally exported 
         }
}
```
I am using vue3 composition api
the page has different components including:

- vuedraggable
- vue3-qr-reader
- vue3-loading-overlay
it is really strange

**Comment by HydroMoon** [comment]
Yes it is returned in setup, i just try to minimize the code so it can be readable.

Interested behaviour Now after removing teleport the first Datepicker work with a catch i have to hold the mouse and drag it to calendar so i can chose date else it will close immediately the second Datepicker now is working and at the same time open the previous Datepicker.

Attached video: [https://www.veed.io/view/5f2c6945-6a5c-4f50-bc06-9c9f0702788b?sharingWidget=true](url)

Reinstaling node_modules did nothing.

The dialog is created using bootstrap 4.

**Comment by Jasenkoo** [comment]
I will check it again

**Comment by Jasenkoo** [comment]
Here is the [demo](https://stackblitz.com/edit/vuepic-vue-datepicker-9xhxly?file=src%2Fcomponents%2FPlayground.vue) with 2 pickers inside the modal with the `teleport` component, however it works fine. I don't know what else can be the problem. You can also try to register the datepicker globally to see if it resolves the issue. 

Also, you can change the teleport target for the component and pass `teleport="#queue_timing"` to render the menu inside the dialog.

**Comment by HydroMoon** [comment]
Thanks @Jasenkoo after using teleport to render menu inside the dialog it is working fine, Confirmed.
