### ISSUE TITLE
When restoring from bfcache the datepicker is blank

### ISSUE THREAD

**Issue by akumanara** [Vuepic/vue-datepicker#500]
**When restoring from bfcache the datepicker is blank**
When using a mobile browser with BFCache enbaled (https://web.dev/bfcache/) and you go back the datepicker shows as blank until you tap on it and it shows the correct date. 

Happens only on iOS

**Comment by Jasenkoo** [comment]
Having trouble reproducing the issue, this won't be worked on unless some kind of reproduction link is provided
