### ISSUE TITLE
The allowed-dates directive does not work

### ISSUE THREAD

**Issue by lebLuiz** [Vuepic/vue-datepicker#501]
**Describe the bug**

In a simple project with Vite(4.4.5) using Vue(3.3.4) and TypeScript(5.0.2), I imported the VueDatePicker(5.4.0) and when using the component with the `allowed-dates` directive passing it as an empty vector value ([]) I realize that all dates are blocked, not being able to insert the specific value

**To Reproduce**
My package.json:
obs: I installed the dependencies using Node v16.19.1
```
{
  "name": "vite-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@vuepic/vue-datepicker": "^5.4.0",
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5",
    "vue-tsc": "^1.8.5"
  }
}
```

Using node v16.19.1, start a vite project:
`npm create vite@latest` (https://vitejs.dev/guide/);
name the project;
select `vue`;
select `typescript`;
at first it is necessary to have created the project, access the project folder and install the VueDatePicker: `npm install @vuepic/vue-datepicker`.

Globally include the VueDatePicker in `main.ts`(https://vue3datepicker.com/installation/#global), for example:
```
import { createApp } from "vue";
import App from './App.vue';

import VueDatePicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css'

const app = createApp(App);

app.component('VueDatePicker', VueDatePicker);

app.mount('#app');
```

Use the VueDatePicker component inside some `.vue` component and include a variable for `v-model`, furthermore define `allowed-dates` by passing it as an empty array value ([]):
```
<VueDatePicker v-model="date" :allowed-dates="[]"></VueDatePicker>
```

**Expected behavior**
According to the documentation, an empty array value ([]) should be free choosing dates, not blocking them. (https://vue3datepicker.com/props/calendar-configuration/#allowed-dates)

**Screenshots**
- Desktop (Firefox):
![image](https://github.com/Vuepic/vue-datepicker/assets/49081359/0a02bff2-20d6-40a8-aa77-d21cd6989792)
![31b7be67235541fbe8ddb0663294d623](https://github.com/Vuepic/vue-datepicker/assets/49081359/5f8cc0ec-66f9-442f-b5c4-21979cf04037)

- Desktop (Edge):
![image](https://github.com/Vuepic/vue-datepicker/assets/49081359/03506616-b326-41b2-b773-379597faf76d)

**Comment by Jasenkoo** [comment]
This is the intended behavior, an empty array will disable all dates, added in #458. If you use it dynamically, pass `undefined` or `null` instead of an empty array.
