### ISSUE TITLE
I cannot use date picker where parent have overflow: hidden set

### ISSUE THREAD

**Issue by iCreatorStudio** [Vuepic/vue-datepicker#502]
**Describe the bug**

**To Reproduce**
Try to use date picker inside a card and provide card overflow:hidden. Refer screenshot

**Expected behavior**
It should be appear without changing  parent div/elements style. Like in Flatpicker

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/140206685/ca7aced3-a4dd-47e0-9949-dab13b153ca5)

**Desktop & mobile (please complete the following information):**
 - Browser Chrome
 - Library version 5.4.0

**Comment by Jasenkoo** [comment]
You can just set `:teleport="true"`.

**Comment by iCreatorStudio** [comment]
Hello @Jasenkoo

Thanks for reply and it is very helpful.

there is shorthand error:
![image](https://github.com/Vuepic/vue-datepicker/assets/140206685/974b8226-b8bd-450f-b34d-b1f976ec1874)

**Comment by Jasenkoo** [comment]
@iCreatorStudio This is just an eslint error `:teleport="true"` is the same as just writing `teleport`, however, that might not work as vue has a built-in component called teleport, you may try it and see.

**Comment by cannap** [comment]
HI, i have the same issue 

https://stackblitz.com/edit/nuxtlabs-ui-hw4nox?file=app.vue 
i added Teleport when i add teleport-center it works 
but thanks for this awesome picker

**Comment by cannap** [comment]
is teleport broken or something?

**Comment by cannap** [comment]
found it i have to add   teleport="body"

**Comment by cannap** [comment]
also for me it works when i use teleport="body"
