### ISSUE TITLE
Auto-apply does not work when the component is inline

### ISSUE THREAD

**Issue by Csardelacal** [Vuepic/vue-datepicker#503]
**Describe the bug**
When the component is inline, auto-apply stops working after changing it once.

**To Reproduce**
Sample code:

```vue
<template>
  <div>
    <Datepicker v-model="date" :flow="['calendar']" :inline="true" :enable-time-picker="false"  six-weeks="fair" :auto-apply="true" @internal-model-change="(e) => internal = e" />
    <br/>
    <span>{{date}}</span>
    <br/>
    <span>{{internal}}</span>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

const date = ref(new Date());
const internal = ref(new Date());
</script>
```

1. Set a date
2. Set another date
3. The internal model changes, but the external does not

**Expected behavior**
Aut-apply implies that the date should change whenever the user changes the date.

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/1152823/215e6713-407b-4007-b009-2e750dd4c7a0)

**Desktop & mobile (please complete the following information):**
 - Firefox 115
 - "@vuepic/vue-datepicker": "^5.3.0"

**Comment by Jasenkoo** [comment]
The issue is you are passing `flow` mode with `inline`, there is no way to keep the proper flow as the picker is always open. By removing the flow (in your case it is redundant with just the `calendar` value) will enable `auto-apply`
