### ISSUE TITLE
How to customize the action buttons?

### ISSUE THREAD

**Issue by lienyun** [Vuepic/vue-datepicker#504]
**Describe the bug**
I have checked [the page](https://vue3datepicker.com/slots/content/#now-button) but can't understand how to code the `selectDate()` part.

**To Reproduce**
Sample code: 
```
<template>
        <VueDatePicker v-model="date" ref="dp" range :format="format" :dark="isDark">
          <template #action-buttons>
            <v-btn class="custom-select" @click="selectDate">Select</v-btn>
          </template>
        </VueDatePicker>
</template>

<script setup>
import { ref } from "vue";
const date = ref([]);
const dp = ref();

const format = (date) => {
  const startDate = moment(date[0]).format("YYYY/MM/DD HH:MM");
  const endDate = moment(date[1]).format("YYYY/MM/DD HH:MM");

  return `${startDate}-${endDate}`;
};
const selectDate = () => {
  ref.value.selectDate(); // error
}

</script>
```

**Expected behavior**
I expect that customize button can work like default button. So do the cancel button.

**Screenshots**
<img width="370" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/102656879/5beebf69-f677-4e53-9c01-20a5ff4e7805">
<img width="290" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/102656879/3980666a-048a-4774-bcae-a8c0b2138150">

**Desktop & mobile**
Vue3+vite+vuetify3
@vuepic/vue-datepicker": "^5.3.0",

Thanks!

**Comment by Jasenkoo** [comment]
It is wrong in the documentation, the `ref` value is actually `dp`, you should use `dp.value.selectDate()`.

**Comment by lienyun** [comment]
@Jasenkoo I got it! Thanks a lot!
