### ISSUE TITLE
Other calendars

### ISSUE THREAD

**Issue by hamedfaryabi** [Vuepic/vue-datepicker#507]
Is there a way to use a calendar other than the Gregorian calendar? For example, the Jalali or Hijri (Lunar) calendar?

**Comment by Jasenkoo** [comment]
I am not familiar with those calendars, will have to investigate a bit, probably this will not be included in the upcoming version

**Comment by Jasenkoo** [comment]
This requires too much work to incorporate, I think the best approach is to go with some other libraries that are specific for these types of calendars.

**Comment by nort3x** [comment]
i like the structure and amount work already done on this library
this is the leading lib for datepickers in Vue and we should probably extend it to include other calendars as well
i'm kindly asking you to reconsider your choice on this <3
let me know how can i help.
- best regards

**Comment by Jasenkoo** [comment]
@nort3x Unfortunately, `date-fns` does not currently support different calendars, meaning, that all additional calculations will not be correct. If they add the support in the future, then we can easily make update the calendar.

**Comment by hamedfaryabi** [comment]
Is there any way to use [date-io](https://github.com/dmtrKovalenko/date-io)?

**Comment by ErfanBahramali** [comment]
Any updates ?

How can i use [date-fns-jalali](https://github.com/date-fns-jalali/date-fns-jalali) instead of date-fns
