### ISSUE TITLE
Autorange 1 day

### ISSUE THREAD

**Issue by scenaristeur** [Vuepic/vue-datepicker#509]
**Describe the bug**
Ho . Is there a way with autorange to and /or max/min to limites the range to 24h max. I was not able to set paramètres to do that. 
And the start date not in the past and the end date not a monté un the futur. 
In fact, I want the user can only select range  date in the futur from now but not more that on month away . And the range dors not cover more that 24 hours
If it could be in vue2/options ami that would be perfect, and showing the dates in french would perfect over the top of the moon beyond my espérances 🙂

**Comment by Jasenkoo** [comment]
`auto-range` can be set on 1 day

You can track selected range via `@internal-model-change` event, and update min and max date accordingly (24h range)
