### ISSUE TITLE
When using fixed-start prop, allow to set auto-focus date to ending date

### ISSUE THREAD

**Issue by Creatium** [Vuepic/vue-datepicker#510]
I am implementing a custom range calendar datepicker using this plugin. I have two fields: "from" and "to". My idea is to allow user to select each date separately, but also show the range in the datepicker.

So I am using 2 datepickers, the first one has fixed-end prop, the second one has fixed-start prop. Now what I dont see an option for is to set "focus-end" so that datepicker would autofocus on the last date of range, when the start is fixed.

I tried playing around with startDate, but that one does not seem to do anything when range prop is true.

Am I missing something? If not, this simple feature would be very useful.

In the meantime, maybe there is a manual way to set focused date?

**Comment by Jasenkoo** [comment]
@Creatium You can use `start-date` to set a calendar view on a given date, if I am understanding you correctly

**Comment by Creatium** [comment]
Yes, you understand correctly. But start-date does not seem to work together with range. No matter what start-date I set, if range is set and v-model is set to array of "to" and "end" dates, then it looks like start-date is ignored.

**Comment by Jasenkoo** [comment]
Took a deeper look, you can set the `focus-start-date` prop to ignore `v-model` value

**Comment by Creatium** [comment]
Thanks, I might have misunderstood that option.

However, is it possible its not working properly? Like in the documentation, there is a demo, that works for the first time when you open the Datepicker, but when I open it once more, it defaults back to v-model date.


Doc link: https://vue3datepicker.com/props/calendar-configuration/#focus-start-date

If in the playground I use this code, it focuses on end date no matter what. Am I missing something?

`<template>
  <div>
    <Datepicker v-model="date" range :start-date="new Date('2019-01-01')" focus-start-date />
  </div>
</template>

<script setup>
import { ref } from 'vue';
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

const date = ref([new Date('2019-01-01'), new Date()]);
</script>
`

**Comment by Jasenkoo** [comment]
@Creatium Yes, you are right, it is not working correctly, reopening.

**Comment by Jasenkoo** [comment]
The fix is included in the released v6

**Comment by Creatium** [comment]
Indeed now everything works as expected. Great job!
