### ISSUE TITLE
Invalid date return after date format

### ISSUE THREAD

**Issue by mzee19** [Vuepic/vue-datepicker#514]
**Describe the bug**
The date formats that start with DD are not working correctly. For example, the dates 31.12.2000 and 13.12.2000 are invalid when they are passed to the DD.MM.YYYY, DD/MM/YYYY, or DD-MM-YYYY formats.  The error occurs when the day is between 13 and 31. @Jasenkoo 

**To Reproduce**
1. Date format change to hard form or static form

**Expected behavior**
Must be changed but not changed in input field as given attachment

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/72722281/b47e5c9a-f5ec-4e7e-b0be-e2260e663f21)

**Desktop & mobile (please complete the following information):**
 - Browser [chrome]
 - Library version [5.4.0]

**Comment by Jasenkoo** [comment]
@mzee19 I don't get what the issue is here, in your `time` label, it is properly formatted

**Comment by mzee19** [comment]
> @mzee19 I don't get what the issue is here, in your `time` label, it is properly formatted

But not displayed inside the date-picker.

**Comment by Jasenkoo** [comment]
`DD` is not a valid token for format, please refer to valid tokens here: https://github.com/date-fns/date-fns/blob/main/docs/unicodeTokens.md
