### ISSUE TITLE
How to convert calendar to Islamic "Hijri" date and display it in different language "Arabic and English"?

### ISSUE THREAD

**Issue by berTOTAry** [Vuepic/vue-datepicker#515]
When I use locale prop. with value "ar-SA" prop it only displayed Hijri Months' name only and it is not the name of the current Hijri Month Name.
How to convert calendar to Islamic "Hijri" preferply Hijri calendar based on Um AlQura date and display it in different language "Arabic and English"  with the correct Hijri Date value? if possible ...

**Comment by Jasenkoo** [comment]
This relates to #517

**Comment by Jasenkoo** [comment]
@berTOTAry I added a comment on the linked issue, this will not be worked on, however if you need to modify the display values, you can use slots and display what is needed
