### ISSUE TITLE
How to update the documentation for a PR (docs generated?)

### ISSUE THREAD

**Issue by camya** [Vuepic/vue-datepicker#516]
Hi

I'm working on a **PR for the "preset-ranges"** and have to **update the documentation**. 

The file with contains the "preset-ranges" section of the documentation is https://github.com/Vuepic/vue-datepicker/blob/main/docs/props/modes-configuration/index.html.

Unfortunately the file looks like it's **generated**. 

How can I update the documentation for my PR?

Documentation page: https://vue3datepicker.com/props/modes-configuration/#preset-ranges
Documentation source: https://github.com/Vuepic/vue-datepicker/blob/main/docs/props/modes-configuration/index.html

**Comment by Jasenkoo** [comment]
Yeah, docs are generated from another repo, not public, feel free to create a PR, I'll take care of the documentation

**Comment by camya** [comment]
Nice to meet you. 

Great, I will do. I will write the documentation part into the PR for easy copy and paste than. :) Thank you for the info.

Maybe you can add a note to the CONTRIBUTING.md in the **"Submitting a pull request"** section explaining **"how to add the documentation"** for a PR. This would be helpful.
