### ISSUE TITLE
min-date and timezone both are set to UTC time, and the time limit is incorrect

### ISSUE THREAD

**Issue by Ltyi** [Vuepic/vue-datepicker#520]
```vue
<VueDatePicker
    min-date="2023-08-09T08:00:00.000Z"
    timezone="UTC"
  ></VueDatePicker>
```

![image](https://github.com/Vuepic/vue-datepicker/assets/32029674/881bd75a-54bb-424c-b6a4-7e983ba76446)

The expected is that the date picker should be able to select August 9, 2023.

ps. my system timezone is UTC+8.

**Comment by Jasenkoo** [comment]
It doesn't matter, `min-date` doesn't take the time into consideration, in this case, the 9th should be disabled
