### ISSUE TITLE
Incompatibility with timezone and utc props

### ISSUE THREAD

**Issue by aspitrine** [Vuepic/vue-datepicker#522]
**Describe the bug**
When i set timezone and utc props, the date value was bad caclculated
UTC date was calculated from the browser timezone instead of the timezone passed as props

**To Reproduce**
1. go to (https://stackblitz.com/edit/nuxt-starter-u8yvpj?file=app.vue)[https://stackblitz.com/edit/nuxt-starter-u8yvpj?file=app.vue]
2. change the date and show the value displayed upside the input

**Expected behavior**
When timezone and utc props was used, compute the value from the timezone props instead of browser timezone

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome and Arc
 - Library version: 5.4.0

**Comment by Jasenkoo** [comment]
They are basically the same prop, `utc` was only supported before the `timezone` prop was added. In your case, the check for `utc` is before the one for the `timezone`.
