### ISSUE TITLE
v model value format

### ISSUE THREAD

**Issue by djixadin** [Vuepic/vue-datepicker#525]
i see that there are props to format value on the input and on the action row but is there a way to format the value before it is assigned to the v-model.. cant seem to find that info anywhere in the docs or here in the issues.. im using latest version 5.4.0 in nuxt 3.6.5 project

btw keep up the good work on this package :)

**Comment by Jasenkoo** [comment]
@djixadin Yes, take a look at [`model-type`](https://vue3datepicker.com/props/general-configuration/#model-type) prop

**Comment by djixadin** [comment]
so this doesnt work for regular date picker? is there any other way for me then to round the date im receiving (something like moment.startOf('day'))
