### ISSUE TITLE
No CSS styles in v6.0

### ISSUE THREAD

**Issue by alessandromontesanti** [Vuepic/vue-datepicker#526]
FIrst of all, thank you for the awesome new release!
I had some problems with styles in the new version in my Vue CLI based project: it seems that no styles were loaded at all.
I've managed to fix it by changing package.json option "sideEffects": false to "sideEffects": ["*.css"], but I don't know if it's the right way to proceed.

**Comment by alessandromontesanti** [comment]
Tried using Vite, and the styles are correctly loaded without need to modify package.json.
Maybe a Vue CLI specific problem?

**Comment by Jasenkoo** [comment]
@alessandromontesanti Yes, because `sideEffects` is taken into consideration by webpack

**Comment by Davus111** [comment]
Same problem here using Inertia-vue3

this is how it looks like to me
![image](https://github.com/Vuepic/vue-datepicker/assets/108654069/14658c9d-67eb-4016-b620-17700e7a7c7a)

**Comment by soorajsprakash** [comment]
styles not working in vue-cli,
it's working fine in vite

**Comment by stephane-martin** [comment]
same using parcel 2.9.3 / yarn 3.6.0

everything is built without error but the css files are removed from distribution

`parcel build --no-scope-hoist` works as a workaround
