### ISSUE TITLE
Auto-open calendar on focus

### ISSUE THREAD

**Issue by cokoladasarizom** [Vuepic/vue-datepicker#533]
Is there a feature when datepicker gets focus using keyboard "tab" to auto-open calendar, just like when it gets focus via mouse click?

**Comment by Jasenkoo** [comment]
@cokoladasarizom Tab to focus input, enter to open, this won't be added as it might cause conflicts with tabbing in the menu and how the focus is managed between input and the menu. If you use `text-input` there is an option to open on tab.

**Comment by jeffgabhart** [comment]
> [@cokoladasarizom](https://github.com/cokoladasarizom) Tab to focus input, enter to open, this won't be added as it might cause conflicts with tabbing in the menu and how the focus is managed between input and the menu. If you use `text-input` there is an option to open on tab.

I'm having trouble finding the option to open on tab for `text-input` - has it since been removed?
