### ISSUE TITLE
Multiple dates do not work property

### ISSUE THREAD

**Issue by makerovski** [Vuepic/vue-datepicker#536]
**Describe the bug**
Hello,

Even in the documentation, it is not possible to selected multi dates setting a specific time.

**To Reproduce**

Select multiple dates > choose to select time > save

Only the last "day" will get the time which was selected, the other selected days will get the current time

**Expected behavior**
Example: I selected 25.08 26.98 and 29.08 and select time for 4 am. It should save all days with 4am, and not only the last day I selected

**Screenshots**
Documentation:

<img width="729" alt="Bildschirmfoto 2023-08-21 um 16 07 09" src="https://github.com/Vuepic/vue-datepicker/assets/86009432/07c097e7-24ff-46d2-b725-d6fc42368e7d">

My Program:
<img width="1256" alt="Bildschirmfoto 2023-08-21 um 16 11 26" src="https://github.com/Vuepic/vue-datepicker/assets/86009432/dd1bd919-61b3-413d-b568-03d183d261f2">

Thank you!

**Comment by Jasenkoo** [comment]
This is the intended behavior, select date > select time for that date, select another date > select time for that date, and so on. Time will update on last selected date.

**Comment by makerovski** [comment]
> This is the intended behavior, select date > select time for that date, select another date > select time for that date, and so on. Time will update on last selected date.

Is it somehow possible ? 

Thank you!

**Comment by Jasenkoo** [comment]
@makerovski This is the current behaviour
