### ISSUE TITLE
usage with nuxthq-ui leads to browser creash when on page loading

### ISSUE THREAD

**Issue by gustawdaniel** [Vuepic/vue-datepicker#537]
I described it on SO few days ago

https://stackoverflow.com/questions/76892781/when-vuedatepicker-and-uselectmenu-from-nuxthq-ui-are-used-in-the-same-page-the

1. Install this pacakge
2. Add @nuxthq/ui
3. create the simplest components from these libs on the main page and reload the page

https://github.com/gustawdaniel/daisyui-nuxtui-conflict-reproduction

**Expected behavior**
Both components should be displayed, and any of them should be independent from second 

**Seen behavior**
The page works if I will add a component from this lib OR @nuxthq/ui but not when I will add both

**Desktop & mobile (please complete the following information):**
 - Browser chrome, firefox, chromium
 - Library version `5.4.0` now I will test on 6.x

**Comment by Jasenkoo** [comment]
@gustawdaniel Can you add a wrapper div in `app.vue` and see if it resolves the issue?

**Comment by gustawdaniel** [comment]
I fixed it by the upgrade of this lib to 6.0.1 in my project. I will confirm it on this exemplary repo and if it works then close the issue. Thanks, @Jasenkoo .

![Screenshot from 2023-08-21 21-06-27](https://github.com/Vuepic/vue-datepicker/assets/16663028/ecd11ee2-c234-44fd-9708-758acdeaaf54)

**Comment by gustawdaniel** [comment]
In the reproduction repo with version 5.4.0 i had to refresh the browser few times to see:

"Page not responding"

![Zrzut ekranu z 2023-08-21 23-19-37](https://github.com/Vuepic/vue-datepicker/assets/16663028/a41190cd-2d5d-4906-a681-8ed3fa3da74a)

Additional `div` did not solved problem

```
<template>
  <div>
    <USelectMenu v-model="selected" :options="people"/>
    <VueDatePicker v-model="date"/>
  </div>
</template>
```

I updated vue-datapicker to 6.0.1 and unfortunately reproducing still this behavior when I am using `select`.

In another project I have data picker and table from `nuxthq-ui` then error is not possible to reproduce.

**Comment by Jasenkoo** [comment]
If this works with the latest version, I'll leave it as it is for now.

**Comment by gustawdaniel** [comment]
@Jasenkoo. It works with tables but not with select, so this is still existing not solved error.

> I updated vue-datapicker to 6.0.1 and **unfortunately reproducing still this behavior** when I am using select.

**Comment by gustawdaniel** [comment]
@Jasenkoo now I have this problem even without `select` (with table). There required more restarts to see it but this issue should be opened.

**Comment by Jasenkoo** [comment]
@gustawdaniel can you remove the picker and try developing a while without it, to see if the issue is still there, it may be the ui library as the picker does not add anything in the nuxt context. If the issue is not present, will reopen and take a look.

**Comment by gustawdaniel** [comment]
Ok. Every time when I remove `@vuepic/vue-datepicker` my page works.

I can try to develop it 2-3 days and check if there is any other source of this problem.

**Comment by Jasenkoo** [comment]
@gustawdaniel Tried to replicate on the repo you provided, everything seems ok, perhaps it is the node version 20 causing the issue. I am on 18 LTS


https://github.com/Vuepic/vue-datepicker/assets/23171105/ba3e4db5-1fe8-49e0-aa8b-ec5f637f45f8

**Comment by gustawdaniel** [comment]
Ok. So if it is not possible to reproduce let's leave it closed. I reproduced it many times, so was forced to resign from this library and implement a solution using v-calendar.

Now it is not a blocker for me, but maybe in the future, somebody will be able to reproduce it.
