### ISSUE TITLE
min-date and max-date is not working

### ISSUE THREAD

**Issue by dungtv1291** [Vuepic/vue-datepicker#538]
**Describe the bug**
Error when selecting range by month. if set
     :min-date="'01/01/2021'"
     :max-date="'01/01/2024'"
  then when selecting from January 2021 to January 2024 the disable month is incorrect. exactly January 2024 must be enabled, the remaining months must be disabled.

**To Reproduce**
I use the following props
      -:min-date="'01/01/2021'" 
      -:max-date="'01/01/2024'"
      - :multi-calendars="true" 
      - monthPicker 
      - autoApply
      - :range="true"
**Expected behavior**
i expect the user to be selected only for a period of 3 years.

**Screenshots**

https://github.com/Vuepic/vue-datepicker/assets/112230409/405f14c5-cb53-4390-84a6-5982ca06ef77

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by Jasenkoo** [comment]
This is expected behaviour, won't be worked on as it affects a lot of other validations
