### ISSUE TITLE
Picker does not focus selected range into view when re-opened. Same applies when updating using presetRanges.

### ISSUE THREAD

**Issue by Chuuone** [Vuepic/vue-datepicker#54]
**Describe the bug**
When this option https://vue3datepicker.com/api/props/#multicalendars is enabled. The picker does not focus into the selected period.
**To Reproduce**
1. Go to the link above.
2. Select some date in the past or the future.
3. Close the picker.
4. Open the picker.
5. See that the calendar is focused on "current date" rather than "selected range"

**Expected behavior**
I would expect the calendar to focus into view of the selected periods. I would like to add that the picker also fails at this if you "select a date by preset range as well. 

**Screenshots**
N/A

**Desktop & mobile (please complete the following information):**
N/A

**Comment by Jasenkoo** [comment]
Ok, on mounted it should focus on the view. You can pass `multiStatic="false"` to set view on the current selection

**Comment by Chuuone** [comment]
Its a miss on my side, didn't notice that there is a prop to customize this behavior. Thanks!.
