### ISSUE TITLE
Multi calendar does not show start date if range is large

### ISSUE THREAD

**Issue by charliepy** [Vuepic/vue-datepicker#540]
**Describe the bug**
When the startDate and endDate are beyond a certain range (like 90 days), the startDate month is the same as the endDate month.

**To Reproduce**
https://vue3datepicker.com/props/modes/#multi-calendars

`const endDate = new Date(new Date().setDate(startDate.getDate() + 90));`

**Expected behavior**
The startDate month shows the correct month

**Desktop & mobile (please complete the following information):**
 - "@vuepic/vue-datepicker": "^6.0.1",

**Comment by Jasenkoo** [comment]
@charliepy I am not sure what are you trying to do, are you providing the `endDate` prop?

**Comment by charliepy** [comment]
@Jasenkoo sorry for the confusion. I was using the code example for multi calendars. Instead of 7 days, I increased it to 90 days

This is what the calendar looks like if the endDate is 60 days ahead
![Capture](https://github.com/Vuepic/vue-datepicker/assets/45889586/afc75a38-68aa-41ef-8ff5-1e1a05433e3a)

This is what it looks like if it is 90 days. The months are the same
![Capture2](https://github.com/Vuepic/vue-datepicker/assets/45889586/27d7fd83-16b0-4cfc-a8fa-98e79771b7eb)
