### ISSUE TITLE
Feature Request: utc_offset_minutes property similar to timezone property

### ISSUE THREAD

**Issue by TimJohns** [Vuepic/vue-datepicker#543]
I am using the Datepicker to select arrival and departure times for locations. I am using the Google Places service, and have the [utc_offset_minutes](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult.utc_offset_minutes) readily available, but I don't have the IANA time zone name used by the existing `timezone` property. 

**Describe the solution you'd like**
It would be handy in my case, and possibly necessary in other cases where the UTC offset is known but the location is not, to be able to specify the UTC offset (in minutes) as an alternative to the existing `timezone` property. I would also propose keeping both but only allowing one or the other to be set.

**Describe alternatives you've considered**
In my specific use case I actually do have the location information, so I can almost certainly look up the IANA time zone using an API call to the [Google Time Zone API](https://developers.google.com/maps/documentation/timezone/overview), and I suspect there are other libraries that provide this functionality. Because the mapping is non-trivial, I would expect most solutions would require an API call to a service or a fairly large library.

I also looked at Intl and Temporal. Intl doesn't seem to have support for converting from UTC offset to time zone identifier. [Temporal.TimeZone](https://tc39.es/proposal-temporal/docs/timezone.html) allows for either an IANA specifier or UTC offset at initialization, and is part of the inspiration for submitting this request, but also does not appear to me to allow for run time conversion from offset to IANA time zone identifier.

**Additional context**
While it's relatively easy to get a single definitive current offset from a given IANA time zone name, there is no trivial mapping the other direction. Given a UTC offset, you can't definitively determine the IANA time zone name without also knowing the corresponding location. In my application, I do have the location, but I suspect there are other use cases where the offset is known or easily inferred from a datetime string, but the location is unknown.

I noticed several comments in existing Issues that the time zone support was being reworked so hoping this is a timely request, and if it turns out to be expensive for me to implement my planned use of the Google Time Zone API, I will try follow-up with additional comments, and possibly even a PR.

Thanks as always for creating and maintaining this date picker!

**Comment by TimJohns** [comment]
FYI quick follow-up for anyone reading this and also looking at the Google Time Zone API and associated pricing (max 5.00 USD per 1000 requests), I'm also taking a look at [TimeAPI](https://timeapi.io/), which is currently free and has a [GET /api/Time/current/coordinate](https://timeapi.io/swagger/index.html) endpoint that appears to do exactly what I need.

**Comment by Jasenkoo** [comment]
@TimJohns Why not just add the UTC minutes offset before setting the `v-model`?

```ts
import { ref } from 'vue';
 
const date = ref(); // v-model object

const utc_offset_minutes = 60;

function addMinutes(date: Date, minutes: number) {
    return new Date(date.getTime() + minutes*60000);
}

// On your API calls
date.value = addMinutes(new Date(), utc_offset_minutes )
```
