### ISSUE TITLE
Datepicker clears all other input values

### ISSUE THREAD

**Issue by yurijosha** [Vuepic/vue-datepicker#546]
Hi, thank you for sharing this wonderful library with us.

When using <Datepicker>tag in a form with other input tags, 
my Datepicker clear button clears all other input values as well.

Could you check if there is any problem with my code or setting?

```vue
<template>
  <div>
    <form>
      <input
        id="postcode"
        class="postcode"
        type="text"
        maxlength="8"
        placeholder="000-0000"
        :value="postcode"
        autocomplete="off"
      />
      <Datepicker
        uid="birthday"
        name="birthday"
        v-model="birthday"
        :enable-time-picker="false"
        locale="ja"
        :format="format"
        :year-range="[1960, 2010]"
        :start-date="new Date(2000, 9)"
        no-today
        :auto-position="false"
      ></Datepicker>
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

const date = ref();
const birthday = ref(null);
const postcode = ref('');
const format = (date) => {
  const day = date.getDate();
  const month = date.getMonth() + 1;
  const year = date.getFullYear();

  return `${year}/${month}/${day}`;
};
</script>
``` 

**To Reproduce**
1. Create a form with datepicker tag and other input tags
2. input any values to other input tags
3. Click clear of datepicker, or select any date on datepicker
4. all other values gone

**Expected behavior**
just a value of datepicker is updated/cleared.

**Comment by yurijosha** [comment]
I couldn't reproduce with this simple code, so it might be the other part of my codes which causes this problem.
I will retest my code and report if any problems.

**Comment by Jasenkoo** [comment]
![gif](https://media.tenor.com/_hLOQx93h_QAAAAC/wtf-gif.gif)

**Comment by Jasenkoo** [comment]
@yurijosha Based on the provided example, your `value` is empty, when you update it, the value is not set anywhere, then when the v-model is updated, that value is re-rendered and that is why it is reset.

For example, you can set another input below your input but add a `v-model` on it:

```vue
<template>
  <div>
    <form>
      <input
        id="postcode"
        class="postcode"
        type="text"
        maxlength="8"
        placeholder="000-0000"
        :value="postcode"
        autocomplete="off"
      />
     <!-- The input above will reset when you update this input -->
     <input type="text" v-model="test" />
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const test = ref('');
const postcode = ref('');
</script>

```

**Comment by yurijosha** [comment]
Thank you.
This was just my lack of understanding of vue.
