### ISSUE TITLE
Go to next available month when clicking on next arrow and the next month only contains blocked dates

### ISSUE THREAD

**Issue by s-rigaud** [Vuepic/vue-datepicker#548]
This is more an open question as I'm not an expert of the library.
In my application I have a standard CalendarPicker with `min-date` and `max-date` defined.
![image](https://github.com/Vuepic/vue-datepicker/assets/46346622/fe0b930e-8ac7-47c7-b36c-864883b9675b)

The thing is the users using my application do not properly understand that they need to click on the year or the month directly if the next month does not contain any valid date. Is there a way to redirect them directly to the next month with valid dates ?

Thanks for taking the time to respond to me 🙏

**Comment by Jasenkoo** [comment]
The picker already skips disabled months, however, if you use a combination of max and min date, there is nowhere to skip.

If the user by default lands on a disabled month, you can set the `start-date` property on some enabled month.
