### ISSUE TITLE
Accesibility

### ISSUE THREAD

**Issue by norbertp3** [Vuepic/vue-datepicker#549]
Hi guys,

We are currently working on making our software fully accessible for everyone (ADA). We wanted to let you know that we have sent your datepicker to an external company for a basic review. We have received some feedback:

_I wanted to let you know that I got some feedback from my auditing team on the Vue Datepicker. One of our auditors went through the site. She went to the stock example of their “Playground” and found that it wasn’t all that accessible. However, she stated that she could navigate all the way through it using her screen reader. She noted there were some issues with labels and the grid cell role that wasn’t working. Without fully auditing it, that was just a quick analysis of the consumer-facing site.
We still would recommend that if you want to go with them as a vendor, make sure to ask and get confirmation that when accessibility issues inevitably arise, they will be willing to fix them in a timely manner._

Do you have any plans to update ADA?

Thanks a lot,
Norbert

**Comment by Jasenkoo** [comment]
@norbertp3 There is nothing in the plan to enhance it further, some minor improvements might be made in the subsequent releases. If there are issues reported, they will be addressed.
