### ISSUE TITLE
TimePicker not working

### ISSUE THREAD

**Issue by Phipseyy** [Vuepic/vue-datepicker#55]
**Describe the bug**
Imported the Vue-Datepicker into my project and added it to my main.ts in order to use it globally
But if I use the TimePicker, there's the elements to input the time missing:
![image](https://user-images.githubusercontent.com/101321224/170490070-5094e434-2c81-4b41-b640-89acaff7d99d.png)

**To Reproduce**
1. Use npm install @vuepic/vue-datepicker on your project
2. Add the Datepicker globally in your main.ts 
![image](https://user-images.githubusercontent.com/101321224/170489515-2d00c016-ebe2-430e-baf4-63c4c420b4e6.png)

4. Use the Code example from here: https://vue3datepicker.com/api/props/#timepicker
Added it like that
![image](https://user-images.githubusercontent.com/101321224/170490030-c3994014-ea24-4f43-a60a-fbc3878bef6a.png)

5. Open the view to see the first screenshot

**Desktop & mobile (please complete the following information):**
 - Browser: Google Chrome Version 101.0.4951.67 (Official Build) (64-bit)
 - Library version: @vuepic/vue-datepicker 3.2.1

**Comment by Phipseyy** [comment]
No errors in the console sadly, the content of the box is just empty
How did u import the project into the sandbox?
Maybe I can try that to import it into my project

**Comment by Jasenkoo** [comment]
You can check the sandbox for code, just pasted your config.

**Comment by Phipseyy** [comment]
After a good while of finding the issue:
Turns out if u got :
`*,
*::before,
*::after {
  position: relative;
}`
in your code, the buttons for the Clock will just disappear
![image](https://user-images.githubusercontent.com/101321224/170545757-1e789f5a-1058-46c4-97fa-f5d2037a5fc0.png)
Got it now but gotta find a workaround for the other elements then
