### ISSUE TITLE
Customize 

### ISSUE THREAD

**Issue by Timothy16** [Vuepic/vue-datepicker#550]
Is it possible to customize only the calendar and not input field ?

**Comment by Jasenkoo** [comment]
It is possible, you can check the slot sections.

**Comment by Timothy16** [comment]
I have checked the slot section and i don't think i was able how to find how to achieve it.
 
 I want  input field to be white and the calendar should be dark. 
 Using the dark themes makes the input and the calendar dark .

**Comment by Jasenkoo** [comment]
You can just use CSS to override the classes.
