### ISSUE TITLE
`year-picker` does not apply `dp__overlay_cell_disabled` class when used with `disabled-dates`

### ISSUE THREAD

**Issue by olivervorasai** [Vuepic/vue-datepicker#551]
**Describe the bug**
When using `year-picker` and providing a `disabled-dates` function, the cells of the dates to be disabled are not getting the `dp__overlay_cell_disabled` class applied to them.

**To Reproduce**
https://stackblitz.com/edit/vuepic-vue-datepicker-m8uk1w?file=src%2Fcomponents%2FPlayground.vue

**Expected behavior**
A `year-picker` calendar should look the same when using either `disabled-dates` or `min-date`/`max-date`

**Screenshots**
Expected:
![image](https://github.com/Vuepic/vue-datepicker/assets/6283219/b265b7f6-cb16-4036-a784-a0dfbb77f18f)

Actual:
![image](https://github.com/Vuepic/vue-datepicker/assets/6283219/15ab4195-d1de-43fe-808c-090dba3733eb)

**Desktop & mobile (please complete the following information):**
 - Chrome 117.0.5938.22 Desktop
 - `"@vuepic/vue-datepicker": "^6.0.2"`

**Comment by Jasenkoo** [comment]
This is intended usage, you can use filters to disable needed years or months.
