### ISSUE TITLE
Custom format does not work when option text-input is used

### ISSUE THREAD

**Issue by lealea401** [Vuepic/vue-datepicker#552]
Dear @Jasenkoo,

The calendar works nicely with the text-input option enabled. But I am facing an issue which is not present if I don't enable text-input and pick directly the date from the calendar. I need to show the date in the datepicker input box in UTC. For this, I created a custom formatting function. For example the current date is 31/08/2023 12:47 but in the datepicker input box I display it as 31/08/2023 10:47. This works fine without text-input.
If I use text-input option, there is an error related to the format. As you can see from the video, after I click outside the input box the date becomes blank. It works only if I use format="dd/MM/yyyy HH:mm" but I don't know how to customize it correctly to display the date in UTC. 

Is this a bug when using text-input or I need to use the customized function differently along with text-input ?

https://github.com/Vuepic/vue-datepicker/assets/51837829/e1bcf906-b655-4b7e-b3b1-7d22acaae99d

The code I use in Playground is
```
<template>
  <div>
    <VueDatePicker
      :model-value="selectedDate"
      @update:model-value="handleDateUpdate"
      :clearable="false"
      :year-range="[1900, 2470]"
      auto-apply
      :format="formatDateToCustomString"
      text-input
    ></VueDatePicker>
  </div>
</template>

<script>
import VueDatePicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

export default {
  components: {
    VueDatePicker,
  },
  data() {
    return {
      selectedDate: new Date(),
    };
  },
  methods: {
    handleDateUpdate(newDate) {
      this.selectedDate = newDate;
    },
    formatDateToCustomString(dateString) {
      const date = new Date(dateString);
      const day = String(date.getUTCDate()).padStart(2, '0');
      const month = String(date.getUTCMonth() + 1).padStart(2, '0'); // Months are 0-based
      const year = date.getUTCFullYear();
      const hours = String(date.getUTCHours()).padStart(2, '0');
      const minutes = String(date.getUTCMinutes()).padStart(2, '0');
      return `${day}/${month}/${year} ${hours}:${minutes}`;
    },
  },
};
</script>

```

**Comment by Jasenkoo** [comment]
@lealea401 What you are trying to achieve is not possible.

1. You can't use `function` for both `text-input` parsing and `format`
     - `text-input` parser function must return `Date` or `null`
     - `format` function must return `string` 
2. To separate these concerns, you need to provide 
     - `:format="formatDateReturnString"`
     - `:text-input={ format: parseDateReturnDate }`

When the function is provided to the `text-input` format, the value displayed in the input field will fall back to the `format` prop.

Keep in mind that the `Date` that is returned from the parser function needs to be in sync. In your case, if your format is set that months start from 0, you will need to bump numbers in the format function in order to return the proper date, otherwise, it will always return one month before the current.

**Comment by lealea401** [comment]
Dear @Jasenkoo, I understand...but without using any formatting, is it possible to create a calendar that gives the dates in UTC?
I saw this example in the documentation
<img width="339" alt="calendarUTC" src="https://github.com/Vuepic/vue-datepicker/assets/51837829/2a540cc3-e3fc-41fd-aada-1edd28ef643b">

But it works only if you select the UTC from the list. 
I was wondering if it would be possible to have it work like this:

```
<VueDatePicker 
            v-model="date" 
            :timezone="UTC"
 />

```
I am working with scientific data and the dates are in UTC so, an UTC calendar would be useful.

**Comment by Jasenkoo** [comment]
@lealea401 Yes, you can use [`utc`](https://vue3datepicker.com/props/modes/#utc) prop

**Comment by lealea401** [comment]
@Jasenkoo , thanks! I knew about this property but it was not working as I was expecting. I tried to use the option 'preserve' expecting to see a difference of two hours in the calendar but I see that the input is converted in local timezone. My goal is to to see the time in UTC when I open the calendar as the preserve option would work (preserve : The input date will be the same, meaning, that it will not convert the date in the local timezone, but preserve the original UTC time)

https://github.com/Vuepic/vue-datepicker/assets/51837829/f9a3a787-8727-4216-ae60-2efec4a0275e

**Comment by lealea401** [comment]
Dear @Jasenkoo, could you give me feedback on my last question? If I could have the dates in the calendar in UTC it would be great. Thank you so much.

**Comment by Jasenkoo** [comment]
@lealea401 

The date object in the browser must be in the local time zone. You can't remove the timezone, most of the libraries,  just add/sub times depending on the timezone. That said, you will have to convert the date object to a string value if you want to remove the timezone value. 

Let's say the current time is UTC `18:00` and your timezone is `GMT+1`

- `preserve` if you provide the date, it will keep it on `18:00` (expected that you only work with UTC dates and not concerned about the timezone)
- `true` will add `+1` and the value will be `19:00` (You will receive UTC date and want to display it in user local timezone)

**Comment by lealea401** [comment]
@Jasenkoo, but the example that you provide here [timezone](https://vue3datepicker.com/props/modes/#timezone) works exactly how I want it to work, i.e.: if you select "UTC" as timezone, and let's say my local time is 07:55 when I open the calendar to pick up a date with hour and minutes the hours-minutes picker reflects the UTC time, i.e. it does not show 07:55 but 05.55. 

https://github.com/Vuepic/vue-datepicker/assets/51837829/9f29206d-d13a-4826-a228-581d00a087be


In this example I see that you use :timezone="UTC" 
`<VueDatePicker v-model="date" :timezone="timezone" /> `
but it works only if you select the timezone from the select droplist. Ideally it should work like this:
`<VueDatePicker v-model="date" :timezone="UTC" />`

I thought that using utc='preserve' it would work in the same way, i.e. when you open the watch with hour:minutes, I would see 05:55 not 07:55. Since the time on the pc shows the same time as in the calendar it is not evident for the user that the calendar is set to UTC.
Is it possible to achieve a calendar like in the  [timezone](https://vue3datepicker.com/props/modes/#timezone)  but without selecting the timezone but setting it by default? Unfortunately utc="true" or utc='preserve' do not have the same behavior.

Thank you so much
