### ISSUE TITLE
Since updating to version 6 from 5, month and year modes no longer use month-year slot

### ISSUE THREAD

**Issue by BrachyKnight** [Vuepic/vue-datepicker#554]
**Describe the bug**
Since updating the package from version 5.4.0 to 6.0.2, the "year" and "month" modes no longer use the "month-year" slot. I had implemented a custom version of that overlays since using that slot basically disabled any kind of overlay.

**To Reproduce**
- Update the component from version 5.4.0 to 6.0.2 while having a custom "month-year" slot
- The new custom overlays are not respected

**Expected behavior**
I expected the component to still behave like in version 5.4.0, since in the documentation it doesn't say anything regarding this change

**Screenshots**
![old_year_mode](https://github.com/Vuepic/vue-datepicker/assets/47126278/8f3a2036-2e09-4d71-947a-1554fa480461)
![new_year_mode](https://github.com/Vuepic/vue-datepicker/assets/47126278/157d1abe-0656-4540-8192-ca8ee19a7bcb)
![old_month_mode](https://github.com/Vuepic/vue-datepicker/assets/47126278/4c162c1a-f4bd-4a8f-a49b-1a82515b86b8)
![new_month_mode](https://github.com/Vuepic/vue-datepicker/assets/47126278/5d9db45d-a905-44b9-ad3f-f2daab69a353)

**Desktop & mobile (please complete the following information):**
 - Browser Chrome
 - Library version 6.0.2

**Comment by Jasenkoo** [comment]
Missed that one, it was not ported to the new component, it will have a minor breaking change, will update the documentation too.
