### ISSUE TITLE
Auto range to select disabled dates within the range apart from start and end date.

### ISSUE THREAD

**Issue by ToinePK** [Vuepic/vue-datepicker#555]
First of all, thank you for this awesome package. 

I do have an issue with the disabled dates prop and it's inconsistency. What I would like is the disabled dates to only be in effect for the start and end date. Which is how it works out of the box. E.g. the no-disabled-range prop is false by default. 

However, I find it confusing this isn't the case when auto-range is active. For the flow of our webform I really need the autorange option for a customer first selects a "period" of days.

It used to be the case this worked more consistently, though I notice this has been changed as a "bugfix" on issue number #48. However I would say the initial issue is not a bug because the setting the prop no-disabled-range to true would have been sufficient imho. And it wouldn't create inconsistency in expectation/behaviour.

Is there a way to revise this or to have a prop no-disabled-auto-range for example?

Love to hear your thoughts.

**Comment by Jasenkoo** [comment]
I don't quite follow the expected behavior. Do you have issues with `no-disabled-range` including disabled dates when it is enabled?

**Comment by ToinePK** [comment]
The problem is that no-disabled-range doesn't work / gets ignored when using auto-range. So for example in my app:

`<VueDatePicker
    v-model="dateModel"
    :enable-time-picker="false"
    :range="true"
    :auto-range="range?.value"
    :auto-apply="true"
    :no-disabled-range="false" // Although it's default false, get's ignored nontheless
    :disabled-dates="disabledDates()"
    :disabled-week-days="disabledWeekDays()"
    :min-date="minDate"
    inline
/>`

Without auto-range the no-disabled-range prop works as expected. I don't understand why there should be a difference in behaviour. In our consuming application we need the customer to first select a period (in days) before they can select a date. Using range without the auto-range wouldn't make sense here.

As I said earlier, it looks like this behavioural change was added on #48 with accompanying commit:
https://github.com/Vuepic/vue-datepicker/commit/b3de2e29152ae352628da298ef4ca8abca3253fb
