### ISSUE TITLE
Click event propagation

### ISSUE THREAD

**Issue by dev387** [Vuepic/vue-datepicker#556]
**Describe the bug**
In our intern application, we have some kind of user inactivity logic which is based on click and touch events. In `vue-datepicker` library, almost every click event is followed by stop propagation. Maybe there are cases where stop propagation is needed, but I have tried to removing it and it looks that it not break anything. If you want, I can make a PR.

**To Reproduce**

1. Click on whatever on datepicker '....'
2. Click event is not propagated

**Expected behavior**
Click event is propagated to parent element.

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Browser: every browser
 - Library version: Probably all versions, but for now let's say `6.0.0`

**Comment by Jasenkoo** [comment]
Initially, it was added [here](https://github.com/Vuepic/vue3-date-time-picker/issues/51)(link to an old repo). I'll probably add a prop to disable these events without the need to remove them completely as it might break existing functionalities with 3rd party libraries, but will see exactly.
