### ISSUE TITLE
 startTime doesnt work if range is specified.

### ISSUE THREAD

**Issue by Ghostff** [Vuepic/vue-datepicker#56]
**Describe the bug**
Start time doesn't work on ranged selection

**To Reproduce**
```vue
<Datepicker v-model="date" :startTime="{ hours: 0, minutes: 0 }" range placeholder="Select Date" />
```

**Expected behavior**
When the date is selected, the time should be `00:00` but its uses system time instead.

**Comment by Jasenkoo** [comment]
@Ghostff Sorry for the late response, this is not an issue, you have to provide time arr when using a range. Following code will work as expected.

```vue
<Datepicker
     v-model="date"
     :start-time="[{ hours: 0, minutes: 0 }, { hours: 0, minutes: 0 }]"
     range
     placeholder="Select Date" 
/>
```
