### ISSUE TITLE
disable dates don't obey utc preserve

### ISSUE THREAD

**Issue by morteza-mortezai** [Vuepic/vue-datepicker#560]
Hi
when **utc** is set to **preserve**
and you set disabled dates like this ['2023-09-08']
then it display wrong disabled dates .
it seems it doesn't consider utc preserve

**Comment by Jasenkoo** [comment]
Looks like the correct date is displayed

![Screenshot 2023-09-08 213219](https://github.com/Vuepic/vue-datepicker/assets/23171105/65260536-2620-4817-ba5d-82544946a873)

**Comment by morteza-mortezai** [comment]
But if you change your system time zone to positive and negative UTC zones , you will see it display different disabled dates

**Comment by morteza-mortezai** [comment]
`        <VueDatePicker utc='preserve' :format="format" :model-value="form.plan_start_date" 
          :disabled-dates="closedDates" @update:model-value="onStartDateChange" :enable-time-picker="false"
          model-type="format" />`

![image](https://github.com/Vuepic/vue-datepicker/assets/75200938/6b061d5c-bce4-4b91-ab1b-7b0494626486)
when OS time zone is set to Iran

![image](https://github.com/Vuepic/vue-datepicker/assets/75200938/72200473-35ce-40cf-8f5d-7386534f461c)
and when OS time zone is set to Vancouver/Canada
As you can see they it displays different disabled dates while **UTC** is **preserve**

**Comment by Jasenkoo** [comment]
Yes, I see, can you please provide me a list value for `closedDates` so I can check
