### ISSUE TITLE
Allow timepicker to have range dates in reverse order

### ISSUE THREAD

**Issue by Nemega** [Vuepic/vue-datepicker#57]
First of all thank you for providing such a nice component.

I would very much appreciate if I could do the following in timepicker:

20:00 - 04:00 (from 8pm to the next day until 4am)

In short it does not allow me to have Time A > Time B
You can actually force it with textinput prop (might not be intended, let me know if I should open an issue for that)

Best Regards

**Comment by Jasenkoo** [comment]
I don't know, this happens because it is the same date in range. If you set one for today and one for tomorrow, you can select the needed time

**Comment by Nemega** [comment]
Exactly! The issue being in Timepicker you can only select a time, not a date.
The use case would be for example setting up a daily night shift that starts at 20:00 and ends at 4:00. A Datetimepicker would only do the job for one day while it would be useful to have it every day, therefore the use of Timepicker instead.

Thank you very much for your taking the time to read my request. It would be nice to have a prop giving us more control over this date order check in range mode, at least for the Timepicker.

**Comment by Nemega** [comment]
Awesome! Thank you very much. Looking forward to the next update.
