### ISSUE TITLE
disabled-times have a bug!

### ISSUE THREAD

**Issue by javazyx** [Vuepic/vue-datepicker#570]
![1694742926649](https://github.com/Vuepic/vue-datepicker/assets/16065663/460c9e11-86cd-49ba-b476-462f043d90cc)

**Comment by ayrtonandino** [comment]
Looks like that if you enable `disabled-times` the `Select` button gets disabled when you select any of the minutes present in the array, regardless of the hour selected:

Using https://vue3datepicker.com/props/time-picker-configuration/#disabled-times `V6.1.0` as an example:

```js
const disabledTimes = [
  { hours: 15, minutes: '*' }, // disable full hour
  { hours: 16, minutes: 15 },
  { hours: 16, minutes: 20 },
  { hours: 17, minutes: 30 },
];
```

09:15 -> `disabled` **not ok**
09:20 -> `disabled` **not ok**
09:30 -> `disabled` **not ok**

16:15 -> `disabled` ok
16:20 -> `disabled` ok
16:30 -> `disabled` **not ok**

17:15 -> `disabled` **not ok**
17:20 -> `disabled` **not ok**
17:30 -> `disabled` ok
