### ISSUE TITLE
Please implement single quarter and quarter range selector

### ISSUE THREAD

**Issue by bytemelab** [Vuepic/vue-datepicker#571]
**Is your feature request related to a problem? Please describe.**
I need to use quarters for customer and there is no vue3 datepicker plugin that offers it except Vue Ant Design, but there are also some other issues

**Describe the solution you'd like**
I would like to select a single quarter or a range between two quarters

**Describe alternatives you've considered**
As mentioned above Vue Ant Design has it, but I have different problems there.

**Additional context**
To get an idea of how it would look like, you can check Vue Ant Desing or you can check vue2 datepicker https://vue-datepicker.netlify.app/. It seems that it's not maintained anymore so I can't use it

**Comment by mitjarobic** [comment]
@Jasenkoo  QuarterPicker works great, but the month names do not get translated. Default is english.
