### ISSUE TITLE
min-date doesn't obey UTC preserve

### ISSUE THREAD

**Issue by morteza-mortezai** [Vuepic/vue-datepicker#574]
I am using DatePicker like this :
`        <VueDatePicker  :utc="'preserve'" :format="format" 
          :min-date="new Date()" :enable-time-picker="false" model-type="format" />
`
and it seems there is some problem with min-date .

today is **2023-09-18** 

in Iran time zone 2023-09-18 is enabled

![image](https://github.com/Vuepic/vue-datepicker/assets/75200938/e1552272-8360-4fa6-9784-37f224109824)

But in Canada time zone is diabled

![image](https://github.com/Vuepic/vue-datepicker/assets/75200938/14587502-1da1-4805-82bd-6d64591609d8)

and I think this is bug .

**Comment by Jasenkoo** [comment]
@morteza-mortezai You would need to use ISO format for example `min-date="2023-09-18"` in order to be independent of time zone. If you use `new Date()` it will always be on the client zone.
