### ISSUE TITLE
time-picker doesn't obey UTC preserve

### ISSUE THREAD

**Issue by morteza-mortezai** [Vuepic/vue-datepicker#575]
Hi
`
        <VueDatePicker :utc="'preserve'" format="yyyy-MM-dd HH:mm" v-model="dateTime" 
          model-type="yyyy-MM-dd HH:mm" />
`
as you see utc is set to **preserve**

but when you pass a date-time like this **2023-09-15 11:48** 

time is change by changing OS time zone .
1. Canada time zone
![image](https://github.com/Vuepic/vue-datepicker/assets/75200938/b995978b-ab3f-45d5-b794-a85fa57c6c32)
2. Iran time zone
![image](https://github.com/Vuepic/vue-datepicker/assets/75200938/c20c19b6-854f-4ed5-896b-6261f5b4aacb)

as you see results are **different**

**Comment by Jasenkoo** [comment]
`utc` mode is not compatible with `model-type`. There is already conversion when model-type is used.
