### ISSUE TITLE
model-value output format is incorrect

### ISSUE THREAD

**Issue by morteza-mortezai** [Vuepic/vue-datepicker#576]
this is my code

`
        <VueDatePicker :utc="'preserve'" format="yyyy-MM-dd HH:mm" v-model="dateTime" 
          model-type="format" />
`

when I set date and time the **output** is like this

![image](https://github.com/Vuepic/vue-datepicker/assets/75200938/637b8682-940b-41fd-8a68-fe058debaf73)

it expect to be like this

**2023-09-10 08:18**

**Comment by Jasenkoo** [comment]
It is correct, you are just providing a format for the input field. To have `model-value` as a formatted string, you need to set `model-type`
