### ISSUE TITLE
Year Slot does not provide year as value

### ISSUE THREAD

**Issue by ihardyslide** [Vuepic/vue-datepicker#577]
Hi,

I tried to use the `year`-slot as described [in the docs](https://vue3datepicker.com/slots/overlay/#year), but unfortunately it does not seem to work as intended.
The element gets replaced as expected, but the value for the year does not get returned.

**To Reproduce**
1. Replace the year-slot as described in the docs
```
<template>
    <VueDatePicker v-model="date">
      <template #year="{ year }">
        {{ year }}
      </template>
    </VueDatePicker>
</template>

<script setup>
import { ref } from 'vue';

const date = ref(new Date());
</script>
```
2. Open the datepicker
3. See there is no year populated

**Expected behavior**
If I use the year-Slot, I expect the `year` property to be filled with a value.

**Screenshots**
![2023-09-19 10_39_36-Debian 11 Fresh  wird ausgeführt  - Oracle VM VirtualBox](https://github.com/Vuepic/vue-datepicker/assets/1192287/f70aa827-80de-4570-9280-fc0bc437c0a3)

**Desktop & mobile:**
 - Browser: Chrome & Firefox
 - Library version: 6.1.0 (also did not work with 6.0.3)

**Comment by Jasenkoo** [comment]
This is actually wrong in the docs, it was changed in v6, the value is named `value` instead of `year` like `#year="{ value }"`
