### ISSUE TITLE
Fix time validation bug

### ISSUE THREAD

**Issue by manuxdjent** [Vuepic/vue-datepicker#578]
**Describe the bug**
When time is set using timepicker input, time validation is not performed on component closed/blurred.

**To Reproduce**
1. Set timepicker prop format to datetime and set max or/and min time
2. Click on datetime input and write an invalid time (above max-time e.g).
3. Click outside vue-datepicker component, now is closed.
4. Invalid time still appears in the time input.

**Expected behavior**
When time is set via time input and you close the component (blur), the time that it should be appear is the last valid input value.

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/3187359/9edb219f-713f-464b-ba26-3a5f20e86dc6)
![image](https://github.com/Vuepic/vue-datepicker/assets/3187359/b874510a-eb63-4ac3-9d60-5f04630d943c)
![image](https://github.com/Vuepic/vue-datepicker/assets/3187359/29efd53e-2a00-4516-8e91-247278c7ae0c)

**Desktop & mobile (please complete the following information):**
 - Desktop Chrome version 116.0.5845.188
 - Library version 6.1.0

**Comment by Jasenkoo** [comment]
It is more of an enhancement as the `text-input` doesn't provide validation

**Comment by manuxdjent** [comment]
> It is more of an enhancement as the `text-input` doesn't provide validation

Do you know when the next version is going to be released approximately ?
Thanks :D

**Comment by Jasenkoo** [comment]
Somewhere during the next week probably
