### ISSUE TITLE
Base CSS breaks animation of TimePicker

### ISSUE THREAD

**Issue by Phipseyy** [Vuepic/vue-datepicker#58]
**Describe the bug**
As soon as the Base.CSS of the site contains the following code:
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  position: relative;
  font-weight: normal;
}

The Timepicker wont load any content

Could u help me to fix this problem?

https://stackblitz.com/edit/vitejs-vite-dqeken?file=src/assets/base.css

**Comment by Jasenkoo** [comment]
I am aware, just remove this line `position: relative;`. Since `*` will affect all elements, and overlays in the calendar are positioned absolutely
