### ISSUE TITLE
`utc="preserve"` does not work with week-picker mode

### ISSUE THREAD

**Issue by cjcanlas01** [Vuepic/vue-datepicker#581]
**Describe the bug**
Hello! I've been reading the docs for some hours now trying to look for answers and I was wondering if its intended that the `utc="preserve"` does not work with the week-picker mode. When I'm using a single date picker, the date value is returned in ISO format but with week-picker mode, the two date values is return as the default date string in my local timezone.

**To Reproduce**
1. Set prop `utc` to `preserve`
2. Set prop `week-picker`

**Expected behavior**
Both date values will be in ISO format, not in default date string.

**Screenshots**
On week-picker mode and `utc` is set to `preserve`
![image](https://github.com/Vuepic/vue-datepicker/assets/40020298/70730352-7ca2-4a35-aeb8-11d677ccb8e8)

On normal mode with `utc` set to `preserve`
![image](https://github.com/Vuepic/vue-datepicker/assets/40020298/ec6ecad6-c44b-4762-a33b-7681bf012177)

**Desktop & mobile (please complete the following information):**
 - Browser Chrome
 - Library version `v6.1.0`

**Comment by Jasenkoo** [comment]
Changing to enhancement, the `utc` mode only works with the date-picker, however, it can be easily adjusted to support the week picker.

**Comment by cjcanlas01** [comment]
Thank you!
