### ISSUE TITLE
How to work model-type and format together

### ISSUE THREAD

**Issue by komodora** [Vuepic/vue-datepicker#582]
**Describe the bug**
I want the input fields to be displayed in Japanese and the modelValue to be kept in ISO format. However, if I **put a function into format property**, it did not work. 

**To Reproduce**
1. Write the code as below
```
<script setup>
const date = ref();
const formatStr = "yyyy-MM-dd'T'HH:mmXXX";
const displayFormatFunc = (date) => {
  const year = date.getFullYear();
  const month = date.getMonth() + 1;
  const day = date.getDate();
  const dayOfWeek = date.getDay();
  const dayOfWeekStr = ["日", "月", "火", "水", "木", "金", "土"][dayOfWeek];

  return `${year}.${month}.${day}(${dayOfWeekStr})`;
};
</script>

<template>
  {{ date }}
  <VueDatePicker
    v-model="date"
    :enable-time-picker="false"
    locale="jp"
    :model-type="formatStr"
    :format="displayFormatFunc"
  >
</template>
```
2. Select  the date
3. See date value and input field

**Expected behavior**
I expect that date was formatted by formatStr and input field was formatted by displayFormatFunc.
Like this screenshots.
![image](https://github.com/Vuepic/vue-datepicker/assets/50969667/90cdfb81-47eb-48f1-b0c9-91363e5d8cca)

But, the results are shown below.

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/50969667/50e2fed7-9d56-49f7-be73-dc784fb231a1)

**Desktop & mobile (please complete the following information):**
 - Browser: chrome
 - Library version: 6.1.0

**Comment by doubled3264** [comment]
me too, i use this to solve

`<script setup lang="ts">
import { format } from 'date-fns'
import { id } from 'date-fns/locale'

const datePicker = ref()
const dateToShow = ref()


function customFormat(date: Date) {
  const day = date.getDate()
  const month = date.getMonth() + 1
  const year = date.getFullYear()

  return `Selected date is ${day}/${month}/${year}`
}

function handleInternal(date: any) {
  console.log(date)
  datePicker.value = date
  dateToShow.value = format(date, 'dd MMMM yyyy', { locale: id })
}
</script>
<template>
  <div class="custom-date-picker-v2">
    <p>{{ dateToShow }}</p>
    <vue-date-picker
      :model-value="datePicker"
      :format="customFormat"
      :placeholder="getPlaceholder"
      :enable-time-picker="false"
      month-name-format="long"
      locale="id"
      position="left"
      @update:model-value="handleInternal"
    ></vue-date-picker>
  </div>
</template>
`

**Comment by komodora** [comment]
Thank you @Jasenkoo !
I am eagerly awaiting this update.
