### ISSUE TITLE
auto-apply and flow don't work together

### ISSUE THREAD

**Issue by xras-dev** [Vuepic/vue-datepicker#583]
**Describe the bug**
Using flow for define the selecting order and auto-apply for automatically select the value, if you jump from year or month select to calendar clicking in the calendar button auto-apply stops working.

**Expected behavior**
Clicking on a date value will automatically select the value.

**Screenshots**
https://github.com/Vuepic/vue-datepicker/assets/65831939/cdd81374-86cb-48df-a036-63d97b9cf1c6

**Desktop & mobile (please complete the following information):**
 - Chrome
 - Library version 6.1.0

**Comment by Jasenkoo** [comment]
You need to set [`partial-flow`](https://vue3datepicker.com/props/modes-configuration/#partial-flow) to enable that behavior
