### ISSUE TITLE
Tree shake suggestions?

### ISSUE THREAD

**Issue by Jasenkoo** [Vuepic/vue-datepicker#587]
Hello everyone, I am currently investigating the possibility of tree shaking. In that regard, I would like to see what you think of it, is it worth it, or if you have any better suggestions?

As you see, currently the picker exports a single component. Child components are imported depending on the `mode` you select, e.g. `month-picker`, `year-picker`, and so on. Even tho, the logic for each mode is scoped per mode, the menu components imports all components, and depending on the mode, it displays the needed one, meaning, that all of these components are going to be included in the single output.

I have created a blank `vite` app and tried different approaches.

Here is the build output based on the current state where the build app is **~250kB**

![Standard](https://github.com/Vuepic/vue-datepicker/assets/23171105/3b58e9ba-2fc7-47f1-a9e1-5b6be8462a79)

The solution I came up with (the only one actually that worked) is to remove imports from the menu component and move it to the prop. Basically, you will pass a component that you want to use instead of a mode. Something like this:

From:  `:month-picker=true` to `:mode="MonthPicker"`

Using that approach, we can see that the same app size changes based on the mode used (some modes require less logic):

**DatePicker**

![DPicker](https://github.com/Vuepic/vue-datepicker/assets/23171105/84b2a1a3-5471-4287-8f50-f86906b81c5b)

**MonthPicker**

![MPicker](https://github.com/Vuepic/vue-datepicker/assets/23171105/48b8ca76-5f67-4179-a77a-6add1f93d4a7)

**TimePicker**

![TPicker](https://github.com/Vuepic/vue-datepicker/assets/23171105/436a9dd9-fb1f-4081-a2fa-c6bccc4a7f9e)

**YearPicker**

![YPicker](https://github.com/Vuepic/vue-datepicker/assets/23171105/a0872d47-5dc5-44a7-9894-df9b9c4b2713)

The proposed change would look something like this

```vue
<template>
    <VueDatePicker :mode="DatePicker">
<template>

<script setup>
  import { VueDatePicker, DatePicker } from "@vuepic/vue-datepicker"
</script>

```

Would love to hear your thoughts.

**Comment by Jasenkoo** [comment]
Linking #479 as it was previously raised.

**Comment by Jasenkoo** [comment]
Close due to low interest, can be reopened in the feature.

**Comment by riderx** [comment]
I currently use 1 time the picker in my project, and it takes up to 12% of it in my bundle:
![CleanShot 2024-07-12 at 12 38 21@2x](https://github.com/user-attachments/assets/0455fb4d-c923-4c51-a626-44b72b4e5402)
And date-fn is 50% of it, I would vote for explicit import if possible
