### ISSUE TITLE
make disable weekdays and allowedDates and disabledDates work together

### ISSUE THREAD

**Issue by zynth17** [Vuepic/vue-datepicker#59]
**Is your feature request related to a problem? Please describe.**
right now only disable weekdays and disabled dates work fine together
but if i added the alloweddates it replace all the settings for disableddates and disabled weekdays

**Describe the solution you'd like**
allowing the 3 of them work together

**Additional context**
[example](https://stackblitz.com/edit/vitejs-vite-hnth41?file=src/App.vue)

**Comment by Jasenkoo** [comment]
This kinda defeats the purpose, if you need to add disabled dates, just remove them from allowed dates. There is no point in using all of them together. Or am I missing something?
