### ISSUE TITLE
Changing the width does not seem to work correctly

### ISSUE THREAD

**Issue by mark1502** [Vuepic/vue-datepicker#590]
**Describe the bug**
Using style to change the width of the datepicker input field.   The input element size changes, but it still takes most of the rest of the space:

Here's a quickly drawn example:
```
<form>
   <div>
      <div class="mr-2">
           Line 1
      </div>
      <div class="flex w-[600px]">
         <label class="mr-3">
            Date1:
         </label>
         <VueDatePicker v-model="date1" uid="demo1" class="vdtp_sm"/>
         <label>
            Date2:
         </label>
      </div>
      <div>
          Line 3
      </div>
   </div>
</form
```
```
<style>
.vdtp_sm .dp__input {
    height: 32px;
    width: 200px;
    border-radius: 4px;
    border-color: lightgray;
    font-size: 14px;
}
</style>
```
Here's a picture of the result:

![VueDTP_sizing_issue](https://github.com/Vuepic/vue-datepicker/assets/38567111/8a415088-d9a3-4d61-b21a-f3b8377dc5aa)

If I click anywhere from the start of the datepicker field all the way up to the 'Date 2', the datepicker is activated.  This has made it difficult to place date fields side by side on a form.

I'm probably not styling it correctly, but not sure how to do it.

Thanks

**Comment by Jasenkoo** [comment]
You need to target it like this in order to limit the width, because it has a wrapper container that is `100%` width

```css
.dp__main  {
  width: 200px;
}
```

**Comment by mark1502** [comment]
That's great, thanks for your help!
