### ISSUE TITLE
NPM running issue facing

### ISSUE THREAD

**Issue by abbelal** [Vuepic/vue-datepicker#591]
**Describe the bug**
After Installation when I command npm start then getting some error. I can not understand why showing this error. 
I installed by this command `yarn add @vuepic/vue-datepicker`

I need some assistance on how to solve it. Can anyone help me?

my node: v18.0.0
npm version: 8.6.0

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/54698209/6c486ee7-c353-487f-97b4-2cfae6f163bb)
![image](https://github.com/Vuepic/vue-datepicker/assets/54698209/b1c8ae05-80f2-4d39-b2d4-8bf47dcb082b)
![image](https://github.com/Vuepic/vue-datepicker/assets/54698209/15ee5206-7c1d-41ab-8f39-1bb69a268a56)

**Comment by Jasenkoo** [comment]
This error comes from the `vueuse/shared` library, it is possible that it was in a lock file but removed from package.json, and when you added a new package, the lock file was regenerated. Try running `yarn add @vueuse/shared` or reinstall `vueuse`
