### ISSUE TITLE
Textinput not working with custom format

### ISSUE THREAD

**Issue by Kingside88** [Vuepic/vue-datepicker#592]
**Describe the bug**

I want my visible format to be "yyyy-MM-dd-HH:mm", the modal format should be iso ""yyyy-MM-dd'T'HH:mm:ss"" 
but I want to write down fast in this format: "yyyyMMddHHmm"

**To Reproduce**
```
let datetime = ref<string>("1988-02-22T08:30:00")

  <div>
    <VueDatePicker 
    :model-value="datetime" 
    format="yyyy-MM-dd-HH:mm" 
    model-type="yyyy-MM-dd'T'HH:mm:ss"
    text-input
      :text-input-options="{
        enterSubmit: true,
        tabSubmit: true,
        openMenu: true,
        format: 'yyyyMMddHHmm'
      }" 
       />
  </div>
```

**Expected behavior**
I use the newest version 6.1.0.
A former 5. something worked that way.
I could type in "202309070830" -> Enter -> the datetimepicker changed 2023-09-07 08:30 without problems.
But now Enter do nothing. Even a click on "select" in the dialog do nothing.

Also I have a feature request on this: Can you please add a new textInputOption, when focus on input it should select the input.
So when I type something it overwrites the input field.

Here https://vue3datepicker.com/props/modes-configuration/#text-input-configuration I read that it would only work when it could parse to javascript date. Is it true?
```
new Date('2023-09-27 08:30') // works
new Date('202309270830') // Invalid Date
```
power user always wants to type fast. So it would be amazing this could work this way

**Comment by Jasenkoo** [comment]
It is not a bug, the `text-input-options` prop is removed in v6. It is moved directly to the `text-input` like: 

```vue
 <div>
    <VueDatePicker 
    :model-value="datetime" 
    format="yyyy-MM-dd-HH:mm" 
    model-type="yyyy-MM-dd'T'HH:mm:ss"
    :text-input="{
       enterSubmit: true,
       tabSubmit: true,
       openMenu: true,
       format: 'yyyyMMddHHmm'
    }" 
   />
  </div>
```

For the new option, I'll add it.

**Comment by Kingside88** [comment]
Thank you so much. 
Just :text-input do the job.
My workaround for selecting is now

```
onMounted(() => {
  datePickerRef.value?.$el.addEventListener('focusin', (event: any) => {
    if(event.target.tagName != 'INPUT'){
      return
    }
    event.target.select()
  })
})
```

it's not that cool but it works
