### ISSUE TITLE
Package usage stops my global event listener working.

### ISSUE THREAD

**Issue by shealavington** [Vuepic/vue-datepicker#595]
**Describe the bug**
When I click inside the date input from this package, a global click event listener attached to my application is not fired.

**To Reproduce**
1. Implement package normally
2. Register a global event listener 
2.1 `window.addEventListener('click', () => console.log('Should See this for every click on the page'))`
4. Click on empty space on the page, the event is fired.
5. Click inside the date-picker input, the event is _not_ fired.

**Expected behavior**
I would expect the package to work fine, but also expect my event listener to fire.
This is because, when a click event happens, I need to close a dialog.
My dialog is being closed when clicking everywhere except in the date field.

I would guess this package is performing some kind of click event hijack without propagation?
I'll take a look if I get time, if not, it's raised as an issue. :)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome Latest
 - Library Version: v7.0.0

**Comment by shealavington** [comment]
I have found a workaround for now.

I don't believe my workaround should be a permanent solution that is relied upon. However, if propagation has been disabled for a particular reason, I can understand. This ticket can serve as a reference for anyone else who has this issue.

I'll leave this ticket open for now, but happy for you to handle as seen fit.

### Solution:

Change the `useCapture` property of the event listener to `true`.
`window.addEventListener('click', () => console.log('Should See this for every click on the page'), true)`

**Comment by Jasenkoo** [comment]
@shealavington This is intended usage, to disable it set `allowStopPropagation` in `config` prop, `:config="{ allowStopPropagation: false }"`
