### ISSUE TITLE
Documentation -> Installation custom SCSS folder path not correct

### ISSUE THREAD

**Issue by ga-devfront** [Vuepic/vue-datepicker#6]
**Describe the bug**
In the documentation, **Installation** page, the path for full custom control SCSS is : 
```scss
@import '@vuepic/vue-datepicker/src/Vue3DatePicker/style/main.scss';
```
But the true path is : 
```scss
@import '@vuepic/vue-datepicker/src/VueDatePicker/style/main.scss';
```

**To Reproduce**
1. Go to 'https://vue3datepicker.com/installation/#local'
2. Watch the end of **Local** section.

**Expected behavior**
Change the documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/52718717/159936289-184a291b-5e65-4e26-83ea-c08babe01ec5.png)

**More informations:**
I fix this issue in my pull request -> https://github.com/Vuepic/vue-datepicker/pull/5

**Comment by Jasenkoo** [comment]
Missed that, tnx. Merged

**Comment by Jasenkoo** [comment]
Updated
