### ISSUE TITLE
I can't selectable current month

### ISSUE THREAD

**Issue by harundogan01** [Vuepic/vue-datepicker#60]
Hello. I can't selectable current month. To be able to select the current month, I need to set the largest month as the next month or the following months. This is an unreasonable method.

I recorded a video for this question. You can understand the problem better after watching the video.

https://user-images.githubusercontent.com/100342868/172051136-ad6c88a3-4643-43bd-9e83-c43afee3fc9e.mp4

**Comment by Jasenkoo** [comment]
Do you have any errors in the console?

**Comment by harundogan01** [comment]
> Do you have any errors in the console?

No,there are no error messages on the console screen.

**Comment by Jasenkoo** [comment]
@harundogan01 Checked it, it happens because internally dp is working with the entire date object, meaning, that when you provide '2022/06' it is parsed to `June 1, 2022` which is < today. To be able to select, add a day larger than today for the current month. 

I will see to add a separate check when the month picker is used for validation in the next version.

**Comment by harundogan01** [comment]
> @harundogan01 Checked it, it happens because internally dp is working with the entire date object, meaning, that when you provide '2022/06' it is parsed to `June 1, 2022` which is < today. To be able to select, add a day larger than today for the current month.
> 
> I will see to add a separate check when the month picker is used for validation in the next version.

Thank you so much. I will try this solution. I will let you know.

**Comment by harundogan01** [comment]
@Jasenkoo  I finded a bug. The method you mentioned in the date selection does not work. I show the reason with the video below.

https://user-images.githubusercontent.com/100342868/172109730-8a276b59-864a-4db0-8430-d88619b8a8c6.mp4

**In short, the largest day determined in the current system must be the current day or one day greater than it. This seemed like a problem to me. For example, if I set the biggest day as June 20, when we come to June 21, I will not be able to choose June again. What is your comment on the subject?**

**Comment by Jasenkoo** [comment]
There is no workaround for this atm. You can always set the max date as the last day in a month. Since you are using the `monthPicker`, it doesn't really matter if it is the 1st or 30th as a date.

**Comment by harundogan01** [comment]
> There is no workaround for this atm. You can always set the max date as the last day in a month. Since you are using the `monthPicker`, it doesn't really matter if it is the 1st or 30th as a date.

Good news,

I dynamically took the last day of the month and added it to the max parameter. It's working flawlessly now. I wish you a good day.
