### ISSUE TITLE
Week picker: make selected date available, not only the week

### ISSUE THREAD

**Issue by MirasMustimov** [Vuepic/vue-datepicker#600]
Hi, guys! 
Very nice date picker! Thank you!

**Is your feature request related to a problem? Please describe.**
I am using the component in week picker mode. I am able to access selected week via v-model, but I also need the clicked day to be available.

**Describe the solution you'd like**
An emitted event with clicked date would be great!

**Describe alternatives you've considered**
I've considered getting clicked date by adding @click handler to `#day` scoped slot but that is not a good solution since the slot content is not the same click target as the one the your component is listening to.

**Comment by Jasenkoo** [comment]
Will be handled by #597
