### ISSUE TITLE
Year overflow with specific dates

### ISSUE THREAD

**Issue by MrKoopie** [Vuepic/vue-datepicker#601]
**Describe the bug**
When using `:flow="['year', 'month', 'calendar']"`, with 01-01-1981 an overflow occurs.

**To Reproduce**
1. Start https://stackblitz.com/edit/github-xgjvnc?file=app.vue
2. Enter 01/01/1981
3. An overflow occurs, see screenshot.

**Expected behavior**
The years should be contained within the box. It looks like the years is a flex div layered on top of the days of the month. In 01/01/1981, the month has just 5 rows with dates, making the box shorter and the years overflow. However, with 01/01/1983, the month has 6 rows with days, making the years not overflow in the box.

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/3456873/fcbac6e5-1c3e-493c-b8bb-27be1e1f9046)

**Desktop & mobile (please complete the following information):**
 - Browser chrome
 - Library version 7.1.0

**Comment by MrKoopie** [comment]
@Jasenkoo You are fast! I have compared the fix and it resolves the issue:
![image](https://github.com/Vuepic/vue-datepicker/assets/3456873/720900cf-d0e3-4141-8577-2d01330a6169)

When do you expect to release the fix?

**Comment by Jasenkoo** [comment]
@MrKoopie Weekend probably
