### ISSUE TITLE
Add configuration options to highlight current year, month, quarter

### ISSUE THREAD

**Issue by nirpan** [Vuepic/vue-datepicker#607]
**Is your feature request related to a problem? Please describe.**
Currently there is an option to [specify dates to highlight](https://vue3datepicker.com/props/general-configuration/#highlight) as well as a few other options to highlight week days, disabled dates and so on. 

But there does not seem to an option to set highlighted month, quarter, week or year. 

**Describe the solution you'd like**
A config option to set the highlighted month(s), quarter(s), week(s) or year(s) similar to the `:highlight` option. This will then apply the class `dp__cell_highlight dp__date_hover` to set the style to something like this:
![CleanShot 2023-10-12 at 16 37 10@2x](https://github.com/Vuepic/vue-datepicker/assets/3050657/3cd71729-91d2-47e7-b104-af6cabd37d6e)

**Describe alternatives you've considered**
I am thinking of using the `open` event to manually add the class on the relevant cell in the opened calendar for now. 

**Additional context**
There is a way to "highlight" the current month, quarter and year by setting the model value but in this occasion I just need to "soft highlight" it on the calendar as a guide rather than selecting it. I wrote a custom handler to scroll to the calendar rows containing the current year when the mode is a `year-picker`:

```js
setTimeout(() => {
    const currentYear = new Date().getFullYear().toString();

    const container = document.getElementById(`year-picker`);
    const elements = container.querySelectorAll('div.dp__overlay_cell_pad');

    for (const element of elements) {
        if (element.textContent.includes(currentYear)) {
            element.scrollIntoView({
                behavior: "smooth",
                block: "center",
            });
            break;
        }
    }

}, 400);
```

**Comment by Jasenkoo** [comment]
@nirpan Not sure what do you mean, everything looks ok [here](https://stackblitz.com/edit/vuepic-vue-datepicker-umltc5?file=src%2Fcomponents%2FPlayground.vue).

**Comment by nirpan** [comment]
@Jasenkoo Sorry forgot to reply but I figured it out and the highlight prop needed to be as follows for the various modes:

For Year Picker:
```vue
<Datepicker
  v-model="date"
  year-picker
  :highlight="{
    years: [
      new Date().getFullYear(),
      new Date().getFullYear() - 1,
      new Date().getFullYear() + 1,
    ],
  }"
/>
```
For Quarter Picker:
```js
{ quarters: [{ quarter: getQuarter(new Date()), year: new Date().getFullYear() }] }
```
For Month Picker:
```js
{ months: [{ month: new Date().getMonth(), year: new Date().getFullYear() }] }
```
