### ISSUE TITLE
Position issues

### ISSUE THREAD

**Issue by stephanieraymos** [Vuepic/vue-datepicker#609]
**Describe the bug**
The picker works great when the click that triggers the open is near the middle or top of the screen, but if it happens near the bottom, the end of the picker is cut off due to the available screen space not being enough. I read the docs [here](https://vue3datepicker.com/props/positioning/#auto-position) and this is supposed to be true by default, however it's still cutting off the bottom of the picker. 

**Expected behavior**
I would expect that when the picker is too close to the bottom of the viewport, it would move up. I have inline and inline-with-input active in my configuration. Please let me know if I can keep these while also having the picker place itself intelligently when needed. 

**Screenshots**
The screenshot isn't super helpful because I cropped out the grid behind it (proprietary). But the screen / viewport ends where it cuts off.
![image](https://github.com/Vuepic/vue-datepicker/assets/58127737/f27d7fdc-3a7e-4ea9-917b-2a2c69298df8)

**Desktop & mobile (please complete the following information):**
 - Chrome
 - "@vuepic/vue-datepicker": "^3.3.1"

**Comment by Jasenkoo** [comment]
Please update to a newer version, as this is fixed in the meantime. [Playground](https://stackblitz.com/edit/vuepic-vue-datepicker-9nvpwp?file=src%2Fcomponents%2FPlayground.vue)
