### ISSUE TITLE
differentiate event updateMonthYear from button and from picker

### ISSUE THREAD

**Issue by zynth17** [Vuepic/vue-datepicker#61]
**Describe the bug**
right now the event `updateMonthYear` is called whenever we pick a month or a year from the picker or we scrolling or change throught button.
this is kinda bad because when we change the calendar via the button prev and next the event got called twice, first the month and then the year

in my case i called an api everytime user change the month or year so it is really bad to call the api twice. isn't it a better case if the payload for changing the month via button have both year and month at once so it does not called twice? 

**Expected behavior**
when the button prev or next clicked got the month and year at once

**Comment by Jasenkoo** [comment]
Yeah, you are probably right, one event is a better approach.
