### ISSUE TITLE
Remove need to add 0 in text input before in single digit months and days

### ISSUE THREAD

**Issue by cxammar** [Vuepic/vue-datepicker#614]
**Is your feature request related to a problem? Please describe.**
My app users frequently complain that it's tedious to add a 0 before single digit months or days like 04.

**Describe the solution you'd like**
The library could recognize single digit days and months without the need of addinga a 0

**Additional context**
This obviously only occurrs when text input mode is enabled.

**Comment by Jasenkoo** [comment]
You can configure [`format`](https://vue3datepicker.com/props/modes-configuration/#text-input-configuration) for `text-input`. For example, you can configure it to use `M` instead of `MM` for months.
