### ISSUE TITLE
enable time picker & flow

### ISSUE THREAD

**Issue by Ischafak** [Vuepic/vue-datepicker#615]
i am using datepicker with flow and also i dont want users to select time(clock) 

:flow="flow"

const flow = ref(['month', 'year', 'calendar'])

my flow is like this also i have 

:enable-time-picker="false" is false but i still see the bottom button

<img width="290" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/13226879/7ef27373-bf69-46ff-a767-5bd662525219">

btw when i click bottom button 
<img width="294" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/13226879/6d88e509-2fee-49af-a3ea-d7bbd621d6af">
day select opens but when i click any dates v-model does not change normally i have close-on-auto-apply prop

<VueDatePicker 
              :flow="flow"
              v-model="propModel" 
              :enable-time-picker="false" 
              format="dd/MM/yyyy" 
              text-input auto-apply close-on-auto-apply
          
          />

**Comment by Jasenkoo** [comment]
You don't see the time picker, it will remove whole access to it. As a workaround, you can set time picker button height to something like 0 or 1, and you will be able to access it via flow

**Comment by Ischafak** [comment]
You mean should i overrite bottom buttons css

**Comment by Jasenkoo** [comment]
Yes, but remove `:enable-time-picker="false"`

**Comment by Ischafak** [comment]
Ok i will try it thanks. btw when i click buttom button date pick screen opens and normally it should close after click any date i guess but it doesnt.
