### ISSUE TITLE
The DatePicker menu can't work properly with the HTML <Dialog> tag.

### ISSUE THREAD

**Issue by Ltyi** [Vuepic/vue-datepicker#616]
[stackblitz](https://stackblitz.com/edit/vuepic-vue-datepicker-xbz4m7?file=src%2Fcomponents%2FPlayground.vue)

1. `<dialog>` has its own stacking order, z-index dosen't work.
2. I attempted to teleport it to the `<body>`, but it still didn't work.

I'm wondering if there's any way to make the DatePicker work correctly with the `<dialog>` tag?

**Comment by Jasenkoo** [comment]
Currently not, you can use it as shown in dialog 1, make the modal bigger, or use it with scroll. The HTML dialogs are using some special placement which renders another dom(iframe) inside it, making teleport not work properly.

**Comment by ThatzOkay** [comment]
Keep teleport and and give the dialog overflow: visible;. That worked for me and fixed it in your dialog 1
