### ISSUE TITLE
Fully inactive months still can be chosen

### ISSUE THREAD

**Issue by elizavetaKrainova** [Vuepic/vue-datepicker#617]
**Describe the bug**
`month-picker` datepicker doesn't work with `disabled-dates`.

**To Reproduce**
1. Set the props `month-picker` and `disabled-dates`, say, to `(date) => {
                    return date < new Date();
                  }`.
2. Click on the datepicker to choose the month. 
3. See error

**Expected behavior**
All previous months should be disabled. Without `month-picker` prop it works but only for days, not for the months. 

**Screenshots**
<img width="275" alt="Screenshot 2023-10-19 at 16 24 52" src="https://github.com/Vuepic/vue-datepicker/assets/118441503/f1232546-5880-4209-b3dc-23e88c9f9ca4">

<img width="265" alt="Screenshot 2023-10-19 at 16 25 18" src="https://github.com/Vuepic/vue-datepicker/assets/118441503/21659ded-c7d4-4b54-a956-9e5f0c5591df">

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: 7.2.0

**Comment by Jasenkoo** [comment]
It is intended behavior, as `disabled-dates` only work on the calendar. You can use filters to disable months or years if needed.
