### ISSUE TITLE
minDate maxDate not working in iOS Browsers

### ISSUE THREAD

**Issue by asweeneymarathon** [Vuepic/vue-datepicker#619]
**Describe the bug**
When using the minDate and maxDate properties, the minDate and maxDate do not update. 

Edit: This is looking like it only not working on iOS iPhone and iPad. Safari and Chrome on iOS show this. Android Chrome works properly.

I currently have this set up to initialize with empty minDate and maxDate values. I have an action where I grab data from an API and then update the minDate and maxDate. The values update, but the calendar does not. 

**To Reproduce**
1. Set up minDate and maxDate properties as empty strings
2. Update minDate and maxDate values
3. Calendar doesn't update

**Expected behavior**
The calendar should update normally. As I've said, this works everywhere else, except for browsers on iOS.

**Screenshots**
Plugin set-up: 
![image](https://github.com/Vuepic/vue-datepicker/assets/41925838/568a24d7-6047-454d-a266-50ffb2f7b71a)

Vue App Variables Set Up:
![image](https://github.com/Vuepic/vue-datepicker/assets/41925838/ec65ca18-ca36-4b95-9fae-714b9970e10f)

The Vue App Mounted Function (on mounted gets the values for these)
![image](https://github.com/Vuepic/vue-datepicker/assets/41925838/a5b8d618-252f-4868-b1f0-9f063a10311d)

Screen from iOS with debugs showing the value of minDate and MaxDate values and non-updated calendar
![image](https://github.com/Vuepic/vue-datepicker/assets/41925838/4942cfe7-1453-44a8-b15b-c0e0d66dfa04)

**Desktop & mobile (please complete the following information):**
 - iOS Browsers (Chrome and Safari)
 - Library Version 7.2.0

**Comment by Jasenkoo** [comment]
Tested on Safari browser works fine.

[Playground](https://stackblitz.com/edit/vuepic-vue-datepicker-itk4ec?file=src%2Fcomponents%2FPlayground.vue)
