### ISSUE TITLE
Don't allow second date in range to be before the first date

### ISSUE THREAD

**Issue by EmilyFlocc** [Vuepic/vue-datepicker#62]
I would like to disable the ability to select a date in the past once the first date in a range has been selected.

Eg. if I select the 1st June as the first date in my range, I should only be able to select dates above the 2nd June for the second date in my range. Any date in the past before 1st June should now be disabled.

I'm guessing I could update the minDate once the first date in the range is selected, but this feels a little hacky, and would be nice for it to be a built in prop if possible!

**Comment by Jasenkoo** [comment]
I don't see a point in it. If you don't want before dates, that is what `minDate` is for. If you need to adjust the range starting from some date, you can use [`fixedStart` prop](https://vue3datepicker.com/api/props/#fixedstart)
