### ISSUE TITLE
Allowing Appending Icons using slots even if the input is Disabled or Readonly

### ISSUE THREAD

**Issue by huseink** [Vuepic/vue-datepicker#620]
**Is your feature request related to a problem? Please describe.**

When I set the `:disabled` prop to `true`, the clear icon is automatically hidden. However, in my use case for an appointment system, I need to append a 3-dot menu icon to the input even when it's disabled, allowing users to perform actions like rescheduling or removal. The current behavior of hiding the clear icon is limiting my application's functionality.

**Describe the solution you'd like**

I would like the library to allow appending an icon or additional content to the input, even when it's disabled. This would provide the flexibility needed for my use case.

**Describe alternatives you've considered**

I tried having :clearable="true" with :disabled="true" but it doesn't work.

<img width="522" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/39205453/02591b28-507b-4c4f-b8f0-a32460299aa3">

**Comment by Jasenkoo** [comment]
It is kind of an edge-case scenario where you actually don't have a disabled state. However, you just use an external icon appended to the input when the calendar is disabled. That way you can perform any action.
