### ISSUE TITLE
The month names in quarter picker do not get translated 

### ISSUE THREAD

**Issue by mitjarobic** [Vuepic/vue-datepicker#621]
**Describe the bug**
The month names in quarter picker do not get translated when locale prop is set. 

**To Reproduce**

1. Set the the quarter-picker prop and locale prop
2. Click on the date picker
3. The month names in the dropdown are in English. 

**Expected behavior**
The month names in the dropdown should be translated.

**Desktop & mobile (please complete the following information):**
 - Chrome, Brave
 - 7.2.0

**Comment by Jasenkoo** [comment]
> By default, quarter item displays first and last month of the quarter, to change locale of the displayed value, you can use [format-locale](https://vue3datepicker.com/props/localization/#format-locale) prop or custom [quarter](https://vue3datepicker.com/slots/content/#quarter) slot

As stated in the docs https://vue3datepicker.com/props/modes/#quarter-picker
