### ISSUE TITLE
`text-input-options` -> `openMenu = false` is not working

### ISSUE THREAD

**Issue by re-kfa** [Vuepic/vue-datepicker#623]
Hi,

the option `text-input-options` -> `openMenu` is not working as expected. When setting it to `false`, the DatePicker menu still opens when clicking or typing in the input field.

Thank you!

**Comment by Jasenkoo** [comment]
Take a look at this [example](https://stackblitz.com/edit/vuepic-vue-datepicker-ex21vg?file=src%2Fcomponents%2FPlayground.vue).
