### ISSUE TITLE
Vue 3 + webpack: fail to parse module

### ISSUE THREAD

**Issue by christian-benseler-farm** [Vuepic/vue-datepicker#624]
**Describe the bug**
Using the lib in version 7.2.0 in a Vue 3 project with vue-loader 16.8.3, Node 18.18.0, when I import it:

`import VueDatePicker from '@vuepic/vue-datepicker/';`

webpack throws this error:

`
error  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js
Module parse failed: Unexpected token (617:15)
`

<img width="594" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/84783765/678bf6fd-74dd-4857-a826-874b76cee806">

Any suggestion?

**Comment by Jasenkoo** [comment]
Please take a look at: https://github.com/Vuepic/vue-datepicker/issues/473#issuecomment-1691930726

**Comment by nermin99** [comment]
I have tried using Vue `3.2.0` and the latest patch `3.2.47` but I still get the same error
>  ERROR  Failed to compile with 12 errors12:09:57
 error  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js
Module parse failed: Unexpected token (179:168)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }, ml = (e, t) => {
|   if (!e) return 0;
>   const l = /* @__PURE__ */ new Date(), a = new Date(l.toLocaleString("en-US", { timeZone: "UTC" })), n = new Date(l.toLocaleString("en-US", { timeZone: e })), i = (t ?? n).getTimezoneOffset() / 60;
|   return (+a - +n) / (1e3 * 60 * 60) - i;
| };
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--15-3!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/RisikomarkeringList.vue?vue&type=script&lang=ts 6:0-51 15:4-17
