### ISSUE TITLE
Hebrew translation does not work correctly

### ISSUE THREAD

**Issue by inleonid** [Vuepic/vue-datepicker#625]
![image](https://github.com/Vuepic/vue-datepicker/assets/71083023/c7694e4f-5d33-452a-bc34-fc6e71967b72)

it should be like this

Sunday	      א
Monday	      ב 
Tuesday	      ג 
Wednesday   ד
Thursday       ה 
Friday            ו
Saturday	     ש

and My browser version
https://unpkg.com/@vuepic/vue-datepicker@latest
can't change the buttons text
thx

**Comment by Jasenkoo** [comment]
Day names are translated by JavaScript native localization API, using the first 2 letters. You can adjust it by using `day-names` props or `calendar-header` slot

**Comment by inleonid** [comment]
Thanks for the tip, I'll use it. Thx
