### ISSUE TITLE
Teleport error

### ISSUE THREAD

**Issue by ljgaro** [Vuepic/vue-datepicker#631]
**Describe the bug**
As per the documentation and some issues in this repo, teleport should be passed an element id. Example: :teleport="#someElement". I'm encountering the following errors while trying to declare the teleport string:

- **:teleport="#someElement"**  | _**[plugin:vite:vue] Error parsing JavaScript expression: Private names are only allowed in property accesses (`obj.#teleportDiv`) or in `in` expressions (`#teleportDiv in obj`). (1:1)**_ 
- **:teleport="'#someElement'"**  & **teleport="#teleportDiv"** | (passing it as a string with '') teleports as if teleport was set to 'true', opening in the input rather than on the referenced div.
- **:teleport="'teleportDiv'"** | (without the # selector) 'teleportDiv' Failed to locate Teleport target with selector "teleportDiv". Note the target element must exist before the component is mounted - i.e. the target cannot be rendered by the component itself, and ideally should be outside of the entire Vue component tree. 

**To Reproduce**
1. Create 2 divs in inside the template tag (one with the VueDatePicker component) and assign ids to them.
2. Reference the id of in the :teleport prop.

**Expected behavior**
It should open the VueDatePicker in the referenced element.

**Screenshots**
A simple DOM structure explaining the problem. (Note: the behavior of the strings passed to teleport are described above)
![Log](https://github.com/Vuepic/vue-datepicker/assets/140542294/21f88bf0-4fb7-4e07-8cb1-ecdd3b8ea3b8)
![Capture](https://github.com/Vuepic/vue-datepicker/assets/140542294/541d7d83-a6a0-4e17-8c18-7c2783fbf30c)

**Desktop & mobile (please complete the following information):**
 - Browser: All browsers 
 - Library version: 7.2.0
 
 Thanks in advance

**Comment by Jasenkoo** [comment]
1. This is expected, prop is invalid as #id is not an element
2. It is correct behavior, when the menu is open, it is placed in the target div
3. Again, expected behaviour
