### ISSUE TITLE
Props 'max-date' and 'min-date' use system timezone for validation, instead of 'timezone' prop

### ISSUE THREAD

**Issue by nbcare** [Vuepic/vue-datepicker#632]
**Describe the bug**
When using the VueDatepicker component with the `timezone` prop and date-strings in that same timezone, the `max-date` and `min-date` props use the system timezone for validating if days in the calendar are within range.

**To Reproduce**
```
const dateString = ref('2023-11-03T00:00:00.000+01:00')

<VueDatePicker
        v-model="dateString"
        :enable-time-picker="false"
        :ignore-time-validation="true"
        min-date="2023-11-03T00:00:00.000+01:00"
        timezone="Europe/Amsterdam"
/>
```
Timepicker and -validation isn't used. To reproduce either use the full ISO string or only `2023-11-03`. It produces the same result.

1. Set the system timezone with one that is befoe 'Europe/Amsterdam'. So for example that one is +01:00, so use a +02:00 timezone.
2. Given the code example, click the datepicker inputfield to open the calendar.
3. In the open calendar the date of 03-11-2023 is disabled.

When using the `max-date` prop instead, with the same code, the date of 04-11-2023 is still selectable when following the above steps.

**Expected behavior**
With the timezone prop set, the datepicker is expected to work entirely with that timezone and the date of 03-11-2023 should not be disabled when that date is set in `min-date`. With the same date and using `max-date` the date of 04-11-2023 should be disabled.

**Screenshots**
![Example](https://github.com/Vuepic/vue-datepicker/assets/124369927/c13ab8f6-81a1-4a28-8161-049cf157cfaa)

**Desktop & mobile (please complete the following information):**
 - Windows 11
 - Chrome 118.0.5993.118
 - @vuepic/vue-datepicker@7.2.0
 - nuxt@3.6.5
 - vue@3.3.4

**Comment by Jasenkoo** [comment]
It is difficult to handle all possible scenarios when and how it should validate. Unfortunately, it would add a lot of boilerplate code to handle various cases due to the limitations as the browser date object is always in the current zone, therefore validating is done by hours. I recommend you to work with UTC date for setting dates, or convert the validation dates to the given timezone.

**Comment by nbcare** [comment]
Thanks for the reply. Working with UTC is not an option, since the set timezone of the application is relevant. We've opted to shift the timezone of the min/max dates to the system timezone, while keeping the same time. This way the date doesn't change anymore because of the timedifference between the applications' timezone and system timezone.
