### ISSUE TITLE
Extraneous non-props attributes (value) were passed to component

### ISSUE THREAD

**Issue by mehdies7** [Vuepic/vue-datepicker#633]
**Describe the bug**
I am using Vue3 Composition API and am using official example.
Every time I open the Datepicker there few warning appear in the console.
`Extraneous non-props attributes (value) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.`

**To Reproduce**
This is my code
```
<template>
  <VueDatePicker v-model="date"></VueDatePicker>
</template>
  
  <script>
import { ref } from "vue";
import VueDatePicker from "@vuepic/vue-datepicker";
import "@vuepic/vue-datepicker/dist/main.css";

export default {
  components: { VueDatePicker },
  setup() {
    const date = ref();

    return {
      date,
    };
  },
};
</script>
```

**Expected behavior**

**Screenshots**
![Screenshot 2023-11-04 at 7 24 05 PM](https://github.com/Vuepic/vue-datepicker/assets/10376739/4a41e403-a705-4e30-bd44-67871c3c6fde)

**Desktop & mobile (please complete the following information):**
 - Browser Chrome
 - Library version 6.1.0

**Comment by mehdies7** [comment]
I found the issue.
It was on my side

**Comment by Hernando-sys** [comment]
hi, how did you solved it? I'm having the same problem

**Comment by Anastasiia118** [comment]
™ Hi, what updating did you do ? I'm migrating to Vue 3 (using compatConfing still) and this warning appears every time I use date picker.

**Comment by AlexDegterov** [comment]
@Hernando-sys Can you share your experience on this issue? The same problem as @Anastasiia118 mentioned.
Thanks!

**Comment by NicoHof** [comment]
@mehdies7 I am also experiencing this warning in vue compat mode.

What did you do to solve it. You said it was "on your side"?
