### ISSUE TITLE
Subdependency issue when using with Nuxt 3.8.0

### ISSUE THREAD

**Issue by AngeloSchulerPiletti** [Vuepic/vue-datepicker#634]
**Describe the bug**
I am facing the following exceptions when using Vue Datepicker with Nuxt 3.8.0:

`[vite-node] [ERR_LOAD_URL] date-fns/parse/index
`

`Cannot find module '../_lib/defaultLocale/index.js' Require stack: - S:\Zytro\customer-dashboard\frontend\date-fns\parse\index
`

The first one happens when I try to run the project with Vue Datepicker. The second one occurred once I installed the `date-fns@2.30.0` on my project (as dev and not dev dependency).

My Vite version is 4.4.9.

I am using SSR.

**To Reproduce**
1. Start a Nuxt 3.8.0 project
3. Install Vue Datepicker
4. `pnpm dev`
5. See error

**Expected behavior**
I was expecting it to not throw an exception on Vue Datepicker dependency.

**Desktop & mobile (please complete the following information):**
 - Windows 11, Brave
 - 7.2.1

I really appreciate using Vue Datepicker. I am also not sure if that is a problem related to Vue Datepicker, or if should I configure something else on Vite. 

Thank you for your time.

**Comment by AngeloSchulerPiletti** [comment]
I workaround it by downgrading Vue Datepicker to 7.1.0

**Comment by djixadin** [comment]
7.2.0 is the latest working version.. its the 7.2.1 changes that brought this bug
