### ISSUE TITLE
date-fns crashes after the new release

### ISSUE THREAD

**Issue by CavalcanteLeo** [Vuepic/vue-datepicker#635]
<img width="1512" alt="Screenshot 2023-11-06 at 10 28 02 am" src="https://github.com/Vuepic/vue-datepicker/assets/1735944/f3e0d68f-fdc2-4250-b53d-f94fc1632f4c">

Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/date-fns@2.30.0/node_modules/date-fns/_lib/getTimezoneOffsetInMilliseconds/index.js?v=eab50020' does not provide an export named 'default' (at index.js?v=eab50020:2:8)

**Comment by Jasenkoo** [comment]
Same as #634. Will be handled.

**Comment by CavalcanteLeo** [comment]
yep, it was fixed, thanks
