### ISSUE TITLE
id on day cells are not using the locale of the calendar

### ISSUE THREAD

**Issue by Grutula** [Vuepic/vue-datepicker#639]
**Describe the bug**
Following #630, I'm trying to use the new `id` attribute on day cells, but after few tests, I figure that the day shown and its id could be different depending on the locale

Here I have a calendar with a computer using a Central European Standard Time timezone, and the ID of the current day seems to be the ISO day

HTML generated:

```
<div id="2023-12-05" role="gridcell" class="dp__calendar_item" aria-label="" tabindex="0">
    <div class="dp__cell_inner dp__pointer">
        <!---->6<!----><!---->
    </div>
</div>
``` 

**To Reproduce**
1. Go to the [playground](https://stackblitz.com/edit/vuepic-vue-datepicker-chgko5?file=src%2Fcomponents%2FPlayground.vue) with a device located on a not +X offset
2. Check the generated html

**Expected behavior**
The ID represents a day, and must be consistent with the day displayed by the calendar

**Screenshots**

![Screenshot 2023-11-06 at 17 07 16](https://github.com/Vuepic/vue-datepicker/assets/4665028/0f34f57b-4873-427b-aaa7-dbdb7c1a50de)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: 7.2.1

**Comment by Jasenkoo** [comment]
This won't be altered, it follows standard ISO format without time, YYYY-mm-dd
