### ISSUE TITLE
The css style disorder

### ISSUE THREAD

**Issue by Bruce-1988** [Vuepic/vue-datepicker#645]
**Describe the bug**
I lost the CSS style, it looks chaotic.
![image](https://github.com/Vuepic/vue-datepicker/assets/52615429/27acc702-da7b-4eba-acb0-fe7e1231279a)

**To Reproduce**
I used it in the `.vue` file and `script setup` like:
```js
<script setup>
import VueDatePicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css'
</script>
```

**Comment by marcuspoehls** [comment]
@Bruce-1988 how did you solve this issue?
