### ISSUE TITLE
How to have an active state/ highlight for preset buttons?

### ISSUE THREAD

**Issue by whimsicaldreamer** [Vuepic/vue-datepicker#646]
**Describe the bug**
Is there a way in which we can highlight which preset is currently active? Presently, we can see a hover effect on the preset buttons, but when we click on one of it, let's say `This Week`, the range is selected on the calendar but no highlighting of the active button.

**To Reproduce**
Go to https://vue3datepicker.com/props/modes-configuration/#preset-dates

**Expected behavior**
Highlight the preset button that is active.

**Desktop & mobile (please complete the following information):**
 - Browser [chrome, firefox]
 - Library version [7.2.2]

**Comment by Jasenkoo** [comment]
These are just buttons to easily preset a date, not an active state.

**Comment by whimsicaldreamer** [comment]
@Jasenkoo I do understand that these are buttons to easily preset a date, but it would be nice to highlight the preset that is currently active.

Currently, to get the below active state/ highlight on the button, I had to use a work around which involved watching the date value and modifying the preset array on the fly.
<img src="https://github.com/Vuepic/vue-datepicker/assets/8104493/c8542ee8-e5d2-43e5-a119-a07ced296ac8" height="300" />



How I did it is as below:

```
const date = ref()
const presetDates = ref([
  {
    label: 'Today',
    value: [dayjs().startOf('day'), dayjs().endOf('day')]
  },
  {
    label: 'This Week',
    value: [dayjs().startOf('isoWeek'), dayjs().endOf('isoWeek')]
  },
  {
    label: 'This month',
    value: [dayjs().startOf('month'), dayjs().endOf('month')]
  },
  {
    label: 'This year',
    value: [dayjs().startOf('year'), dayjs().endOf('year')]
  }
])

watch(date, () => {
  const presetActiveStyle = { backgroundColor: '#1976d2', color: '#f8f5f5' }

  for (const preset of presetDates.value) {
    if (preset.value[0].format('YYYY-MM-DD HH:mm') === date?.value[0] && preset.value[1].format('YYYY-MM-DD HH:mm') === date?.value[1]) {
      preset.style = presetActiveStyle
    } else {
      delete preset.style
    }
  }
})
```
