### ISSUE TITLE
Uncaught TypeError 

### ISSUE THREAD

**Issue by atruhoo** [Vuepic/vue-datepicker#65]
![image](https://user-images.githubusercontent.com/107148672/172703423-16ee1776-f6d7-49db-b032-e523351ec98a.png)

Getting error message above when trying to run app after registering DatePicker Globally. I also noticed I am getting these warnings seen below. Any thoughts on what I might need to do? Looking for a good Vue 3 date picker and yours looked like it fit the bill but if can't get it to load I will need to punt and look elsewhere.

 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js
"export 'createElementBlock' (imported as 'S') was not found in 'vue'
 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js
"export 'createElementVNode' (imported as 'U') was not found in 'vue'
 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js
"export 'getCurrentScope' (imported as 'ga') was not found in 'vue'
 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js
"export 'guardReactiveProps' (imported as 'at') was not found in 'vue'
 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js
"export 'normalizeClass' (imported as 'pe') was not found in 'vue'
 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js
"export 'normalizeProps' (imported as 'je') was not found in 'vue'
 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js
 [webpack.Progress] 100% 
"export 'normalizeStyle' (imported as 'wt') was not found in 'vue'
 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js
"export 'onScopeDispose' (imported as 'wa') was not found in 'vue'
 warning  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.es.js

**Comment by Jasenkoo** [comment]
What version of vue you have installed? Try to reinstall node_modules

**Comment by atruhoo** [comment]
Currently on vue : 3.0.11. Also when you say try to reinstall node_modules are you saying to uninstall and then reinstall your date picker through npm or delete all in node_modules folder. Assume the first option but I have been wrong before LOL.

**Comment by Jasenkoo** [comment]
I meant fully, but no need. You need to have Vue >= 3.2.x. All versions before 3.2 were still in a beta phase  and there are some breaking changes internally. 

Tdlr. Libraries built with vue > 3.2 are not compatible with vue < 3.2

**Comment by atruhoo** [comment]
Thanks I must have missed that as a requirement to use this.
