### ISSUE TITLE
start-date props does not work with year-picker mode

### ISSUE THREAD

**Issue by theo-chmbn** [Vuepic/vue-datepicker#650]
**Describe the bug**
When the calendar is in year-picker mode, that start-date prop is ignored, and the year picker always starts at 1900 if the v-model is empty (even with the focus-start-date prop).

When is full date picker mode, there is no issue.

**To Reproduce**
1. Set the calendar to year-picker mode
2. Let the v-model empty
3. Add the start-date and focus-start-date props
4. The year picker starts at 1900 instead of your chosen start-date

See this playground example : https://stackblitz.com/edit/vuepic-vue-datepicker-hh7dah?file=src%2Fcomponents%2FPlayground.vue

**Expected behavior**
In year-picker mode, when the start-date prop is set, and the v-model is empty, the calendar should focus on the start-date year.

**Desktop & mobile (please complete the following information):**
The issue is reproduced on all browsers, and is present on the 7.2.2 but was also present in earlier v6.x.x

**Comment by michalgrunwald** [comment]
@Jasenkoo Same problem exists in month-picker mode. focus-start-date prop works excelent on date-picker mode but its ignored for all others

**Comment by theo-chmbn** [comment]
@Jasenkoo working great now, thanks!

**Comment by michalgrunwald** [comment]
@Jasenkoo it works! Thanks!

**Comment by rudachenkoev** [comment]
@Jasenkoo as far as I can tell, the issue is occurring again in the 12.x.x versions [[playground example](https://stackblitz.com/edit/vuepic-vue-datepicker-m257ycum?file=src%2Fcomponents%2FPlayground.vue)]
