### ISSUE TITLE
Unable to open the DatePicker menu when using the component inside a web component

### ISSUE THREAD

**Issue by LouisAndrew** [Vuepic/vue-datepicker#656]
**Describe the bug**
When using the component in a vue project, built as a web component, the DatePicker menu cannot be opened and the following error is thrown `Uncaught TypeError: Cannot read properties of null (reading '_vnode')`

**To Reproduce**
Reproduction link to a sandbox (loading the component in a vue custom element)
https://codesandbox.io/p/devbox/naughty-moser-j6shmk
- try to click on the input to open the menu and take a look into the console output

**Expected behavior**
DatePicker component should be working when used in a web component

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/61015467/459dcfd4-fb88-45ed-b0cf-36396ec3622a)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: 7.2.2

**Comment by ihardyslide** [comment]
Any plan when this fix will get released approximately? I have the exact same issue.
Thanks & BR
