### ISSUE TITLE
Timezone is Always Local Time Instead of emit-timezone

### ISSUE THREAD

**Issue by waqleh** [Vuepic/vue-datepicker#658]
I am trying to convert datetime to UTC, however the timezone is always showing as local timezone, in display and emit.

```
<template>
    <Datepicker
        :modelValue="value"
        format="dd/MM/yyyy HH:mm z"
        emit-timezone="UTC"
        @update:model-timezone-value="handleDate"
    />
</template>
...
...
...
handleDate($event) {
    console.debug($event);
    $event = $event.toISOString();
    console.debug($event);
    this.$emit('input', $event);
},
```

**To Reproduce**
1. Select date
2. Select time
3. Click "Select"
4. See timezone in field is GMT+1 (my local time)

**Expected behavior**
Since i have set the emit timezone as UTC `emit-timezone="UTC"` I expect the timezone output would be in UTC not GMT+1 after the time was subtracted by one

**Screenshots**
field and console after step 3
![image](https://github.com/Vuepic/vue-datepicker/assets/2108837/1c589fe7-129c-4f7d-99bd-771496e6f666)
using `toISOString` subtracts another hour which also proves that the timezone is not UTC
![image](https://github.com/Vuepic/vue-datepicker/assets/2108837/7f4659c7-ec4a-4757-936d-24835bdbabce)

**Desktop & mobile (please complete the following information):**
 - Browser firefox 120.0 (64-bit)
 - Library version 7.2.2

**Comment by Jasenkoo** [comment]
It is working as expected, you can't change the timezone in the default `Date` object, however, the time value is subtracted
