### ISSUE TITLE
Text-input not working properly with time-picker-inline option

### ISSUE THREAD

**Issue by kubedo8** [Vuepic/vue-datepicker#659]
**Describe the bug**
When using `text-input` option together with `time-picker-inline` it is not possible to write date to input field. First click opens the picker but input immediately loses the focus. The second click closes the picker and cursor is now present in the input but when I try to write something, it opens the picker and focus is lost again.

```
<template>
    <VueDatePicker v-model="date" placeholder="Start Typing ..." text-input time-picker-inline />
</template>

<script setup>
import { ref } from 'vue';

const date = ref();
</script>
```

**To Reproduce**
1. Use example above
2. Click on the input
3. Try to write something

**Expected behavior**
It should work exactly same way like it works without `time-picker-inline` option.

**Screenshots**
I think this bug is pretty straightforward.

**Desktop & mobile:**
 - Chrome version 119.0.6045.159 
 - Library version 7.2.2
 - MacOS Sonoma 14.1.1

**Comment by Jasenkoo** [comment]
Not sure what you mean, the text input works as intended.

https://github.com/Vuepic/vue-datepicker/assets/23171105/c17c89ea-26d6-4d1f-8494-a20b84db7546
