### ISSUE TITLE
How to show datepicker in UTC?

### ISSUE THREAD

**Issue by catrius** [Vuepic/vue-datepicker#66]
Even If I pass in a UTC time, datepicker still shows it in my local time.
There is a prop called`utc`, but it only changes the output format to UTC.

**Comment by jamesh-purr** [comment]
Hey @Jasenkoo 

I could be missing something here however I was going to use your package but came across the same issue here. The picker should be able to ignore locale time. I would expect setting utc value that its not just a formatter but to have time sent in utc. To me it makes no sense to not have this ability. 

Time should be saved in utc and then have a timezone applied to it. 

I ended up using this - https://vcalendar.io/datepicker.html 

Just my two cents that not being able to send time in a utc format it pretty crazy.

**Comment by Jasenkoo** [comment]
@jamesh-purr You can use UTC, just set [utc prop](https://vue3datepicker.com/api/props/#utc).
