### ISSUE TITLE
Incorrect behavior of the "openMenu" method

### ISSUE THREAD

**Issue by sergeev-vn** [Vuepic/vue-datepicker#662]
**Describe the bug**
When the "openMenu" method is run, the calendar is first hidden, even if it was already open.

**To Reproduce**
https://stackblitz.com/edit/vuepic-vue-datepicker-jjnuhw?file=src%2Fcomponents%2FPlayground.vue

**Expected behavior**
When the calendar is open, the "openMenu" method doesn't initially hide the calendar.

**Video**

https://github.com/Vuepic/vue-datepicker/assets/52858217/92f341d5-7f38-40a0-9b35-977583f87a76

**Comment by Jasenkoo** [comment]
This is expected behavior as you are doing a  click-away.

**Comment by sergeev-vn** [comment]
@Jasenkoo So at the moment it is impossible to make a condition for toggling the calendar? I want to make a handler for clicking an icon.
