### ISSUE TITLE
Input element does not show the datetime in mobile but shows on desktop/laptop

### ISSUE THREAD

**Issue by mthuggett** [Vuepic/vue-datepicker#663]
I'm not sure this is a bug, but didn't know where else to post my inquiry, in the hopes that someone else might have experienced this and provide me some ponters.

The component renders just fine on desktop/laptop browsers.  However, on mobile devices (iphone/ipad) the datetime is NOT showing up in the input element.  I've test in both chrome and safari.  I can't figure out why this is happening.  No errors in the devtools log (chrome://inspect).

Has anyone else had this issue or similar?  Any pointers?

I was expecting the date and time to appear on mobile same as it does on desktop/laptop.

Thanks,
Mike

**Comment by mthuggett** [comment]
Closing.  Narrowed the issue to my implementation.

**Comment by gluebi** [comment]
Could you tell please what the problem with your implementation was? I am having the same issue currently.
