### ISSUE TITLE
It is not possible to select more than 1 week

### ISSUE THREAD

**Issue by moistrenko** [Vuepic/vue-datepicker#665]
Hello. There may already be a solution, but I haven't found it.

The essence of the problem is that with the range and week-range parameters, the calendar allows you to select only one week, but I need to select a range by week

This is the choice of weeks I need to implement
<img width="671" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/61918010/20b71eef-05ef-40e7-b23a-8eac13bcbd97">

but when I try to implement it in the sandbox, I feel like the calendar is breaking
<img width="1025" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/61918010/98f61704-ae26-4c45-b7d4-2198658eda31">

without range parameter
<img width="1085" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/61918010/2e78c3cc-e0e2-43f6-ae4a-bb5dfdfba258">

But if we select a month or a year, then we can select a range by month or year
<img width="1040" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/61918010/a7591ef3-f9c6-4c9d-814e-b8c79c0add42">

I will be very grateful if you suggest a solution to the problem.
Thank you.

**Comment by Jasenkoo** [comment]
The `range` in combination with `week-picker` is not supported, as a week is already a type of range. It would introduce a lot of possible conflicts by adding it.
