### ISSUE TITLE
Toggle calendar

### ISSUE THREAD

**Issue by sergeev-vn** [Vuepic/vue-datepicker#666]
How can I open and close the calendar with one button? 

There is a new method "toggleMenu", but it only opens the calendar if it was closed. If you use the "openMenu" and "closeMenu" methods, the situation is the same.

https://stackblitz.com/edit/vuepic-vue-datepicker-tmdwvz?file=src%2Fcomponents%2FPlayground.vue

**Comment by Jasenkoo** [comment]
As answered on #662, you are doing a click away on the menu. You can override a default one like specified [here](https://vue3datepicker.com/props/general-configuration/)
