### ISSUE TITLE
AR Locale getDaysNames

### ISSUE THREAD

**Issue by HabardiT** [Vuepic/vue-datepicker#67]
**Is your feature request related to a problem? Please describe.**
For 'ar' locale, the days' names aren't displayed properly, making it hard to distinguish between the days, please find the below screenshot.
![ar datepicker](https://i.imgur.com/gn8gnxk.png)

**Describe the solution you'd like**
getDayNames _utils/util.ts_  generates the day names based on locale and week start. 
it also takes only the first 2 characters from each day's name.
my suggestion is to have this method as a default one, and to allow passing a different getDaysNames method to override it if needed.

**Comment by Jasenkoo** [comment]
Will be added, also, you can override the default labels with a slot [`calendar-header`](https://vue3datepicker.com/api/slots/#calendar-header)
