### ISSUE TITLE
Open Menu from dp-input Slot

### ISSUE THREAD

**Issue by nruffing** [Vuepic/vue-datepicker#673]
**Is your feature request related to a problem? Please describe.**

Open the date picker menu from within the `dp-input` slot. We would like to trigger the date picker to open when clicking an icon within the input in the `dp-input` slot.

**Describe the solution you'd like**

Could a callback be passed as a prop to the `d-input` slot to open the date picker menu?

**Describe alternatives you've considered**

We currently have to add a `ref` to the date picker component to call `openMenu` on but that seems like an antipattern.

**Comment by Jasenkoo** [comment]
@nruffing I am don't know what your wrapper looks like, but the dp-input should open the menu by default. Make sure you don't have any `@click.prevent` actions.

**Comment by nruffing** [comment]
We have the `text-input` prop set to `{ openMenu: false }` on the `Datepicker` component because we don't want any click or focus within the input to open the date picker menu. We have an icon/button in the input and that is the only element that if clicked should open the date picker menu. 

This is how the [html5 native date input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) works.  Another example that works this way is the [MUI date picker](https://mui.com/x/react-date-pickers/date-picker/#basic-usage).

To achieve this common pattern it does seem useful to be able to open the date picker menu through a callback on the `dp-input` slot.

**Comment by Jasenkoo** [comment]
Sure, will add it in the next release

**Comment by nruffing** [comment]
Thank you for taking care of that so quick and for all your work on this date picker. It is a much needed component. I am trying to do something similar with a [data grid](https://datagridvue.com) which I think is another missing missing piece.
