### ISSUE TITLE
Year range picker: end year is not highlighted

### ISSUE THREAD

**Issue by Coelmount** [Vuepic/vue-datepicker#677]
**Describe the bug**
When using the month picker in range mode, the end month is not correctly highlighted when you open the picker again. 

**To Reproduce**
1. setup up vue-datepicker in month mode and enable range selection
2. select a range of months
3. close the picker
4. open again
5. now the first month is highlighted while all subsequent months are highlighted as "in-between-months". 

**Expected behavior**
The first and last month are highlighted using the --dp-primary-color. The text is using the variable --dp-primary-text-color

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/26696798/89ca9db7-dc8b-491c-9b34-5fab53f412d2)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: 7.4.0

**Comment by Coelmount** [comment]
Side note: using tailwind

**Comment by MuhammadFarrelFaiz** [comment]
@Coelmount hey i saw you used year picker combined with range and you can pick the middle of the list of year without issues. i used year picker combined with range too but got issued when i scroll and pick the year in the middle of the list, the list teleport to the beginning. did you got the same issues?
