### ISSUE TITLE
Select date without button

### ISSUE THREAD

**Issue by mdeprezzo** [Vuepic/vue-datepicker#679]
Is it possible, somehow, to leave the date selection to clicking on the calendar instead of using the buttons below?

**Comment by JNietou** [comment]
I'm just wondering the same. I think is possible by using refs, but it would be easier if we had a prop to configure it.

**Comment by Jasenkoo** [comment]
It is possible, take a look at [`auto-apply`](https://vue3datepicker.com/props/general-configuration/#auto-apply) prop

**Comment by JNietou** [comment]
> It is possible, take a look at [`auto-apply`](https://vue3datepicker.com/props/general-configuration/#auto-apply) prop

wonderful, it already existed! Thank you! <3
