### ISSUE TITLE
Bug in translation - Locale not working

### ISSUE THREAD

**Issue by domium42** [Vuepic/vue-datepicker#68]
Hello, that cool but ... i've a bug.

what about this ? 

"I discovered that locale does not seem to affect the format output, and added a test for it.
The root cause is not passing the component's locale down to the date-fns format function. Would you accept a PR if I modified formatDate to also accept a locale? Several components would also have to know about the locale as a result.
This PR is just the test.
Reviewed by misha at 2021-12-14 05:09"

When i put this on my component locale=".." that not work for 'it' or 'eu' etc... that a bug.
I try to use scope #header but i can't acces to month traduction. I can translate the days but not the months.

Thank for help

**Comment by Jasenkoo** [comment]
> Would you accept a PR if I modified formatDate to also accept a locale

Sure

**Comment by Jasenkoo** [comment]
Closing, the locale is indeed passed, if you need to use language-specific keys, not just numbers, you would need to import locale package from the `date-fns` locally and provide it [as described here](https://vue3datepicker.com/api/props/#formatlocale)
