### ISSUE TITLE
Question: what is the best way to hide disabled years/months/days

### ISSUE THREAD

**Issue by Coelmount** [Vuepic/vue-datepicker#682]
By default the datepicker shows dates starting in 1900 and they go up to 2100 or so.
I use the datepicker for a portal that allows querying of financial data from a backend. Seen the fact I don't have data from 1900, i would like to hide years and months for which i have no data. Now I can only disable them.

Is there a way I can do this? I had a look to filters but it looks these only disable them.

**Comment by nirajfu3e** [comment]
I have had [a similar](https://github.com/Vuepic/vue-datepicker/issues/676) but not same question about styling disabled future and past dates the same way so I think a solution for these two issues would be the same!

**Comment by nirpan** [comment]
I have had [a similar](https://github.com/Vuepic/vue-datepicker/issues/676) but not same question about styling disabled future and past dates the same way so I think a solution for these two issues would be the same!

**Comment by Jasenkoo** [comment]
The styling part will be handled on #676, however, in your specific case, I would suggest taking a look at [`year-range`](https://vue3datepicker.com/props/calendar-configuration/#year-range) prop
