### ISSUE TITLE
Error when selecting multiple dates in month calendar

### ISSUE THREAD

**Issue by seperez-ncl** [Vuepic/vue-datepicker#687]
When I am in a calendar of months and I try to select the last month of one year and the first month of the next, I get an error.
 Note: This is happening to me in the latest version 7.4.0, with version 6.1.0 this does not happen.

https://github.com/Vuepic/vue-datepicker/assets/8641728/2df1db3e-23d0-44bc-96e3-1b6fef06e550

![Screenshot 2023-12-19 at 4 28 54 PM](https://github.com/Vuepic/vue-datepicker/assets/8641728/6842be16-b955-4574-a8b4-fd01817ea4d7)

**Comment by regoremor** [comment]
https://github.com/Vuepic/vue-datepicker/assets/9708927/95ed950c-2b50-4543-818c-092a72d8f917
