### ISSUE TITLE
Update date-fns dependency to 3.0 version

### ISSUE THREAD

**Issue by basil-gor** [Vuepic/vue-datepicker#688]
Hello!
A new version of date-fns just [released](https://github.com/date-fns/date-fns/releases/tag/v3.0.0). Are you going to update this dependency?

Thank you for your job!

**Comment by Jasenkoo** [comment]
This is currently on hold, as `date-fns-tz` is not compatible yet with `date-fns@3`. There is an open issue https://github.com/marnusw/date-fns-tz/issues/260

**Comment by aubcel** [comment]
Is there a reason to keep `date-fns-tz` as a library?
Or could the functionality be replaced by the new available https://github.com/date-fns/utc ?
Didn't look deep into it, so might be totally on the wrong track 🙈
