### ISSUE TITLE
Daterange preview does not use locale

### ISSUE THREAD

**Issue by bregjevandongen** [Vuepic/vue-datepicker#689]
**Describe the bug**
I have my locale set to "nl" and the format to "dd-MM-yyyy - dd-MM-yyyy", but still the preview shows as "12/20/2023 - "

**To Reproduce**
Set the locale and format as above and select a date in the datepicker. In the bottom section next to the select button the preview date is in the wrong format.

<VueDatePicker v-on:click="col.datepicker.value.openMenu()" v-model="col.filter" :placeholder="col.placeholder" ref="col.datepicker" input-class-name="datepickerfilter" range :enable-time-picker="false" :format="dd-MM-yyyy - dd-MM-yyyy" :preview-format="dd-MM-yyyy" @update:model-value="applyFilters()" locale="nl" select-text="Kies" cancel-text="Annuleren"></VueDatePicker>

**Expected behavior**
To have the preview use the format or the previewformat

**Comment by Jasenkoo** [comment]
You need to use [`format-locale`](https://vue3datepicker.com/props/localization/#format-locale) prop
