### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by PyroxFyre** [Vuepic/vue-datepicker#69]
**Describe the bug**

When I'm trying to install the module with npm, I got this error :
![Screenshot_20220615_162142](https://user-images.githubusercontent.com/58972345/173851508-61a2e3f5-9bcb-41bf-85c1-16f04eb8704d.png)
I succeed installing it by adding `--legacy-peer-deps`

And I don't know if this is linked to this potentially broken dependency, but after adding the component as said in the doc, I got this error on console and the component don't appear :
![image](https://user-images.githubusercontent.com/58972345/173852042-697dd1af-d27e-4d9f-9afa-51051c546363.png)

**Desktop & mobile (please complete the following information):**

OS : Debian GNU/Linux 10
KDE Plasma version : 5.14.5
Qt version : 5.11.3
KDE Frameworks version : 5.54.0
Kernell version : 4.19.0-20-amd64
OS Type : 64-bit
Processors : 4 × Intel® Core™ i3-2100 CPU @ 3.10GHz
Memory : 7,8 Gio 

Hope you know what's the problem and can help me

**Comment by Jasenkoo** [comment]
Looks like you are using `Vue 2`, however, this component is `Vue 3` only

**Comment by PyroxFyre** [comment]
Yes, nvm, sorry. I didn't understand it first, then I took a break and read it again, then... I understood how dumb am I ^^
