### ISSUE TITLE
Display is slow when entering year

### ISSUE THREAD

**Issue by DoanKhiem** [Vuepic/vue-datepicker#694]
**Describe the bug**
I'm having trouble displaying the year slowly when using the text input feature (it works much slower if i use a lot of props)

**To Reproduce**
1. Click the start year or end year in the input
2. Black out the year and enter the new year value from the keyboard
3. See error: The screen displays the last 2 numbers of the year for quite a while (tab console: [Violation] 'input' handler took 6947ms)

**Expected behavior**
Display normally

**Link demo**
https://stackblitz.com/edit/vuepic-vue-datepicker-e6slck?file=src%2Fcomponents%2FPlayground.vue

![image](https://github.com/Vuepic/vue-datepicker/assets/73279214/81eff05b-eb20-44ef-90c4-3269dd86d5e9)

**Comment by Jasenkoo** [comment]
Will see what can be done here, because when you remove the 2 numbers, it assumes the year is 20 and the range check becomes quite big.

**Comment by DoanKhiem** [comment]
Have you resolved this issue and been able to close this issue?

**Comment by DoanKhiem** [comment]
I still have that problem when using min date, max date, max range
Link demo: https://stackblitz.com/~/edit/vuepic-vue-datepicker-ckuygw?file=src%2Fcomponents%2FPlayground.vue

**Comment by DoanKhiem** [comment]
Thank you for resolving this issue.
Can you resolve this issue at the end-year?
![image](https://github.com/Vuepic/vue-datepicker/assets/73279214/3219b169-eb07-4fd0-90d9-086ba3a0894c)
