### ISSUE TITLE
setting min-date to a date in the previous year breaks month navigation

### ISSUE THREAD

**Issue by JamieMcDonnell** [Vuepic/vue-datepicker#697]
**Describe the bug**
Configuring the date picker to display only the previous 30 days active dates fails to navigate properly to the previous month when it is last year. It appears that navigating to the previous month actually navigates to December 2024, which is out of range and therefore displays all dates as disabled.

**To Reproduce**
Steps to reproduce the behaviour:
1/ Load the date picker at the following stackblitz:
https://stackblitz.com/edit/vuepic-vue-datepicker-uxce1a?file=src%2Fcomponents%2FPlayground.vue

2/ Navigate to the previous month (should be December 2023

**Expected behavior**
I should see 29 active days in December 2023 which are selectable and which should emit a 'change' event

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Chrome (latest version
 - 7.4.0 (latest)

<img width="520" alt="Screenshot 2024-01-02 at 14 11 10" src="https://github.com/Vuepic/vue-datepicker/assets/647732/48efe5e8-a038-458e-a793-3bbf3b00aee3">
<img width="531" alt="Screenshot 2024-01-02 at 14 11 04" src="https://github.com/Vuepic/vue-datepicker/assets/647732/9c30699e-4ad4-4443-8554-c681be537d04">

**Comment by twanbaten** [comment]
As stated in the [documentation for `disable-year-select` ](https://vue3datepicker.com/props/general-configuration/#disable-year-select), navigation will cycle through the current or provided year. Indeed, it goes from januari 2024 to december 2024 on navigation to the previous month. Dates in december 2024 are out of range, as noted.

**Comment by Jasenkoo** [comment]
As stated by the @twanbaten , `disable-year-select` will loop the current year, in your case, yesterday was from previous year, therefore, it is ignored
