### ISSUE TITLE
Failed to load main.css.map from vue-router subdirectory

### ISSUE THREAD

**Issue by kevinstory** [Vuepic/vue-datepicker#7]
The main.css.map file is not able to be loaded when the component is being called from within a subdirectory using vue-router. If I use this component in a top level/root directory within vue-router, it works as expected and loaded the main.css.map file. If there a way to hard code link the location of these files since I think it's appending the sub-directory into the URL path.

**Error:**

> DevTools failed to load source map: Could not load content for http://localhost:3000/customer/main.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

- Notice how it added "customer" into the location for the main.css.map url?

The pop-up works as expected but all the CSS classes are not applied and it doesn't look like it should.
![no_css](https://user-images.githubusercontent.com/904587/160289234-61b68e36-db22-4f66-b563-5a6db27ceddf.jpg)

**Comment by Jasenkoo** [comment]
@kevinstory How do you import the CSS file?

**Comment by kevinstory** [comment]
ahh, disregard, it was my error!

**Comment by laurensatvloto** [comment]
I have the same error, how did you resolve this?
