### ISSUE TITLE
Default year in solo range calendar is broken (shows 0 instead of current year)

### ISSUE THREAD

**Issue by vad1ym** [Vuepic/vue-datepicker#702]
Default year in solo range calendar is broken. We can also see it in documentation

<img width="1128" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/26406732/ff3eee5b-d925-4c53-8b20-b4e6cf62e1df">

**Comment by mofman** [comment]
Yes this is semi fixed in 7.4.1 however after the user initially picks 2 dates then closes the date picker and then goes back in it, it shows the second as 'January 0'

**Comment by aminebenaddi-centris** [comment]
> As reported in #681, however, it looks like the issue is still valid

I have the same issue. I just wanna know when the next version will be released ? Thank you!
