### ISSUE TITLE
why it open their 

### ISSUE THREAD

**Issue by neonarc4** [Vuepic/vue-datepicker#704]
![image](https://github.com/Vuepic/vue-datepicker/assets/140290288/52ddc061-0e09-471b-ab25-45d37bc7eac5)

```
   <VueDatePicker class="flex justify-end -mt-10" v-model="month" month-picker />

 wrapping over doesnt affect any state either seems like override is not alowed

**Comment by Jasenkoo** [comment]
This should not happen; I suggest removing classes added on the picker itself, and adding a wrapping div if needed.

**Comment by neonarc4** [comment]
i tried many time it doesnt work i fond element style when toggle create left 0
