### ISSUE TITLE
events that triggered when menu is open

### ISSUE THREAD

**Issue by yeseul4072** [Vuepic/vue-datepicker#708]
I want to make a feature where selecting a date is triggered by a double-click on menu.
To achieve this, I need a way to detect events such as clicking on a date on menu. Is there any feature available for this now?"

**Comment by Jasenkoo** [comment]
Take a look at [events] page https://vue3datepicker.com/methods-and-events/events/

**Comment by yeseul4072** [comment]
The documentation states that @update-month-year should work for both year and year-month types, but it does not work for the year-picker type.
