### ISSUE TITLE
Focus range to the end date

### ISSUE THREAD

**Issue by AVaccar** [Vuepic/vue-datepicker#709]
**Is your feature request related to a problem? Please describe.**
A client requested to have the calendar be opened on the end date of a range instead of the start date.  
This was requested as a period that spans across years and starts on december, could lead the users to select a new range in the old year instead of the current year.  
It's quite easy to make this mistake (I did it a few times as well) becase in a mobile view the text is not very big.

**Describe the solution you'd like**
Add a option to the calendar that by default keeps the current logic unchanged, but when defined does what descrived above.  
This could be for example `open-range-on-end` with the default value `false`.

**Describe alternatives you've considered**
I've tried implementing the `focus-start-date`, but it's a lot more work to keep an extra computed that depends on the current end date. Expecially as i have quite a few different range selectors in my application.

**Comment by Jasenkoo** [comment]
The prop that handles this behavior is [`show-last-in-range`](https://vue3datepicker.com/props/modes-configuration/#show-last-in-range), however, it looks like it is not working properly, as it is enabled by default

**Comment by Jasenkoo** [comment]
My bad, the prop is working, in the docs example it is set to false.

**Comment by AVaccar** [comment]
Oh thanks. I didn't see it even thow i looked throu most of the documentation more than ounce.  
To me it looks like the component has too many props.  
Anyway, thanks for your time
