### ISSUE TITLE
Position remains fixed when scrolling when using teleport

### ISSUE THREAD

**Issue by r-rivero** [Vuepic/vue-datepicker#710]
**Describe the bug**
The position of the date/time picker remains fixed when scrolling on a screen that did not initially scroll (eg. height increased due to expanding an accordion)

**To Reproduce**
1. Declare an instance of the VueDatePicker component with the teleport property explicitly set to true in a view that does not cause overflow.
2. Programmatically increase the height of that view so that the content now overflows.
3. Click on the date input field to expand the Date/Time picker and scroll

**Expected behavior**
The date picker should be positioned right below the input field

**Screenshots**
https://github.com/Vuepic/vue-datepicker/assets/156231797/47ae0c40-1851-4d41-b76c-d422a884fd89

**Desktop & mobile (please complete the following information):**
 - Browser [chrome, firefox] (performed the tests in these browers only)
 - Library version [e.g. 7.4.1]

**Comment by Jasenkoo** [comment]
It is a bit overkill to watch if the parent div becomes scrollable, you can manually trigger [`onScroll`](https://vue3datepicker.com/methods-and-events/methods/#onscroll) function when needed.
