### ISSUE TITLE
clearValue not working as expected

### ISSUE THREAD

**Issue by navsterx** [Vuepic/vue-datepicker#713]
When I have auto-apply, range and min-range activated with :invalid-select, when I call clearValue(), I expect it to clear my range selection, however it does not - (I don't actually have any date selected at this point), however it does clear the range selection when I have a date that was previously selected. 

Example below.

Markup:
```
<VueDatePicker ref="datepicker" auto-apply inline v-model="date" range :min-range="minRange"
  :partial-range="false" :enable-time-picker="false" @update:model-value="handleDate"
  @invalid-select="invalidRange" :allowed-dates="allowedDates" style="display:block"
  :style="{ '--secondary-color': secondaryColor }" />
```

Method:
```
const invalidRange = () => {
  dialogOpen.value = true;
  datepicker.value.clearValue();
}
```

There's a strong chance I may be missing something, but thought I'd flag. Thanks!

**Comment by Jasenkoo** [comment]
You are doing it correctly, make sure that `handleDate` can accept the `null` value because you are manually updating it. `clearValue` method sets `v-model` to `null`
