### ISSUE TITLE
Time overlay closes when hours, month, year selected from their respective overlays, However works fine if you stick to calender or simple time picker.

### ISSUE THREAD

**Issue by tabish-ali** [Vuepic/vue-datepicker#714]
If you need to go to specifc year, you would not want it to go through all the years 1 by 1, or same with months, you directly go to months / years overlay. Same with time, if you need to jump to time, then you need to go to hours or minutes overlay. However in the overlay closes and no bind variable is updated.
![years](https://github.com/Vuepic/vue-datepicker/assets/52597760/9c0f548c-047d-4066-b722-6bdd2af2171f)
![Screenshot 2024-01-14 212202](https://github.com/Vuepic/vue-datepicker/assets/52597760/bb3d15c7-7295-4246-addb-97910860d990)

**Comment by Jasenkoo** [comment]
This is expected behavious, if you want to update `v-model`, you need to set `auto-apply`. Updating month or year, doesn't update the date directly.
