### ISSUE TITLE
Custom trigger with inline configuration not working

### ISSUE THREAD

**Issue by ersi77** [Vuepic/vue-datepicker#717]
Description:
I would like to replace built-in input with my custom input and apply inline rule.
My end goal is card with custom input and calendar from datepicker displayed under that.
Something like this:
![image](https://github.com/Vuepic/vue-datepicker/assets/102036810/816855c9-28c1-43ff-af87-fcf82b38ad46)

To reproduce:
currently when I try it in playground custom trigger + inline rule I dont see the trigger.

playground:
https://stackblitz.com/edit/vuepic-vue-datepicker-spzttp?file=src%2Fcomponents%2FPlayground.vue

additional question:
I see the slot for action-preview https://vue3datepicker.com/slots/content/#action-preview
but is it possible to just turn off this attribute from datepicker?

**Comment by Jasenkoo** [comment]
You need to specify `:inline="{ input: true }"` to show the input field as stated [here](https://vue3datepicker.com/props/modes-configuration/#inline-configuration). The slot you need is called `dp-input`, however, it is not working properly in inline mode, I will take care of it.

**Comment by ersi77** [comment]
thank you, and can you help me with additional question also please?
I see the slot for action-preview https://vue3datepicker.com/slots/content/#action-preview
but is it possible to just turn off this attribute from datepicker?

**Comment by ersi77** [comment]
I just wanted to ask when do you expect this fix will be released? thank you
