### ISSUE TITLE
get month on next/previous arrow button is clicked in range calendar

### ISSUE THREAD

**Issue by mshakhriyorov** [Vuepic/vue-datepicker#723]
![image](https://github.com/Vuepic/vue-datepicker/assets/71601329/31a7e546-c406-4094-889e-407bc1ec8960)

How can I get the month above once I click one of arrow buttons?! Namely, if I click previous month button on left (October), it moves to September. This is the thing I need. 
And if I click right button in December, it moves to January. This is the thing I need.

```
           <vue-datepicker
              v-model="date"
              format="MM-DD-YYYY"
              type="date"
              range
              @pick="handlePick"
            />
```

This is what I have so far

**Comment by Jasenkoo** [comment]
You can use `@update-month-year` event.
