### ISSUE TITLE
Make an handleEsc which will go to the original state of the date 

### ISSUE THREAD

**Issue by ArdyZ** [Vuepic/vue-datepicker#724]
**Is your feature request related to a problem? Please describe.**
Sometimes I accidentally change the input as I am using it as a text field. It would be nice to undo all those changes by pressing the Esc button on the keyboard.

**Describe the solution you'd like**
Using the @keydown.esc, call a the function handleEsc (like the handleEnter and handleTab) which then goes back to the state before the focus came onto the input field.

**Additional context**
Feedback on the issue is welcome, as it is my first time on a open-source project.

**Comment by Jasenkoo** [comment]
This is kinda redundant, as the input is a text input field, you can just use browser undo.
