### ISSUE TITLE
Ref from DatePicker returns array

### ISSUE THREAD

**Issue by TomDeSmet** [Vuepic/vue-datepicker#73]
Following this example: https://vue3datepicker.com/api/methods
The ref I receive from DatePicker is an array. So I need to do `datepicker.value[0]`.
This seems weird? I'm using it inside `script setup`.

**Comment by Jasenkoo** [comment]
This is the behavior from Vue if you use a component inside a `v-for` loop.

**Comment by TomDeSmet** [comment]
Oh my, so sorry. I forgot all about that! Thanks.
