### ISSUE TITLE
[question] min/max-date specification

### ISSUE THREAD

**Issue by teast** [Vuepic/vue-datepicker#731]
**Describe the bug**
The current min and maxdate fields do not take timezone into consideration. Instead they seems to require to be specified in the given timezone.
If the user is located in a different timezone than what is specified to datepicker both mindate and maxdate fields expects the dates to be in datepickers timezone. This can be troublesome if we want to specify "today+10 minutes", because then we will have to convert the date to correct timezone first.

Is this how it is expected to work?

**To Reproduce**
1. Specify a timezone that differs from your timezone
2. Try to set mindate to "now + 10 minutes" using Date()
3. The date will be seen as "datepickers's timezone" and not converted

**Expected behavior**
Datepicker to convert input date to correct timezone

**Desktop & mobile (please complete the following information):**
- latest chrome, firefox and edge
- 7.4.1

**Related issues**
#642

**Comment by Jasenkoo** [comment]
It is very tricky to handle this. As the current integration is not very good at managing date validations across timezones and will need some restructuring. I plan to fix this, but it won't be included in the next release, as it will be quite a big refactor.

**Comment by Jasenkoo** [comment]
New timezone configuration is available now.
