### ISSUE TITLE
Slot dp_input and text-input

### ISSUE THREAD

**Issue by Icoder9699** [Vuepic/vue-datepicker#734]
**Describe the bug**
When I use slot dp_input to customize styles of date picker the value doesn't change. 

**To Reproduce**
1: configurated datepicker with options: 
```
{ 
  format: "dd.MM.yyyy",
  openMenu: true,
}
```
2: The input value was changed when openMenu option is `false`    

**Expected behavior**
The problem is that when the user types to input in the slot, the value doesn't change and can't validate so I added onInput event.

**Screenshots**
```
<Datepicker
  v-model="personalData.birthday"
  text-input
  :text-input-options="textInputOptions"
  :format="dateFormat"
  placeholder=" "
  model-type="dd.MM.yyyy"
  :enable-time-picker="false"					
  :auto-apply="true"					
  :clearable="false"					
 >

<template #dp-input="{ value, onInput }">
  <input type="text" @input="onInput($event)" :value="value" />
  <label>{{ $t("personal.birthday") }}</label>
</template>

</Datepicker>
```

**Comment by prostoleo** [comment]
@Icoder9699 i'm experiencing the same problem. Did you manage to solve it?

**Comment by Jasenkoo** [comment]
@Icoder9699 @prostoleo If you want to type in the input field, set `text-input` prop.
