### ISSUE TITLE
Cannot select February of the previous year

### ISSUE THREAD

**Issue by hanbiya** [Vuepic/vue-datepicker#736]
**Describe the bug**

**It seems that there is an issue with the monthPicker where I am unable to select any February from previous years. Whenever I try to select February, it automatically jumps to March. This problem is consistently occurring only in the monthPicker. I have noticed the same issue on your official website as well. Could you please look into this matter?**

**To Reproduce**
1. configure the mode to monthPicker.
2. select February 2023.
3. See error

**Expected behavior**

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - ALL Browser
 - Library version [e.g. 3.0.0]
 - All Version

**Comment by dathacky** [comment]
+1

**Comment by andriusManvesta** [comment]
+1

**Comment by LorenteDev** [comment]
It happens in non-leap years, not just the previous year.
