### ISSUE TITLE
Datepicker in Month mode depends on current Date

### ISSUE THREAD

**Issue by kkfuri** [Vuepic/vue-datepicker#738]
**Describe the bug**
When picking a month in the Datepicker using `month-view`, since we're on day 30, if you pick february, it will match march because it's relying on the current day to create a new javascript `Date`. 

**To Reproduce**
1. Go to https://vue3datepicker.com/props/modes/#month-picker
2. Open the month picker
3. Select 2021
4. Select February and save
5. The showed month should be march, unexpectedly

**Expected behavior**
To show february when february is picked

**Screenshots**

https://github.com/Vuepic/vue-datepicker/assets/42350846/b17feba3-713a-4815-b211-0a94614565b3

**Comment by kkfuri** [comment]
Related to https://github.com/Vuepic/vue-datepicker/issues/736

**Comment by alessioforti** [comment]
Same issue for me too
