### ISSUE TITLE
Automatic closing of month or year picker in inline mode

### ISSUE THREAD

**Issue by timoteiNicsoft** [Vuepic/vue-datepicker#741]
**Describe the solution you'd like**
I am using vue-datepicker with the inline and multiple calendar mode. It would be helpful if the month-picker or year-picker could automatically close when clicking outside of the selector.

**Comment by Jasenkoo** [comment]
It will be redundant adding it, you can achieve this by providing a custom prop

```vue
<template> 
    <VueDatePicker ref="dp" :conifg="{ onClickOutside }" >
</template>

<script setup>
  import { ref } from "vue";
  
  const dp = ref();

  const onClickOutside = () => {
     dp.value?.switchView('calendar', 0);
  }
</script>
```
