### ISSUE TITLE
'fixedStart' in month-picker mode does not work

### ISSUE THREAD

**Issue by sato-anna** [Vuepic/vue-datepicker#742]
**Describe the bug**

'fixedStart' in month-picker mode does not work.
Even if you write as below, the starting month is not fixed and the starting month can be changed.
The initial value for month of v-model has already been set in the following format.

```
month: [{month: 0, year: 2024},{month: 0, year: 2025}]
```
Is there any solution?
```
<VueDatePicker
    v-model="month"
    locale="ja"
    teleport-center
    :clearable="false"
    input-class-name="dp-custom-input"
    menu-class-name="dp-custom-menu"
    month-picker
    format="yyyy/MM"
    :range="{ fixedStart: true }"
    auto-apply
></VueDatePicker>
```

**Comment by Jasenkoo** [comment]
This configuration is only available on regular date picker
