### ISSUE TITLE
Menu is out of bounds when positioned above the input but there is insufficient space

### ISSUE THREAD

**Issue by BryanKuiper** [Vuepic/vue-datepicker#747]
**To Reproduce**
1. Go to https://stackblitz.com/edit/vuepic-vue-datepicker-v2wkgv
2. Adjust the size of the screen to make sure there is more space above the input than below the input
3. Click on the input
4. The menu opens above the menu, but is partially outside of the screen (see screenshot)

**Expected behavior**
The menu should never go out of bounds at the top of the screen. The menu should go above the input if both are valid:
- The height of the menu is less than the available space above the input
- The space above the input is more than the space below the input

The getMenuPlacement method determines whether the menu should be placed above or below the input but goes past all the if statements and therefore defaults to MenuPlacement.top in this situation. Maybe it should default to MenuPlacement.bottom.

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/30691301/96c93a99-fee5-4797-9d2c-0cc4d0f47ae5)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: 8.1.1, but this also happens on 7.4.0 and higher.

**Comment by Jasenkoo** [comment]
This is really an edge case and won't be fixed, also, this is on end application to make sure that the picker has enough space to open, if not, other props can help with it.

**Comment by xak2000** [comment]
@Jasenkoo I have similar problem. By "other props" you probably meant https://vue3datepicker.com/props/positioning/#alt-position? It can solve the problem, but I didn't find any docs that describe how often (or on what events) the `customPosition` function is called.

My idea is to use something like https://floating-ui.com/docs/vue to calculate `top`/`left` and then use `alt-position` to apply the values.

But, as the values are not constant (scroll position, window size, hidden/visible other elements, etc.), I need some hook to force `vue-datepicker` to re-call the `customPosition` function. Can you point me to the right direction, please?
