### ISSUE TITLE
Aria labels for short day names (mo, tu, we...)

### ISSUE THREAD

**Issue by bapman81** [Vuepic/vue-datepicker#749]
Not a specialist but I think it would be nicer for accessibility if the short day names (mo, tu, we...) in the calendar could have aria-labels with their full name (monday, tuesday, wednesday...).

Maybe this is already the purpose of the property `day` in `aria-labels` prop. If so, could you please indicate how to use it?

**Comment by Jasenkoo** [comment]
`day` is for calendar cells, it is a `function` with the `{value}` parameter, `value` property is the date in the cell.
