### ISSUE TITLE
range monthPicker cannot handle 'null' as first month (and doesn't display otherwise)

### ISSUE THREAD

**Issue by ronaaron** [Vuepic/vue-datepicker#75]
*First problem*:

I initialize a DatePicker with a value of [null, dt] (dt is a valid Date object). The DatePicker options are 'range', 'monthPicker', 'autoRange', 'textInput', 'autoApply', 'enableTimePicker=false', 'format="yyyy-MM".

On parse, I get the exception:

```
vue-datepicker.es.js?0278:1 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'month' in null
    at r (vue-datepicker.es.js?0278:1)
    at eval (vue-datepicker.es.js?0278:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?d2dd:155)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?d2dd:164)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js?d2dd:2687)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?d2dd:358)
    at flushJobs (runtime-core.esm-bundler.js?d2dd:403)
```

I've got the latest datepicker from npm 

*Second problem*:

If I give the DatePicker two valid dates, it doesn't complain but also doesn't display the values in the text field.

It should be noted that I have no problem with a non-range monthPicker, so clearly I'm doing something wrong.

**Comment by Jasenkoo** [comment]
Picker does not handle the first range item when it is null, it must be provided. For `monthPicker` the `v-model` is slightly different, you can check [here](https://vue3datepicker.com/api/props/#modelvalue). To make it work properly you pass an array of objects like this:

 `[{ month: 6, year: 2022 }, { month: 7, year: 2022 }]`, meaning that the range will be from June to July.

**Comment by ronaaron** [comment]
Update: I am giving the DatePicker a range in the form of objects, [null, {month:0, year:2022}] and that doesn't work.
