### ISSUE TITLE
Propagate the selected date immediately on the calendar instead of having to click 'Select'

### ISSUE THREAD

**Issue by JasmineLaiHua** [Vuepic/vue-datepicker#751]
Firstly, thank you to the contributors of this library; it has been greatly useful for my project!

Just a minor issue, but I couldn't find any reference in the documentation. As mentioned in the title, I would like the date to be propagated immediately after I select it on the calendar. Currently, I have hidden the action row, but without the 'Select' button, the date does not change upon selection.
I have worked around with the `@update:model-value` event to set the date value. However, I would like to know how I can achieve the same result in an official manner.

Thank you,

**Comment by Jasenkoo** [comment]
Just set the `auto-apply` prop.
