### ISSUE TITLE
1-digit year of 0 or 1 as 1900 or 1901 instead of 0 AD or 1 AD

### ISSUE THREAD

**Issue by iouomo** [Vuepic/vue-datepicker#752]
**Describe the bug**
 Getting 1900 or 1901 instead of 0 AD or 1 AD, when picking 0 or 1 year.

**To Reproduce**
1. Set :year-range="[0, 10000]".
2. Pick year 0 or 1 in the year picker.
3. Get 1900 or 1901.

**Expected behavior**
Picking 0 or 1 year the result must be 01/01/0000 or 01/01/0001.

**Screenshots**
no

**Desktop & mobile (please complete the following information):**
 - Browser [all]
 - Library version [8.1.1]

**Comment by Jasenkoo** [comment]
This adds so much complexity, that it is not worth doing it as it will require a full rewrite. Here is a good [read](https://stackoverflow.com/questions/65587240/how-to-construct-a-historic-date-year-0-100-in-javascript)
