### ISSUE TITLE
Option to keep output in local time but in a Date object

### ISSUE THREAD

**Issue by JohnCampionJr** [Vuepic/vue-datepicker#755]
**Is your feature request related to a problem? Please describe.**
My dates are input to the date picker via local time, but output as UTC which is causing inconsistencies throughout the app.

**Describe the solution you'd like**
An option to keep output Date object in local time.  The `utc` option, if set to false, puts the output in a string in local time, but not a Date

**Describe alternatives you've considered**
Open to suggestions

**Comment by Jasenkoo** [comment]
You can use `timezone` to keep it in the `Date` object

**Comment by JohnCampionJr** [comment]
Thanks, I'm sorry I missed that.  

Should I just get the clients time zone and set the `timezone` option to that?
