### ISSUE TITLE
 Multicalendar configuration shows second calendar with inccorect year

### ISSUE THREAD

**Issue by stephanfriedrich** [Vuepic/vue-datepicker#757]
**Describe the bug**
Hi, 
thx for your awesome vueJs-App.

I have a problem, and maybe someone could help me.
I want to show Datepicker with config: `multi-calendars="{ solo: true, count: 2}"  range month-picker` and `monthDate: [Today, Next Month]`.

everything is ok in the first datepicker, but i expect the 2nd datepicker to also adjust to the current year (at initialization with "Next Month" value).
however, the 2nd datepicker shows the next year

```Javascript
  VueDatePicker(
    :multi-calendars="{ solo: true, count: 2}" 
    month-picker
    range 
    v-model="monthDate"
    format="dd.MMM yyy"
  )
  
  
export default {
  name: 'MyAwesomeDatePicker',
  components: {
    VueDatePicker
  },
  data() {
    return {
      monthDate: []
    }
  },
  mounted() {
    const startMonth = new Date().getMonth()
    const startYear = new Date().getFullYear()

    const endMonth = startMonth + 1
    const endYear = startYear

    this.monthDate.push({ month: startMonth, year: startYear }, { month: endMonth, year: endYear })
  }
}
```

![issue](https://github.com/Vuepic/vue-datepicker/assets/2052955/f2a3d7c5-ea89-4b44-bc39-7b7bac7ddf8f)

**Comment by Jasenkoo** [comment]
This is expected behavior as both dates are in the same year
