### ISSUE TITLE
use range mode   i want display local time(kst) not utc 

### ISSUE THREAD

**Issue by evelo0702** [Vuepic/vue-datepicker#76]
I'm using range mode. I am trying to display the time using {{date}}, but it is displayed in utc. So I marked it with <Datepicker v-model="date" locale="kst"  range>, but it doesn't work. still display in utc. What should I do?

**Comment by Jasenkoo** [comment]
Are you trying to put the date object into the template? You need to format it properly. The next version will have the option to specify a`v-model` format.

**Comment by evelo0702** [comment]
oh sorry I typed it wrong 

I'm using range mode. I am trying to display the time using {{date}}, but it is displayed in utc. So I marked it with <Datepicker v-model="date" locale="kst"  range>, but it doesn't work. still display in utc. What should I do?

**Comment by evelo0702** [comment]
<Datepicker
            v-model="date"
            locale="kst"
            range> 

i use this code but {{ date }} is still display in utc... 

and not use range  
<Datepicker
            v-model="date"
            locale="kst"
             />     use this code {{date}} is display in kst

**Comment by Jasenkoo** [comment]
When you use `{{date}}` in the `<template>`, it is interpolated as a string. To show it in the proper format, you have to make a custom format. If you want to use a localized date format in the picker, check [`formatLocale prop`](https://vue3datepicker.com/api/props/#formatlocale)
