### ISSUE TITLE
`text-input` with `range` causes page freeze

### ISSUE THREAD

**Issue by danulqua** [Vuepic/vue-datepicker#761]
**Describe the bug**
When using datepicker with `text-input` and `range` modes, and attempting to edit the date by pressing backspace, the page freezes.

**To Reproduce**
1. Click on the datepicker component
2. Choose any date range
3. Click on the component text field
4. Press backspace
5. The page freezes

**Expected behavior**
Page does not freeze, everything works fine.

**Screen recording**

https://github.com/Vuepic/vue-datepicker/assets/38916225/7058f5b8-0102-4a73-bcae-f11d8c6bafca

**Desktop & mobile (please complete the following information):**
 - Arc, Version 1.30.0 (46409), Chromium Engine Version 121.0.6167.184
 - Google Chrome Version 122.0.6261.57 (arm64)
 - Library version: `"@vuepic/vue-datepicker": "^7.4.0",`

**Comment by Jasenkoo** [comment]
Please use the latest version, this issue is resolved
