### ISSUE TITLE
Hydration mismatch when used with SSR

### ISSUE THREAD

**Issue by thijsw** [Vuepic/vue-datepicker#762]
**Describe the bug**
When I use this library I'm encountering hydration errors. I'm using the lib in a Nuxt 3 project.

**To Reproduce**
Use this Vue component as a page in Nuxt:

```vue
<template>
  <div>
    <vue-date-picker v-model="date" />
  </div>
</template>

<script lang="ts" setup>
import VueDatePicker from '@vuepic/vue-datepicker'
import '@vuepic/vue-datepicker/dist/main.css'

const date = ref()
</script>
```

**Expected behavior**
I am expecting that the date picker works without hydration errors. I am suspecting that teleport might be the culprit.

**Screenshots**
![Screenshot 2024-02-22 at 16 00 40](https://github.com/Vuepic/vue-datepicker/assets/28638/d9c0a163-d1c0-4e04-aee7-1b67affd7b92)

**Comment by lumos94** [comment]
have the same issue as well!
