### ISSUE TITLE
Auto-apply does not work when a flow is defined

### ISSUE THREAD

**Issue by phuze** [Vuepic/vue-datepicker#764]
**Describe the bug**
When using a flow, auto-apply does not work if the user skips directly to the calendar.

**To Reproduce**
Apply both `auto-apply` and `flow` props:
```vue
<template>
  <div>
    <Datepicker
      v-model="date"
      :flow="['year', 'month', 'calendar']"
      auto-apply
    />
  </div>
</template>

<script setup>
import { ref } from 'vue';
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

const date = ref();
</script>
```

**Expected behavior**
For auto-apply to function as expected.

**Screenshots**
![auto-apply-error](https://github.com/Vuepic/vue-datepicker/assets/9218035/75ab4087-d4d6-4ea5-ab69-2757ac2dfba0)

**Desktop & mobile (please complete the following information):**
```Microsoft Edge Version 122.0.2365.52 (Official build) (64-bit)```
 - Library version [e.g. 3.0.0]
```"@vuepic/vue-datepicker": "^8.1.1"```

**Comment by phuze** [comment]
I just came across this [issue #583](https://github.com/Vuepic/vue-datepicker/issues/583), in which you say to apply the `partial-flow` prop. It did not work:

![partial-flow-error](https://github.com/Vuepic/vue-datepicker/assets/9218035/e9e873d3-a9e5-4871-908f-27f1383e03f2)

**Comment by phuze** [comment]
I came across issue #583, in which identifies that we must also set `partial-flow`, when combining `flow` and `auto-apply`. Please consider updating the documentation to make note of this:

![image](https://github.com/Vuepic/vue-datepicker/assets/9218035/f749c42c-64a1-4060-9de4-3c3229f6e546)

**Comment by phuze** [comment]
Something else I've just noticed, when you apply a combination of `auto-apply`, `flow` and `partial-flow`, the calendar no longer closes as it normally does when using `auto-apply`.

![date-errors](https://github.com/Vuepic/vue-datepicker/assets/9218035/d2345e4e-267b-4ee3-8760-a4d979af1dd2)

I considered using the `@update:model-value` event along with the `closeMenu` method, but this relies on defining a component ref. This concept is difficult when you consider a scenario with a dynamic number of date selectors (ie: a user is adding additional items to a form or something).

```vue
<script setup>
  const mydate = ref(null);
  const closeCalendar = () => {
    if (mydate) { mydate.value.closeMenu() }
  }
</script>

<template>
  <div v-for="(item, index) in whatever" :key="item.id">
    <VueDatePicker
        :flow="['year', 'month', 'calendar']"
        auto-apply
        partial-flow
        @update:model-value="closeCalendar"
        ref="mydate"
    />
  </div>
</template>
```

I was hoping we could do something like:

```vue
<template>
  <div v-for="(item, index) in whatever" :key="item.id">
    <VueDatePicker
        :flow="['year', 'month', 'calendar']"
        auto-apply
        partial-flow
        @update:model-value="($event) => {
          $event.closeMenu()
        }"
    />
  </div>
</template>
```
But the event only emits the selected date value, and not a reference to itself. It seems everytime I try and address one thing, something else breaks. Whats the best way to go about this?

**Comment by faizaaulia** [comment]
hi @Jasenkoo , it seems like bugged again. I try on https://vue3datepicker.com/props/modes-configuration/#partial-flow but after i pick a date, it closed directly, not open the time

https://github.com/Vuepic/vue-datepicker/assets/21327758/8823277e-6bf8-4285-ba78-f0a3fa5782cd

**Comment by faizaaulia** [comment]
hi @Jasenkoo , it seems like bugged again. I try on https://vue3datepicker.com/props/modes-configuration/#partial-flow but after i pick a date, it closed directly, not open the time. Isn't should be open the time menu?

https://github.com/Vuepic/vue-datepicker/assets/21327758/4f59a0c8-4b33-4f25-9e7a-7b59e13df573
