### ISSUE TITLE
Aria issue when using cypress-axe `aria-dialog-name`

### ISSUE THREAD

**Issue by hfekete** [Vuepic/vue-datepicker#765]
**Describe the bug**
To support accessibility we integrated cypress-axe plugin into our automated tests. Running cypress suite cypress-axe reports `aria-dialog-name` error when date pick dialog is open. 

After investigating a bit our team found that potential solution might be to have a way to pass `aria-label` to `dp_menu` component. 
Let us know if this is a bug or enhancement, and possible courses for solving it.

Additionally, if it would be beneficial, we can collaborate with you to create a pull request for a solution that we believe will resolve the problem.

**To Reproduce**
1. Go to cypress test suite (that has cypress axe plugin)
2. Run cypress test suite to verify accessibility implementation on any page where the datepicker dialog is open
3. Check the console for the error

repro repository: https://github.com/hfekete/components-axe-errors

**Expected behavior**
No `aria-dialog-name` error showing up when running test suite with cypress-axe plugin

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/7550170/83594630-c357-477c-b33b-c1d9bdaf787f)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome v122
 - Library version: 8.1.1

**Comment by Jasenkoo** [comment]
It is a bug, as there is already a `menu` property in `ariaLabels` prop, however it is not used

**Comment by hfekete** [comment]
Thanks for verifying this quickly and fixing it !
