### ISSUE TITLE
The switchView method does not work when there is a "month-year" slot

### ISSUE THREAD

**Issue by danilpon98** [Vuepic/vue-datepicker#770]
**Describe the bug**
There is no way to open month-overlay using the switchView method. I'm also using the month-year slot and I think it's because of it. I tried doing a month-overlay slot, but it didn't work. There are no errors in the console.

**To Reproduce**
1. Go to [Playground](https://stackblitz.com/edit/vuepic-vue-datepicker-mwhjrs?file=src%2Fcomponents%2FPlayground.vue)
2. Click on 'View Month' button
3. See that month-overlay did not open

**Expected behavior**
month-overlay slot is displayed

**Comment by Jasenkoo** [comment]
This is expected behavior, as the overlays are part of the `month-year` header, when you use the slot, these components are not rendered.
