### ISSUE TITLE
min-date/max-date not following format property

### ISSUE THREAD

**Issue by fabiodp1** [Vuepic/vue-datepicker#772]
Since the last update, the min/max data properties are not functioning correctly. When passing a specific format (e.g., dd-MM-yyyy), they do not adhere to it; instead, they continue to use the default format (MM-dd-yyyy).

**To Reproduce**
I reproduced the issue here:
https://codesandbox.io/p/devbox/error-on-min-max-date-w6kzc4?file=%2Fpnpm-lock.yaml%3A7%2C14

Thanks

**Comment by Jasenkoo** [comment]
The `format` does not have any effect on the dates provided. When you provide a date in a `string` or `number` format, it is parsed with `new Date()`. If the string is not in the correct format. it will not work properly.
