### ISSUE TITLE
:flow menu doesn't close if last flow step doesn't end with calendar

### ISSUE THREAD

**Issue by zipl2** [Vuepic/vue-datepicker#774]
**Describe the bug**
The datepicker menu won't close if flow steps doesn't end with 'calendar'.

**To Reproduce**
```
<script setup>
import {ref} from 'vue'
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

const date = ref(0);
</script>

<template>
  
  <Datepicker
    v-model="date"
    auto-apply
    :enable-time-picker="false"
    :close-on-auto-apply="true"
    :flow="['calendar', 'month', 'year']"    
  />
  
</template>
```

After selecting year, the menu should close, but it goes back to calendar. You can pick any date multiple times but the menu won't close.
If you add 'calendar' as fourth (= last) step
`:flow="['calendar', 'month', 'year', 'calendar']"    `
 then it will close.

**Expected behavior**
The menu should close when the last flow step is finished even if it isn't 'calendar' & the value should be applied to the model.

**Desktop & mobile (please complete the following information):**
 Every browser
 - Library version [e.g. 3.0.0]
  "@vuepic/vue-datepicker": "^8.2.0"

**Comment by Jasenkoo** [comment]
There is no point in opening overlays after selecting the date, as it has no effect, making this point redundant.
