### ISSUE TITLE
Min-time/max-time limits not working for minutes with tz

### ISSUE THREAD

**Issue by iCascada** [Vuepic/vue-datepicker#778]
**Describe the bug**
Hi guys. When configuring the time picker, the set limits for minutes do not work properly. At the same time, the hours reacts correctly.

**To Reproduce**
1. Go to your [Datepicker playground](https://stackblitz.com/edit/vuepic-vue-datepicker?file=src%2Fcomponents%2FPlayground.vue)
2. Set model with a time zone different from the system one
3. Enable the min-time or max-time by adding the prop (ex: `:min-time="{ hours: 11, minutes: 30 }"`)
4. Open the datepicker
5. Pay attention to the minutes, there will be no any restrictions

Besides, the problem is reproduced on the documentation page [Link](https://vue3datepicker.com/props/time-picker-configuration/#min-time)

**Expected behavior**
Prop should sets the minimal available time to pick for minutes including.

**Desktop & mobile (please complete the following information):**

- Browser: Chrome (last version)
- Package version 8.2
- OS - MacOS Sonoma 14.2

**Comment by Jasenkoo** [comment]
Everything seems ok. [Playground](https://stackblitz.com/edit/vuepic-vue-datepicker-3jz2nz?file=src%2Fcomponents%2FPlayground.vue)
