### ISSUE TITLE
missing directory "./dist"

### ISSUE THREAD

**Issue by Lusky1001** [Vuepic/vue-datepicker#78]
the dist directory is not part of the package, but you need it if you want to include main.css

**Comment by Jasenkoo** [comment]
What do you mean it is not part of the package?

**Comment by Lusky1001** [comment]
in your readme you describe how to register and import the component but the directory /dist does not exist

import { createApp } from 'vue';
import App from './App.vue';
import Datepicker from '@vuepic/vue-datepicker';
**import '@vuepic/vue-datepicker/dist/main.css';**

const app = createApp(App);
app.component('Datepicker', Datepicker);

**Comment by Jasenkoo** [comment]
Do you have any errors? The directory exists, check out [working demo](https://stackblitz.com/edit/vuepic-vue-datepicker?file=src%2Fcomponents%2FPlayground.vue)

**Comment by Lusky1001** [comment]
if I add the component with yarn add @vuepic/vue-datepicker there is no "dist" directory in the root. in Git I can not see as wel
![vuepic-vuedatepicker](https://user-images.githubusercontent.com/108676917/177563515-28180baf-917b-4599-a242-a2e21bb583f7.png)
l

**Comment by Jasenkoo** [comment]
I will check with yarn, but it should be ok, the dist folder is just built library and available on npm
