### ISSUE TITLE
Datepicker thinks input is incorrectly formated

### ISSUE THREAD

**Issue by bjornandrip** [Vuepic/vue-datepicker#785]
**Describe the bug**
We are using your nice Datepicker with our custom input field. 
I have noticed a big problem however, when the format passed to the datepicker is dd/MM/yyyy it seems to assume the value it gets from the v-model is incorrect (in MM/dd/yyyy) and formats it according to that. So I accidentally kept getting an infinite loop of it changing format, since our input gets the value emits it back to the component where the datepicker is checks if it is the same as the cached value (which it isn't because the datepicker flipped the d and M) and then that goes through the datepicker and well the rest is infinite history. I will explain better bellow...

**To Reproduce**
1. Pass a value like 07/08/2023 and the format dd/MM/yyyy to the datepicker
2. From the input #dp-input template view the `value`
3. 

**Current behavior**
The value passed back is 08/07/2023

**Expected behavior**
The datepicker should probably expect the value passed to it to be correctly formated? 
Or some other way to bypass this 

**Screenshots**
![IMG_DFC49EBBB8D7-1](https://github.com/Vuepic/vue-datepicker/assets/102038451/5833d142-08b8-4cf8-8d8e-bbd6a7d35eaa)

After the last log I would perform a check if it matches the last known value and therefore get an infinite loop

 - Browser chrome, safari
 - Library version 8.3.1

**Comment by Jasenkoo** [comment]
You should use the format in `text-input` in this case, as the picker has no way of knowing where is the month/date

**Comment by bjornandrip** [comment]
@Jasenkoo How does this make sense?
I have my own input component using the `dp-input` slot passing the prop `value` through it to my inputs v-model.
Now using the format in `text-input` like you suggested makes the value passed to my input component not formatted at all (just default format)
 what is the purpose then form me to use the format prop??? As I have read this format only formats when native input is selected, which seems useless to me...
Am I just left with taking care of the formating completely myself???

**Comment by Jasenkoo** [comment]
@bjornandrip Provide a playground with what you are trying to achieve, I can't tell based on the provided context. The format on `text-input` prop is used to override the default, in this case from the `format` prop.
