### ISSUE TITLE
Date Selection Mismatch and Timezone Configuration Issue

### ISSUE THREAD

**Issue by dvmoomoodv** [Vuepic/vue-datepicker#787]
**Describe the bug**

**To Reproduce**
1. I selected the 6th
3. but the 7th was activated
4. See screenshot

**Expected behavior**
-> 
As you can see from the selection results below, the 6th is selected, but the 7th is activated. I wanted to solve this issue, so I upgraded from version 7 to the latest version 8 to test, but the problem persisted. However, when I set the timezone to 'UTC', the calendar activation issue was resolved, but then the time values were incorrect. I live in Korea, and it seems like the activation issue might be related to the timezone settings. Can you recommend how to configure this properly?
```
const timezone = ref({
  timezone: 'UTC',
  exactMatch: true,
  dateInTz: 'UTC',
  emitTimezone: 'UTC',
})
```

**Screenshots**
![chrome_imlXlISsQM](https://github.com/Vuepic/vue-datepicker/assets/12573299/2c7efb9b-30cf-459b-ae76-f0540558d355)

**Desktop & mobile (please complete the following information):**
 - Browser [e.g. chrome, safari] : Chrome  122  window 11 
 - Library version [e.g. 3.0.0] : 8.3.1

**Comment by Jasenkoo** [comment]
@dvmoomoodv Can you try with `v8.2` and see if the problem persists?

**Comment by Jasenkoo** [comment]
Investigated the issue. The time change is expected, as you are now rendering the calendar in the specific timezone, which means, it will display time in the UTC timezone.
