### ISSUE TITLE
MultiDates Calendar Input Bug

### ISSUE THREAD

**Issue by kentbong** [Vuepic/vue-datepicker#79]
When on MultiDates mode,
~ The selected dates only captured the first 2 selected date values, the rest are not captured.
~ When select single date, the second date values default to "1970-MM-dd hh:mm:ss".

**Screenshots**
![image](https://user-images.githubusercontent.com/6791270/177464654-deeaa9d4-4dad-48c8-9443-b054d0526443.png)
![image](https://user-images.githubusercontent.com/6791270/177464408-09d5b4a3-5385-4151-818c-18c2464df187.png)

Please advise. Thank you.

**Comment by Jasenkoo** [comment]
Probably an issue, will check
