### ISSUE TITLE
Highlight a preset button has been selected

### ISSUE THREAD

**Issue by nguyenquocdaile** [Vuepic/vue-datepicker#793]
Hi, Thanks for the awesome feature. 
I am working with `preset-dates`. But I don't see a way to highlight the button on the left when I click on it, like Today button I click it doesn't have any different class to style.

![image](https://github.com/Vuepic/vue-datepicker/assets/12345613/ea9c1e69-f7d0-48ba-a078-932c25032278)

**Comment by Jasenkoo** [comment]
You can use a custom slot and match the active value in your parent component. It is a bit redundant to add this check when it can be implemented manually if needed.
