### ISSUE TITLE
month-picker not working with disabled-week-days

### ISSUE THREAD

**Issue by michal-stachura** [Vuepic/vue-datepicker#796]
**Describe the bug**
If you set `disabled-week-days` and `month-picker` you cannot pick particular months

**To Reproduce**
E.g
`<VueDatePicker v-model="applicationsMonth" month-picker :disabled-week-days="[6, 0]" />`
disables to pick June, September and December

**Expected behavior**
1. `disabled-week-days` have no effect in month-picker
2. Add `:disabled-months` param.

**Desktop & mobile (please complete the following information):**
 - Browser - any
 - Library version [6.1.11]

**Comment by Jasenkoo** [comment]
Disabled dates work, you can also use the filters property.
