### ISSUE TITLE
Question: Prevent calendar from switching to next/previous month when clicking outside of current month

### ISSUE THREAD

**Issue by germsb** [Vuepic/vue-datepicker#797]
Is there any option to prevent this behavior?
I find it very disturbing when you have to select a period between two months.

[](https://github.com/Vuepic/vue-datepicker/assets/3269994/433e29ce-b505-47aa-a42c-946ec248a467)

https://stackblitz.com/edit/vuepic-vue-datepicker-jq9xwm?file=src%2Fcomponents%2FPlayground.vue

**Comment by Jasenkoo** [comment]
This is expected behavior, and it is handled automatically when clicking a date. It would require some unnecessary checks to prevent this behavior. You can just hide the offset dates if it is causing a distraction.

**Comment by Jasenkoo** [comment]
I will see what can be done, but can't promise anything, if it starts interfering with the existing logic, it will be closed.
