### ISSUE TITLE
Menu positioning issue with "teleport" prop due to margin collapse on body

### ISSUE THREAD

**Issue by mcmimik** [Vuepic/vue-datepicker#799]
**Describe the bug**
When using the `teleport` option, the menu is misaligned due to the collapsed margin of the body's first child. This results in the menu being positioned incorrectly, either too high or too low, depending on the direction of the collapsed margin. The current positioning calculation does not account for this effect.

**To Reproduce**
1. Set `position: relative;` for _body_.
2. Set `margin-top: 100px;` for the _body's_ first child.
3. Click on the component.
4. See wrong positioning.

Playground: https://stackblitz.com/edit/vuepic-vue-datepicker-collapsed-margin-teleport?file=src%2Fcomponents%2FPlayground.vue

**Expected behavior**
When the `teleport` option is active, the menu should intelligently adjust its vertical positioning to account for any displacement caused by the collapsed _body's_ margin, ensuring it aligns correctly with the associated trigger element.

**Screenshots**
<img width="1244" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/3358193/9d930817-bb41-4a8b-a407-97ac219c4962">

**Possible Solutions:**

1. Update the positioning algorithm to consider the top offset of the _body_ when the menu is teleported. Source: [src/VueDatePicker/composables/position.ts](https://github.com/Vuepic/vue-datepicker/blob/main/src/VueDatePicker/composables/position.ts#L50). One way to calculate the body's offset is `document.body.getBoundingClientRect().top`.
2. Expand the documentation to address this specific case, providing guidance on manual adjustments through the `altPosition` prop for scenarios involving margin collapse.

**Desktop & mobile:**
 - Chrome 123
 - Library version 8.3.1

**Comment by Jasenkoo** [comment]
Edge case that can be easily solved with wrapper div.
