### ISSUE TITLE
The whole calendar popup is disabled and transparent.

### ISSUE THREAD

**Issue by NaturalDevCR** [Vuepic/vue-datepicker#800]
**Describe the bug**
I am currently utilizing Quasar v2 along with this particular component for managing datepickers. Everything functioned smoothly until version 8.1.1 of the component. However, all subsequent versions exhibit the following behavior:

![IMG_2966](https://github.com/Vuepic/vue-datepicker/assets/35145882/66805b06-2353-4634-b364-5fdb5f5ffb70)

As illustrated in the image:

<img width="409" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/35145882/7c350079-79b0-42f7-9a42-995fd9b5c22b">

I had to employ a class to adjust the z-index of the element since it appears beneath everything else.

Moreover, there exists a disabled state within the div element, causing the entire popup to become disabled and the background to become semi-transparent, although it is still possible to select a date.

Reverting back to version 8.1.1 restores the expected functionality, as evidenced by the screenshot below:

<img width="300" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/35145882/04e916e0-b8f0-4646-8768-51aeb09099ee">

Below is the current code snippet I am utilizing:

    <VueDatePicker
      :clearable="false"
      :enableTimePicker="false"
      input-class-name="text-center dark-light-bg"
      auto-apply
      :dark="commonStore.isDarkMode"
      v-model="selectedStore.mainDate"
      :auto-position="false"
      format="dd/MM/yyyy"
    />

Any insights on this matter would be greatly appreciated.

Thank you in advance.

**Comment by 0xBiriyani** [comment]
Yes @NaturalDevCR ,  I can also confirm it's same for me. 
I am using Quasar V2 and vue-datepicker==8.3.2.

**Comment by NaturalDevCR** [comment]
> Yes @NaturalDevCR , I can also confirm it's same for me. I am using Quasar V2 and vue-datepicker==8.3.2.

I just found out, thanks to the commit title, that if I pass `:teleport="true"` to the component, the issue will dissapear. 

Not sure if the fact of a commit means that this is not an expected behavior anyway, so I'm not closing the issue to wait for an answer.

**Comment by Jasenkoo** [comment]
@NaturalDevCR No need to close the issue, it will be auto-closed on publishing. Looks like Quasar is handling the `disabled` flag and adding some opacity to it. The flag originated previously from the `teleport` component, as a main wrapper where it was disabled by default. Now when you are not using teleport, it adds a `div` wrapper with `disabled` flag on it
