### ISSUE TITLE
Popup arrow is not placed properly when the calendar is wider than the input field

### ISSUE THREAD

**Issue by Tsuyoshi84** [Vuepic/vue-datepicker#802]
**Describe the bug**
The popup arrow pointing to the calendar's input field is not placed properly when the calendar is wider than the input field.
This issue tends to occur when enabling `multi-calendars` since it widens the calendar popup.

**To Reproduce**
1. Go to https://stackblitz.com/edit/vitejs-vite-xq8lnk?file=src%2FApp.vue
2. Click on the input field
3. You can see that the arrow is not pointing to the input field exactly

**Expected behavior**
Ideally, the arrow should be placed under the center of the input field.

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/11254699/ca8b2db4-4a25-4a32-9f6e-af3e4b806578)

**Desktop & mobile (please complete the following information):**
 - Browser Chrome, Edge
 - Library version 8.3.2

**Comment by allusernamestakenexceptthis** [comment]
Just to add.  When you have two fields next to each other's, it may cause confusion or at best looks bad UX-wise.
