### ISSUE TITLE
Component UI bug after device rotation

### ISSUE THREAD

**Issue by aminebenaddi-centris** [Vuepic/vue-datepicker#803]
**Describe the bug**
The fix for the issue above, doesn't seem working https://github.com/Vuepic/vue-datepicker/issues/739

**Desktop & mobile (please complete the following information):**
 - Library version 8.3.2

**Comment by Jasenkoo** [comment]
@aminebenaddi-centris Can't reproduce it anymore, try disabling `auto-position` if you are facing something unwanted.
