### ISSUE TITLE
v-model to accept ISO datetimes

### ISSUE THREAD

**Issue by IlyaSemenov** [Vuepic/vue-datepicker#804]
**Is your feature request related to a problem? Please describe.**
Typically, external APIs send and receive dates in ISO datetime format. I'm always frustrated that I need to add cumbersome watch/computed/type conversion boilerplate to convert between ISO datetime and the formats the date picker supports (native Date or timestamp or date-fns tokens).

**Describe the solution you'd like**
I'd like `model-type` to support new option: `iso`.

**Describe alternatives you've considered**
For dates (not date+time+timezone) I could use `model-type="yyyy-MM-dd"`. However, it doesn't seem possible to construct the full ISO8601 datetime string as `T` seems to be a reserved token in date-fns formatter that you're using. Also, this kind of manual format templating is prone to mistakes/typos.

**Comment by Jasenkoo** [comment]
The `ISO` string can be natively parsed with `new Date()`, meaning you just pass the date string as it is to the datepicker. When you move it from the `v-model` just use `.toISOString()`

**Comment by IlyaSemenov** [comment]
That's basically what I was referring to: boilerplate conversion.

Instead of doing:

```vue
<vue-date-picker v-model="fields.startTime" model-type="iso" />
```

one has to repeat this for each field:

```vue
<vue-date-picker
  :model-value="fields.startTime"
  @update:model-value="v => fields.startTime = v?.toISOString()"
/>
```

I'm not really following why timestamps have first class support and ISO time, arguably much more popular format, doesn't deserve one. 🤔

**Comment by Jasenkoo** [comment]
You are right, I'll add it, it is a minor thing to implement.
