### ISSUE TITLE
Is there a way to programmatically select dates in the picker, without changing the model value?

### ISSUE THREAD

**Issue by skstuder** [Vuepic/vue-datepicker#814]
I was hoping to use something similar to  `updateInternalModelValue` to update the picker values, but without changing the model value itself. 

We have an explicit button for selecting dates. So we need a way to update picker values, show the range, but not actually change the model value until they hit our select button that fires `selectDate()`

Here is our usecase for reference

We want to let them see what 52 weeks in the past looks like as a selection, without making the selection for them until the click 'select date` button.

 
![Screenshot 2024-04-08 at 9 20 13 AM](https://github.com/Vuepic/vue-datepicker/assets/55567604/5c233bb7-5415-4baa-9073-c1d53d5b8f74)

**Comment by Jasenkoo** [comment]
By calling [`updateInternalModelValue`](https://vue3datepicker.com/methods-and-events/methods/#updateinternalmodelvalue) it will just select dates internally in the picker, not the `v-model` bind.

**Comment by Jasenkoo** [comment]
@skstuder It is not in that format, as the internal model is only `Date` or `Date[]`, in this case, you pass the starting date from both weeks instead of double array.

**Comment by Jasenkoo** [comment]
Didn't try it, but it should work. If not, you'll need to use the first date in the week.
