### ISSUE TITLE
yearpicker with range not working

### ISSUE THREAD

**Issue by mak962753** [Vuepic/vue-datepicker#82]
Hello

tried to use yearpicker with range and it does not seem to work 
I tried to use a combination of these props 

      year-picker
      range
      multi-calendars
      
here is a demo 
https://stackblitz.com/edit/vuepic-vue-datepicker-skggrd?file=src%2Fcomponents%2FPlayground.vue

thanks

**Comment by Jasenkoo** [comment]
`range` is not supported with year picker.

**Comment by mak962753** [comment]
Ah.... I thought I was doing it wrong ... but thanks for the quick answer anyway
