### ISSUE TITLE
month-overlay-value not work with month-picker

### ISSUE THREAD

**Issue by EliaAlesiani** [Vuepic/vue-datepicker#821]
**Describe the bug**
Using month-overlay-value with month-picker mode, it's not working as expected.

**To Reproduce**
https://stackblitz.com/edit/vuepic-vue-datepicker-gkejiv?file=src%2Fcomponents%2FPlayground.vue

**Expected behavior**
custom value for every month

**Comment by brunolopesr** [comment]
While this behaviour would be very good, this is not a bug because the `month-overlay-value` is a slot available only in the date-picker mode.

I will look if it is possible to add some slots for the month-picker mode

**Comment by EliaAlesiani** [comment]
yes, thank you!

**Comment by brunolopesr** [comment]
PR #823 adds the slot needed for the `month-picker` mode.
