### ISSUE TITLE
Add an option to have the timepicker on the same page as the calendar

### ISSUE THREAD

**Issue by mark1502** [Vuepic/vue-datepicker#824]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, just that sometimes when entering a date and time, it's more visually obvious to have both pickers appear on the screen at the same time, so the user sees the date and time at once.  The component's current design is slick and works well when the flow setting is properly configured, but I'd love to have the option to have a unified date and time picker.

**Describe the solution you'd like**
Have a setting like 'unified-datetime-picker' which would be a boolean.  When set to true, the time picker would appear on the date picker, in place of the clock face icon.  In this mode, the component wouldn't switch between date and time because both are already on the screen.  The appearance of the time picker may need a slight modification , but all of the other functionality for both pickers would be the same as before.

**Describe alternatives you've considered**
I tried flatpickr, which has this type of interface.  But I prefer using vue-datepicker because it's a better component.

Thanks!

**Comment by laurens94** [comment]
You can use the `time-picker-inline` prop for that: https://vue3datepicker.com/props/time-picker-configuration/#time-picker-inline

**Comment by mark1502** [comment]
That's great, exactly what I was looking for!  Thank you!

**Comment by mark1502** [comment]
That's great, exactly what I was looking for!  Thanks!
