### ISSUE TITLE
Locale not working for :format='dd MMM yyyy'

### ISSUE THREAD

**Issue by PaulShef** [Vuepic/vue-datepicker#826]
Hello!
I have a problem with localization when using the format :format=‘dd MMM yyyy’ and :locale. Unfortunately, localization does not work properly. The name of the month in the input remains in English.
Please check the settings.
Thank you in advance for your attention and help!

**Comment by Jasenkoo** [comment]
@PaulShef You need to use [`format-locale`](https://vue3datepicker.com/props/localization/#format-locale) prop
