### ISSUE TITLE
On enabling timezone prop it shows only 1 week dates & hide all other dates its important issue kindly have a look

### ISSUE THREAD

**Issue by AwaisSikander** [Vuepic/vue-datepicker#832]
**Describe the bug**
On passing timezone  PROP designs beak Or Js break & only show  one row of dates

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot from 2024-04-15 15-38-31](https://github.com/Vuepic/vue-datepicker/assets/75409188/28ba4304-97e6-4fec-91e1-150a6da7aa7e)

![Screenshot from 2024-04-15 15-36-13](https://github.com/Vuepic/vue-datepicker/assets/75409188/ad8ffb44-20f5-410e-85ab-f33df177ba81)

**Desktop & mobile (please complete the following information):**

 - Library version [e.g. 3.0.0]

**Comment by AwaisSikander** [comment]
I just copied each & everything from the example code provided on website & It did not worked for me 

Below is dependencies list used in my project 


 "dependencies": {
    "@fullcalendar/core": "^6.1.8",
    "@fullcalendar/daygrid": "^6.1.8",
    "@fullcalendar/interaction": "^6.1.8",
    "@fullcalendar/timegrid": "^6.1.8",
    "@fullcalendar/vue3": "^6.1.8",
    "@pdftron/pdfjs-express": "^8.7.4",
    "@pdftron/pdfjs-express-utils": "^1.3.1",
    "@stripe/stripe-js": "^2.1.10",
    "@tinymce/tinymce-vue": "^5.1.0",
    "@vee-validate/rules": "^4.7.3",
    "@vuepic/vue-datepicker": "^5.4.0",
    "actioncable-vue": "^2.5.1",
    "axios": "^1.3.5",
    "chart.js": "^4.4.0",
    "compression": "^1.7.4",
    "date-fns": "^3.6.0",
    "express": "^4.18.2",
    "file-saver": "^2.0.5",
    "k-progress-v3": "^1.0.0",
    "libphonenumber-js": "^1.10.19",
    "lint-staged": "^13.1.0",
    "maska": "^2.1.8",
    "mitt": "^3.0.0",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.40",
    "pinia": "^2.0.28",
    "serve-static": "^1.15.0",
    "tiny-emitter": "^2.1.0",
    "tippy.js": "^6.3.7",
    "vee-validate": "^4.7.3",
    "videojs-record": "^4.7.0",
    "vite-plugin-imp": "^2.3.1",
    "vue": "^3.2.47",
    "vue-chartjs": "^5.2.0",
    "vue-country-flag-next": "^2.3.2",
    "vue-multiselect": "^3.0.0-beta.2",
    "vue-router": "^4.1.6",
    "vue3-circle-progress": "^1.0.7",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@pinia/testing": "^0.0.15",
    "@rushstack/eslint-patch": "^1.1.4",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vitejs/plugin-vue-jsx": "^3.0.0",
    "@vitest/ui": "^0.29.2",
    "@vue/eslint-config-prettier": "^7.0.0",
    "@vue/test-utils": "^2.2.6",
    "autoprefixer": "^10.4.13",
    "eslint": "^8.32.0",
    "eslint-plugin-vue": "^9.9.0",
    "husky": "^8.0.3",
    "jsdom": "^20.0.3",
    "postcss": "^8.4.21",
    "prettier": "^2.7.1",
    "sass": "^1.58.3",
    "tailwindcss": "^3.2.4",
    "vite": "^4.0.0",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-imagemin": "^0.6.1",
    "vitest": "^0.25.6"
  },

**Comment by Jasenkoo** [comment]
You are using a newer version prop for `timezone` that supports the `object` definition, however, you are on v5 which only supports the `string` format. For v5 specification, please refer to v5 [docs](https://v5.vue3datepicker.com/props/modes/#timezone)
