### ISSUE TITLE
The current month should be second but not the first month in the multi-calendar 

### ISSUE THREAD

**Issue by EugenGedroyc** [Vuepic/vue-datepicker#833]
**Is your feature request related to a problem? Please describe.**
I need to select days in the previous month in multi-calendar, because it has no any data after the current day. Therefore next month is disable always.
![image](https://github.com/Vuepic/vue-datepicker/assets/15181141/e44f71d3-d4f8-4fcd-99e9-ea61cd548aa3)

**Describe the solution you'd like**
Add prop that shifts the months in the multi-calendar:
![image](https://github.com/Vuepic/vue-datepicker/assets/15181141/213ef9dd-d443-48eb-b8ba-3972841f76d2)

**Comment by decoded-cipher** [comment]
Thanks to @EugenGedroyc for this issue.
Infact, right now I was surfing through the documentation to check if there was any other way to get this done.

**Comment by EugenGedroyc** [comment]
> to check if there was any other way to get this done.

I even asked various LLMs and the best answer was:
`:start-date="new Date(new Date().setMonth(new Date().getMonth() - 1))"`
But not work for me.

**Comment by decoded-cipher** [comment]
> > to check if there was any other way to get this done.
> 
> I even asked various LLMs and "the best answer" was: `:start-date="new Date(new Date().setMonth(new Date().getMonth() - 1))"` But not work for me.

Me too 🤣

**Comment by Jasenkoo** [comment]
Hello @EugenGedroyc @decoded-cipher , not sure why 

> I even asked various LLMs and "the best answer" was:
> `:start-date="new Date(new Date().setMonth(new Date().getMonth() - 1))"`
> But not work for me.

didn't work, however, here is the playground  [example](https://stackblitz.com/edit/vuepic-vue-datepicker-wxajtt?file=src%2Fcomponents%2FPlayground.vue) that achieves what you are trying to do.

**Comment by EugenGedroyc** [comment]
@Jasenkoo thanks for the good example, but [with range](https://stackblitz.com/edit/vuepic-vue-datepicker-wrkvyg) doesn't work

**Comment by Jasenkoo** [comment]
@EugenGedroyc This is because you are providing a `v-model` which is not empty, to force the start date you need [focus-start-date](https://vue3datepicker.com/props/calendar-configuration/#focus-start-date) prop enabled

**Comment by decoded-cipher** [comment]
Mine too... Thanks @EugenGedroyc
