### ISSUE TITLE
Make `preset-dates` a stand-alone feature

### ISSUE THREAD

**Issue by decoded-cipher** [Vuepic/vue-datepicker#834]
### Is your feature request related to a problem? Please describe.
- I was working on a project in which the date range picker with `multiple-calenders` - (2 calender format) is being used. The `preset-dates` are also used for better UX.
- The idea was to use the calendar as follows:
  - When we click on the trigger, the calendar module opens with only the `preset-dates` in view.
  - Only if we click on a particular option (eg: "**Custom Range**"), the calendar options would expand to the full format.

**Compressed Layout**

![image](https://github.com/Vuepic/vue-datepicker/assets/44474792/bb1d2d7c-dd17-4be6-8d77-ff76e5e341b8)

**Expanded Layout**

![image](https://github.com/Vuepic/vue-datepicker/assets/44474792/a5ac4269-9a23-4522-b754-0b167a0dcc80)

---

### Describe the solution you'd like
- A prop to set the visibility status of `preset-dates`
- A prop to set the position of `preset-dates` on the module, as their might be cases in which someone wants to position the `preset-dates` towards the right side of the module.
- A way to bind the same to any of the preset items, so that we could trigger by clicking on that.

**Comment by Jasenkoo** [comment]
This is more of a custom implementation which should not be part of the picker, as you can simply have an inline calendar and a wrapper that you will trigger when needed. It is a bit overhead to add this functionality.
