### ISSUE TITLE
prop to enable and disable `selection_preview`

### ISSUE THREAD

**Issue by decoded-cipher** [Vuepic/vue-datepicker#835]
**Is your feature request related to a problem? Please describe.**

It would be nice if there's a prop to enable and disable the `selection_preview` from the calendar. I'm not sure, whether there's an existing way to do this.

Note:
Anyway, fixed the issue by adding a `display: none;` to the `dp__selection_preview` class.

**Comment by Jasenkoo** [comment]
You can hide it in [`action-row`](https://vue3datepicker.com/props/general-configuration/#action-row) prop
