### ISSUE TITLE
Mask for editable input

### ISSUE THREAD

**Issue by RdebSono** [Vuepic/vue-datepicker#840]
**Is your feature request related to a problem? Please describe.**
For date of birth, it's easier to type the year or the whole date with the keyboard.
**Describe the solution you'd like**
I've enabled the text input for the control and it works well, but I would like the input to have a mask for the date, to be able to specify a v-mask attribute to the input directly.
**Describe alternatives you've considered**
I haven't found any yet. I tried the dp-input slot but it seems not to work with control input.
**Additional context**

**Comment by Jasenkoo** [comment]
This won't be worked on as it is basically a whole new library, you can either implement your own or find a package and use `dp-input` slots, and all methods are provided to parse date.
