### ISSUE TITLE
Multi selected with auto apply not working correctly. 

### ISSUE THREAD

**Issue by wasifsyed-driverup** [Vuepic/vue-datepicker#844]
**Describe the bug**
I'm trying to use auto-apply with multi-select but after selecting each date the calendar closes itself, which is a bit annoying.

**To Reproduce**
Top reproduce this issue you can use multi-select with autoApply.
**Expected behaviour**
We should be able to select as many as dates possible without the calendar closing by itself.

**Link for example**
https://stackblitz.com/edit/nrqa3f?file=src%2Fmain.js,src%2FApp.vue

**Desktop & mobile (please complete the following information):**
 - Browser [chrome]
 - any version

**Comment by Jasenkoo** [comment]
You can use `config.closeOnAutoApply: false` prop to prevent this. [Playground](https://stackblitz.com/edit/vuepic-vue-datepicker-3gfyn5?file=src%2Fcomponents%2FPlayground.vue)

**Comment by wasifsyed-driverup** [comment]
Thanks @Jasenkoo
