### ISSUE TITLE
AutoApply with range picker

### ISSUE THREAD

**Issue by axelkennedal** [Vuepic/vue-datepicker#845]
**Is your feature request related to a problem? Please describe.**
When using a range picker you can't use auto-apply, because then the date picker will close after you pick the first date. So you can't select a range. I want to have auto-apply to reduce the amount of required clicks.

**Describe the solution you'd like**
When using auto-apply with a range picker the calendar should close automatically after the user selects two dates, instead of one. And the action-buttons should be displayed, so that the user may choose to just select one date and then click "confirm".

**Describe alternatives you've considered**
The only alternative now is to not use auto-apply.

**Additional context**
-

**Comment by Jasenkoo** [comment]
It does work, you can verify on the [playground](https://stackblitz.com/edit/vuepic-vue-datepicker-zcdfgj?file=src%2Fcomponents%2FPlayground.vue)
