### ISSUE TITLE
Sync the value when selected with the input field 

### ISSUE THREAD

**Issue by nguyenquocdaile** [Vuepic/vue-datepicker#846]
Hi there, Thanks for the awesome library ❤️ 

I have a question here. How can I sync the value when selected with the input field?
( The value of input will change when I press the apply button. You can see the example below )

https://github.com/Vuepic/vue-datepicker/assets/12345613/a460edc2-c294-41ff-ad3d-250514ea99a4

**Comment by nguyenquocdaile** [comment]
> Hello, you can use the `auto-apply` prop.

Hmm. with `auto-apply` props. We just hide the apply button here. 
I just want to when select a day. The value of input will change. But the apply button still shows here.

**Comment by Jasenkoo** [comment]
You need to provide `config.keepActionRow` prop in that case

**Comment by nguyenquocdaile** [comment]
The apply button shows, but the value of the input field doesn't change. You can take a look at my record. 
Like when I select day 6. the input will change to day six, too. 

https://github.com/Vuepic/vue-datepicker/assets/12345613/f31b8a2a-a4e0-4b2e-b144-69926543a825
