### ISSUE TITLE
Today should be highlighted even when you choose to go back a month

### ISSUE THREAD

**Issue by ahazelwood** [Vuepic/vue-datepicker#850]
**Is your feature request related to a problem? Please describe.**
When the menu is popped open in range mode, today's date is highlighted correctly with a border.  Once you go back to the previous month, today's date (even if it is visible) is no longer highlighted.

**Describe the solution you'd like**
today's date should continue to keep the class dp__today always so it can be highlighted (or offer an option) if not being overridden.

**Describe alternatives you've considered**
None yet, just beginning to look at the control.

**Additional context**
View the first sample at:  https://vue3datepicker.com/props/modes-configuration/   Today's date is May 2nd, so if you go back to April, May 2 is no longer highlighted.

Thanks.

**Comment by Jasenkoo** [comment]
Today is as the name says for today, if you want to mark this date with a separate class, there's an option to add classes on specific dates.
