### ISSUE TITLE
Emitted value wrong on UTC+2 if range's initial value is from 2 different months and timezone observes DST

### ISSUE THREAD

**Issue by jfpromoter** [Vuepic/vue-datepicker#853]
**Describe the bug**
Emitted value is wrong if the range's initial value is from 2 different months and timezone observes DST (I guess?). I made a reproduction case [here](https://codesandbox.io/p/sandbox/young-paper-t8826c?file=%2Fsrc%2Fdate-utils.ts%3A5%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvkspx0r00063b6ih4g8rkbm%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvkspx0r00023b6itszcazua%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvkspx0r00033b6ij2vukw8t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvkspx0r00053b6icj508p0e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvkspx0r00023b6itszcazua%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkspx0r00013b6iqcag84s6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvktrcc100413b6i9dwqzrv0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvku2v6u00023b6i8trlmbg2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522endLineNumber%2522%253A11%252C%2522startColumn%2522%253A17%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fdate-utils.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvkspx0r00023b6itszcazua%2522%252C%2522activeTabId%2522%253A%2522clvku2v6u00023b6i8trlmbg2%2522%257D%252C%2522clvkspx0r00053b6icj508p0e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkspx0r00043b6i5c3xefrc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvkspx0r00053b6icj508p0e%2522%252C%2522activeTabId%2522%253A%2522clvkspx0r00043b6i5c3xefrc%2522%257D%252C%2522clvkspx0r00033b6ij2vukw8t%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvkspx0r00033b6ij2vukw8t%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**To Reproduce**

Use this [link](https://codesandbox.io/p/sandbox/young-paper-t8826c?file=%2Fsrc%2Fdate-utils.ts%3A5%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvkspx0r00063b6ih4g8rkbm%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvkspx0r00023b6itszcazua%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvkspx0r00033b6ij2vukw8t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvkspx0r00053b6icj508p0e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvkspx0r00023b6itszcazua%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkspx0r00013b6iqcag84s6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvktrcc100413b6i9dwqzrv0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvku2v6u00023b6i8trlmbg2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522endLineNumber%2522%253A11%252C%2522startColumn%2522%253A17%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fdate-utils.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvkspx0r00023b6itszcazua%2522%252C%2522activeTabId%2522%253A%2522clvku2v6u00023b6i8trlmbg2%2522%257D%252C%2522clvkspx0r00053b6icj508p0e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkspx0r00043b6i5c3xefrc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvkspx0r00053b6icj508p0e%2522%252C%2522activeTabId%2522%253A%2522clvkspx0r00043b6i5c3xefrc%2522%257D%252C%2522clvkspx0r00033b6ij2vukw8t%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvkspx0r00033b6ij2vukw8t%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. Change your timezone to UTC+2, in my case I tested it with `Warsaw - Poland`
2. Notice that the initial `model`'s value is from March to April
3. Select dates April 8 to April 14
4. The starting date in the model is `2024-04-07T23:00:00.000Z` but the displayed date is `04/08/2024`

<img width="611" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/168815098/cbd4aff5-2505-45b8-9412-2ee2dec571c6">

It works correctly if the initial value is from the same month, i tested it with `const model = ref(["2024-04-23", "2024-04-29"]);`. I did the same steps above and this is what I got.

<img width="611" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/168815098/d9a9fbe4-7c1c-4520-8479-850acea44970">

**Expected behavior**
It should emit the correct start date.

**Desktop & mobile (please complete the following information):**
 - Browser - Chrome 124.0.6367.91
 - Library version 8.5.1

**Comment by spintokha** [comment]
Same issue.

**Comment by spintokha** [comment]
> Same issue here, anyone got fix?

Works in my case using converting:

`dateRange[0].toLocaleDateString('en-US', {
  month: '2-digit',
  day: '2-digit',
  year: 'numeric'
})`

**Comment by Jasenkoo** [comment]
I am not sure what you are trying to achieve exactly, but I would suggest using the `timezone` prop if you need to keep a specific date across the time zones. The example you are showing is not quite correct because when you print the date in the `<template>`, it is converted to an iso string.

Given that our date object looks something like this:

```
Mon Apr 08 2024 01:00:00 GMT+0200
```

When you add `toISOString()` , that same object will be represented as

```
'2024-04-07T23:00:00.000Z'
```

Furthermore, the dates you specified are covering  daylight savings change, where parsing the `2024-03-23` gives 
```
Sat Mar 23 2024 01:00:00 GMT+0100 (Central European Standard Time)
```
and parsing `2024-04-29` gives

```
Mon Apr 29 2024 02:00:00 GMT+0200 (Central European Summer Time)
```

But changing the range from march to April parses both dates in `Central European Summer Time`, therefore the result is expected.
