### ISSUE TITLE
Add hold option for timepicker mode

### ISSUE THREAD

**Issue by 0SilentFox0** [Vuepic/vue-datepicker#855]
When time-picker mode enabled - it is an option to choose time from additional menu by clicking on time number
I think it will be also nice to have an option just hold mouse on arrow for updating time

**Comment by 0SilentFox0** [comment]
@Jasenkoo any updates? I see that issue is closed but as i get - it is not realized yet

**Comment by Jasenkoo** [comment]
@0SilentFox0 It is added, you need to enable it via  `config.timeArrowHoldThreshold`
