### ISSUE TITLE
Unexpected token '=' at Safari

### ISSUE THREAD

**Issue by AndreiDishlenko** [Vuepic/vue-datepicker#859]
I have found bug since 8.3.0 version of @vuepic/vue-datepicker. 

When i connect datepicker
...
import VueDatePicker from '@vuepic/vue-datepicker';
...

i've got error "Unexpected token '='. Expected an opening '(' before a method's parameter list."

Error is found in function:
class Setter {
  subPriority = 0;  <-------- Here

  validate(_utcDate, _options) {
    return true;
  }
}

This error occurs at Safari 13.1.2 (13609.3.5.1.5) at MacBook.
Chrome works normaly.

**Comment by AndreiDishlenko** [comment]
Sorry, test again. 
This error appears from v.8.0. 
On v.7.4.1 there is no problem

**Comment by Jasenkoo** [comment]
It appears as a Safari problem, you can inspect the code and try adding needed `polyfill`

Safari 17.* looks ok


https://github.com/Vuepic/vue-datepicker/assets/23171105/9715718e-ce2e-44bb-abfb-792e7e2faeb8
