### ISSUE TITLE
Month picker issue in combination with "prevent-min-max-navigation" and max and min date

### ISSUE THREAD

**Issue by NicoHof** [Vuepic/vue-datepicker#861]
**Describe the bug**

_This may be two different bugs but can be both seen in the repro example_

- Arrow back is not disabled. It should be since I cannot select something from 2022
- I cannot select "May 2023". The entry is not in "disabled state" - User can click it but not "select" it

**Steps to reproduce the behavior:**

https://codesandbox.io/p/sandbox/vue3-datepicker-monthpicker-issue-forked-s8dy7v?file=%2Fsrc%2FApp.vue

1. Open picker
2. Use "Year back button" - Can come to year 2022. But should not be, right?
3. Try to click (works) and then select (does not work) "May 2023"

**Expected behavior**
- No back button enabled
- Can select May **OR** disable May in calendar (prefer selectable, since minDate is 20. Apr. 2023, so May 2023 should be selectable)

**Hint**
The not disabled arrow button also happens if you change the start year in this example to 2024.
Then you can go to 2025! (2022 disabled then though)

**Desktop & mobile (please complete the following information):**
 - Library version: 8.5.0

**Comment by Jasenkoo** [comment]
Looks like the issue is only present if `v-model` is provided
