### ISSUE TITLE
New #top-extra covered by month selection

### ISSUE THREAD

**Issue by skstuder** [Vuepic/vue-datepicker#862]
Noticed the calendar is covering #top-extra when a month is selected. When the top-extra is large it feels a bit odd, can it be made to only cover the calendar?
![Screenshot 2024-05-10 at 11 38 35 AM](https://github.com/Vuepic/vue-datepicker/assets/55567604/a2e07754-310a-4ce7-84b9-2ef9531c9a52)

![Screenshot 2024-05-10 at 11 36 45 AM](https://github.com/Vuepic/vue-datepicker/assets/55567604/efe9f7eb-a513-42c2-b15d-64ced89ad0ce)

**Comment by Jasenkoo** [comment]
@skstuder It adds so much boilerplate code to calculate the proper height on various modes, alongside the time picker overlay.

On your end it will be easier if you know which mode you are using and what is the height, then simply override the class with the proper `top` offset.
