### ISSUE TITLE
I using NuxtJs V3 I want to customer Date Range Picker

### ISSUE THREAD

**Issue by mayutheandev** [Vuepic/vue-datepicker#870]
The link below is an example, I want to custom like this. How can we do this in NuxtJs V3?
https://www.daterangepicker.com/#example4
![68747470733a2f2f692e696d6775722e636f6d2f5554526c6161722e706e67](https://github.com/Vuepic/vue-datepicker/assets/66521798/af492eac-3381-4547-a64f-6e20c57cdc43)

**Comment by Jasenkoo** [comment]
This look is achievable by passing `multi-calendars` and `preset-dates` props
