### ISSUE TITLE
Just view Time Picker solo, without date picker

### ISSUE THREAD

**Issue by alexanderkraemer** [Vuepic/vue-datepicker#871]
**Is your feature request related to a problem? Please describe.**
The Datepicker and Timepicker look great! It would be even better, if the timepicker could be shown withouth the datepicker.
I couldn't find anything in the documentation about that.

**Describe the solution you'd like**
Hide the date-selection and just let the user pick a time. The output format could then be just the configured format. hh:mm or hh:mm:ss

**Describe alternatives you've considered**
using a different one.

**Additional context**

**Comment by Jasenkoo** [comment]
Just pass [`time-picker`](https://vue3datepicker.com/props/modes/#time-picker) prop
