### ISSUE TITLE
dp-input slot is not change modelValue of date-picker

### ISSUE THREAD

**Issue by OguzhanAgca** [Vuepic/vue-datepicker#873]
**Describe the bug**
Hello, when we use custom input using slot (`#dp-input`), datepicker's modelValue is not updated. Whether the input used is native or custom input, it does not work very well.

I looked through the documentation a lot, but I couldn't find anything regarding this situation. If this is really a bug, I am sharing screenshots below.

Also, I'm not sure, but this problem seems to be present in the example in the documentation. [Dp-Input](https://vue3datepicker.com/slots/trigger-and-input/#dp-input)

**To Reproduce**
1. Create a datepicker component. Like:
```html
<VDatePicker
  v-model="model"
  v-bind="$attrs"
  auto-apply
  :min-date="minDate"
  :max-date="maxDate"
  :inline="isPartial"
  :range="isRange"
  :text-input="textInput"
  calendar-cell-class-name="date-picker-cell"
  calendar-class-name="date-picker-calendar"
  :enable-time-picker="withTime"
>
  <template v-if="textInput" #dp-input="{ value, onInput }">
    <input
      :value="value"
      :placeholder="$attrs.placeholder"
      class="mt-1"
      @input="onInput"
    />
  </template>
</VDatePicker>
```
2. When I use this component and give `textInput=true` and `format='yyyy-MM-dd'`, it creates a custom input.
3. Select a date from the dialog that opens when we click on Input.
4. Click on Input again and just make a small change to the date with the keyboard.
5. Just click on an area outside of input.
6. See the error. (The date you selected from the dialogue appeared again.)

**Expected behavior**
When we make a change to the custom input, the modelValue in the datepicker should be updated.

**Screenshots**
[Screencast from 17-05-2024 13:52:19.webm](https://github.com/Vuepic/vue-datepicker/assets/82233025/3ca0054b-0f3a-4a58-93aa-47dcbed8e47f)

**Desktop**
 - Browser: Chrome
 - Library version: 8.6.0

**Comment by Jasenkoo** [comment]
The issue here is that the `onFocus` method is not exposed when a new version is published, you would need to connect both the `onFocus` and `onBlur` input events to be able to parse the date with `auto-apply`. 

I should probably make docs a bit clearer :)

**Comment by OguzhanAgca** [comment]
> The issue here is that the `onFocus` method is not exposed when a new version is published, you would need to connect both the `onFocus` and `onBlur` input events to be able to parse the date with `auto-apply`.
> 
> I should probably make docs a bit clearer :)

Thank you for your interest, I will try it when the new version is released. :)

**Comment by Bowske** [comment]
> The issue here is that the `onFocus` method is not exposed when a new version is published, you would need to connect both the `onFocus` and `onBlur` input events to be able to parse the date with `auto-apply`.
> 
> I should probably make docs a bit clearer :)

By "connecting" you mean just using `#dp-input="{ value, onInput, onBlur, onFocus }"` and then simply 
```
@input="onInput"
@focus="onFocus"
@blur="onBlur"
```

Damn, that would be great to have 👍

**Comment by Jasenkoo** [comment]
@Bowske Yes, that is correct
