### ISSUE TITLE
Month Picker should not have a highlighted month for other years

### ISSUE THREAD

**Issue by fanckush** [Vuepic/vue-datepicker#876]
**Describe the bug**
The current month should not be highlighted if it's part of another year

**To Reproduce**
1. use the flow `flow="['year', 'month', 'calendar']`"
2. click the input -> select a year other than the current year (example: 2019)
3. next, you'll see the month picker
4. notice how May (or the current month) is highlighted 

**Expected behavior**
the month picker should not highlight any month of the selected year from the previous year is not the current year

**Screenshots**
video: 

https://github.com/Vuepic/vue-datepicker/assets/6278713/f744e8b9-d74e-4b58-b9ed-419f813a1fcf

**Desktop & mobile (please complete the following information):**
safari, chrome

 - Library version 8.6.0

**Comment by Jasenkoo** [comment]
Expected behavior, these selections are not related to the model-value itself, they show what is currently in the calendar.

**Comment by fanckush** [comment]
> they show what is currently in the calendar

what do you mean by "currently in the calendar"
