### ISSUE TITLE
Inline time picker icon customization

### ISSUE THREAD

**Issue by csabakiss-us** [Vuepic/vue-datepicker#884]
**Is your feature request related to a problem? Please describe.**
It would be really nice if we could use a custom icon for the inline time picker here:
https://github.com/Vuepic/vue-datepicker/blob/1bfd6625ba0e3b85c2e73148934727da817f94e7/src/VueDatePicker/components/TimePicker/TimeInput.vue#L89C60-L89C75

**Describe the solution you'd like**
You have already implemented the custom-icon slot for the overlay time picker, A similar solution would be nice for the inline version.

**Describe alternatives you've considered**

**Additional context**

**Comment by csakis** [comment]
You're awesome, dude! Thank you!
