### ISSUE TITLE
Enable inline vertical scroll

### ISSUE THREAD

**Issue by cwist2** [Vuepic/vue-datepicker#885]
On mobile, it would be great to have a vertical scrolling calendar, similar to the Calendar app on iOS/Android. I want to add months as I scroll down to the bottom. I've tried many approaches to get this to work, but I consistently encounter issues when dynamically changing the `count` of `MultiCalendarsOptions`.

Here is a sample of the current behavior:
https://stackblitz.com/edit/vuepic-vue-datepicker-nqzywp?file=src%2Fcomponents%2FPlayground.vue,src%2FApp.vue

As you can see on the [Stackblitz](https://stackblitz.com/edit/vuepic-vue-datepicker-nqzywp?file=src%2Fcomponents%2FPlayground.vue,src%2FApp.vue), each added month is displayed as "January 0".

**Describe the solution you'd like**
The solution would be to allow changing the `count` of `MultiCalendarsOptions`.

**Describe alternatives you've considered**
I found that calling `datepickerRef.value.setMonthYear({})` (where `datepickerRef` is the `ref` of the `Datepicker` component) after incrementing the `count` of `MultiCalendarsOptions` works, but only if the `modelValue` of the `Datepicker` component is not defined.

_Tested on vue-datepicker v8.7.0_

**Comment by simbacod3** [comment]
+1 for this feature, it would be great, encountered the same issue recently, it is quite blocking our development as we really wanna use this lib.
