### ISSUE TITLE
closeOnScroll no work

### ISSUE THREAD

**Issue by luckyover3** [Vuepic/vue-datepicker#887]
I want to scroll then close the menu but it doesn't work, I try removing v-model="date" then closeOnScroll works
![ảnh](https://github.com/Vuepic/vue-datepicker/assets/73824704/9e5018c5-5cf6-49f6-825e-deb10647a700)

**Comment by Jasenkoo** [comment]
It does work, [playground](https://stackblitz.com/edit/vuepic-vue-datepicker-assdap?file=src%2Fcomponents%2FPlayground.vue). There is a special case where it might not work as expected, is if you have a parent scroll, as the listener is attached to the window object. In that case, you would have to handle the scroll manually.
