### ISSUE TITLE
DisabledWeekDays mode does not exclude Weekend days

### ISSUE THREAD

**Issue by kentbong** [Vuepic/vue-datepicker#89]
**Describe the bug**
DisabledWeekDays mode does not exclude Weekend days under Range and maxRange mode.

**Expected behavior**
Weekend day shall not be included in range selection, with maxRange mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/6791270/179183639-56bd502d-c419-482f-9a47-cfd01841e6a3.png)
![image](https://user-images.githubusercontent.com/6791270/179183713-6bc363f0-c476-44bd-9049-b15d6135a5ef.png)

**Comment by Jasenkoo** [comment]
What would be the desired result here, since the range needs to have a start and end date? The only solution I can think of is to prevent range if it overlaps with a disabled date.

**Comment by kentbong** [comment]
The desired result here should be, when on "range" and "maxRange" mode, the range selection/count shall exclude the disabled dates? 

Example: 
![image](https://user-images.githubusercontent.com/6791270/179433039-db5cdfdb-6e90-4a37-a521-5183605edfb3.png)
maxRange set to 5 days, and weekend is disabled dates, when range start at 22nd July, the range shall end at 1st August instead of 28th July.

The focus here is more to maxRange count, that exclude the disabled dates if possible? 

Thanks.

**Comment by kentbong** [comment]
Hi there, noticed the fixes has been committed. Would like to know when will be the main release ya? 

Thanks.
