### ISSUE TITLE
text-input with month-picker, year-picker, time-picker

### ISSUE THREAD

**Issue by luckyover** [Vuepic/vue-datepicker#891]
I use text-input with month-picker, year-picker, time-picker, desired when calendar opens and change input, desired in calendar is also updated and displayed accordingly.
<img width="631" alt="time" src="https://github.com/Vuepic/vue-datepicker/assets/103552257/72c16849-dd91-4ccf-984d-bb650f58e19a">
<img width="643" alt="year" src="https://github.com/Vuepic/vue-datepicker/assets/103552257/3450485a-9205-4f26-bcd4-cf6ee1c0c2d1">
<img width="689" alt="MONTH" src="https://github.com/Vuepic/vue-datepicker/assets/103552257/76532671-52a3-41f5-9d58-953c94bf0bb7">

**Comment by Jasenkoo** [comment]
@luckyover You don't have to post from another account, as mentioned in the previous issue, everything works ok, please take a look at the docs when connecting the custom text input to the calendar.
