### ISSUE TITLE
Datepicker show wrong date when having timezone

### ISSUE THREAD

**Issue by mjnamjkaze** [Vuepic/vue-datepicker#892]
**Describe the bug**
The date picker jump to another date when I input manually them press Enter key

**To Reproduce**
Steps to reproduce the behaviour:
1. Input 01/28/1988
2. Click on input
3. Press enter
4. It shows 01/26/1988

**Expected behaviour**
It shows 01/28/1988 when I press Enter key

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/15181511/81f4cf33-ed09-4d40-ab00-b9500b15bdd8)

Link stackblitz
https://stackblitz.com/edit/vuepic-vue-datepicker-fszavi?file=src%2Fcomponents%2FPlayground.vue

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by Jasenkoo** [comment]
The example you provided works as expected.
