### ISSUE TITLE
Time picker not update when change from text-input

### ISSUE THREAD

**Issue by leonardospeca** [Vuepic/vue-datepicker#893]
Using the following options:
```
<Datepicker v-model="date" time-picker text-input auto-apply />
```
So `time-picker` , `text-input` and `auto-apply` you can notice that if you change the time from the picker, the input change, but if you change the input, the picker not update. It works correctly with the date and date&time version

Simplified not working example: https://stackblitz.com/edit/vuepic-vue-datepicker-5gkuyw?file=src%2Fcomponents%2FPlayground.vue
Advanced not working example: https://stackblitz.com/edit/vuepic-vue-datepicker-4re8s3?file=src%2Fcomponents%2FPlayground.vue
Video: 
https://github.com/Vuepic/vue-datepicker/assets/26072174/f7225a2e-e62e-42eb-a188-ab612227e371

**Comment by felipe-lima-gupy** [comment]
I have a issue similar to this https://github.com/Vuepic/vue-datepicker/issues/894

When we use the multi-calendars prop, the calendar is no longer reactive

**Comment by Tsuyoshi12** [comment]
I am also having this problem in **month-picker** and **year-picker** too

**Comment by leonardospeca** [comment]
How to use the patched version until the next release?
