### ISSUE TITLE
Changing `count` in `multi-calendars` adding calendar with wrong data

### ISSUE THREAD

**Issue by Ky6uk** [Vuepic/vue-datepicker#895]
**Describe the bug**
The calendar displays the wrong data when the `count` for the `multi-calendars` property is changed.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [stackblitz.com](https://stackblitz.com/edit/vue-datepicker-multi-calendars-bug?file=src%2Fcomponents%2FPlayground.vue)
2. Click on "Add calendar"
4. See wrong data in the added calendar

**Expected behaviour**
The newly added calendar is extending the existing calendars.

**Screenshots**
<img width="278" alt="Screenshot 2024-06-06 at 15 58 30" src="https://github.com/Vuepic/vue-datepicker/assets/46930/0449b2fc-b24b-46c0-bea8-559f710d043d">

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome 125.
 - Library version: `^8.7.0`

**Comment by Jasenkoo** [comment]
Added in #885. Will be included in the next release
