### ISSUE TITLE
Documentation doesn't reflect accurate example at Methods page

### ISSUE THREAD

**Issue by Ashlayyy** [Vuepic/vue-datepicker#896]
At the Methods page in the documentation there is a inaccurate representation of the implementation.

I have attached a screenshot, the part where it isn't correct is  ref<DatePickerInstance>(null), if you define this as null it never will be anything besides null.

Unfortunately I am not that gifted in programming that I know what's wrong with it, but hopefully someone can figure out what should be changed :)

![image](https://github.com/Vuepic/vue-datepicker/assets/105703068/1ff28283-9d37-4104-8f7a-2872b2c50ad2)

**Comment by Jasenkoo** [comment]
Nothing wrong with the example. It's working as expected. You can see it in this simple [example](https://stackblitz.com/edit/vuepic-vue-datepicker-ldvgeq?file=src%2Fcomponents%2FPlayground.vue).

If your `ref` is never updated, there could be a mismatch in the variable name and what you set in `ref=""`.

You can always get more info in the [documentation](https://vuejs.org/guide/essentials/template-refs)
