### ISSUE TITLE
Cannot select time without choose the date first

### ISSUE THREAD

**Issue by faizaaulia** [Vuepic/vue-datepicker#897]
**Describe the bug**
The time cannot be selected it the user doesn't choose the date first

**To Reproduce**
1. Go to 'Stackblitz playground](https://stackblitz.com/edit/vuepic-vue-datepicker?file=src%2Fcomponents%2FPlayground.vue)
2. Click the datepicker
3. Click time overlay -> time picker menu opened
4. Click select
5. Unable to select time

**Expected behavior**
User is able to select the time without choose the date first, when the time is selected, the date value will be auto assign to today date

**Screenshots**
Notice that in this picture, user has select a date then then user will be able to select the time
![image](https://github.com/Vuepic/vue-datepicker/assets/21327758/b4d1c2a9-37dd-4dac-b864-1b834ebdebe8)
When the date is not selected yet, the time is not able to be selected
![image](https://github.com/Vuepic/vue-datepicker/assets/21327758/61c3c2be-7ec7-4c16-b8b5-b1e249aa1052)

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by Jasenkoo** [comment]
Expected behaviour, won't be actioned. Alternating this will cause random behavior in the validation logic. You can simply provide a default date if needed.
