### ISSUE TITLE
Docs/Example for input validation

### ISSUE THREAD

**Issue by oneringtorulethemall** [Vuepic/vue-datepicker#899]
Hello,

I apologize if I'm doing this incorrectly. I've been trying to figure out how to do validation on the vue-datepicker when user enters values using keyboard. I've tried the dp-input approach to no avail.
Do you have any additional documentation on how to validate the date.
I am allowing users to enter a date (and the vue-datepicker honors that if I enter a valid date)
If I have [ 2024/05/12 14:15 PM] in the text input field, set focus on the month portion and enter '99'...
and press enter, the last valid date is used and my form is submitted. 
Thanks for your time!

**Comment by Jasenkoo** [comment]
You can access the `value` property which displays the `text-input` value. In the next release, there will be an event capturing input text.
