### ISSUE TITLE
iOS selecting dates with markers + label

### ISSUE THREAD

**Issue by jose-seabra** [Vuepic/vue-datepicker#904]
**Describe the bug**
On iOS, selecting dates with markers + label toggles the tooltip without selecting the date. The behavior on android is to toggle the tooltip **and** selects the date.

**To Reproduce**
1. Use an iOS device or emulator
2. Go to this demo https://stackblitz.com/edit/vitejs-vite-qtgtb9 or serve it's example code to your device/emulator
3. Click on a date with a marker
4. See how the first click only opens the tooltip and a second click is required in order to select the date

**Expected behavior**
I would expect iOS to have the same behavior as android, because as it is right now you need to click twice on a date in order to select it.

**Screenshots**
Clicking once:
![image](https://github.com/Vuepic/vue-datepicker/assets/55154249/0ffffb1c-94b9-454d-8750-4855a8f53b19)

Clicking twice:
![image](https://github.com/Vuepic/vue-datepicker/assets/55154249/b3941153-f8d2-4678-99cf-41fb32973abf)

**Desktop & mobile (please complete the following information):**
 - iPhone 13 v16.3, Safari
 - Library version 8.8.0

I've played around with possible solutions and if we change the `@click` event for a `@touchend` event it behaves just as my expectation.
`<div v-if="dayVal.marker?.tooltip" class="dp__tooltip_content" @click="onTpClick">`
`<div v-if="dayVal.marker?.tooltip" class="dp__tooltip_content" @touchend="onTpClick">`
src/VueDatePicker/components/DatePicker/DpCalendar.vue:94

I'm not knowledgeable enough to understand if such change would break other expected behaviors, but it appears to make it work the same on iOS/android/desktop

**Comment by jose-seabra** [comment]
Should this be handled with the `allowPreventDefault` config? It makes it so it doesn't require two clicks to select the date but the tooltip won't trigger

**Comment by perruche** [comment]
Having the same issue.

**Comment by leeyongeun9** [comment]
This happened again in the latest version 12.0.1
