### ISSUE TITLE
How could we separate the start and end range into 2 inputs?

### ISSUE THREAD

**Issue by fagnerpelicioni** [Vuepic/vue-datepicker#91]
![image](https://user-images.githubusercontent.com/26371670/179618304-5419c61b-8cc9-495b-9551-4b6c013c9caa.png)

I tried to separate the template with 2 inputs, but I couldn't. It is possible? Do you have any suggestions? I didn't find anything in the documentation

**Comment by Jasenkoo** [comment]
Use both inputs as a single picker, if you want to make the second date after the first, pass value from the first `v-model` to the second as a `min-date`
