### ISSUE TITLE
Range fixedStart or fixedEnd doesn't disable time picker

### ISSUE THREAD

**Issue by vukadinFE** [Vuepic/vue-datepicker#910]
**Describe the bug**
Using `fixedStart` on the range picker still enables pick-up time. The same is true for `fixedEnd`.

**To Reproduce**
1. `<VueDatePicker :range="{ fixedStart: DATE }" time-picker-inline  />`
2. Open picker

**Expected behavior**
The time picker for the start date should be disabled

**Screenshots**
<img width="271" alt="image" src="https://github.com/Vuepic/vue-datepicker/assets/38419355/127fedad-6d47-48cc-9d9a-77f7c552b12b">

**Desktop & mobile (please complete the following information):**
 - Browser chrome
 - Library version 8.8.0

**Comment by Jasenkoo** [comment]
You are not setting `fixedStart` properly, you need to pass `boolean` and then in `v-model` to set a desired date, either first or second
