### ISSUE TITLE
calendar icon show only

### ISSUE THREAD

**Issue by Thuytran79** [Vuepic/vue-datepicker#915]
I want to show calendar icon only. 
not show Input field.
Can you guide me?

**Comment by lupus78** [comment]
You can use custom input or trigger element, see: https://vue3datepicker.com/slots/trigger-and-input/

In one of my projects I had to show the calendar in my own custom overlay, so I uses the `inline` option, see: https://vue3datepicker.com/props/modes/#inline

**Comment by Jasenkoo** [comment]
As @lupus78 said. Closing.
