### ISSUE TITLE
ui input style width

### ISSUE THREAD

**Issue by Thuytran79** [Vuepic/vue-datepicker#916]
I can't fix input width.
I try to used input-class-name to the width fit content but it's not working.

`<VueDatePicker
        v-model="monthModeValue"
        position="center"
        locale="ja"
        format="yyyy年MM月"
        auto-apply
        :clearable="false"
        :enable-time-picker="false"
        @update:modelValue="emitSelectedDate"
        input-class-name="dp-custom-input"
        month-picker/>`

`.dp-custom-input {
    border: none;
    width: 150px;
    min-width: fit-content;
    font-size: larger;
    font-weight: bold;
    &:focus {
      outline: none;
      border: none;
      box-shadow: none;
    }
  }`

![image](https://github.com/Vuepic/vue-datepicker/assets/86605918/d6f5de0a-5b2d-4178-9b8c-9640fedb74fc)

**Comment by Jasenkoo** [comment]
You can just target the class directly, or use a slot input.

The `input-class-name` prop is deprecated.
