### ISSUE TITLE
The datepicker breaks with v8.8.0

### ISSUE THREAD

**Issue by nanu-c** [Vuepic/vue-datepicker#917]
**Describe the bug**
If you click the datepicker field it doesn't open. No output to the terminal
**To Reproduce**
* use 8.8.0
* make a simple datepicker with or without any arguments.

**Expected behavior**
the picker opens.

**Screenshots**

**Desktop & mobile (please complete the following information):**
- Firefox 127/ubuntu
- "vue": "^3.4.29" and typescript "~5.4.5"

**Comment by Jasenkoo** [comment]
Please provide an actual example of this behavior.
