### ISSUE TITLE
Add an option for a max number of selected dates

### ISSUE THREAD

**Issue by Eworm** [Vuepic/vue-datepicker#92]
I'm working on software where the amount of dates a user can select has a max. Maybe you could add a prop for this, if a user wants to select more than the max amount he/she should deselect a date before adding another one. The max dates/chosen dates should be visible in the datepicker so a user understands what's happening.

**Comment by Jasenkoo** [comment]
You can use [`multi-dates`](https://vue3datepicker.com/api/props/#multidates) prop with the [`multi-dates-limit`](https://vue3datepicker.com/api/props/#multidateslimit) prop. It is up to you how to handle UX.
