### ISSUE TITLE
v-model and 'date' props in slot #day is not same format

### ISSUE THREAD

**Issue by aqordeon** [Vuepic/vue-datepicker#924]
**Describe the bug**
in v-model I got the value: `2024-06-29T00:00:00.000000Z`
in 'date' props in slot #day I got the value: `2024-06-28T16:00:00.000Z`  (I assume the wrong return is in this part)

**Expected behavior**
Should return the same value, so it easier to compared that

**Desktop & mobile (please complete the following information):**
 - Browser: Firefox
 - Library version: 8.7.0

**The code:**
```
<DatePicker
    v-model="datexxx"
    inline auto-apply
    :disabled-dates="disableBeforeToday"
    :enable-time-picker="false"
>
    <template #day="{ day, date }">
        {{ date == datexxx }}
    </template>
</DatePicker>
```

**Comment by Jasenkoo** [comment]
This is intended behaviour, the dates in the calendar have time reset values
