### ISSUE TITLE
@update-month-year Event Not Triggering When Selecting a Day in the Previous or Next Month

### ISSUE THREAD

**Issue by RLans** [Vuepic/vue-datepicker#925]
**Description**
I'm encountering issues with the calendar functionality in vue-datepicker. The problem is that the @update-month-year event is not being triggered when selecting a day that falls in the previous or next month. However, @update-month-year does get triggered when using the arrow buttons at the top to navigate through the months.

**Steps to reproduce the behavior:**
1. Open a modal containing the datepicker configured to use the @update-month-year event and include a console.log to track the event.
2. Select a day that falls in either the next or the previous month, without using the arrow buttons to navigate between months.
3. Check the console to verify if the logging occurs (observe that no logging is found).

**Expected behavior**
I expect the @update-month-year event to be triggered when I click on a day that falls in either the previous or the next month

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/11278937/1a55b832-b8d4-4943-ada0-7597c665c886)
Started on the 25th(current day), clicked on the 2nd(different month). _Arrows do trigger @update-month-year:_ 
![image](https://github.com/Vuepic/vue-datepicker/assets/11278937/96a15b2b-4e91-4d9e-984a-3e1c418e15eb)

 - Browser: Chrome
 - Library version: 8.8.0

**Comment by Jasenkoo** [comment]
The event won't be triggered on month or year change, therefore the name. You can use different events to get the clicked date.
