### ISSUE TITLE
Failed to compile 

### ISSUE THREAD

**Issue by liboub** [Vuepic/vue-datepicker#927]
### bug description 
I import the picker like that 
```
import VueDatePicker from "@vuepic/vue-datepicker";
import "@vuepic/vue-datepicker/dist/main.css";
```

and I got that error 
```

 error  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js

Module parse failed: Unexpected token (230:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const t = r(e);
|   return t != null && t.$el ? t == null ? void 0 : t.$el : t;
> }, gl = (e) => ({ type: "dot", ...e ?? {} }), Mn = (e) => Array.isArray(e) ? !!e[0] && !!e[1] : !1, Ka = {
|   prop: (e) => `"${e}" prop must be enabled!`,
|   dateArr: (e) => `You need to use array as "model-value" binding in order to support "${e}"`
```

The application is in vue 2.6 with webpack , the picker require vite ? 
I had try to install the version 6 and 7 but I still got the same issues.

**Comment by Jasenkoo** [comment]
It doesn't require Vite but it requires Vue 3. It is also compatible with a vue compat library

**Comment by nissenyeh** [comment]
I used Vue 3.2 and encountered the same issue. Does it support Vue 3.2 but use Vue 2 syntax?

```
ERROR in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js 237:37
Module parse failed: Unexpected token (237:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const t = o(e);
|   return t != null && t.$el ? t == null ? void 0 : t.$el : t;
> }, hl = (e) => ({ type: "dot", ...e ?? {} }), An = (e) => Array.isArray(e) ? !!e[0] && !!e[1] : !1, Ga = {
|   prop: (e) => `"${e}" prop must be enabled!`,
|   dateArr: (e) => `You need to use array as "model-value" binding in order to support "${e}"`
 @ ./src/components/inputs/DateSelectInput.vue?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/dist??ref--13-0!./src/components/inputs/DateSelectInput.vue?vue&type=script&setup=true&lang=js) 1:0-48 117:15-25
 @ ./src/components/inputs/DateSelectInput.vue?vue&type=script&setup=true&lang=js
 @ ./src/components/inputs/DateSelectInput.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/dist??ref--13-0!./src/pages/informations/InformationsCurrentStatus.vue?vue&type=script&lang=js
 @ ./src/pages/informations/InformationsCurrentStatus.vue?vue&type=script&lang=js
 @ ./src/pages/informations/InformationsCurrentStatus.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/dist??ref--13-0!./src/pages/informations/Informations.vue?vue&type=script&lang=js
 @ ./src/pages/informations/Informations.vue?vue&type=script&lang=js
 @ ./src/pages/informations/Informations.vue
 @ ./src/router/index.js
 @ ./src/index.js
 ```

**Comment by runxc1** [comment]
seems to be related to running in webpack as the 3 with it not working are all webpack.

**Comment by nermin99** [comment]
I have tried using Vue `3.2.0` and the latest patch `3.2.47` but I still get the same error
>  ERROR  Failed to compile with 12 errors12:09:57
 error  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js
Module parse failed: Unexpected token (179:168)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }, ml = (e, t) => {
|   if (!e) return 0;
>   const l = /* @__PURE__ */ new Date(), a = new Date(l.toLocaleString("en-US", { timeZone: "UTC" })), n = new Date(l.toLocaleString("en-US", { timeZone: e })), i = (t ?? n).getTimezoneOffset() / 60;
|   return (+a - +n) / (1e3 * 60 * 60) - i;
| };
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--15-3!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/RisikomarkeringList.vue?vue&type=script&lang=ts 6:0-51 15:4-17
