### ISSUE TITLE
UTC model type

### ISSUE THREAD

**Issue by faizaaulia** [Vuepic/vue-datepicker#930]
**Describe the bug**
`utc` prop is true and `model-type` is set to **yyyy-MM-dd HH:mm:ss**, but the model value format is not **yyyy-MM-dd HH:mm:ss**, it returned an ISOString instead

**To Reproduce**
1. Go to https://stackblitz.com/edit/vuepic-vue-datepicker-8pjnev?file=src%2Fcomponents%2FPlayground.vue
2. Pick a date on the first input, the value format is not match with the `model-type` prop value
3. Pick a date on the second input, the value format will match the `model-type` prop value

**Expected behavior**
If the utc set to true, and model-type set to **yyyy-MM-dd HH:mm:ss** the expected model value is like the result on the second input

I'm not really sure if it's a bug or because it's not possible...

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/21327758/fc2316a4-af5c-4eaf-9233-1673640cbc07)

**Comment by Jasenkoo** [comment]
This edge case prop handles specific behavior where `model-type` is not applied. If you want to use the UTC with `model-type`, you should set it via the `timezone` prop in that case
