### ISSUE TITLE
Auto Apply & Flow Using Partial Flow Doesn't Work

### ISSUE THREAD

**Issue by faizaaulia** [Vuepic/vue-datepicker#936]
**Describe the bug**
Set the `flow` to `['date', 'time']`, then `autoApply` and `partialFlow` to `true`.

**To Reproduce**
1. Go to [Partial Flow Documentation](https://vue3datepicker.com/props/modes-configuration/#partial-flow)
2. Pick a date
3. Should be open the time menu instead of close the picker

**Expected behavior**
[Stackblitz Playground using version 7.4.1](https://stackblitz.com/edit/vuepic-vue-datepicker-zkyerw?file=src%2Fcomponents%2FPlayground.vue) I did a traceback to the previous versions and it's just work on version 7.4.1, it's start to bug on version 8.0.0

**Screenshots**

https://github.com/Vuepic/vue-datepicker/assets/21327758/f33abddf-2e32-4906-a354-a858226dfb1e

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: 8.8.1; 8.7.0, and likely start to bug on version 8.0.0

**Comment by JasonMan34** [comment]
This still happens if using `range` mode - https://stackblitz.com/edit/vuepic-vue-datepicker-u3jtq3oc?file=src%2Fcomponents%2FPlayground.vue

@Jasenkoo Should I open a new issue for that?
