### ISSUE TITLE
Stop month scrolling on Mouse Scroll Wheel inputs

### ISSUE THREAD

**Issue by ZermattChris** [Vuepic/vue-datepicker#939]
At the moment there doesn't seem to be any way to stop the Mouse Scroll Wheel from scrolling (rapidly) through the Calendar months. In my use case it's easy to end up selecting a date in the wrong month if you bump the scroll wheel.

A property, something like:
```disable-scroll-wheel : true```
would be great.

Thanks for the great work! :+1: 
-Chris

**Comment by Jasenkoo** [comment]
Please tale a look at `month-change-on-scroll` prop
