### ISSUE TITLE
Date picker with optional date and time

### ISSUE THREAD

**Issue by katenorquay** [Vuepic/vue-datepicker#944]
More of a question than a feature request:

I have a requirement create a date field that can either be a date with a time, a date, or just a month and year. I was thinking that I could use the date picker for the first two scenarios, but allow text input in case they wanted to remove the day and validate that myself. However the text input handlers only fire when there is a valid date input, so I am struggling to capture the month and year value.

Do you have an example of how I could achieve this? Or would I be better off just using an input field and doing the validation myself with these requirements?

**Comment by Jasenkoo** [comment]
There is a new event added in the latest release that will emit on input called `@text-input`. You can also use a dynamic switch between modes for different needs, and for time you can disable it by setting `:enable-time-picker="false"`
