### ISSUE TITLE
When using the clear icon slot, the `dp__clear_icon` class is applied.

### ISSUE THREAD

**Issue by uchksh** [Vuepic/vue-datepicker#945]
Regarding the following changes in v9.0.0

> Class dp__clear_icon is renamed to dp--clear-btn and the icon is wrapped in <button> tag

When using slots, the `dp__clear_icon` class is applied.
Should this be the `dp--clear-btn` class?

https://github.com/Vuepic/vue-datepicker/blob/a742b9d457d51c2eea48235774d795a9ef881b24/src/VueDatePicker/components/DatepickerInput.vue#L62

**Comment by carlssonemil** [comment]
This also causes some issues with the positioning of the clear icon:

![CleanShot 2024-07-18 at 14 43 10](https://github.com/user-attachments/assets/7d622026-2370-41ea-8ec8-7c4582764ce0)
