### ISSUE TITLE
Issue on Android device when there is tooltip

### ISSUE THREAD

**Issue by Guilm** [Vuepic/vue-datepicker#948]
**Describe the bug**
When i am on android device, i need to stay clicked to select end date. However my start date is replace by the touched end date. Even if i stay clicked, my selected range didn't work.

This issue has appear after this update for me : https://github.com/Vuepic/vue-datepicker/commit/1413902d357d5e864a342666939b3ba3a0780a6d

**To Reproduce**
This url : https://www.parceltinyhouse.com/location/brunel/

**Expected behavior**
Seems behavior than IOS Safari

**Screenshots**
https://www.loom.com/share/3c66ffe3629d4f6b808aca73c77dd15e?sid=6712d5b3-b64a-4571-a329-07f3d2deee45

**Desktop & mobile (please complete the following information):**
 - Device : Android Samsung Galaxy S23 - Browser : Chrome
 - Lib version : 9.0.0

**Comment by pwebdev** [comment]
Same problem here, now

**Comment by perruche** [comment]
Having the same issue has well since updating
