### ISSUE TITLE
Datepicker UTC

### ISSUE THREAD

**Issue by noxsii** [Vuepic/vue-datepicker#95]
Hi,
Is there a way to change how the date is displayed in the input? Couldn't find anything about it. Would like to change it from 7/25/2022 to 25/7/2022. Thanks :)

**Comment by Jasenkoo** [comment]
UTC has an issue currently, (ref #66), to format the date, use [`format`](https://vue3datepicker.com/api/props/#format) prop.

**Comment by arzola** [comment]
Thanks for this awesome component, any plans to release #66 soon?

**Comment by Jasenkoo** [comment]
@arzola Around the 1st
