### ISSUE TITLE
Format template not typing the separators for text-input

### ISSUE THREAD

**Issue by elena-lorente** [Vuepic/vue-datepicker#952]
**Is your feature request related to a problem? Please describe.**
When `text-input` is set to `true`, it would be convenient not needing to type the separator manually (for example `/` or `-`), since the placeholder disappears and that can confuse some users in order to complete the date.

**Describe the solution you'd like**
I think something like a template would work. That way the user would see, for example, `dd/mm/yyyy`, and while they are typing, they won't need to type the separators manually, while seeing the format for the part that isn't completed yet.
Something like this:

| Input | Field |
| - | ----------- |
| 2 |2d/mm/yyyy | 
| 6 | 26/mm/yyyy | 
| 0 | 26/0m/yyyy | 
| 7 | 26/07/yyyy |
| 2 | 29/07/2yyy | 
| 0 | 29/07/20yy |
| 2 | 29/07/202y |
| 4 | 29/07/2024 |

**Describe alternatives you've considered**
I tried by modifying the value itself to mimic that behavior, but it's not easily manageable when many inputs are needed

**Additional context**
Maybe this feature already exists, but I haven't been able to find it.

**Comment by Jasenkoo** [comment]
This would require an input mask, which would be a completely new library, I suggest you use some mask library and connect the input events withing the `dp-input` slot.
