### ISSUE TITLE
Datepicker doesn't create `form` input event

### ISSUE THREAD

**Issue by ExEr7um** [Vuepic/vue-datepicker#953]
**Describe the bug**
I'm using date-picker inside form along with other inputs. I have event listener on form, which listens to `input` event to handle validation.

When user inputs something in any other input this event fires. But when user selects a date it does not fire.

It's important that I'm using form's input event, not input.

**To Reproduce**
1. Create a form with datepicker inside
2. Add event listener on form with `input` event
3. Select date
4. See that event listener did not fire

**Expected behavior**
When date is selected, form should fire `input` event.

**Screenshots**

**Desktop & mobile (please complete the following information):**
 - Browser [e.g. chrome, safari]: Safari
 - Library version [e.g. 3.0.0]: `v9.0.1`

**Comment by Jasenkoo** [comment]
Expected behavior, as this is a custom vue component, which emits an `update:model-value` event when the value is updated.
