### ISSUE TITLE
Set Today Date

### ISSUE THREAD

**Issue by faizaaulia** [Vuepic/vue-datepicker#955]
**Is your feature request related to a problem? Please describe.**
The today marker here is auto selected by the date on the device. Is it possible to set the today with custom date?
![image](https://github.com/user-attachments/assets/89028fa2-d57c-46bd-82ac-0b2917978750)

**Describe the solution you'd like**
Add todayDate maybe, that will set the today marker by the todayDate value. If it set 2024-07-29 for example, event in the device today is 2024-07-30, the today marker will be on 2024-07-29

**Comment by Jasenkoo** [comment]
Kinda defeats the purpose of marking today. You can hide it and custom border class on a needed date.
