### ISSUE TITLE
Cannot use with Vuetify since v9 ("Could not find defaults instance")

### ISSUE THREAD

**Issue by soetz** [Vuepic/vue-datepicker#956]
**Describe the bug**
This bug seems very similar to #572. Using any Vuetify component in a VueDatePicker slot prints the error in the console and the datepicker menu doesn’t open.

Here are the errors that I get:
<img width="609" alt="[Vue warn]: injection 'Symbol(vuetify:defaults)' not found. 
  at <VBtn variant='outlined' > 
  at <ActionRow key=3 menu-mount=false multiCalendars=undefined  ... > 
  at <DatepickerMenu multiCalendars=undefined modelValue=null modelType=null  ... >" src="https://github.com/user-attachments/assets/079b9c74-1da2-47af-a871-8466e1497989">
<img width="609" alt="Uncaught Error: [Vuetify] Could not find defaults instance
    at injectDefaults (chunk-3SA2LMFG.js?v=6b41c1b1:1311:11)
    at setup (chunk-3SA2LMFG.js?v=6b41c1b1:1127:24)
    at callWithErrorHandling (chunk-PW74NBAW.js?v=6b41c1b1:1676:19)
    at setupStatefulComponent (chunk-PW74NBAW.js?v=6b41c1b1:9137:25)
    at setupComponent (chunk-PW74NBAW.js?v=6b41c1b1:9098:36)
    at mountComponent (chunk-PW74NBAW.js?v=6b41c1b1:6526:7)
    at processComponent (chunk-PW74NBAW.js?v=6b41c1b1:6492:9)
    at patch (chunk-PW74NBAW.js?v=6b41c1b1:5961:11)
    at mountChildren (chunk-PW74NBAW.js?v=6b41c1b1:6203:7)
    at mountElement (chunk-PW74NBAW.js?v=6b41c1b1:6116:7)" src="https://github.com/user-attachments/assets/18ea4f81-9a5f-4a23-8b56-92626a66df52">

**To Reproduce**
1. Access the minimal reproduction at https://stackblitz.com/edit/vitejs-vite-tqu9lh?file=src%2FApp.vue
2. Try to open the datepicker menu by clicking the input
3. Menu doesn’t open + console prints error

**Expected behavior**
The same as with v8: https://stackblitz.com/edit/vitejs-vite-vau6bq?file=src%2FApp.vue
The menu opens and the Vuetify components are shown inside.

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome 127.0.6533.73
 - Library version: 9.0.1

**Comment by Jasenkoo** [comment]
@soetz It looks like Vuetify is doing some internal overriding on how components render, or in this case if you are using it inside some of their components. 

To fix this, pass the config prop with `:config={ shadowDom: true }` which should resolve the issue.

**Comment by soetz** [comment]
Thanks @Jasenkoo, this looks like it works. I have one question though: this prop doesn’t actually use shadow DOM directly, right? It just changes how the datepicker renders to make it possible to use it in conjunction with the shadow DOM. Or did I get it wrong?

**Comment by soetz** [comment]
Great, thanks again, and thanks for the great library.

**Comment by olehpryimak1999** [comment]
Same bug with action-extra slot, thanks a lot for this project. @Jasenkoo
