### ISSUE TITLE
Disable Year picker and display full month name

### ISSUE THREAD

**Issue by victory-sokolov** [Vuepic/vue-datepicker#96]
**Is your feature request related to a problem? Please describe.**

Greetings! Is it possible to disable only year picker?  There is `disableMonthYearSelect` prop, which removes both, for my specific needs i would like to remove only year and if possible to display full month name.

**Comment by Jasenkoo** [comment]
Not right now

**Comment by Jasenkoo** [comment]
This is a unique request and will add unnecessary logic to handle. However, you can easily implement your own solution with a custom component. Check the [components](https://vue3datepicker.com/api/components/#monthyearcomponent) info. Also, you can use a `VNode` for a component if it is a preferred coding style in your application.

**Comment by sreeharshrajan** [comment]
Hi, I come across [Disable Year Select](https://vue3datepicker.com/props/general-configuration/#disable-year-select) in the documentation, but it is not working in the project. Is there anything else I need to do other than adding the disable-year-select tag
