### ISSUE TITLE
Date Range not working on mobile screens in web

### ISSUE THREAD

**Issue by mjawadhaider** [Vuepic/vue-datepicker#964]
**Describe the bug**
When range is set for the component (it works fine on desktop web), and is open on mobile screen then the range doesn't work and it returns same date for start and end date. 

**Expected behavior**
Different ranges should be allowed to select even for mobile screen,

**Desktop & mobile (please complete the following information):**
 - Browser: chrome (mobile version)
 - Library version 9.0.1

**Comment by Jasenkoo** [comment]
Caused by the same issue reported in #948
