### ISSUE TITLE
Wrong calendar position using teleport prop and relative position on body

### ISSUE THREAD

**Issue by alexovn** [Vuepic/vue-datepicker#965]
**Describe the bug**
If document body has `position: relative;` and VueDatePicker component with `teleport prop` has been placed in some `<div>` with `margin-top`, VueDatePicker can't calculate calendar position properly.

In demo I also prepared tooltip component that is using `@floating-ui/vue` library and vue 3 built-in teleport component. You can see that there's no such issue.

**To Reproduce**
1. Add `position: relative;` to document.body;
2. Place VueDatePicker component in `<div>` with `margin-top`;
3. Add teleport prop to VueDatePicker component;
4. Open calendar.

**Expected behavior**
VueDatePicker with `teleport prop` can calculate calendar position right no matter whether you use `position: relative;` on document body and `margin-top` on `<div>` or not.

**Demo**
https://stackblitz.com/edit/vitejs-vite-eqsen2?file=src%2FApp.vue

**Desktop & mobile (please complete the following information):**
 - Chrome 127.0.6533.89 
 - Library version [8.8.1, 9.0.1]

**Comment by Jasenkoo** [comment]
This is an edge case and such won't be worked on, as updating for this specific scenario will break a regular one. You can always use alt position if/when needed.

**Comment by alexovn** [comment]
> This is an edge case and such won't be worked on, as updating for this specific scenario will break a regular one. You can always use alt position if/when needed.

Can you provide an example how to deal with this case using alt position, 'cause I don't understand how do it right?
