### ISSUE TITLE
Better UX if min-time is set to a value greater than now

### ISSUE THREAD

**Issue by atzen88** [Vuepic/vue-datepicker#966]
**The problem**
The arrows in the timepicker cannot be used if `min-time` is set to a value greater than `now` and no start is set.
For users who are not familiar with using the vue-datepicker, this feels very confusing.
If, for example, the hours entry for `min-time` is in the future, you must first click on the number of hours to set a valid value from the list

**Solution:**
Set `start-time` to `min-time` if no value is specified for `start-time` and `now` is less than `start-time`

**Alternative**
Allows hours and minutes to be incremented and set to `min-time` if it is out of range.

**Additional context**
Maybe it is the responsibility of the developer to set at least a `start-time`, but I find no reason to not set the `start-time` programmatically

**Comment by Jasenkoo** [comment]
As you already mentioned, it is the developer's responsibility to set this value.
