### ISSUE TITLE
Flow with only Year and Month, not calendar

### ISSUE THREAD

**Issue by CavalcanteLeo** [Vuepic/vue-datepicker#969]
Even setting the flow to have only month and year, it automatically adds the calendar... But I don't want the calendar, the picker I need is only month and year, and if a day is required, then we could use any day, like 01, just hide the calendar from the picker...

```vue
<template>
    <VueDatePicker v-model="date" :flow="flow"  />
</template>

<script setup>
import { ref } from 'vue';

const date = ref();
const flow = ref(['month', 'year']);
</script>
```

**Comment by leje512** [comment]
I'm not entirely sure if that's what you meant, but sounds to me like the month-picker mode should solve your problem?
Docs: https://vue3datepicker.com/props/modes/#month-picker
