### ISSUE TITLE
Prop teleport destoys css

### ISSUE THREAD

**Issue by AniaKru95** [Vuepic/vue-datepicker#979]
**Describe the bug**
I have component with changed styles.
If I use this component without prop "teleport" - styles are ok, in case of teleport=true - styles dissapeared.

**To Reproduce**
1. Create component without teleport
2. Change styles
3. Check whether styles are applied
4. Add prop teleport=true
5. Check whether styles disappeared

**Expected behavior**
Apply styles when teleport=true

**Screenshots**
https://stackblitz.com/edit/vuepic-vue-datepicker-7q5atm?file=src%2Fcomponents%2FPlayground.vue

**Desktop & mobile (please complete the following information):**
 - firefox, desktop
 - vue-datepicker 3.0.9

**Comment by Jasenkoo** [comment]
Expected behavior because the component is then moved out of the dom and placed in the `<body>` or in your case, outside scoped styles.

**Comment by iv-thomson** [comment]
> Expected behavior because the component is then moved out of the dom and placed in the `<body>` or in your case, outside scoped styles.

Is there a way to pass a css selector to a teleport prop in order to render the calendar not to body, but to some div instead?

```vue
 <page>
    <section>
      <card style="height: 200px; overflow: hidden">
          <datepicker
            v-model="date"
            teleport="#portal"
          ></datepicker>
      </card>
    </section>

    <div id="portal"></div>
  </page>
  ```
  
  This doesn't seem to work, but I assumed that it was possible because prop accepts both boolean and string.

**Comment by ShGKme** [comment]
> Expected behavior

According to the [documentation](https://vue3datepicker.com/customization/theming/#theming), styles can be scoped.

> When changing the properties, you only need to declare the class in the <style> tag, can be in global or scoped, depending on your needs

Does it still mean that scoped styles are expected to break teleport feature?
Is there a way to use the library with scoped styles without breaking the teleport feature?
