### ISSUE TITLE
teleport with teleport-center make calendar not in center

### ISSUE THREAD

**Issue by DefiCzech** [Vuepic/vue-datepicker#980]
**Describe the bug**
After setting props **teleport** with **teleport-center** both to true, the calendar is not centered, there is small shift to right and down. After removing props **teleport** the calendar is centered properly.

**To Reproduce**
1. add both props **teleport** and **teleport-center** to true
2. open calendar
3. calendar is not centered in window

**Expected behavior**
The calendar will be centered in window

**Desktop & mobile (please complete the following information):**
 - Browser? Microsoft Edge
 - Library version: 9.0.2

**Comment by Jasenkoo** [comment]
They shouldn't be used in combination

**Comment by DefiCzech** [comment]
So there is no way how to have teleported and centered calendar? teleport-center is missleading name, because element is not teleported.
