### ISSUE TITLE
Changing month/year position if uses multiple calendar

### ISSUE THREAD

**Issue by hobuttt** [Vuepic/vue-datepicker#981]
**Describe the bug**

When I use multiple calendar with range, 2 parts and use solo mode I want to get 2 independently switching calendars. But when I select first date in the left part, right part changes month/year on the next one after first part (I now it's in documentation but it's not convenient). Moreover if I select first date in the right part when the left part differs from the right one by several months , this right part changes month/year on the next one after first part too. 

**To Reproduce**

1. Create calendar with 
:multiCalendars = { solo: true, static: false, number: 2 }
range

2. open calendar dialog
3. Set the left part of the calendar to be a few months apart from the right part.
4. You will see changes in the right part

**Expected behavior**
 I want to get 2 independently switching calendars.

**Desktop & mobile (please complete the following information):**
 - Library version 8.8.1 - 9.0.2

**Comment by Jasenkoo** [comment]
This is the current limitation in the logic, it would require significant adjustment, as it was planned to be used as the standard multi-calendar layout with support to update the months/years independently.
