### ISSUE TITLE
Positioning active month in multiple calendar.

### ISSUE THREAD

**Issue by hobuttt** [Vuepic/vue-datepicker#982]
**Is your feature request related to a problem? Please describe.**
I often use today as maxDate for work with past dates and default day usually is today too. It's really inconvenient when single active month on the left side of calendar and unavailable months on the right in this case.

**Describe the solution you'd like**
I'd like to be able change start position of current active month. Or not showing unavailable months 

![image](https://github.com/user-attachments/assets/1d7450db-d7de-4d64-b7bb-f8ac37f02840)

**Comment by Jasenkoo** [comment]
You can use `start-date` prop

**Comment by hobuttt** [comment]
It's doesn't help. If I choose any date in current month I still see active month on the left and disabled month on the right.

> You can use `start-date` prop
