### ISSUE TITLE
Daylight Savings Mismatch in Text Input

### ISSUE THREAD

**Issue by klongmitre** [Vuepic/vue-datepicker#983]
**Describe the bug**
When I select a date outside of DST (e.g. March 10, 2022) and select a time (e.g., 12:00), the value emitted and displayed is an hour off (e.g., 13:00)

**To Reproduce**
```
<VueDatePicker v-model="vData.startDate" :clearable="false" :month-change-on-scroll="false" format="MMM d, yyyy '@' HHmm" :timezone="{ timezone: 'UTC' }" :max-date="maxDate"></VueDatePicker>
```
* Select March 10, 2022 at 12:00
* Observe that text displayed in TextInput is `March 10, 2022 @ 1300`

In the case above, the value of `vData.startDate` is `Fri Mar 11 2022 08:00:00 GMT-0500 (Eastern Standard Time)`

**Expected behavior**
Selected time should be preserved and displayed correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/540247aa-beee-4a5b-89e7-b54773b19908)

 - Browser: Chrome
 - Library version: 9.0.2

**Comment by Jasenkoo** [comment]
This is ok, as time in the `Date` object differs from the `string` representation
