### ISSUE TITLE
vue.esm-bundler.js:1611 [Vue warn]: Extraneous non-props attributes (value) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

### ISSUE THREAD

**Issue by lilz-sofia** [Vuepic/vue-datepicker#984]
**Describe the bug**
I get the warning everytime I click the input field:
```
vue.esm-bundler.js:1611 [Vue warn]: Extraneous non-props attributes (value) were passed 
to component but could not be automatically inherited because component renders fragment or text root nodes.
at <DatePicker ref_key="dynCmpRef" ref=Ref< Proxy(Object) {clearHoverDate: ƒ, presetDate: ƒ, selectCurrentDate: ƒ, toggleMonthPicker: ƒ, toggleYearPicker: ƒ, …} > multiCalendars=undefined  ... > 
```
I am using vue compat build in `MODE: 3`

**To Reproduce**
Here's how I am using the library:
```
<vue-date-picker
   v-model="dateTimeInput"
   class="lg-datepicker"
   locale="en-US"
   :clearable="false"
   :format-locale="datePickerLanguage"
   :enable-time-picker="false"
   format="yyyy-MM-dd"
  />
```

**Expected behavior**
The warning to be gone
**Screenshots**
![Screenshot 2024-09-05 at 17 56 58](https://github.com/user-attachments/assets/0cb9e180-65f7-44e4-b066-832de17a30fb)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: 9.0.2

**Comment by Jasenkoo** [comment]
This is not a picker issue, looks like you are passing some values not defined as props to your parent component.

**Comment by lilz-sofia** [comment]
@Jasenkoo 

Okay it makes sense to assume it's from my side of the application and it might be. But for several factors I thought it is from the library. Let me try explaining my point of view in more details. I would really appreciate if you can provide me your insights on what's happening here after hearing me out. 

I thought it was from the library:
1.  because the point of issuing the warning is at `Datepicker` component which belongs to `vuepic` library
2. the warning indicates the extraneous prop to be `value`, which I am not passing to my parent company from anywhere

Note, I do not think  it's a bug in the library. But this might be due to the library acting in vue2 mode for some reason, as I am using a compat build (although in the parent component I configured the build to be in vue3 mode), and instead of translating `v-model ` to be passing `modelValue` prop, it is actually binding the prop as `value` to the component as it does in Vue2. 

I assumed the above as I get the below consequent warnings on clicking the input field that pops up the calendar: 
<img width="368" alt="Screenshot 2024-09-09 at 6 48 35" src="https://github.com/user-attachments/assets/5da785c3-6feb-472c-a893-9a8da9db7dff">

Can you give any idea on how I can resolve this? I tried setting the `COMPONENT_V_MODEL` to `false` in the compatConfig as recommended in the warning.

**Comment by Jasenkoo** [comment]
The library is not supporting fully compat mode, the code is added, but in the end, it may come to a developer to make some adjustments. I would suggest that you either add a manual `v-model` binding by providing `:model-value` and `@update:model-value` separately like [here](https://v3-migration.vuejs.org/breaking-changes/v-model.html#_3-x-syntax) or setting `COMPONENT_V_MODEL` in your compat config
