### ISSUE TITLE
Dates below 1000 showing a leading zero? (or fixed already?) 

### ISSUE THREAD

**Issue by spookyahell** [Vuepic/vue-datepicker#985]
**Describe the bug**
If it still even exists in this library... I spotted [tagesschau.de](https://www.tagesschau.de/archiv/sendungen) using a version of this datepicker.

Year 0815 shows up, which if you consider the [general meaning of 0815 in German](https://de.wikipedia.org/wiki/08/15_(Redewendung)) is pretty funny.
(linked article only for those who understand German)
_I want to travel to a more normal year. Someone just needs to invent that dang missing time machine._

Anyway, not sure why it's even set up to go further back than a few years, they use the calendar for their news program archive.
But year 815 showing a leading zero feels like it would be an upstream issue.

Anyway, sorry if this is sent in error, cause I'm not even 100% sure it's the right library.
But it feels like it is based on the playground vs the way their datepicker looks.

**To Reproduce**
1. Go to the year '815' (yes, really)
2. Click on 'nothing else'
3. Scroll down to 'no really, that's it'
4. See "error" (display issue)

I'm not even saying a leading zero is mathematically wrong, it's not.
Just feels super weird. (And yes, I'd like to stay the only one who was able to travel to 0815)

PS: If you actually select a date lower than 1000, tagesschau.de will move away from the archive page.

**Expected behavior**
I expected not to write this at 3:38 a.m.
_Oh, wait, in reference to the reported bug?_
Maybe no leading zero(s). If that's an actual thing that still happens.

**Screenshots**
Yeah, I could. But I won't.

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by Jasenkoo** [comment]
It is just a matter of date format if needed, easily changeable via prop `format`
