### ISSUE TITLE
Vue3.1.0 : Failed to compile - Module parse failed: Unexpected token (237:37)

### ISSUE THREAD

**Issue by nissenyeh** [Vuepic/vue-datepicker#989]
**Describe the bug**

same as https://github.com/Vuepic/vue-datepicker/issues/927 but I encountered this error when using Vue 3.1 with Vue 2 syntax while trying to implement @vuepic/vue-datepicker version 9.0.3.

**To Reproduce**

1. Use Vue 3.1.0 &  @vue/compat 3.10 

```
    "@vue/compat": "^3.1.0",
    "@vue/compiler-sfc": "^3.1.0",
    "vue": "^3.1.0",
    "vue-loader": "^16.0.0",
    "vue-style-loader": "^4.1.3",
    "@vuepic/vue-datepicker": "^9.0.3",
```

2. Attempt to use 

```
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';
```

3. error  

```
ERROR in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js 237:37
Module parse failed: Unexpected token (237:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const t = o(e);
|   return t != null && t.$el ? t == null ? void 0 : t.$el : t;
> }, hl = (e) => ({ type: "dot", ...e ?? {} }), An = (e) => Array.isArray(e) ? !!e[0] && !!e[1] : !1, Ga = {
|   prop: (e) => `"${e}" prop must be enabled!`,
|   dateArr: (e) => `You need to use array as "model-value" binding in order to support "${e}"`
 @ ./src/components/inputs/DateSelectInput.vue?vue&type=script&setup=true&lang=js (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/dist??ref--13-0!./src/components/inputs/DateSelectInput.vue?vue&type=script&setup=true&lang=js) 1:0-48 117:15-25
 @ ./src/components/inputs/DateSelectInput.vue?vue&type=script&setup=true&lang=js
 @ ./src/components/inputs/DateSelectInput.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/dist??ref--13-0!./src/pages/informations/InformationsCurrentStatus.vue?vue&type=script&lang=js
 @ ./src/pages/informations/InformationsCurrentStatus.vue?vue&type=script&lang=js
 @ ./src/pages/informations/InformationsCurrentStatus.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/dist??ref--13-0!./src/pages/informations/Informations.vue?vue&type=script&lang=js
 @ ./src/pages/informations/Informations.vue?vue&type=script&lang=js
 @ ./src/pages/informations/Informations.vue
 @ ./src/router/index.js
 @ ./src/index.js
```

**Expected behavior**
I expected the vue-datepicker component to work with Vue 3.1, but instead encountered a module parse failure related to missing loaders.

**Screenshots**
Error screenshot:
<img width="668" alt="CleanShot 2024-09-14 at 18 30 42@2x" src="https://github.com/user-attachments/assets/cad70766-33b5-46e5-b303-eeec230fb944">

**Desktop & mobile (please complete the following information)**

Library version: @vuepic/vue-datepicker ^9.0.3
Vue version: 3.1

=========================

Does it support Vue 3.1(Migration build) but use Vue 2 syntax?  (I can't directly upgrade to the latest version of Vue because I need to use Vue 3.1 first to ensure compatibility between Vue 2 and Vue 3 syntax.）

**Comment by Jasenkoo** [comment]
The supported `vue` version is `>=3.2`. Versions prior that were still in the alpha/beta stage, and they had breaking changes in 3.2

**Comment by runxc1** [comment]
So I'm using Vue 3.5 with webpack and am running into the same error.  Perhaps this is more of a webpack issue?


This is the error message that I am getting

`
Module parse failed: Unexpected token (237:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const t = o(e);
|   return t != null && t.$el ? t == null ? void 0 : t.$el : t;
> }, hl = (e) => ({ type: "dot", ...e ?? {} }), An = (e) => Array.isArray(e) ? !!e[0] && !!e[1] : !1, Ga = {
|   prop: (e) => `"${e}" prop must be enabled!`,
|   dateArr: (e) => `You need to use array as "model-value" binding in order to support "${e}"`

 @ ./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--15-2!./node_modules/vue-loader-v16/dist??ref--1-0!./src/views/Home.vue?vue&type=script&lang=ts 19:0-51 519:4-17
 @ ./src/views/Home.vue?vue&type=script&lang=ts
 @ ./src/views/Home.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ ./src/entry-client.ts
 @ multi ./src/entry-client.ts

`

**Comment by nermin99** [comment]
I have tried using Vue `3.2.0` and the latest patch `3.2.47` but I still get the same error as OP

>  ERROR  Failed to compile with 12 errors12:09:57
 error  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js
Module parse failed: Unexpected token (179:168)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }, ml = (e, t) => {
|   if (!e) return 0;
>   const l = /* @__PURE__ */ new Date(), a = new Date(l.toLocaleString("en-US", { timeZone: "UTC" })), n = new Date(l.toLocaleString("en-US", { timeZone: e })), i = (t ?? n).getTimezoneOffset() / 60;
|   return (+a - +n) / (1e3 * 60 * 60) - i;
| };
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--15-3!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/RisikomarkeringList.vue?vue&type=script&lang=ts 6:0-51 15:4-17

**Comment by solomoni96** [comment]
Any guidance on this issue? I'm also using webpack can get the following errors

```
Message:
    ./node_modules/@vuepic/vue-datepicker/dist/main.css (./node_modules/css-loader/dist/cjs.js!./node_modules/@vuepic/vue-datepicker/dist/main.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/solomon/dev/bristol-beacon/node_modules/css-loader/dist/index.js:20:27)
 @ ./node_modules/@vuepic/vue-datepicker/dist/main.css 4:14-69
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/dist??ref--14-0!./src/vue/date-picker/App.vue?vue&type=script&lang=js
 @ ./src/vue/date-picker/App.vue?vue&type=script&lang=js
 @ ./src/vue/date-picker/App.vue
 @ ./src/vue/date-picker/index.js
./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js 220:11
Module parse failed: Unexpected token (220:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     u(), E.preventDefault();
|     const k = document.activeElement;
>     if (!k?.hasAttribute("data-dp-action-element"))
|       return;
|     let g = -1, M = -1;
 @ ./src/vue/date-picker/App.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist??ref--14-0!./src/vue/date-picker/App.vue?vue&type=script&lang=js) 2:0-55 6:4-17
 @ ./src/vue/date-picker/App.vue?vue&type=script&lang=js
 @ ./src/vue/date-picker/App.vue
 @ ./src/vue/date-picker/index.js
```

```
ERROR in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js 220:11
Module parse failed: Unexpected token (220:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     u(), E.preventDefault();
|     const k = document.activeElement;
>     if (!k?.hasAttribute("data-dp-action-element"))
|       return;
|     let g = -1, M = -1;
 @ ./src/vue/date-picker/App.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist??ref--14-0!./src/vue/date-picker/App.vue?vue&type=script&lang=js) 2:0-55 7:4-17
 @ ./src/vue/date-picker/App.vue?vue&type=script&lang=js
 @ ./src/vue/date-picker/App.vue
 @ ./src/vue/date-picker/index.js
```
