### ISSUE TITLE
Selecting only a given date outside DST causes the time (hours) to shift unexpectedly.

### ISSUE THREAD

**Issue by petarstoyanov-ekko** [Vuepic/vue-datepicker#991]
**Describe the bug**
Selecting only a given date causes the time (hours) to shift unexpectedly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://stackblitz.com/edit/vuepic-vue-datepicker?file=src%2Fcomponents%2FPlayground.vue
2. Select e.g. 1 February 2024 10:00 am
3. Start changing the day to 11th, then 12, then 13.
4. Each time the day is changed, the time presented (hours) moves an hour ahead

**Observations**
This seems to be related to DST changes, local timezone is in DST now and selected date is outside DST. This issue does not reproduce when selecting another date in DST.

**Expected behaviour**
When the user is interacting with the date only as in this example, the selected hours should not be affected.

In the edge case of starting with hours as 23, selecting e.g. 16th overflows into actually selecting 17th (this interaction changes both the date and the hours)

**Screenshots**
![image](https://github.com/user-attachments/assets/26c07da4-6c08-479a-9302-e8c2c23afd04)

**Desktop & mobile (please complete the following information):**
 - Browser Chrome - Version 128.0.6613.138 (Official Build) (64-bit)
 - Library version 9.0.3
 - Local timezone - Europe/Athens

**Comment by alexgil1994** [comment]
Having a similar behavior when combined with  `:timezone=" { timezone: "UTC" } as TimeZoneConfig;`, whenever the user changes anything in the `vue-date-picker` instance as a datetime picker (change of day, minutes, hours) then the hours are also increasing by +1.

**Comment by cah-charbel-fakhry** [comment]
Any Update on this? As I am facing the same issue

**Comment by cah-iman-matar** [comment]
This bug is almost 1 year old.
Did anyboday find a workaround?

**Comment by cah-charbel-fakhry** [comment]
Will this be released soon?
