### ISSUE TITLE
Accessibility issues detected by axe automated check in browser

### ISSUE THREAD

**Issue by JustinaDesriute** [Vuepic/vue-datepicker#992]
**Describe the bug**
axeDevTools detect 2 types of issues:
1. Unsupported aria attribute 

![Screenshot 2024-09-17 at 16 09 00](https://github.com/user-attachments/assets/af70255a-8e94-40f8-b881-01f54c3b5479)

2. alertdialog node needs an accessible name

![Screenshot 2024-09-17 at 16 05 19](https://github.com/user-attachments/assets/e5fc0c5e-c997-4b57-bef8-84e69fa9404a)

**To Reproduce**
1. Go to: https://stackblitz.com/edit/vuepic-vue-datepicker?file=src%2Fcomponents%2FPlayground.vue 
2. Open dev tools and run axeDevTools browser extension (tested in Chrome).

**Expected behavior**
No issues detected by the automated accessibility testing tool axe.

**Desktop & mobile (please complete the following information):**
 - Browser Version 128.0.6613.138
 - Library version "@vuepic/vue-datepicker": "^9.0.3"

**Comment by Jasenkoo** [comment]
Aide from colors that are easily changeable per design, other issues are reported specifically in stackblitz container. Low prior, but I doubt this will be worked on at all
