### ISSUE TITLE
Disabled datepicker overlay blocks interaction with other Elements due to high z-index

### ISSUE THREAD

**Issue by solidevolution** [Vuepic/vue-datepicker#997]
**Describe the bug**
When the Vue Datepicker component is disabled, the dropdown menu overlay (dp_menu) remains rendered with a z-index of 99999. As a result, other elements on the page, such as select inputs, become unclickable and unusable since they are covered by this invisible overlay.

**To Reproduce**

1. Create a form that includes a Vue Datepicker component and a select dropdown.
2. Set the Datepicker to be disabled (via :disabled="true").
3. Attempt to click on the select dropdown.
4. Notice that the select element cannot be interacted with, as it’s blocked by the invisible Datepicker overlay.

**Expected behavior**
When the Datepicker is disabled, the overlay should not interfere with other elements on the page. The dp_menu overlay should either be removed entirely or have its z-index significantly reduced, allowing other form elements like select to be usable.

**Desktop & mobile**

Browser: Chrome

**Additional context**
This issue occurs specifically due to the dp_menu overlay retaining a high z-index of 99999, even when the Datepicker is in a disabled state. We fixed it while bug is open with overwriting the z-index to 1.

```
  .dp-menu-loading,
  .dp__menu_readonly,
  .dp__menu_disabled {
    z-index: 1;
  }
```

**Comment by aries2004-bit** [comment]
download
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Jasenkoo** [comment]
This isn't reproducible on my end. If you can, please provide some kind of reproduction demo
